/** Biblioteca inicial — DRILLS (exercícios de quadra repetíveis). */

import { bolinha, cone, desloca, diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const DRILLS = [
  {
    slug: 'dink-cruzado-pe-de-dentro',
    version: 1,
    featured: true,
    kind: 'drill',
    title: 'Dink cruzado no pé de dentro',
    summary: 'Dupla na linha da cozinha trocando dinks cruzados com um cone como alvo. Para quem já mantém o dink e quer precisão.',
    objective: 'Ao final, o atleta consegue manter 10 dinks cruzados seguidos caindo na cozinha, perto do pé de dentro do parceiro.',
    skills: ['kitchen.dink_cruzado', 'kitchen.paciencia'],
    level_min: 2.5,
    level_max: 4.5,
    players_min: 2,
    players_max: 4,
    roles: ['Parceiro de dink'],
    duration_min: 12,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    setup: 'Os dois na linha da cozinha, um de frente para o outro na diagonal (direita com direita). Um cone dentro de cada cozinha, a um palmo da linha, na frente do pé de dentro (o pé mais perto do meio). Com quatro pessoas, a outra dupla usa a diagonal da esquerda ao mesmo tempo.',
    steps: [
      'Quem está à direita solta a bola e começa com um dink cruzado.',
      'Troquem dinks cruzados, sempre mirando o cone do outro lado.',
      'Contem em voz alta cada dink que cai dentro da cozinha.',
      'Errou (rede, fora ou bola alta demais), a contagem volta a zero.',
      'A cada 3 minutos, troquem para a diagonal da esquerda.',
    ],
    cues: ['Raquete na frente, como uma pá', 'Pico da bola antes da rede', 'Mire o cadarço do parceiro'],
    positioning: [
      { type: 'certo', text: 'Pés logo atrás da linha da cozinha, base aberta e raquete na frente da cintura.' },
      { type: 'errado', text: 'Um passo atrás da linha: a bola quica no seu pé, você bate de baixo e o dink sobe.' },
    ],
    common_errors: [
      { error: 'O dink sobe e o parceiro poderia atacar.', fix: 'Faça o ponto mais alto da bola ficar do seu lado da rede e termine a raquete apontando o cone.' },
      { error: 'A bola morre na rede.', fix: 'Levante a bola com as pernas, como quem joga areia com uma pá; a raquete termina na altura da fita.' },
      { error: 'O dink cai no meio da cozinha, fácil de alcançar.', fix: 'Mire o cone perto da linha: dink baixo e comprido obriga o parceiro a jogar de baixo.' },
    ],
    variations: {
      easier: 'Tarefa: dink paralelo (bola mais curta e mais fácil de controlar) e meta de 5 seguidos.',
      harder: 'Tarefa: o parceiro alterna o alvo entre o pé de dentro e o pé de fora; bola acima da rede pode ser atacada.',
    },
    metric: { type: 'sequencia', target: '10 seguidos' },
    success_criteria: 'Conta se cai dentro da cozinha e passa abaixo da altura da cintura do parceiro. Fez 10 seguidos duas vezes? Vá para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Base aberta, pernas dobradas e raquete na frente da cintura, com a face um pouco aberta.',
        execucao: 'As pernas sobem e a raquete empurra a bola para cima e para a frente, sem bater.',
        finalizacao: 'A raquete para apontando o alvo e volta para a frente do corpo.',
      },
      abilities: ['precisao', 'equilibrio', 'ritmo'],
    },
    when_to_use: 'Rally de cozinha em duplas, quando ninguém tem bola alta para atacar.',
    diagrams: [
      diagrama('Diagonal da direita', 'cozinha', [
        jogador(75, 68, 'a', 'A'),
        jogador(25, 32, 'b', 'B'),
        cone(30, 37),
        cone(70, 63),
        trajeto(75, 66, 31, 38, '1'),
        trajeto(25, 34, 69, 62, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-paralelo-junto-a-lateral',
    version: 1,
    kind: 'drill',
    title: 'Dink paralelo junto à lateral',
    summary: 'Dink reto, de frente para o parceiro, com alvo numa faixa perto da lateral. Treina o dink mais curto e o controle da altura.',
    objective: 'Ao final, o atleta consegue trocar 15 dinks paralelos seguidos sem a bola passar da altura da cintura do parceiro.',
    skills: ['kitchen.dink_paralelo', 'kitchen.paciencia'],
    level_min: 2.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    setup: 'Os dois na linha da cozinha, frente a frente, perto da mesma lateral. Dois cones em cada cozinha marcam uma faixa de um metro junto à lateral: é o alvo. Com quatro pessoas, a outra dupla faz o mesmo junto à outra lateral.',
    steps: [
      'Um solta a bola e começa com um dink reto para a faixa do outro.',
      'Troquem dinks paralelos, sempre dentro da faixa.',
      'Contem os dinks seguidos que caem na faixa.',
      'Bola fora da faixa ou acima da cintura zera a conta.',
      'A cada 2 minutos, troquem de lateral: quem jogava de forehand passa para o backhand.',
    ],
    cues: ['Bola baixa, faixa estreita', 'Empurre devagar, sem bater', 'Raquete termina na altura da fita'],
    positioning: [
      { type: 'certo', text: 'De frente para a rede, raquete na frente e um pouco aberta antes de a bola chegar.' },
      { type: 'errado', text: 'Raquete lá atrás, preparando um balanço grande: a bola sai rápida e passa da faixa.' },
    ],
    common_errors: [
      { error: 'A bola passa da cozinha.', fix: 'Encurte o gesto: a raquete anda só um palmo e para apontando a faixa.' },
      { error: 'No backhand, o dink sobe demais.', fix: 'Encontre a bola na frente do corpo e levante com as pernas, não com a raquete.' },
      { error: 'Você fica parado e a bola quica no pé.', fix: 'Dê um passo curto até a bola e bata com ela na sua frente.' },
    ],
    variations: {
      easier: 'Espaço: faixa de dois metros e meta de 8 seguidos.',
      harder: 'Espaço: o alvo vira só o último meio metro da cozinha, junto à linha; bola fora dele zera a conta.',
    },
    metric: { type: 'sequencia', target: '15 seguidos' },
    success_criteria: 'Conta se a bola cai na faixa e não passa da altura da cintura. Duas sequências de 15? Suba para o dink em oito.',
    motor: {
      phases: {
        preparacao: 'Pernas dobradas, raquete na frente, face levemente aberta.',
        execucao: 'Gesto curto de baixo para cima; as pernas fazem a bola subir.',
        finalizacao: 'A raquete para na altura da fita, apontando a faixa.',
      },
      abilities: ['precisao', 'ritmo', 'coordenacao'],
    },
    when_to_use: 'Quando a bola vem para a sua lateral e o adversário está na sua frente: o dink paralelo é o mais curto e chega mais rápido.',
    diagrams: [
      diagrama('Faixa junto à lateral', 'cozinha', [
        zona(84, 35, 100, 49, 'Alvo'),
        zona(84, 51, 100, 65, 'Alvo'),
        jogador(90, 68, 'a', 'A'),
        jogador(90, 32, 'b', 'B'),
        trajeto(90, 66, 92, 40, '1'),
        trajeto(90, 34, 92, 60, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-em-oito',
    version: 1,
    kind: 'drill',
    title: 'Dink em oito: cruzado e paralelo',
    summary: 'Um faz só dink cruzado, o outro só paralelo: a bola desenha um oito e os dois andam pela linha da cozinha. Para quem já mantém o dink parado.',
    objective: 'Ao final, o atleta consegue manter 12 dinks seguidos alternando cruzado e paralelo, deslocando-se junto à linha.',
    skills: ['kitchen.dink_cruzado', 'kitchen.dink_paralelo', 'physical.agilidade'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    duration_min: 12,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: 'Dois jogadores na linha da cozinha, frente a frente, do mesmo lado da quadra. A é o "cruzado": todo dink dele vai na diagonal. B é o "paralelo": todo dink dele vai reto.',
    steps: [
      'A começa com um dink cruzado.',
      'B anda até a bola e devolve paralelo, reto para a frente.',
      'A anda até a bola e manda cruzado de novo; B anda e manda paralelo.',
      'Contem os dinks seguidos que caem na cozinha.',
      'A cada 3 minutos, troquem os papéis.',
    ],
    cues: ['Ande até a bola, depois bata', 'Raquete aponta o próximo alvo', 'Pare antes de bater'],
    positioning: [
      { type: 'certo', text: 'Passos curtos e laterais pela linha, chegando parado na bola.' },
      { type: 'errado', text: 'Bater ainda correndo, com o corpo indo para o lado: a bola sai torta ou alta.' },
    ],
    common_errors: [
      { error: 'Quem corre para alcançar a bola fica dentro da cozinha.', fix: 'Pode entrar para jogar a bola que quicou; volte para trás da linha antes da próxima, porque de dentro não se voleia.' },
      { error: 'A bola começa a subir quando o deslocamento aperta.', fix: 'Volte ao dink parado até a altura estabilizar e só então retome o oito.' },
      { error: 'O paralelo sai cruzado.', fix: 'Aponte a raquete para o alvo antes de bater.' },
    ],
    variations: {
      easier: 'Espaço: usem só metade da largura da quadra para andar menos; meta de 6 seguidos.',
      harder: 'Tarefa: depois de 5 dinks, quem faz o paralelo pode trocar de direção quando quiser; o outro precisa ler e se ajustar.',
    },
    metric: { type: 'sequencia', target: '12 seguidos' },
    success_criteria: 'Conta se cai na cozinha e quem bateu estava parado. 12 seguidos nos dois papéis? Passe para a variação mais difícil.',
    safety: 'Desloque-se de lado com passos curtos; cruzar as pernas com pressa é como se tropeça perto da rede.',
    motor: {
      phases: {
        preparacao: 'Passo lateral curto até a bola, base aberta ao chegar.',
        execucao: 'Gesto curto de baixo para cima, apontando o alvo do seu papel.',
        finalizacao: 'Volte para o centro da sua área com a raquete na frente.',
      },
      abilities: ['agilidade', 'precisao', 'equilibrio', 'ritmo'],
    },
    when_to_use: 'Rally de cozinha em que o adversário move você de um lado para o outro.',
    diagrams: [
      diagrama('O oito', 'cozinha', [
        jogador(30, 68, 'a', 'A'),
        jogador(30, 32, 'b', 'B'),
        trajeto(30, 66, 70, 37, '1'),
        desloca(30, 29, 70, 29),
        trajeto(70, 34, 70, 62, '2'),
        desloca(30, 71, 70, 71),
      ]),
    ],
    media: [],
  },
  {
    slug: 'primeiros-dinks-com-alimentador',
    version: 1,
    kind: 'drill',
    title: 'Primeiros dinks: bola na mão e alvo na cozinha',
    summary: 'O parceiro joga a bola com a mão e você devolve um dink para dentro da cozinha. O primeiro passo para quem nunca fez dink.',
    objective: 'Ao final, o atleta consegue devolver 7 de 10 bolas alimentadas com um dink que cai dentro da cozinha do outro lado.',
    skills: ['kitchen.dink_paralelo', 'kitchen.paciencia'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'bloco',
    setup: 'O executor fica na linha da cozinha com a raquete. O alimentador fica do outro lado, também na linha da cozinha, com 10 bolas. O alvo é toda a cozinha do lado do alimentador.',
    steps: [
      'O alimentador joga a bola com a mão, por baixo, para quicar na frente do executor.',
      'O executor deixa quicar e devolve com um dink para a cozinha do outro lado.',
      'O alimentador não devolve: pega outra bola e joga de novo.',
      'Contem quantas das 10 bolas caem dentro da cozinha.',
      'Depois de 10 bolas, troquem os papéis.',
    ],
    cues: ['Bola sobe e desce na cozinha', 'Raquete como uma pá', 'Termine apontando o alvo'],
    positioning: [
      { type: 'certo', text: 'Raquete pronta na frente antes de a bola quicar.' },
      { type: 'errado', text: 'Raquete parada ao lado da perna: você se atrasa e bate a bola para cima, longe.' },
    ],
    common_errors: [
      { error: 'A bola passa da cozinha e vai para o fundo.', fix: 'Gesto curto: a raquete anda um palmo, não um metro.' },
      { error: 'A bola bate na rede.', fix: 'Levante a bola: o ponto mais alto fica antes da rede.' },
      { error: 'O executor bate antes de a bola quicar.', fix: 'Espere o quique: neste drill a bola quica e você joga depois.' },
    ],
    variations: {
      easier: 'Equipamento: bola mais lenta (de quadra coberta ou de espuma) e alvo maior: valem bolas que caem até um metro depois da cozinha.',
      harder: 'Pessoas: o alimentador devolve com dink e vira um rally de verdade; meta de 5 seguidos.',
    },
    metric: { type: 'percentual', target: '7 de 10 na cozinha' },
    success_criteria: 'Conta a bola que quica dentro da cozinha do alimentador. 7 de 10 em duas rodadas? Passe para o dink paralelo em rally.',
    motor: {
      phases: {
        preparacao: 'Pernas dobradas, raquete na frente da cintura com a face um pouco aberta.',
        execucao: 'A raquete encontra a bola na frente do corpo e empurra para cima, devagar.',
        finalizacao: 'A raquete termina apontando a cozinha do outro lado.',
      },
      abilities: ['coordenacao', 'precisao'],
    },
    when_to_use: 'Sempre que a bola cai curta, perto dos seus pés, e o adversário está na rede.',
    diagrams: [
      diagrama('Alimentação com a mão', 'cozinha', [
        zona(10, 35, 90, 49, 'Alvo'),
        jogador(50, 68, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 34, 50, 60, '1'),
        trajeto(50, 66, 44, 42, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-ate-11',
    version: 1,
    kind: 'drill',
    title: 'Dink até 11: jogo só na cozinha',
    summary: 'Jogo de pontos em que toda bola tem de quicar na cozinha. Vence quem tiver mais paciência para manter a bola baixa.',
    objective: 'Ao final, o atleta consegue ganhar mais pontos do que perde mantendo o dink baixo até o adversário errar.',
    skills: ['kitchen.paciencia', 'kitchen.dink_cruzado', 'experience.jogo'],
    level_min: 2.5,
    level_max: 5.0,
    players_min: 2,
    players_max: 4,
    duration_min: 15,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Usem só as duas cozinhas. Em dois (1 contra 1), joguem na diagonal; em quatro (2 contra 2), usem a largura toda. Todos começam e ficam na linha da cozinha.',
    steps: [
      'Quem começa solta a bola e faz um dink de qualquer lugar da linha.',
      'Toda bola tem de quicar dentro da cozinha do outro lado; vale voleio, desde que a bola caia na cozinha.',
      'Bola fora da cozinha, na rede ou fora da quadra é ponto do outro.',
      'Todo rally vale ponto, sem precisar sacar.',
      'Jogo até 11, com 2 de diferença; quem perdeu começa o jogo seguinte.',
    ],
    cues: ['Bola baixa ganha o ponto', 'Mire a linha da cozinha', 'Mova o adversário, não a força'],
    positioning: [
      { type: 'certo', text: 'Os dois parceiros na linha, lado a lado, cobrindo o meio juntos.' },
      { type: 'errado', text: 'Um na linha e o outro meio passo atrás: o dink no pé de quem ficou atrás vira bola alta.' },
    ],
    common_errors: [
      { error: 'Você tenta ganhar o ponto com força e erra fora da cozinha.', fix: 'Ganhe pelo alvo: dink no pé do adversário até ele errar ou subir a bola.' },
      { error: 'O dink vai sempre para o mesmo lugar e o adversário se acostuma.', fix: 'Varie entre o pé, o meio e a lateral, mantendo a bola baixa.' },
    ],
    variations: {
      easier: 'Tarefa: jogo cooperativo — a dupla conta quantos dinks seguidos consegue antes de errar.',
      harder: 'Tarefa: bola que passar acima da rede pode ser atacada (speed-up); o ataque só vale se cair na quadra.',
    },
    metric: { type: 'placar', target: '11 pontos' },
    success_criteria: 'Vence quem fizer 11 com 2 de diferença. Ganhou dois jogos seguidos? Jogue com a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Base aberta na linha, raquete na frente.',
        execucao: 'Dink curto, de baixo para cima, para o alvo escolhido.',
        finalizacao: 'Volte para a base com a raquete na frente.',
      },
      abilities: ['precisao', 'leitura', 'ritmo'],
    },
    when_to_use: 'Pontos de cozinha em duplas, principalmente contra quem ataca bem e erra quando precisa esperar.',
    diagrams: [
      diagrama('A área de jogo', 'cozinha', [
        zona(0, 35, 100, 49, 'Cozinha'),
        zona(0, 51, 100, 65, 'Cozinha'),
        jogador(70, 68, 'a', 'A'),
        jogador(30, 32, 'b', 'B'),
        trajeto(70, 66, 32, 40, '1'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-e-ataque-da-bola-alta',
    version: 1,
    kind: 'drill',
    title: 'Dink e ataque da bola alta',
    summary: 'Rally de dink em que só a bola que sobe acima da rede pode ser atacada. Ensina a esperar a bola certa e a atacar para baixo.',
    objective: 'Ao final, o atleta consegue reconhecer a bola atacável e acertar o ataque para baixo, nos pés do adversário, em 6 de 10 chances.',
    skills: ['kitchen.dink_atacavel', 'net.speed_up', 'kitchen.paciencia'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 4,
    roles: ['Alimentador de dink', 'Executor'],
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: 'Os dois na linha da cozinha, na diagonal. O alimentador troca dinks e, de vez em quando, deixa uma bola subir de propósito. O executor dinka e ataca só a bola alta.',
    steps: [
      'Troquem dinks cruzados baixos.',
      'Sem avisar, o alimentador manda um dink mais alto, acima da rede.',
      'O executor ataca essa bola para baixo, nos pés do alimentador.',
      'O alimentador tenta bloquear e o ponto segue até o fim.',
      'Depois de 10 ataques, troquem os papéis.',
    ],
    cues: ['Bola acima da fita: ataque', 'Bola abaixo da fita: dink', 'Ataque para baixo, nos pés'],
    positioning: [
      { type: 'certo', text: 'Ataque com a bola na frente e acima da rede, a raquete terminando para baixo.' },
      { type: 'errado', text: 'Atacar bola que está abaixo da fita: ela precisa subir para passar a rede e vira presente para o contra-ataque.' },
    ],
    common_errors: [
      { error: 'Ataca a bola baixa por ansiedade.', fix: 'Use a regra da fita: só ataque o que está acima dela.' },
      { error: 'O ataque sai longo, para fora da quadra.', fix: 'Mire os pés do adversário: a bola tem de descer logo depois da rede.' },
      { error: 'Depois de atacar, a raquete fica lá embaixo e o contra-ataque passa.', fix: 'Termine o golpe e traga a raquete de volta para a frente do peito.' },
    ],
    variations: {
      easier: 'Tarefa: o alimentador avisa "agora" antes da bola alta.',
      harder: 'Pessoas: os dois podem atacar qualquer bola alta e o ponto é disputado de verdade (vira dink até 11 com ataque).',
    },
    metric: { type: 'percentual', target: '6 de 10 ataques na quadra' },
    success_criteria: 'Conta o ataque que desce e cai na quadra do outro lado. Atacou bola baixa? Não conta, mesmo se entrar.',
    safety: 'Ataque nos pés, nunca no rosto do parceiro de treino. Óculos de proteção ajudam nas trocas rápidas na rede.',
    motor: {
      phases: {
        preparacao: 'Raquete alta e na frente, pronta para o dink ou para o ataque.',
        execucao: 'Na bola alta, gesto curto e rápido de cima para baixo, com a bola na frente do corpo.',
        finalizacao: 'A raquete volta logo para a frente, pronta para o contra-ataque.',
      },
      abilities: ['leitura', 'tempo_reacao', 'precisao'],
    },
    when_to_use: 'No rally de dink, quando o adversário deixa a bola subir acima da rede.',
    diagrams: [
      diagrama('Bola alta e ataque', 'cozinha', [
        jogador(70, 68, 'a', 'Exec'),
        jogador(30, 32, 'b', 'Alim'),
        trajeto(30, 34, 66, 59, '1'),
        bolinha(67, 60),
        texto(84, 58, 'Bola alta'),
        trajeto(70, 66, 32, 36, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'drop-terceira-bola-com-alimentador',
    version: 1,
    featured: true,
    kind: 'drill',
    title: 'Drop da terceira bola com alimentador',
    summary: 'Do fundo da quadra, você faz o drop para a cozinha enquanto o parceiro alimenta da rede. A base para sair do fundo e chegar à cozinha.',
    objective: 'Ao final, o atleta consegue colocar 6 de 10 drops dentro da cozinha, a partir da linha de fundo.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.transicao'],
    level_min: 2.5,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    roles: ['Alimentador', 'Executor'],
    duration_min: 15,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'bloco',
    setup: 'O executor fica atrás da linha de fundo. O alimentador fica na linha da cozinha do outro lado, com o cesto de bolas, e manda bolas fundas e fáceis, como uma devolução de saque.',
    steps: [
      'O alimentador manda uma bola funda, no meio da quadra do executor.',
      'O executor deixa quicar e faz o drop: a bola sobe, passa a rede descendo e cai na cozinha.',
      'O alimentador deixa a bola quicar (não voleia) para ver onde ela caiu.',
      'Contem quantos dos 10 drops caem na cozinha.',
      'Depois de 10, troquem os papéis.',
    ],
    cues: ['Arco de arco-íris, não linha reta', 'Pico da bola antes da rede', 'Raquete termina apontando o alvo'],
    positioning: [
      { type: 'certo', text: 'Bola na frente do corpo, pernas dobradas, raquete baixa e preparada cedo.' },
      { type: 'errado', text: 'Bola ao lado ou atrás do corpo: a face abre tarde e o drop sobe demais.' },
    ],
    common_errors: [
      { error: 'O drop vem rasante na fita e cai no meio da quadra, fácil de atacar.', fix: 'Suba o arco: o ponto mais alto da bola fica do seu lado, um pouco antes da rede.' },
      { error: 'O drop sai alto e passa da cozinha.', fix: 'Encurte o gesto e diminua a força; levante a bola com as pernas, não com a raquete.' },
      { error: 'Você bate com o corpo indo para trás.', fix: 'Termine o golpe com o peso andando para a rede.' },
    ],
    variations: {
      easier: 'Espaço: comece no meio da quadra (zona de transição), onde a distância é menor; recue um passo a cada 3 acertos.',
      harder: 'Tarefa: o alimentador varia a profundidade e o lado da bola, e pode volear o drop alto nos pés do executor.',
    },
    metric: { type: 'percentual', target: '6 de 10 na cozinha' },
    success_criteria: 'Conta o drop que quica na cozinha ou chega tão baixo que o alimentador só consegue bloquear para cima. 6 de 10 duas vezes? Vá para a escada do drop.',
    motor: {
      phases: {
        preparacao: 'Raquete baixa e preparada cedo, pernas dobradas, peso no pé de trás.',
        execucao: 'Contato na frente do corpo, face um pouco aberta, de baixo para cima; as pernas sobem.',
        finalizacao: 'A raquete termina alta, apontando o alvo; dê dois passos para a frente.',
      },
      abilities: ['precisao', 'coordenacao', 'ritmo'],
    },
    when_to_use: 'Terceira bola: a sua dupla sacou, a devolução veio funda e os adversários já estão na cozinha.',
    diagrams: [
      diagrama('Drop do fundo', 'inteira', [
        zona(15, 35, 85, 49, 'Alvo'),
        jogador(50, 96, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 34, 52, 90, '1'),
        trajeto(50, 94, 44, 42, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'escada-do-drop',
    version: 1,
    kind: 'drill',
    title: 'Escada do drop: do meio para o fundo',
    summary: 'Comece fazendo drop perto da cozinha e recue a cada sequência de acertos. Ensina a dosar a força conforme a distância.',
    objective: 'Ao final, o atleta consegue acertar o drop na cozinha a partir de três distâncias: zona de transição, meio do fundo e linha de fundo.',
    skills: ['groundstrokes.terceira_bola_drop', 'net.reset'],
    level_min: 2.5,
    level_max: 4.0,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 15,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'cesto'],
    practice_mode: 'variado',
    setup: 'Três cones no lado do executor: um no meio da quadra (zona de transição), um a dois passos da linha de fundo e um na linha de fundo. O alimentador fica na linha da cozinha do outro lado, com o cesto.',
    steps: [
      'O executor começa no cone da zona de transição.',
      'O alimentador manda bolas fáceis e o executor faz drops para a cozinha.',
      'Acertou 3 seguidos? Recue para o próximo cone.',
      'Errou 2 seguidos? Volte um cone.',
      'Chegou à linha de fundo e acertou 3? Troquem os papéis.',
    ],
    cues: ['Mais longe, arco mais alto', 'Mesmo gesto, só mais pernas', 'Pico antes da rede'],
    positioning: [
      { type: 'certo', text: 'Parado e equilibrado antes de bater, em cada cone.' },
      { type: 'errado', text: 'Bater ainda andando para trás: a bola sai sem controle de distância.' },
    ],
    common_errors: [
      { error: 'O drop do fundo fica curto e morre na rede.', fix: 'Use mais as pernas e mantenha o mesmo gesto; o arco sobe um pouco mais.' },
      { error: 'O drop de perto passa da cozinha.', fix: 'De perto o arco é menor: a raquete quase só levanta a bola.' },
    ],
    variations: {
      easier: 'Espaço: só dois cones (transição e meio) e o alimentador manda bolas lentas.',
      harder: 'Tarefa: o alimentador sorteia a profundidade da bola e o executor precisa sair do cone para ir até ela.',
    },
    metric: { type: 'sequencia', target: '3 seguidos em cada cone' },
    success_criteria: 'Cada degrau exige 3 drops seguidos na cozinha. Fez a escada inteira em menos de 10 minutos? Passe para o jogo 7-11.',
    motor: {
      phases: {
        preparacao: 'Pernas dobradas e raquete baixa antes de a bola quicar.',
        execucao: 'O mesmo gesto curto em todas as distâncias; as pernas dão a força extra no fundo.',
        finalizacao: 'A raquete termina alta, apontando a cozinha.',
      },
      abilities: ['precisao', 'coordenacao'],
    },
    when_to_use: 'Terceira e quinta bolas, e todo drop no caminho para a rede.',
    diagrams: [
      diagrama('Os três degraus', 'inteira', [
        zona(15, 35, 85, 49, 'Alvo'),
        cone(50, 78),
        cone(50, 89),
        cone(50, 98),
        jogador(42, 78, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(42, 76, 46, 42, '1'),
        desloca(36, 80, 36, 96, 'Recue'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'drive-da-terceira-e-drop-da-quinta',
    version: 1,
    kind: 'drill',
    title: 'Drive da terceira e drop da quinta',
    summary: 'Padrão de dois golpes: drive forte na terceira bola e, se ele voltar bloqueado, drop na quinta. Para quem já tem drop e drive.',
    objective: 'Ao final, o atleta consegue emendar drive e drop e chegar à zona de transição em 6 de 10 sequências.',
    skills: ['groundstrokes.terceira_bola_drive', 'groundstrokes.terceira_bola_drop', 'groundstrokes.transicao'],
    level_min: 3.5,
    level_max: 5.0,
    players_min: 2,
    players_max: 4,
    roles: ['Alimentador', 'Executor'],
    duration_min: 15,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'variado',
    setup: 'O executor no fundo; o alimentador (ou dois, com quatro pessoas) na linha da cozinha do outro lado. O alimentador começa com uma bola funda, como a devolução de saque.',
    steps: [
      'O alimentador manda uma bola funda.',
      'O executor faz um drive forte e baixo, nos pés do alimentador.',
      'O alimentador bloqueia o drive de volta, para o meio da quadra.',
      'O executor dá dois passos à frente, faz split step e responde com um drop para a cozinha.',
      'Joguem o ponto até o fim; depois de 10 sequências, troquem.',
    ],
    cues: ['Drive baixo, rente à fita', 'Mire os pés do alimentador', 'Bloqueou? Drop na cozinha'],
    positioning: [
      { type: 'certo', text: 'Depois do drive, avance um pouco e pare antes de o bloqueio chegar.' },
      { type: 'errado', text: 'Correr direto para a rede depois do drive: o bloqueio pega você andando, no pé.' },
    ],
    common_errors: [
      { error: 'O drive sai alto e o alimentador volea para baixo.', fix: 'Feche um pouco a face e mire a fita: o drive bom passa baixo e cai nos pés.' },
      { error: 'Depois do drive você continua no fundo e o drop sai longe.', fix: 'Dê dois passos para a frente e pare: drop mais curto é mais fácil.' },
      { error: 'Faz drive em toda bola, até na bola baixa.', fix: 'Drive na bola alta e funda; bola baixa pede o drop direto.' },
    ],
    variations: {
      easier: 'Tarefa: o alimentador bloqueia sempre devagar e para o meio.',
      harder: 'Pessoas: em 2 contra 2, a dupla na rede pode contra-atacar e a dupla do fundo marca ponto dobrado se chegar inteira à cozinha.',
    },
    metric: { type: 'percentual', target: '6 de 10 sequências' },
    success_criteria: 'Conta a sequência em que o drop da quinta bola cai na cozinha. 6 de 10? Jogue a terceira bola ao vivo.',
    safety: 'Drive é bola rápida: o alimentador usa óculos de proteção e mantém a raquete na frente do rosto.',
    motor: {
      phases: {
        preparacao: 'Raquete atrás cedo, de lado para a rede, peso no pé de trás.',
        execucao: 'Contato na frente, gesto de baixo para cima e para a frente, com o peso indo para a bola.',
        finalizacao: 'A raquete termina alta, do outro lado; volte à base e avance.',
      },
      abilities: ['potencia', 'coordenacao', 'leitura'],
    },
    when_to_use: 'Terceira bola contra quem demora a chegar à rede ou devolve alto e curto.',
    diagrams: [
      diagrama('Drive e drop', 'inteira', [
        jogador(50, 96, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 94, 52, 36, '3'),
        trajeto(52, 34, 52, 80, '4'),
        desloca(58, 95, 58, 82),
        trajeto(56, 80, 46, 42, '5'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'drive-cruzado-de-fundo',
    version: 1,
    kind: 'drill',
    title: 'Drive cruzado de fundo com alvo',
    summary: 'Troca de drives cruzados do fundo, buscando profundidade. Constrói um golpe de fundo consistente e com peso.',
    objective: 'Ao final, o atleta consegue trocar 8 drives cruzados seguidos com a bola caindo no terço final da quadra do parceiro.',
    skills: ['groundstrokes.drive', 'serve.devolucao_profunda'],
    level_min: 2.5,
    level_max: 4.5,
    players_min: 2,
    players_max: 4,
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    setup: 'Os dois atrás da linha de fundo, na diagonal. Cones marcam o terço final de cada lado, cerca de 2 metros antes da linha de fundo.',
    steps: [
      'Um começa com um drive cruzado depois de deixar a bola quicar.',
      'Troquem drives cruzados, sempre depois do quique.',
      'Contem os drives que caem atrás dos cones.',
      'Bola na rede, fora ou antes dos cones zera a conta.',
      'A cada 3 minutos, troquem de diagonal.',
    ],
    cues: ['Bola passa a rede com folga', 'Mire atrás dos cones', 'Raquete termina do outro lado'],
    positioning: [
      { type: 'certo', text: 'De lado para a rede ao preparar e de frente ao terminar o golpe.' },
      { type: 'errado', text: 'De frente para a rede o tempo todo: o golpe vira só de raquete e a bola sai curta.' },
    ],
    common_errors: [
      { error: 'A bola cai curta, no meio da quadra.', fix: 'Mire mais alto acima da fita: a profundidade vem da altura e do peso indo para a frente.' },
      { error: 'A bola vai para fora no fundo.', fix: 'Termine a raquete subindo, e não reta para a frente: o efeito faz a bola descer antes da linha.' },
      { error: 'Você bate atrasado, com a bola ao lado.', fix: 'Prepare a raquete assim que a bola sai da raquete do parceiro.' },
    ],
    variations: {
      easier: 'Espaço: joguem paralelo (distância menor) e a meta passa a 5 seguidos.',
      harder: 'Tarefa: alternem um drive cruzado e um paralelo, os dois jogadores.',
    },
    metric: { type: 'sequencia', target: '8 seguidos' },
    success_criteria: 'Conta o drive que cai atrás dos cones. 8 seguidos nas duas diagonais? Use na terceira bola com drive.',
    motor: {
      phases: {
        preparacao: 'De lado para a rede, raquete atrás cedo, peso no pé de trás.',
        execucao: 'Passo à frente, contato na frente do corpo, gesto de baixo para cima.',
        finalizacao: 'A raquete termina alta do lado oposto; volte à base.',
      },
      abilities: ['coordenacao', 'potencia', 'ritmo'],
    },
    when_to_use: 'Devolução de saque, terceira bola com drive e qualquer troca de bolas no fundo.',
    diagrams: [
      diagrama('Terço final', 'inteira', [
        cone(10, 15),
        cone(40, 15),
        cone(60, 85),
        cone(90, 85),
        jogador(75, 97, 'a', 'A'),
        jogador(25, 3, 'b', 'B'),
        trajeto(75, 95, 25, 8, '1'),
        trajeto(25, 5, 75, 92, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'reset-na-zona-de-transicao',
    version: 1,
    featured: true,
    kind: 'drill',
    title: 'Reset na zona de transição',
    summary: 'Você avança do fundo e o parceiro, na rede, manda bolas firmes nos seus pés. A missão é amortecer a bola de volta para a cozinha e seguir avançando.',
    objective: 'Ao final, o atleta consegue amortecer 6 de 10 bolas firmes para dentro da cozinha e chegar à linha em até três golpes.',
    skills: ['net.reset', 'groundstrokes.transicao'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Atacante na rede', 'Quem avança'],
    duration_min: 15,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'variado',
    setup: 'O atacante fica na linha da cozinha com o cesto. Quem avança começa na linha de fundo do outro lado, no meio.',
    steps: [
      'O atacante manda uma bola funda; quem avança faz um drop e anda dois passos.',
      'Quando o atacante vai bater, quem avança para com um split step.',
      'O atacante manda uma bola firme e baixa nos pés de quem avança.',
      'Quem avança faz o reset: amortece a bola para a cozinha, com gesto curto.',
      'Se o reset caiu na cozinha, avance mais dois passos e repita; chegou à linha, o ponto segue com dinks.',
      'Depois de 10 sequências, troquem.',
    ],
    cues: ['Raquete na frente, face para cima', 'Amorteça como quem pega um ovo', 'Pare quando ele bater'],
    positioning: [
      { type: 'certo', text: 'Parado em split step quando o atacante bate, pernas dobradas e raquete baixa na frente.' },
      { type: 'errado', text: 'Ainda correndo quando a bola chega: ela bate no pé ou volta alta.' },
    ],
    common_errors: [
      { error: 'O reset volta alto e o atacante finaliza.', fix: 'Tire força: raquete quase parada e um pouco aberta; a bola só bate e cai.' },
      { error: 'Você corre direto para a rede e é atacado no meio do caminho.', fix: 'Avance quando a bola estiver lenta e pare quando o adversário bater.' },
      { error: 'Tenta fazer o reset com balanço grande.', fix: 'Gesto do tamanho de um palmo: a velocidade vem da bola dele.' },
    ],
    variations: {
      easier: 'Equipamento: o atacante alimenta com a mão ou com bolas mais lentas, sem pressa.',
      harder: 'Pessoas: o atacante joga para ganhar e pode alternar ataque e dink curto; quem avança marca 1 ponto a cada chegada à linha.',
    },
    metric: { type: 'percentual', target: '6 de 10 resets na cozinha' },
    success_criteria: 'Conta o reset que cai na cozinha ou volta tão baixo que o atacante não consegue atacar. Chegou à linha em 3 golpes ou menos em 6 de 10? Suba de nível.',
    safety: 'Óculos de proteção para quem avança: as bolas vêm rápidas e na altura do corpo. Atacante: bolas firmes nos pés, não no rosto.',
    motor: {
      phases: {
        preparacao: 'Split step quando o atacante bate, pernas dobradas, raquete baixa e na frente.',
        execucao: 'Raquete quase parada, face um pouco aberta; a bola bate e perde velocidade.',
        finalizacao: 'A raquete fica na frente; avance se a bola caiu curta.',
      },
      abilities: ['tempo_reacao', 'equilibrio', 'precisao', 'leitura'],
    },
    when_to_use: 'Quando você ainda não chegou à cozinha e o adversário ataca nos seus pés.',
    diagrams: [
      diagrama('Avançar, parar, amortecer', 'inteira', [
        jogador(50, 96, 'a', 'A'),
        jogador(50, 32, 'b', 'Rede'),
        desloca(50, 94, 50, 81, '1'),
        texto(64, 80, 'Split'),
        trajeto(52, 34, 52, 77, '2'),
        trajeto(48, 77, 46, 44, '3'),
        desloca(42, 78, 42, 70, '4'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'reset-de-bloqueio-nos-pes',
    version: 1,
    kind: 'drill',
    title: 'Reset de bloqueio nos pés',
    summary: 'Parado na zona de transição, você recebe bolas firmes nos pés e devolve todas para a cozinha. Repetição do reset de forehand e de backhand.',
    objective: 'Ao final, o atleta consegue amortecer 7 de 10 bolas nos pés, de forehand e de backhand, para dentro da cozinha.',
    skills: ['net.reset', 'net.voleio'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'bloco',
    setup: 'O executor fica parado no meio da quadra, entre a linha da cozinha e o fundo. O alimentador fica na linha da cozinha do outro lado, com o cesto.',
    steps: [
      'O alimentador manda bolas firmes e baixas nos pés do executor: 5 de forehand e 5 de backhand.',
      'O executor amortece cada bola para a cozinha, depois do quique ou de voleio.',
      'O alimentador não devolve; só observa onde a bola caiu.',
      'Na segunda rodada, o alimentador mistura forehand e backhand sem avisar.',
      'Depois de 2 rodadas, troquem.',
    ],
    cues: ['Raquete baixa, face para o céu', 'Absorva a bola, sem empurrar', 'Bola morre na cozinha'],
    positioning: [
      { type: 'certo', text: 'Pernas bem dobradas para a raquete chegar baixa, com a face aberta.' },
      { type: 'errado', text: 'Pernas esticadas e raquete apontando para o chão: a bola sobe e passa da cozinha.' },
    ],
    common_errors: [
      { error: 'A bola volta alta.', fix: 'Abaixe-se até a bola em vez de abaixar só a raquete; a face aberta faz o resto.' },
      { error: 'A bola bate na rede.', fix: 'Abra um pouco mais a face e deixe a bola subir antes da rede.' },
    ],
    variations: {
      easier: 'Equipamento: alimentação com a mão, devagar e só de forehand.',
      harder: 'Tarefa: depois do reset, o alimentador escolhe atacar de novo ou dinkar, e o ponto é jogado.',
    },
    metric: { type: 'percentual', target: '7 de 10 na cozinha' },
    success_criteria: 'Conta o reset que cai na cozinha. 7 de 10 com forehand e backhand misturados? Vá para o reset na zona de transição.',
    safety: 'Óculos de proteção para o executor; o alimentador mira os pés.',
    motor: {
      phases: {
        preparacao: 'Base larga, pernas bem dobradas, raquete baixa e na frente.',
        execucao: 'A raquete encontra a bola na frente e cede um pouco, como um travesseiro.',
        finalizacao: 'A raquete termina curta, apontando a cozinha.',
      },
      abilities: ['tempo_reacao', 'precisao', 'equilibrio'],
    },
    when_to_use: 'Bolas rápidas nos pés quando você está entre o fundo e a cozinha.',
    diagrams: [
      diagrama('Bolas nos pés', 'inteira', [
        zona(15, 35, 85, 49, 'Alvo'),
        jogador(50, 80, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 34, 44, 78, '1'),
        trajeto(44, 78, 52, 42, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'devolucao-de-saque-funda',
    version: 1,
    kind: 'drill',
    title: 'Devolução de saque funda',
    summary: 'Devolva o saque para o terço final da quadra adversária. Devolução funda deixa o sacador lá atrás e dá tempo para você chegar à cozinha.',
    objective: 'Ao final, o atleta consegue colocar 7 de 10 devoluções de saque no terço final da quadra do sacador.',
    skills: ['serve.devolucao_profunda', 'groundstrokes.drive'],
    level_min: 2.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    roles: ['Sacador', 'Devolvedor'],
    duration_min: 12,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    setup: 'Cones marcam o terço final da quadra do sacador, cerca de 2 metros antes da linha de fundo. O devolvedor fica um passo atrás da linha de fundo, na diagonal do sacador.',
    steps: [
      'O sacador saca normalmente na diagonal.',
      'O devolvedor deixa quicar e devolve alto e fundo, para trás dos cones.',
      'Depois de devolver, o devolvedor anda até a linha da cozinha.',
      'Contem quantas das 10 devoluções passam dos cones.',
      'Depois de 10, troquem os papéis e a diagonal.',
    ],
    cues: ['Bola alta e funda', 'Mire atrás dos cones', 'Devolveu? Ande até a cozinha'],
    positioning: [
      { type: 'certo', text: 'Um passo atrás da linha de fundo esperando o saque: é mais fácil andar para a frente.' },
      { type: 'errado', text: 'Em cima da linha de fundo: o saque fundo obriga você a recuar e a devolver curto.' },
    ],
    common_errors: [
      { error: 'A devolução cai curta e o sacador ataca.', fix: 'Mire mais alto: a bola passa bem acima da rede e cai lá no fundo.' },
      { error: 'Você devolve e fica parado no fundo.', fix: 'Termine o golpe já andando para a frente, até a cozinha.' },
      { error: 'A devolução vai para fora.', fix: 'Mire o meio da quadra, longe das linhas: profundidade vale mais que canto.' },
    ],
    variations: {
      easier: 'Espaço: o alvo passa a ser a metade de trás da quadra.',
      harder: 'Tarefa: alternem o alvo entre o backhand do sacador e o meio; o sacador joga a terceira bola e o ponto segue.',
    },
    metric: { type: 'percentual', target: '7 de 10 atrás dos cones' },
    success_criteria: 'Conta a devolução que quica atrás dos cones. 7 de 10 nas duas diagonais? Treine devolver e chegar à cozinha.',
    motor: {
      phases: {
        preparacao: 'Um passo atrás da linha, raquete na frente, pronta para os dois lados.',
        execucao: 'Passo à frente na bola e gesto longo e lento, de baixo para cima.',
        finalizacao: 'A raquete termina alta e você já está andando para a rede.',
      },
      abilities: ['precisao', 'leitura', 'coordenacao'],
    },
    when_to_use: 'Toda devolução de saque em duplas.',
    diagrams: [
      diagrama('Devolução funda', 'inteira', [
        cone(10, 15),
        cone(90, 15),
        jogador(25, 3, 'b', 'Sac'),
        jogador(75, 98, 'a', 'Dev'),
        trajeto(25, 5, 72, 90, '1'),
        trajeto(75, 96, 38, 9, '2'),
        desloca(80, 96, 72, 70, '3'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'devolver-e-chegar-a-cozinha',
    version: 1,
    kind: 'drill',
    title: 'Devolver e chegar à cozinha',
    summary: 'Devolução funda e caminhada até a linha antes de a terceira bola chegar. Treina o hábito que mais separa o iniciante do intermediário.',
    objective: 'Ao final, o atleta consegue devolver fundo e estar parado na linha da cozinha quando o sacador bate a terceira bola, em 7 de 10 pontos.',
    skills: ['serve.devolucao_profunda', 'doubles.posicionamento', 'groundstrokes.transicao'],
    level_min: 2.5,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: '1 contra 1 na diagonal (ou 2 contra 2). O sacador fica no fundo; o devolvedor, um passo atrás da linha de fundo.',
    steps: [
      'O sacador saca; o devolvedor devolve alto e fundo.',
      'O devolvedor anda rápido até a cozinha enquanto a bola viaja.',
      'Na linha, ele para em split step quando o sacador bate a terceira bola.',
      'Joguem o ponto até o fim.',
      'Ponto em que o devolvedor já estava parado na linha na terceira bola vale 2; troquem a cada 10 pontos.',
    ],
    cues: ['Bola alta compra tempo', 'Chegue antes da terceira bola', 'Pare quando ele bater'],
    positioning: [
      { type: 'certo', text: 'Na terceira bola, os dois pés atrás da linha da cozinha, parados e de frente para a bola.' },
      { type: 'errado', text: 'Ainda correndo no meio da quadra quando o sacador bate: a terceira bola pega você no pé.' },
    ],
    common_errors: [
      { error: 'A devolução sai rápida e baixa e não dá tempo de chegar.', fix: 'Devolução mais alta e mais lenta: é ela que compra o tempo da caminhada.' },
      { error: 'Chega à linha ainda correndo e passa por cima dela.', fix: 'Encurte os passos perto da linha e pare antes dela.' },
    ],
    variations: {
      easier: 'Tarefa: o sacador faz uma terceira bola fácil, sempre no meio.',
      harder: 'Tarefa: o sacador alterna drop e drive na terceira bola; o devolvedor precisa ler e reagir parado.',
    },
    metric: { type: 'percentual', target: '7 de 10 na linha a tempo' },
    success_criteria: 'Conta o ponto em que o devolvedor estava parado na linha quando o sacador bateu a terceira bola. 7 de 10? Leve o hábito para o jogo.',
    safety: 'Freie com passos curtos e pernas dobradas, sem escorregar sobre a linha.',
    motor: {
      phases: {
        preparacao: 'Devolução com o peso já indo para a frente.',
        execucao: 'Passos rápidos e curtos enquanto a bola viaja.',
        finalizacao: 'Split step parado, base aberta e raquete na frente.',
      },
      abilities: ['agilidade', 'equilibrio', 'leitura'],
    },
    when_to_use: 'Toda vez que a sua dupla recebe o saque.',
    diagrams: [
      diagrama('Devolver e subir', 'inteira', [
        jogador(25, 3, 'b', 'Sac'),
        jogador(75, 98, 'a', 'Dev'),
        trajeto(75, 96, 38, 9, '1'),
        desloca(80, 96, 72, 69, '2'),
        texto(86, 70, 'Split'),
        trajeto(25, 6, 64, 62, '3'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'saque-fundo-com-alvo',
    version: 1,
    kind: 'drill',
    title: 'Saque fundo com alvo',
    summary: 'Saque em série para o terço final da área de saque, com um alvo no fundo. Treina primeiro a consistência e depois a profundidade.',
    objective: 'Ao final, o atleta consegue colocar 8 de 10 saques válidos e 5 de 10 no terço final da área de saque.',
    skills: ['serve.saque_profundo', 'serve.consistencia'],
    level_min: 2.0,
    level_max: 4.5,
    players_min: 1,
    players_max: 4,
    duration_min: 12,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'alvo', 'cesto'],
    practice_mode: 'bloco',
    setup: 'Na área de saque da diagonal, cones marcam o terço final (cerca de 2 metros antes da linha de fundo). Um alvo (toalha, bambolê ou cone deitado) fica no fundo, perto da linha central. O sacador começa atrás da linha de fundo, com o cesto de bolas.',
    steps: [
      'Saque 10 bolas para a área marcada, sem pressa.',
      'Conte quantas são válidas e quantas passam dos cones.',
      'Saque mais 10 mirando o alvo.',
      'Troque para a outra diagonal e repita.',
      'Antes de cada saque, faça a mesma rotina: olhe o alvo, respire e saque.',
    ],
    cues: ['Bola sobe antes de descer funda', 'Mire o alvo, não a rede', 'Mesma rotina em todo saque'],
    positioning: [
      { type: 'certo', text: 'Os dois pés atrás da linha de fundo, entre o prolongamento da linha central e o da lateral.' },
      { type: 'errado', text: 'Pé em cima da linha de fundo na hora do contato: é falta de saque.' },
    ],
    common_errors: [
      { error: 'O saque cai curto, no meio da área.', fix: 'Termine a raquete subindo na direção do alvo, como quem joga a bola por cima de um muro.' },
      { error: 'Muitos saques na rede.', fix: 'Contato na frente do corpo e a bola subindo: mire um metro acima da fita.' },
      { error: 'Você muda a rotina a cada saque.', fix: 'Use sempre a mesma: olhe o alvo, respire, saque.' },
    ],
    variations: {
      easier: 'Espaço: o alvo é a área de saque inteira; meta de 8 de 10 válidos.',
      harder: 'Tarefa: anuncie o alvo antes de sacar (fundo no meio ou fundo na lateral); só vale o saque que cai na metade anunciada.',
    },
    metric: { type: 'percentual', target: '8 de 10 válidos, 5 no fundo' },
    success_criteria: 'Conta o saque que cai na área certa; o bom é o que passa dos cones. 8 válidos e 5 fundos em duas séries? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'De lado para a rede, bola na frente, raquete atrás e baixa.',
        execucao: 'Gesto de baixo para cima, com o contato abaixo da cintura e na frente do corpo.',
        finalizacao: 'A raquete termina alta, apontando o alvo; continue atrás da linha.',
      },
      abilities: ['precisao', 'ritmo', 'coordenacao'],
    },
    when_to_use: 'Todo saque. Saque fundo empurra o devolvedor para trás e dificulta a chegada dele à rede.',
    diagrams: [
      diagrama('Alvo no fundo', 'inteira', [
        zona(1, 1, 49, 15, 'Fundo'),
        cone(3, 15),
        cone(47, 15),
        texto(40, 6, 'Alvo'),
        jogador(75, 98, 'a', 'Sac'),
        trajeto(75, 96, 40, 9, '1'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'voleio-de-bloqueio-contra-drive',
    version: 1,
    kind: 'drill',
    title: 'Voleio de bloqueio contra o drive',
    summary: 'Na linha da cozinha, você bloqueia drives fortes vindos do fundo e devolve a bola curta. Para quem leva bola rápida na rede.',
    objective: 'Ao final, o atleta consegue bloquear 7 de 10 drives fortes de volta para a quadra, 4 deles dentro da cozinha.',
    skills: ['net.voleio', 'net.contra_ataque', 'net.reset'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Batedor de drive', 'Bloqueador'],
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'bloco',
    setup: 'O bloqueador fica na linha da cozinha. O batedor fica no fundo do outro lado, com o cesto, e bate drives firmes depois de deixar a bola quicar.',
    steps: [
      'O batedor deixa a bola quicar e bate um drive firme no bloqueador.',
      'O bloqueador volea com a raquete parada na frente, sem balançar.',
      'A meta é devolver curto, de preferência na cozinha.',
      'Contem quantos bloqueios voltam para a quadra e quantos caem na cozinha.',
      'Depois de 10, troquem.',
    ],
    cues: ['Raquete parada, como um muro', 'Encontre a bola na frente', 'Bola morre perto da rede'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente do peito, cabeça da raquete para cima, entre o forehand e o backhand.' },
      { type: 'errado', text: 'Raquete baixa ou de lado: a bola rápida chega antes de a raquete subir.' },
    ],
    common_errors: [
      { error: 'O bloqueio vai longe, para o fundo.', fix: 'Raquete parada e um pouco aberta: a bola só bate e perde força.' },
      { error: 'Você balança a raquete e a bola sai para fora.', fix: 'Pense em muro, não em martelo.' },
      { error: 'Pega a bola atrasado, ao lado do corpo.', fix: 'Raquete na frente desde o começo; dê meio passo à frente se der tempo.' },
    ],
    variations: {
      easier: 'Equipamento: drives a meia velocidade e só no forehand.',
      harder: 'Tarefa: o batedor mistura drive, drop e lob; o bloqueador lê e decide.',
    },
    metric: { type: 'percentual', target: '7 de 10 na quadra, 4 na cozinha' },
    success_criteria: 'Conta o bloqueio que volta para a quadra; vale ouro o que cai na cozinha. 7 de 10 com 4 na cozinha? Jogue a variação mais difícil.',
    safety: 'Óculos de proteção para o bloqueador. O batedor bate firme, mas no corpo e nos pés, nunca no rosto.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente do peito, base aberta, peso na frente.',
        execucao: 'A raquete encontra a bola na frente e quase não anda.',
        finalizacao: 'A raquete volta para a frente do peito.',
      },
      abilities: ['tempo_reacao', 'precisao'],
    },
    when_to_use: 'Terceira bola com drive quando você já está na cozinha.',
    diagrams: [
      diagrama('Bloqueio na linha', 'inteira', [
        jogador(50, 68, 'a', 'Bloq'),
        jogador(50, 4, 'b', 'Drive'),
        trajeto(50, 6, 50, 64, '1'),
        trajeto(50, 66, 44, 42, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'voleio-firme-nos-pes',
    version: 1,
    kind: 'drill',
    title: 'Voleio firme (punch) nos pés',
    summary: 'Voleio curto e firme, com alvo nos pés de quem está na zona de transição. Para fechar o ponto sem dar chance de contra-ataque.',
    objective: 'Ao final, o atleta consegue colocar 6 de 10 voleios firmes nos pés do parceiro que está na zona de transição.',
    skills: ['net.voleio', 'tactics.alvo'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    setup: 'O executor na linha da cozinha. O alimentador do outro lado, na zona de transição, com dois cones ao lado dos pés dele marcando o alvo.',
    steps: [
      'O alimentador manda uma bola média, na altura do peito do executor.',
      'O executor faz um voleio curto e firme, sem balanço, para os pés do alimentador.',
      'O alimentador tenta devolver; se a bola voltar alta, o executor volea de novo.',
      'Contem quantos voleios caem entre os cones.',
      'Depois de 10, troquem.',
    ],
    cues: ['Gesto curto, como um soco', 'Mire entre os cones', 'Raquete termina apontando o alvo'],
    positioning: [
      { type: 'certo', text: 'Contato na frente do corpo, com a raquete firme e o gesto terminando curto.' },
      { type: 'errado', text: 'Voleio com balanço grande, como no tênis: a bola sai longa e você se atrasa para a próxima.' },
    ],
    common_errors: [
      { error: 'O voleio sai longo, para o fundo.', fix: 'Diminua o gesto: a raquete anda um palmo e para.' },
      { error: 'O voleio vai na raquete do alimentador, na altura da cintura.', fix: 'Mire mais baixo, entre os cones.' },
    ],
    variations: {
      easier: 'Espaço: cones a 1,5 metro um do outro e bolas mais lentas.',
      harder: 'Tarefa: o alimentador anda para a frente e para trás; o executor mira os pés onde ele estiver.',
    },
    metric: { type: 'percentual', target: '6 de 10 nos pés' },
    success_criteria: 'Conta o voleio que quica entre os cones. 6 de 10? Use no jogo quando o adversário estiver no meio da quadra.',
    safety: 'O alvo são os pés. O alimentador usa óculos de proteção, se tiver.',
    motor: {
      phases: {
        preparacao: 'Raquete alta e na frente, base aberta.',
        execucao: 'Gesto curto para a frente e um pouco para baixo, com a raquete firme.',
        finalizacao: 'A raquete para logo depois do contato, apontando o alvo.',
      },
      abilities: ['precisao', 'tempo_reacao'],
    },
    when_to_use: 'Bola acima da rede vinda de quem ainda está no meio da quadra.',
    diagrams: [
      diagrama('Voleio nos pés', 'inteira', [
        cone(44, 20),
        cone(56, 20),
        jogador(50, 68, 'a', 'Exec'),
        jogador(50, 18, 'b', 'Alim'),
        trajeto(48, 20, 48, 64, '1'),
        trajeto(52, 66, 50, 22, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'troca-rapida-de-voleios',
    version: 1,
    kind: 'drill',
    title: 'Troca rápida de voleios na rede',
    summary: 'Os dois na cozinha trocando voleios rápidos, de forma cooperativa. Treina o reflexo e a raquete sempre pronta na frente.',
    objective: 'Ao final, o atleta consegue manter 15 voleios rápidos seguidos com o parceiro, sem a bola tocar o chão.',
    skills: ['net.contra_ataque', 'net.voleio'],
    level_min: 3.0,
    level_max: 5.0,
    players_min: 2,
    players_max: 4,
    duration_min: 8,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: 'Os dois na linha da cozinha, frente a frente; se precisarem de mais tempo, um passo atrás da linha. Com quatro pessoas, duas duplas lado a lado.',
    steps: [
      'Comecem devagar, voleando para a raquete do parceiro, na altura do peito.',
      'A cada 5 voleios seguidos, aumentem um pouco a velocidade.',
      'Mantenham a bola entre a cintura e o peito do parceiro.',
      'Errou, a velocidade volta para a inicial.',
      'Rodadas de 1 minuto com 30 segundos de descanso.',
    ],
    cues: ['Raquete na frente do peito', 'Bola na raquete do parceiro', 'Gesto curto, raquete volta'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente, com a cabeça para cima, pronta para o forehand e o backhand.' },
      { type: 'errado', text: 'Raquete caída entre uma bola e outra: a próxima chega antes de ela subir.' },
    ],
    common_errors: [
      { error: 'A troca vira competição e ninguém acerta dois seguidos.', fix: 'Primeiro cooperem: a meta é o parceiro conseguir devolver.' },
      { error: 'Você usa só o forehand e se atrasa nas bolas no meio do corpo.', fix: 'Bola no meio do corpo sai melhor de backhand, com a raquete na frente.' },
    ],
    variations: {
      easier: 'Espaço: os dois um passo atrás da linha, para ter mais tempo.',
      harder: 'Tarefa: depois de 10 seguidos, vale ponto: quem conseguir uma bola nos pés do outro ganha.',
    },
    metric: { type: 'sequencia', target: '15 seguidos' },
    success_criteria: 'Conta voleio seguido sem a bola cair. 15 seguidos em duas rodadas? Passe para o speed-up e contra-ataque.',
    safety: 'Óculos de proteção recomendados. Velocidade sempre combinada: troca cooperativa, mirando a raquete, não o rosto.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente do peito, pernas um pouco dobradas, peso na frente.',
        execucao: 'Gesto curto, de bloqueio ou de soco leve, com a bola na frente.',
        finalizacao: 'A raquete volta para a frente do peito.',
      },
      abilities: ['tempo_reacao', 'coordenacao', 'ritmo'],
    },
    when_to_use: 'Trocas rápidas na rede, principalmente depois de um speed-up.',
    diagrams: [
      diagrama('Troca na rede', 'cozinha', [
        jogador(50, 68, 'a', 'A'),
        jogador(50, 32, 'b', 'B'),
        trajeto(47, 66, 47, 34, '1'),
        trajeto(53, 34, 53, 66, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'speed-up-e-contra-ataque',
    version: 1,
    kind: 'drill',
    title: 'Speed-up e contra-ataque',
    summary: 'No rally de dink, um acelera a bola (speed-up) e o outro contra-ataca. Treina a hora certa de acelerar e a defesa rápida.',
    objective: 'Ao final, o atleta consegue acelerar só bolas acima da rede e contra-atacar 5 de 10 acelerações recebidas.',
    skills: ['net.speed_up', 'net.contra_ataque', 'kitchen.dink_atacavel'],
    level_min: 3.5,
    level_max: 5.0,
    players_min: 2,
    players_max: 4,
    roles: ['Atacante', 'Defensor'],
    duration_min: 12,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'aleatorio',
    setup: 'Os dois na linha da cozinha, na diagonal. Combinem quem ataca na rodada.',
    steps: [
      'Troquem dinks cruzados.',
      'O atacante escolhe uma bola mais alta e acelera, mirando o ombro do lado da raquete do defensor.',
      'O defensor contra-ataca com a raquete na frente, para os pés do atacante.',
      'Joguem a troca até alguém errar.',
      'Ataque que vence vale 1 ponto para o atacante; contra-ataque que vence vale 1 para o defensor. Troquem a cada 10 ataques.',
    ],
    cues: ['Acelere só acima da fita', 'Raquete na frente, sempre', 'Responda para os pés'],
    positioning: [
      { type: 'certo', text: 'Defensor com a raquete na frente do peito e base aberta durante todo o dink.' },
      { type: 'errado', text: 'Defensor com a raquete baixa depois do dink: a aceleração passa antes de ele reagir.' },
    ],
    common_errors: [
      { error: 'O atacante acelera bolas baixas e manda para fora.', fix: 'Acelere a bola que está acima da rede; a bola baixa pede mais um dink.' },
      { error: 'O defensor balança para contra-atacar e chega atrasado.', fix: 'Bloqueie curto primeiro; o contra-ataque forte vem quando a bola sobe.' },
      { error: 'Depois de acelerar, o atacante fica parado.', fix: 'Raquete de volta à frente logo depois de bater: a bola costuma voltar rápido.' },
    ],
    variations: {
      easier: 'Tarefa: o atacante avisa "vai" um dink antes de acelerar.',
      harder: 'Pessoas: em 2 contra 2, qualquer um pode acelerar e o ponto vale de verdade.',
    },
    metric: { type: 'placar', target: 'Primeiro a 7 pontos' },
    success_criteria: 'Atacou bola abaixo da fita? Perde o ponto mesmo se ganhar a troca. Defensor com 5 contra-ataques vencedores em 10? Troquem os papéis e subam a meta.',
    safety: 'Óculos de proteção recomendados. Aceleração no ombro, no peito ou no pé; mirar o rosto do parceiro de treino está fora do combinado.',
    motor: {
      phases: {
        preparacao: 'Raquete alta e na frente durante o dink, pernas dobradas.',
        execucao: 'No ataque, gesto curto e rápido para a frente; na defesa, raquete firme, em bloqueio ou soco curto.',
        finalizacao: 'Os dois voltam a raquete para a frente do peito.',
      },
      abilities: ['tempo_reacao', 'leitura', 'potencia'],
    },
    when_to_use: 'Rally de dink quando a bola sobe, e toda vez que o adversário acelera em você.',
    diagrams: [
      diagrama('Dink, aceleração, resposta', 'cozinha', [
        jogador(70, 68, 'a', 'At'),
        jogador(30, 32, 'b', 'Def'),
        trajeto(30, 34, 68, 58, '1'),
        trajeto(70, 66, 28, 34, '2'),
        trajeto(32, 34, 72, 64, '3'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'lob-e-recuperacao',
    version: 1,
    kind: 'drill',
    title: 'Lob e recuperação: virar e correr',
    summary: 'O parceiro joga um lob por cima de você na cozinha; você vira, corre e devolve. Treina a forma segura de recuperar o lob, sem andar de costas.',
    objective: 'Ao final, o atleta consegue recuperar 6 de 10 lobs com o deslocamento certo (virar e correr) e devolver a bola para a quadra.',
    skills: ['groundstrokes.lob', 'physical.agilidade', 'doubles.cobertura_meio'],
    level_min: 2.5,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Quem joga o lob', 'Quem recupera'],
    duration_min: 12,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'variado',
    setup: 'Quem recupera começa na linha da cozinha. Quem joga o lob fica na linha da cozinha do outro lado, com o cesto.',
    steps: [
      'Troquem 2 ou 3 dinks.',
      'Quem joga o lob manda uma bola alta, por cima da cabeça do outro, para o fundo.',
      'Quem recupera vira de lado e corre em diagonal até atrás da bola, sem andar de costas.',
      'Deixe quicar se precisar e devolva com um lob alto ou um drop.',
      'Volte para a cozinha com o próximo golpe; depois de 10 lobs, troquem.',
    ],
    cues: ['Vire e corra atrás da bola', 'Chegue atrás da bola, não embaixo', 'Devolução alta compra tempo'],
    positioning: [
      { type: 'certo', text: 'Vira o corpo e corre em diagonal, de lado ou de frente para onde vai.' },
      { type: 'errado', text: 'Anda de costas olhando a bola: é o jeito mais comum de cair e se machucar na quadra.' },
    ],
    common_errors: [
      { error: 'Você corre para baixo da bola e fica sem espaço para bater.', fix: 'Corra para um ponto atrás de onde a bola vai cair.' },
      { error: 'Devolve com força, do fundo e correndo.', fix: 'Devolução alta e lenta: ela dá tempo de voltar.' },
    ],
    variations: {
      easier: 'Tarefa: o lob é avisado e mais baixo, só até o meio do fundo.',
      harder: 'Tarefa: o lob vem sem aviso, no meio de um rally de dinks, e quem jogou o lob avança para atacar.',
    },
    metric: { type: 'percentual', target: '6 de 10 recuperados' },
    success_criteria: 'Conta a recuperação com o deslocamento certo e a bola de volta na quadra. Andou de costas? Não conta.',
    safety: 'Vire e corra; andar de costas atrás do lob é uma das causas mais comuns de queda no pickleball. Comece com lobs curtos e avisados.',
    motor: {
      phases: {
        preparacao: 'Leia o lob cedo: o primeiro passo já vira o corpo para o lado da bola.',
        execucao: 'Corrida em diagonal até atrás do ponto de queda.',
        finalizacao: 'Pare de lado, bata e volte andando para a frente.',
      },
      abilities: ['agilidade', 'leitura', 'equilibrio'],
    },
    when_to_use: 'Sempre que o adversário joga lob por cima de você na cozinha.',
    diagrams: [
      diagrama('Virar e correr', 'inteira', [
        jogador(70, 68, 'a', 'Rec'),
        jogador(30, 32, 'b', 'Lob'),
        trajeto(30, 34, 72, 90, '1'),
        desloca(66, 70, 78, 93, '2'),
        trajeto(78, 92, 40, 20, '3'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'lob-de-ataque-no-dink',
    version: 1,
    kind: 'drill',
    title: 'Lob de ataque no meio do dink',
    summary: 'Durante o rally de dink, um lob bem disfarçado por cima do adversário. Para quem já domina o dink e quer surpreender.',
    objective: 'Ao final, o atleta consegue colocar 5 de 10 lobs de ataque no fundo, atrás do adversário, sem dar chance de smash.',
    skills: ['groundstrokes.lob', 'tactics.selecao_golpe', 'tactics.leitura_adversario'],
    level_min: 3.5,
    level_max: 5.0,
    players_min: 2,
    players_max: 2,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'aleatorio',
    setup: 'Os dois na linha da cozinha, na diagonal ou de frente. Combinem quem pode jogar lob na rodada.',
    steps: [
      'Troquem dinks baixos.',
      'Quem pode jogar lob escolhe a hora: de preferência quando o outro está inclinado para a frente ou fora de posição.',
      'Faça o lob com a mesma preparação do dink, levantando a bola por cima da raquete erguida do outro.',
      'O outro tenta recuperar ou dar smash; joguem o ponto.',
      'Depois de 10 lobs, troquem.',
    ],
    cues: ['Comece igual ao dink', 'Bola por cima da raquete erguida', 'Mire o fundo do backhand'],
    positioning: [
      { type: 'certo', text: 'Lob de dentro da quadra, com a bola na frente e o adversário inclinado para a frente.' },
      { type: 'errado', text: 'Lob depois de recuar, com o adversário parado e pronto: vira smash.' },
    ],
    common_errors: [
      { error: 'O lob sai baixo e o adversário dá smash.', fix: 'Mire mais alto: a bola tem de passar por cima da raquete erguida dele.' },
      { error: 'O lob sai para fora no fundo.', fix: 'Menos força e mais altura: o lob cai pelo próprio peso.' },
      { error: 'Todo mundo percebe que vem lob.', fix: 'Prepare igual ao dink e só no fim levante a raquete.' },
    ],
    variations: {
      easier: 'Tarefa: o lob sai de uma bola jogada com a mão, sem rally.',
      harder: 'Pessoas: em 2 contra 2, o lob é cruzado e a dupla que defende precisa trocar de lado.',
    },
    metric: { type: 'percentual', target: '5 de 10 atrás do adversário' },
    success_criteria: 'Conta o lob que quica no terço final sem o adversário alcançar de voleio. 5 de 10? Use no jogo contra quem se inclina muito na rede.',
    safety: 'Quem recupera vira e corre; nunca recue de costas.',
    motor: {
      phases: {
        preparacao: 'A mesma preparação do dink, raquete na frente e baixa.',
        execucao: 'Gesto de baixo para cima mais longo, com a face aberta.',
        finalizacao: 'A raquete termina alta, apontando o céu; volte à base.',
      },
      abilities: ['leitura', 'precisao'],
    },
    when_to_use: 'Rally de dink contra quem fica muito colado na rede, inclinado para a frente ou fora de posição.',
    diagrams: [
      diagrama('Lob por cima', 'inteira', [
        jogador(70, 68, 'a', 'A'),
        jogador(30, 32, 'b', 'B'),
        trajeto(70, 66, 40, 7, 'Lob'),
        desloca(32, 30, 38, 10, 'Volta'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'smash-depois-do-lob',
    version: 1,
    kind: 'drill',
    title: 'Smash no lob curto',
    summary: 'O parceiro joga lobs curtos e você finaliza com smash para os pés ou para o meio. Para não desperdiçar o lob ruim do adversário.',
    objective: 'Ao final, o atleta consegue finalizar 7 de 10 lobs curtos com smash para baixo, dentro da quadra.',
    skills: ['net.smash'],
    level_min: 3.0,
    level_max: 5.0,
    players_min: 2,
    players_max: 2,
    roles: ['Quem joga o lob', 'Quem dá o smash'],
    duration_min: 10,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'bloco',
    setup: 'Quem dá o smash fica a dois passos da linha da cozinha. Quem joga o lob fica no fundo do outro lado, com o cesto.',
    steps: [
      'Quem joga o lob manda uma bola alta e curta, que cai entre a cozinha e o meio da quadra.',
      'Quem dá o smash vira de lado, aponta a bola com a mão livre e se posiciona atrás dela.',
      'Bata com a bola na frente e no alto, de cima para baixo, mirando os pés ou o meio da quadra do outro lado.',
      'Volte para a linha da cozinha depois de cada smash.',
      'Depois de 10, troquem.',
    ],
    cues: ['Aponte a bola antes de bater', 'Bola na frente e no alto', 'Mire os pés, não a força'],
    positioning: [
      { type: 'certo', text: 'De lado para a rede, atrás da bola, com a bola caindo na sua frente.' },
      { type: 'errado', text: 'De frente para a rede e embaixo da bola: o smash vai na rede ou sai fraco.' },
    ],
    common_errors: [
      { error: 'O smash vai na rede.', fix: 'Deixe a bola chegar à sua frente e bata no alto; mire os pés, além da rede.' },
      { error: 'Você bate com toda a força e manda para fora.', fix: 'Ângulo e alvo vencem o ponto, não a força.' },
      { error: 'O lob vem fundo e você recua de costas.', fix: 'Lob fundo: vire, corra e deixe quicar.' },
    ],
    variations: {
      easier: 'Equipamento: lobs bem curtos e lentos, jogados com a mão.',
      harder: 'Tarefa: lobs de alturas e profundidades misturadas; o jogador decide entre smash, voleio ou deixar quicar.',
    },
    metric: { type: 'percentual', target: '7 de 10 na quadra' },
    success_criteria: 'Conta o smash que desce e quica dentro da quadra. 7 de 10? Passe para os lobs misturados.',
    safety: 'Para buscar o lob, vire e ande de lado; recuar de costas causa muitas quedas. Quem joga o lob fica no fundo, longe da linha do smash.',
    motor: {
      phases: {
        preparacao: 'De lado, raquete atrás e alta, mão livre apontando a bola.',
        execucao: 'Contato na frente e no alto, gesto de cima para baixo.',
        finalizacao: 'A raquete termina do outro lado do corpo; volte para a cozinha.',
      },
      abilities: ['coordenacao', 'potencia', 'leitura'],
    },
    when_to_use: 'Lob curto do adversário quando você está na cozinha ou perto dela.',
    diagrams: [
      diagrama('Smash no lob curto', 'inteira', [
        jogador(50, 74, 'a', 'Smash'),
        jogador(50, 4, 'b', 'Lob'),
        trajeto(50, 6, 52, 72, '1'),
        trajeto(50, 72, 42, 16, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'split-step-no-tempo-certo',
    version: 1,
    kind: 'drill',
    title: 'Split step no tempo do adversário',
    summary: 'Ande para a rede e pare com um pequeno salto (split step) bem quando o parceiro bate na bola. Treina o tempo que evita a bola no pé.',
    objective: 'Ao final, o atleta consegue estar parado em split step no momento do contato do adversário em 8 de 10 repetições.',
    skills: ['groundstrokes.transicao', 'physical.agilidade'],
    level_min: 2.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Quem avança'],
    duration_min: 8,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'bloco',
    setup: 'Quem avança começa no fundo. O alimentador fica na linha da cozinha do outro lado, com o cesto.',
    steps: [
      'Quem avança anda para a frente com passos curtos.',
      'Quando o alimentador vai bater, quem avança dá um pequeno salto e cai com as pernas abertas e dobradas.',
      'O alimentador manda a bola para um dos lados; quem avança dá o primeiro passo até ela e devolve com um drop ou reset.',
      'O alimentador diz "cedo", "certo" ou "tarde" depois de cada repetição.',
      'Depois de 10, troquem.',
    ],
    cues: ['Aterrisse quando ele bater', 'Pare como mola, não estátua', 'Primeiro passo para a bola'],
    positioning: [
      { type: 'certo', text: 'Cai do salto no instante do contato, com o peso na parte da frente dos pés.' },
      { type: 'errado', text: 'Para cedo demais e fica plantado, ou ainda está no ar quando a bola chega.' },
    ],
    common_errors: [
      { error: 'O salto é grande e você fica no ar.', fix: 'Saltinho baixo, de poucos centímetros: só para tirar o peso dos pés.' },
      { error: 'Você para muito cedo e perde tempo.', fix: 'Ande até ele começar o golpe e aterrisse no contato.' },
    ],
    variations: {
      easier: 'Tarefa: sem bola — o alimentador só simula o golpe e quem avança faz o split step.',
      harder: 'Tarefa: o alimentador varia o momento e o lado, e às vezes manda lob.',
    },
    metric: { type: 'percentual', target: '8 de 10 no tempo certo' },
    success_criteria: 'Conta quando o alimentador diz "certo". 8 de 10? Use o split step em todo drill de transição.',
    safety: 'Saltinho baixo e aterrissagem macia, com as pernas dobradas. Em quadra molhada ou escorregadia, pare o treino.',
    motor: {
      phases: {
        preparacao: 'Passos curtos para a frente, olhando a raquete do adversário.',
        execucao: 'Pequeno salto e aterrissagem com as pernas abertas, no instante do contato.',
        finalizacao: 'Primeiro passo na direção da bola.',
      },
      abilities: ['tempo_reacao', 'equilibrio', 'agilidade'],
    },
    when_to_use: 'Toda vez que você está andando e o adversário vai bater: na transição, na devolução e na rede.',
    diagrams: [
      diagrama('Ande, pare, reaja', 'inteira', [
        jogador(50, 96, 'a', 'A'),
        jogador(50, 32, 'b', 'Alim'),
        desloca(50, 94, 50, 81, '1'),
        texto(64, 80, 'Split'),
        trajeto(52, 34, 38, 78, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'skinny-singles',
    version: 1,
    kind: 'drill',
    title: 'Skinny singles: simples em meia quadra',
    summary: 'Jogo de simples usando só metade da quadra, de frente ou na diagonal. Obriga a jogar com drop, dink e paciência, como nas duplas.',
    objective: 'Ao final, o atleta consegue construir pontos com drop e dink em vez de só bater forte, vencendo pela colocação.',
    skills: ['experience.jogo', 'groundstrokes.terceira_bola_drop', 'kitchen.paciencia'],
    level_min: 2.5,
    level_max: 5.0,
    players_min: 2,
    players_max: 2,
    duration_min: 20,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Usem só uma metade da quadra, dividida pela linha central (e pelo prolongamento dela dentro da cozinha). Pode ser de frente ou na diagonal. As linhas laterais e de fundo valem como no jogo normal.',
    steps: [
      'Saque na metade combinada; vale a regra dos dois quiques.',
      'Depois da devolução, os dois buscam chegar à cozinha com drop e dink.',
      'Bola fora da metade combinada é fora.',
      'Jogo até 11, com 2 de diferença, na contagem de simples (ou com todo rally valendo ponto, se combinarem).',
      'Depois do jogo, troquem de metade.',
    ],
    cues: ['Drop primeiro, rede depois', 'Mire a metade estreita', 'Paciência ganha o ponto'],
    positioning: [
      { type: 'certo', text: 'Depois de cada golpe, volte para o meio da sua metade.' },
      { type: 'errado', text: 'Ficar colado na lateral: o adversário abre o ângulo para o outro lado da metade.' },
    ],
    common_errors: [
      { error: 'Você bate forte toda bola e erra a metade.', fix: 'Em meia quadra o espaço é estreito: troque força por drop e dink.' },
      { error: 'Você fica no fundo esperando.', fix: 'Depois de um drop bom, ande para a cozinha.' },
    ],
    variations: {
      easier: 'Tarefa: comecem os dois na cozinha, só com dinks e voleios, sem saque.',
      harder: 'Tarefa: drop obrigatório na terceira bola; quem fizer drive na terceira perde o ponto.',
    },
    metric: { type: 'placar', target: '11 pontos' },
    success_criteria: 'Vence quem fizer 11 com 2 de diferença. Ganhou com a maioria dos pontos vindo de dink e drop? Está jogando do jeito certo.',
    safety: 'Jogo de muito deslocamento: aqueça antes e, para buscar bola por cima, vire de lado.',
    motor: {
      phases: {
        preparacao: 'Base no meio da sua metade, raquete na frente.',
        execucao: 'Golpes de controle (drop e dink) para avançar.',
        finalizacao: 'Volte ao meio da metade depois de cada golpe.',
      },
      abilities: ['leitura', 'agilidade', 'precisao'],
    },
    when_to_use: 'Treino de duas pessoas que imita a lógica das duplas: chegar à cozinha e ganhar no jogo curto.',
    diagrams: [
      diagrama('Metade da quadra', 'inteira', [
        zona(50, 1, 99, 99, 'Meia quadra'),
        jogador(75, 96, 'a', 'A'),
        jogador(75, 4, 'b', 'B'),
        trajeto(75, 94, 72, 42, '1'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'jogo-7-11',
    version: 1,
    kind: 'drill',
    title: 'Jogo 7-11: chegar à rede contra quem está nela',
    summary: 'Um jogador começa no fundo e o outro na cozinha. Quem está no fundo precisa de 7 pontos; quem está na rede, de 11. Treina drop e transição sob pressão.',
    objective: 'Ao final, o atleta consegue ganhar a cozinha a partir do fundo usando drop e reset, mesmo contra quem já está na rede.',
    skills: ['groundstrokes.transicao', 'groundstrokes.terceira_bola_drop', 'net.reset'],
    level_min: 3.0,
    level_max: 5.0,
    players_min: 2,
    players_max: 4,
    roles: ['Jogador do fundo', 'Jogador da rede'],
    duration_min: 20,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Meia quadra, de frente ou na diagonal. O jogador da rede começa na linha da cozinha; o do fundo, atrás da linha de fundo do outro lado.',
    steps: [
      'O jogador da rede começa mandando uma bola funda para o do fundo.',
      'O do fundo joga drop (ou drive, se a bola pedir) e tenta chegar à cozinha.',
      'O da rede tenta mantê-lo no fundo, sem sair da cozinha.',
      'Todo rally vale ponto para quem vencer.',
      'O do fundo vence com 7 pontos; o da rede, com 11. Depois, troquem os papéis.',
    ],
    cues: ['Drop, anda, pare', 'Reset baixo até a linha', 'Chegue parado, não correndo'],
    positioning: [
      { type: 'certo', text: 'Do fundo, avançar em etapas: bola boa, anda; adversário bate, para.' },
      { type: 'errado', text: 'Correr direto do fundo para a rede depois do primeiro drop: a bola pega você no pé.' },
    ],
    common_errors: [
      { error: 'O jogador do fundo desiste de avançar e fica trocando bolas lá atrás.', fix: 'Cada drop bom vale dois passos à frente.' },
      { error: 'O jogador da rede tenta matar toda bola e erra.', fix: 'Na rede, paciência: ataque só a bola que sobe.' },
    ],
    variations: {
      easier: 'Pessoas: o da rede só pode dinkar e bloquear, sem atacar.',
      harder: 'Tarefa: o da rede precisa de só 9 pontos; ou joguem 2 contra 2, dupla do fundo contra dupla da rede.',
    },
    metric: { type: 'placar', target: '7 contra 11' },
    success_criteria: 'Ganhar 7 pontos no fundo antes de o outro fazer 11 já mostra uma boa transição. Venceu nos dois papéis? Use a variação mais difícil.',
    safety: 'Muitas bolas rápidas no meio da quadra: óculos de proteção recomendados.',
    motor: {
      phases: {
        preparacao: 'Do fundo, raquete baixa e pernas dobradas para o drop.',
        execucao: 'Drop ou reset curto; avanço com passos curtos.',
        finalizacao: 'Split step quando o outro bate, raquete na frente.',
      },
      abilities: ['leitura', 'tempo_reacao', 'precisao'],
    },
    when_to_use: 'Treino de duas pessoas para a parte mais difícil das duplas: sair do fundo e chegar à cozinha.',
    diagrams: [
      diagrama('Fundo contra rede', 'inteira', [
        jogador(75, 96, 'a', 'Fundo'),
        jogador(25, 32, 'b', 'Rede'),
        trajeto(25, 34, 72, 90, '1'),
        trajeto(75, 94, 32, 42, '2'),
        desloca(80, 94, 76, 80, '3'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'terceira-bola-ao-vivo',
    version: 1,
    kind: 'drill',
    title: 'Terceira bola ao vivo em duplas',
    summary: 'Saque, devolução, terceira bola e ponto disputado. A dupla que sacou ganha ponto dobrado se chegar inteira à cozinha.',
    objective: 'Ao final, a dupla consegue escolher entre drop e drive na terceira bola e chegar junta à cozinha em metade dos pontos.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.terceira_bola_drive', 'doubles.posicionamento', 'experience.jogo'],
    level_min: 3.0,
    level_max: 5.0,
    players_min: 4,
    players_max: 4,
    duration_min: 20,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Dois contra dois, quadra inteira. A dupla A saca 10 vezes seguidas; a dupla B recebe e sobe para a cozinha.',
    steps: [
      'A dupla A saca e fica no fundo; a dupla B devolve fundo e sobe para a cozinha.',
      'A terceira bola é escolha de quem bate: drop ou drive.',
      'Joguem o ponto até o fim.',
      'O ponto da dupla A vale 2 se os dois estavam na linha da cozinha quando o ponto acabou.',
      'Depois de 10 saques, as duplas trocam de função.',
    ],
    cues: ['Bola baixa: drop. Bola alta: drive', 'Subam juntos, como uma corda', 'Parem quando eles batem'],
    positioning: [
      { type: 'certo', text: 'Os dois da dupla A avançam juntos, lado a lado, depois de um drop bom.' },
      { type: 'errado', text: 'Um sobe e o outro fica no fundo: abre um buraco no meio e nos pés de quem ficou.' },
    ],
    common_errors: [
      { error: 'Todo mundo faz drive em toda terceira bola.', fix: 'Drive na bola alta e funda; bola baixa ou curta pede drop.' },
      { error: 'A dupla A nunca sai do fundo.', fix: 'Depois do drop bom, os dois avançam dois passos e param.' },
    ],
    variations: {
      easier: 'Tarefa: a devolução da dupla B é combinada (sempre no meio, sem força).',
      harder: 'Tarefa: a dupla B ataca qualquer terceira bola alta, e o ponto dobrado só vale se a dupla A chegar em até 3 golpes.',
    },
    metric: { type: 'placar', target: '10 saques por dupla' },
    success_criteria: 'Contem os pontos de cada dupla em 10 saques. A dupla que sacou fez 8 ou mais? Está dominando a transição.',
    safety: 'Muitas bolas rápidas perto da rede: óculos de proteção recomendados.',
    motor: {
      phases: {
        preparacao: 'No fundo, raquete baixa e leitura cedo da devolução.',
        execucao: 'Drop ou drive conforme a altura da bola.',
        finalizacao: 'Avançar juntos e parar quando o adversário bate.',
      },
      abilities: ['leitura', 'precisao', 'agilidade'],
    },
    when_to_use: 'Todo ponto em que a sua dupla saca.',
    diagrams: [
      diagrama('Saque, devolução e terceira bola', 'inteira', [
        jogador(75, 97, 'a', 'A1'),
        jogador(25, 97, 'a', 'A2'),
        jogador(25, 4, 'b', 'B1'),
        jogador(75, 32, 'b', 'B2'),
        trajeto(75, 95, 28, 8, '1'),
        trajeto(25, 6, 50, 88, '2'),
        desloca(20, 6, 22, 29),
        trajeto(50, 90, 50, 42, '3'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'bola-do-meio-quem-chama',
    version: 1,
    kind: 'drill',
    title: 'Bola do meio: quem chama?',
    summary: 'O alimentador manda bolas no meio de uma dupla na cozinha; os dois falam "minha" ou "sua" antes de bater. Acaba com a bola que passa entre os dois.',
    objective: 'Ao final, a dupla consegue chamar em voz alta e devolver 9 de 10 bolas no meio, sem trombar nem deixar passar.',
    skills: ['doubles.comunicacao', 'doubles.cobertura_meio'],
    level_min: 2.0,
    level_max: 4.0,
    players_min: 3,
    players_max: 4,
    roles: ['Alimentador', 'Dupla'],
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'variado',
    setup: 'A dupla na linha da cozinha, lado a lado, a cerca de 3 metros um do outro. O alimentador do outro lado, na linha da cozinha, com o cesto.',
    steps: [
      'Antes de começar, a dupla combina a regra; a mais comum é: quem tem o forehand no meio pega.',
      'O alimentador manda bolas no meio: dink, voleio ou bola rápida.',
      'Quem vai pegar grita "minha"; o parceiro responde "sua" e cobre o resto da quadra.',
      'Bola sem chamada não vale, mesmo se voltar.',
      'Depois de 10 bolas, os dois trocam de lado para treinar a regra do outro lado.',
    ],
    cues: ['Chame antes da bola chegar', 'Forehand no meio pega', 'Chamou? Vá até o fim'],
    positioning: [
      { type: 'certo', text: 'Os dois na linha, a cerca de 3 metros, com as raquetes na frente e voltadas para o meio.' },
      { type: 'errado', text: 'Os dois longe um do outro, colados nas laterais: o meio vira um corredor livre.' },
    ],
    common_errors: [
      { error: 'Os dois param e a bola passa.', fix: 'Usem a regra combinada e chamem cedo, com a bola ainda do outro lado.' },
      { error: 'Os dois vão na bola e as raquetes se batem.', fix: 'Quem não chamou recolhe a raquete e cobre a lateral.' },
    ],
    variations: {
      easier: 'Tarefa: o alimentador avisa o golpe antes ("dink!", "rápida!").',
      harder: 'Tarefa: o alimentador mistura bolas no meio e nas laterais, sem aviso, e às vezes um lob.',
    },
    metric: { type: 'percentual', target: '9 de 10 com chamada' },
    success_criteria: 'Conta a bola devolvida com chamada clara. 9 de 10? Levem as palavras combinadas para o jogo.',
    safety: 'Raquetes perto uma da outra: quem não chamou afasta a raquete do meio para não acertar o parceiro.',
    when_to_use: 'Toda bola que vem entre os dois parceiros, na rede ou no fundo.',
    diagrams: [
      diagrama('O meio da dupla', 'cozinha', [
        zona(42, 60, 58, 72, 'Meio'),
        jogador(35, 68, 'a', 'A1'),
        jogador(65, 68, 'a', 'A2'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 34, 50, 62, '1'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'poach-no-dink-cruzado',
    version: 1,
    kind: 'drill',
    title: 'Poach no dink cruzado',
    summary: 'No rally cruzado, o parceiro do meio atravessa e volea a bola antes de ela chegar ao colega. Treina o tempo do poach e a troca de lado.',
    objective: 'Ao final, a dupla consegue fazer o poach na hora certa e cobrir o lado que ficou vazio em 6 de 10 tentativas.',
    skills: ['doubles.posicionamento', 'net.voleio', 'doubles.comunicacao'],
    level_min: 3.5,
    level_max: 5.0,
    players_min: 4,
    players_max: 4,
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: 'Dois contra dois na cozinha. A diagonal da direita troca dinks cruzados; os outros dois ficam prontos na linha, na frente deles.',
    steps: [
      'A diagonal da direita troca dinks cruzados.',
      'Quando o dink cruzado vem um pouco alto e lento, o parceiro do meio da dupla A atravessa e volea a bola.',
      'Ele chama "minha!" e o parceiro troca de lado para cobrir a lateral que ficou vazia.',
      'O ponto segue até o fim.',
      'Depois de 10 tentativas, troquem quem faz o poach.',
    ],
    cues: ['Saia quando a bola sai', 'Voleie para baixo, no meio', 'Chamou, atravessou, cobriu'],
    positioning: [
      { type: 'certo', text: 'Depois do poach, quem atravessou fica no lado novo e o parceiro vai para o lado vazio.' },
      { type: 'errado', text: 'Atravessar e voltar correndo para o lugar antigo: a quadra fica com um buraco na lateral.' },
    ],
    common_errors: [
      { error: 'Você sai cedo demais e o adversário joga na lateral vazia.', fix: 'Saia quando o adversário já se comprometeu com o dink cruzado, nunca antes.' },
      { error: 'Faz poach em bola baixa e o voleio vai na rede.', fix: 'Poach em bola na altura da rede ou acima; a bola baixa fica para o parceiro.' },
    ],
    variations: {
      easier: 'Tarefa: a cada 3 bolas, o dink cruzado vem de propósito um pouco alto.',
      harder: 'Tarefa: os adversários podem jogar na paralela a qualquer momento para punir o poach cedo.',
    },
    metric: { type: 'percentual', target: '6 de 10 poaches certos' },
    success_criteria: 'Conta o poach em bola atacável, com a troca de lado feita. 6 de 10? Use no jogo, combinado com um sinal.',
    safety: 'Chamem sempre ("minha!") para as raquetes não se cruzarem.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente, peso na frente dos pés, olhando o adversário.',
        execucao: 'Passo cruzado em diagonal para a frente e voleio curto para baixo.',
        finalizacao: 'Siga para o lado novo e prepare a raquete.',
      },
      abilities: ['leitura', 'agilidade', 'tempo_reacao'],
    },
    when_to_use: 'Dink cruzado lento ou alto do adversário para o seu parceiro.',
    diagrams: [
      diagrama('Poach e troca', 'cozinha', [
        jogador(72, 68, 'a', 'A1'),
        jogador(28, 68, 'a', 'A2'),
        jogador(28, 32, 'b', 'B1'),
        jogador(72, 32, 'b', 'B2'),
        trajeto(28, 34, 68, 62, '1'),
        desloca(30, 66, 52, 61, '2'),
        desloca(72, 71, 34, 71, '3'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'voleio-no-paredao',
    version: 1,
    kind: 'drill',
    title: 'Voleio no paredão',
    summary: 'Sozinho, contra uma parede: voleios curtos e seguidos acima de uma linha na altura da rede. O treino solo mais rápido para ter a raquete sempre pronta.',
    objective: 'Ao final, o atleta consegue fazer 30 voleios seguidos na parede, acima da linha da rede, alternando forehand e backhand.',
    skills: ['net.voleio', 'net.contra_ataque'],
    level_min: 2.0,
    level_max: 4.5,
    players_min: 1,
    players_max: 1,
    duration_min: 10,
    intensity: 4,
    place: ['parede'],
    equipment: ['bolas', 'parede'],
    practice_mode: 'bloco',
    setup: 'Marque na parede, com fita, uma linha a 86 cm do chão (a altura da rede no meio). Fique a 2 ou 3 metros da parede.',
    steps: [
      'Jogue a bola na parede acima da linha e volee sem deixar cair.',
      'Faça 10 voleios só de forehand e depois 10 só de backhand.',
      'Depois alterne: um forehand, um backhand.',
      'Bola abaixo da linha ou que caiu no chão zera a conta.',
      'Faça 3 rodadas de 2 minutos, com 1 minuto de descanso.',
    ],
    cues: ['Raquete na frente, sempre', 'Bola acima da linha', 'Gesto curto e firme'],
    positioning: [
      { type: 'certo', text: 'A 2 ou 3 metros da parede, raquete na frente do peito.' },
      { type: 'errado', text: 'Colado na parede: a bola volta rápida demais e o gesto vira pancada.' },
    ],
    common_errors: [
      { error: 'A bola cai abaixo da linha.', fix: 'Mire um palmo acima da linha.' },
      { error: 'Você troca a empunhadura a cada bola e se atrasa.', fix: 'Use a continental: ela serve para o forehand e para o backhand.' },
    ],
    variations: {
      easier: 'Espaço: fique mais longe da parede e deixe a bola quicar uma vez antes de cada golpe.',
      harder: 'Espaço: chegue mais perto da parede e alterne voleio alto e voleio baixo.',
    },
    metric: { type: 'sequencia', target: '30 seguidos' },
    success_criteria: 'Conta voleio seguido acima da linha. 30 seguidos alternando? Chegue mais perto da parede.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente do peito, base aberta.',
        execucao: 'Gesto curto, com a raquete quase parada.',
        finalizacao: 'A raquete volta para a frente.',
      },
      abilities: ['tempo_reacao', 'coordenacao', 'ritmo'],
    },
    when_to_use: 'Treino sozinho entre as sessões de quadra.',
    media: [],
  },
  {
    slug: 'dink-e-drop-no-paredao',
    version: 1,
    kind: 'drill',
    title: 'Dink e drop no paredão',
    summary: 'Sozinho, contra a parede: bolas suaves que tocam logo acima da linha da rede e voltam quicando. Treina o toque do dink e do drop.',
    objective: 'Ao final, o atleta consegue fazer 20 golpes suaves seguidos tocando a parede até um palmo acima da linha da rede.',
    skills: ['kitchen.dink_paralelo', 'groundstrokes.terceira_bola_drop'],
    level_min: 2.0,
    level_max: 4.0,
    players_min: 1,
    players_max: 1,
    duration_min: 10,
    intensity: 2,
    place: ['parede'],
    equipment: ['bolas', 'parede'],
    practice_mode: 'bloco',
    setup: 'Marque na parede uma linha a 86 cm do chão (altura da rede) e outra um palmo acima: essa faixa é o alvo. Fique a 3 ou 4 metros da parede.',
    steps: [
      'Deixe a bola quicar e bata suave, de baixo para cima, para tocar a faixa.',
      'A bola volta, quica e você repete.',
      'Conte os golpes seguidos que tocam a faixa.',
      'A cada série, recue um passo para treinar o drop, que é mais longo.',
      'Faça 4 séries de 2 minutos.',
    ],
    cues: ['Toque a faixa, devagar', 'Bola sobe e desce', 'Raquete termina na faixa'],
    positioning: [
      { type: 'certo', text: 'Pernas dobradas e raquete baixa na frente, levantando a bola.' },
      { type: 'errado', text: 'Pernas esticadas e golpe de cima para baixo: a bola bate abaixo da linha.' },
    ],
    common_errors: [
      { error: 'A bola bate alto na parede e volta forte.', fix: 'Menos força: a bola só precisa chegar à faixa.' },
      { error: 'A bola bate abaixo da linha.', fix: 'Levante com as pernas e termine a raquete mais alta.' },
    ],
    variations: {
      easier: 'Equipamento: faixa de dois palmos e bola mais lenta.',
      harder: 'Tarefa: alterne um golpe curto (dink) e um longo (drop), mudando de distância sem parar.',
    },
    metric: { type: 'sequencia', target: '20 seguidos' },
    success_criteria: 'Conta o golpe que toca a faixa. 20 seguidos duas vezes? Leve o toque para o drop em quadra.',
    motor: {
      phases: {
        preparacao: 'Pernas dobradas, raquete baixa e na frente.',
        execucao: 'Gesto curto de baixo para cima; as pernas sobem.',
        finalizacao: 'A raquete para apontando a faixa.',
      },
      abilities: ['precisao', 'ritmo'],
    },
    when_to_use: 'Treino sozinho do toque de dink e de drop.',
    media: [],
  },
];
