/**
 * Biblioteca inicial — ESTUDOS (regras e leitura de jogo).
 *
 * Regra cita a EDIÇÃO e nunca um número de seção (não inventamos numeração);
 * quem quiser conferir vai ao regulamento oficial pelo link.
 */

const REGRAS = 'USA Pickleball 2025';
const REGULAMENTO = 'https://usapickleball.org/';

export const ESTUDOS = [
  {
    slug: 'regras-do-saque',
    version: 1,
    featured: true,
    kind: 'estudo',
    study_type: 'regra',
    rules_edition: REGRAS,
    link: REGULAMENTO,
    title: 'Regras do saque',
    summary: 'O que torna um saque válido: por baixo, na diagonal, passando da cozinha. O saque de voleio e o saque com quique (drop serve) têm exigências diferentes.',
    objective: 'Ao final, o atleta saca dos dois jeitos sem cometer falta e sabe explicar por que um saque foi ou não válido.',
    skills: ['rules.saque', 'serve.consistencia'],
    level_min: 2.0,
    duration_min: 10,
    place: ['casa', 'quadra'],
    steps: [
      'Saque de voleio: o movimento é de baixo para cima, a bola é batida abaixo da cintura e a cabeça da raquete fica abaixo do pulso no contato.',
      'Saque com quique: solte a bola sem jogar para cima nem empurrar, deixe quicar e bata. Aí as exigências do movimento não valem.',
      'Os dois pés atrás da linha de fundo no contato, dentro das linhas imaginárias do meio e da lateral.',
      'A bola vai na diagonal e precisa passar da cozinha: caindo na linha da cozinha é falta; caindo na linha de fundo ou na lateral é boa.',
      'Só uma tentativa: errou, passa a vez.',
      'Não dá para girar a bola com a mão antes de soltar.',
    ],
    positioning: [
      { type: 'certo', text: 'Contato abaixo da cintura, movimento subindo, pés atrás da linha de fundo.' },
      { type: 'errado', text: 'Pé pisando a linha de fundo no momento do contato: é falta, mesmo que a bola caia boa.' },
    ],
    questions: [
      'O saque caiu em cima da linha da cozinha. Foi bom ou falta?',
      'No saque com quique, posso bater a bola de cima para baixo?',
      'O saque caiu em cima da linha lateral do lado certo. Vale?',
      'Posso dar efeito na bola girando ela com os dedos antes de soltar?',
    ],
    when_to_use: 'Antes do primeiro torneio, ou quando alguém questionar o seu saque no jogo. Confira sempre a edição vigente do regulamento.',
    media: [],
  },
  {
    slug: 'regras-da-cozinha',
    version: 1,
    kind: 'estudo',
    study_type: 'regra',
    rules_edition: REGRAS,
    link: REGULAMENTO,
    title: 'Regras da cozinha (zona de não voleio)',
    summary: 'A cozinha não é proibida: proibido é volear (bater sem deixar quicar) estando nela ou na linha dela. O impulso que leva para dentro depois do voleio também é falta.',
    objective: 'Ao final, o atleta sabe quando pode entrar na cozinha, quando precisa sair e por que o impulso depois do voleio conta como falta.',
    skills: ['rules.cozinha', 'kitchen.paciencia'],
    level_min: 2.0,
    duration_min: 10,
    place: ['casa', 'quadra'],
    steps: [
      'A cozinha são os 2,13 m de cada lado da rede, e a linha faz parte dela.',
      'Você pode entrar a qualquer momento para bater uma bola que já quicou.',
      'Volear tocando a cozinha ou a linha é falta, inclusive com a raquete ou o que estiver vestindo.',
      'Se o impulso do voleio levar você para dentro, é falta, mesmo depois de a bola ter morrido.',
      'Entrou para bater uma bola quicada? Saia com os dois pés antes de volear de novo.',
    ],
    positioning: [
      { type: 'certo', text: 'Pés atrás da linha da cozinha na hora do voleio, com equilíbrio para não cair para frente.' },
      { type: 'certo', text: 'Entrar na cozinha para buscar um dink que quicou, e voltar para trás da linha em seguida.' },
      { type: 'errado', text: 'Volear com a ponta do pé em cima da linha: a linha é cozinha.' },
    ],
    questions: [
      'Voleei com os pés fora, mas o impulso me levou para dentro depois que a bola caiu. Foi falta?',
      'Posso ficar parado dentro da cozinha esperando a bola?',
      'O meu boné caiu na cozinha durante o voleio. Conta?',
      'Entrei para pegar um dink quicado. Quando posso volear de novo?',
    ],
    when_to_use: 'Assim que começar a jogar na rede. É a regra que mais gera discussão entre iniciantes.',
    media: [],
  },
  {
    slug: 'contagem-do-placar',
    version: 1,
    kind: 'estudo',
    study_type: 'regra',
    rules_edition: REGRAS,
    link: REGULAMENTO,
    title: 'Contagem do placar nas duplas',
    summary: 'Três números: os pontos de quem saca, os de quem recebe e o número do sacador (1 ou 2). Só quem saca marca ponto, e o jogo começa em 0-0-2.',
    objective: 'Ao final, o atleta canta o placar certo antes de cada saque e sabe de que lado sacar pelo próprio placar.',
    skills: ['rules.placar', 'doubles.comunicacao'],
    level_min: 2.0,
    duration_min: 10,
    place: ['casa', 'quadra'],
    steps: [
      'Antes de sacar, cante: pontos da sua dupla, pontos da dupla adversária, e se você é o sacador 1 ou 2.',
      'Só a dupla que saca marca ponto. Ganhou o rali sacando? Ponto e o sacador troca de lado com o parceiro.',
      'Perdeu o rali sacando? Passa para o sacador 2 da sua dupla; se já era o 2, o saque vai para a outra dupla.',
      'O jogo começa em 0-0-2: a primeira dupla a sacar tem só um sacador nessa vez.',
      'O jogo comum vai a 11, com 2 de vantagem.',
    ],
    questions: [
      'O placar é 5-3-1 e a minha dupla ganhou o rali. Qual é o próximo placar?',
      'Por que o jogo começa em 0-0-2 e não em 0-0-1?',
      'O placar é 4-6-2 e perdemos o rali. Quem saca agora?',
      'Com a pontuação da dupla par, de que lado da quadra saca quem começou o jogo?',
    ],
    when_to_use: 'Nos primeiros jogos em dupla. Cantar o placar em voz alta evita a maior parte das discussões.',
    media: [],
  },
  {
    slug: 'faltas-e-linhas',
    version: 1,
    kind: 'estudo',
    study_type: 'regra',
    rules_edition: REGRAS,
    link: REGULAMENTO,
    title: 'Faltas, linhas e a regra dos dois quiques',
    summary: 'Bola na linha é boa (menos a linha da cozinha no saque). A devolução do saque e a resposta a ela precisam quicar antes. Quem chama a linha é quem está do lado dela.',
    objective: 'Ao final, o atleta reconhece as faltas mais comuns no jogo e chama as linhas do próprio lado com honestidade.',
    skills: ['rules.faltas'],
    level_min: 2.0,
    duration_min: 10,
    place: ['casa', 'quadra'],
    steps: [
      'Regra dos dois quiques: a devolução do saque quica antes de ser batida, e a resposta da dupla que sacou também. Depois disso pode volear.',
      'Bola tocando qualquer linha é boa, exceto a linha da cozinha no saque.',
      'É falta: bola fora, bola na rede, bola batida duas vezes de forma deliberada, tocar a rede com o corpo ou a raquete com a bola em jogo.',
      'A bola que bate em você antes de quicar é ponto de quem bateu, mesmo que fosse sair.',
      'Quem chama a linha é a dupla do lado em que a bola caiu. Na dúvida, a bola é boa.',
    ],
    questions: [
      'A bola ia sair, mas bateu no meu ombro antes de quicar. De quem é o ponto?',
      'Posso volear a devolução do saque?',
      'Não vi se a bola tocou a linha. Como devo chamar?',
      'A minha raquete encostou na rede depois que a bola quicou duas vezes do outro lado. É falta?',
    ],
    when_to_use: 'Antes de jogar dias de jogo valendo ranking e antes do primeiro torneio.',
    media: [],
  },
  {
    slug: 'assistir-um-jogo-com-olhar-de-tecnico',
    version: 1,
    kind: 'estudo',
    study_type: 'video',
    title: 'Assistir a um jogo com olhar de técnico',
    summary: 'Escolha um jogo (gravado ou na arena) e acompanhe UMA coisa de cada vez: onde vão as terceiras bolas, como a dupla anda junto, quando alguém acelera. Aprender vendo também é treino.',
    objective: 'Ao final, o atleta anota três padrões que viu num jogo e escolhe um para levar ao próprio treino.',
    skills: ['tactics.leitura_adversario', 'tactics.selecao_golpe', 'doubles.posicionamento'],
    level_min: 2.5,
    duration_min: 20,
    place: ['casa'],
    steps: [
      'Escolha um jogo de nível um pouco acima do seu.',
      'Nos primeiros 5 minutos, olhe só a terceira bola: foi drop ou drive? Onde caiu?',
      'Nos 5 minutos seguintes, olhe só os pés da dupla que saca: em que bola ela chega à cozinha?',
      'Depois, olhe só as acelerações na rede: quem acelerou, de que altura veio a bola e quem ganhou o ponto.',
      'Anote três padrões e escolha um para treinar nesta semana.',
    ],
    questions: [
      'Na maioria das vezes, a terceira bola foi drop ou drive? Por quê?',
      'A dupla que chegou primeiro à cozinha ganhou mais pontos?',
      'As acelerações que deram certo saíram de bolas altas ou baixas?',
    ],
    when_to_use: 'Em dia de descanso, ou para ter uma ideia nova antes do próximo treino.',
    media: [],
  },
  {
    slug: 'rotina-entre-pontos',
    version: 1,
    kind: 'estudo',
    study_type: 'leitura',
    title: 'Rotina entre pontos',
    summary: 'O que fazer nos segundos entre um ponto e outro: soltar o ponto que passou, respirar, decidir o próximo plano. Uma rotina curta deixa o jogo mais estável sob pressão.',
    objective: 'Ao final, o atleta tem uma rotina própria de três passos e a usa em todos os pontos de um jogo.',
    skills: ['mental.rotina_entre_pontos', 'mental.pressao', 'mental.foco'],
    level_min: 2.0,
    duration_min: 10,
    place: ['casa', 'quadra'],
    steps: [
      'Soltar: um gesto curto para encerrar o ponto que passou, como arrumar as cordas ou bater a raquete na mão.',
      'Respirar: uma respiração lenta, soltando o ar mais devagar do que puxou.',
      'Decidir: escolha um plano simples para o próximo ponto ("devolução funda no meio").',
      'Pronto: posição de prontidão, olhar na bola.',
      'Use a mesma rotina no ponto ganho e no ponto perdido.',
    ],
    cues: ['Solte, respire, decida', 'Um plano por ponto'],
    questions: [
      'Qual gesto você vai usar para soltar o ponto que passou?',
      'Num ponto decisivo, qual é o seu plano mais simples e seguro?',
      'Depois de um erro bobo, o que costuma passar pela sua cabeça? O que você quer dizer a si mesmo no lugar?',
    ],
    when_to_use: 'Quando o seu jogo cai depois de um erro, ou quando o placar aperta.',
    media: [],
  },
];
