/** Biblioteca inicial — PREPARAÇÃO FÍSICA (sem prescrição médica). */

import { cone, desloca, diagrama, jogador, texto, trajeto } from './quadra.js';

const PARE_SE_DOER = 'Sentiu dor (não cansaço), tontura ou falta de ar fora do normal? Pare. Quem tem lesão ou alguma condição de saúde segue a orientação do seu profissional de saúde.';

export const FISICOS = [
  {
    slug: 'aquecimento-dinamico',
    version: 1,
    featured: true,
    kind: 'fisico',
    title: 'Aquecimento dinâmico de 10 minutos',
    summary: 'Antes de jogar: movimento leve, depois amplo, depois no ritmo do jogo, terminando com dinks. Prepara o corpo em vez de alongar parado.',
    objective: 'Ao final, o atleta está com o corpo aquecido e pronto para o jogo em 10 minutos, sem precisar de equipamento.',
    skills: ['physical.aquecimento', 'physical.mobilidade'],
    level_min: 2.0,
    players_min: 1,
    players_max: 8,
    duration_min: 10,
    intensity: 3,
    place: ['quadra'],
    equipment: ['raquete', 'bolas'],
    practice_mode: 'bloco',
    sets: 1,
    reps: '8 a 10 de cada movimento',
    rest_sec: 0,
    steps: [
      'Dois minutos de trote leve e passos laterais em volta da quadra.',
      'Balanço de perna para a frente e para trás e de um lado para o outro, segurando no poste da rede: 10 de cada.',
      'Afundo andando, girando o tronco para o lado da raquete: 8 de cada lado.',
      'Círculos com os braços, do pequeno para o grande: 10 para a frente e 10 para trás.',
      'Passos laterais e cruzados de uma lateral à outra: 2 idas e voltas.',
      'Saltinhos de split step no lugar: 3 séries de 5.',
      'Dois minutos de dinks leves na cozinha antes de qualquer bola forte.',
    ],
    cues: ['Comece devagar, termine no ritmo do jogo', 'Movimento amplo e controlado', 'Dink leve antes da bola forte'],
    common_errors: [
      { error: 'Ficar parado alongando por muito tempo antes de jogar.', fix: 'Antes do jogo, prefira movimento: deixe o alongamento parado para depois.' },
      { error: 'Começar já com smash e drive forte.', fix: 'Suba aos poucos: movimento leve, depois amplo, depois rápido, e só então bola forte.' },
    ],
    variations: {
      easier: 'Tarefa: só trote leve, círculos de braço e dinks, num total de 6 minutos.',
      harder: 'Tarefa: acrescente 3 tiros curtos até a cozinha e a freada em split step no fim.',
    },
    safety: `Aquecimento não substitui avaliação médica. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Movimentos leves para subir a temperatura do corpo.',
        execucao: 'Movimentos amplos que imitam o jogo: girar, abaixar, deslocar.',
        finalizacao: 'Ritmo de jogo com bola, começando pelos dinks.',
      },
      abilities: ['mobilidade', 'coordenacao', 'ritmo'],
    },
    media: [],
  },
  {
    slug: 'deslocamento-lateral-com-cones',
    version: 1,
    kind: 'fisico',
    title: 'Deslocamento lateral na linha da cozinha',
    summary: 'Passos laterais rápidos ao longo da linha da cozinha, tocando cones com a raquete. Treina o movimento que mais se usa na rede.',
    objective: 'Ao final, o atleta consegue se deslocar de lado com base baixa e sem cruzar as pernas por 30 segundos seguidos.',
    skills: ['physical.agilidade', 'physical.condicionamento'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 8,
    intensity: 7,
    place: ['quadra'],
    equipment: ['cones', 'raquete'],
    practice_mode: 'bloco',
    sets: 4,
    reps: '30 s de trabalho',
    rest_sec: 45,
    steps: [
      'Coloque três cones logo atrás da linha da cozinha: um em cada lateral e um no meio.',
      'Comece no cone do meio, em base baixa e com a raquete na frente.',
      'Desloque-se de lado até o cone da direita e toque nele com a raquete.',
      'Volte ao meio, siga até o cone da esquerda e toque.',
      'Repita por 30 segundos e descanse 45.',
    ],
    cues: ['Toque o cone com a raquete', 'Passos curtos, pés rápidos', 'Raquete na frente o tempo todo'],
    common_errors: [
      { error: 'Cruzar uma perna na frente da outra.', fix: 'Passo lateral: o pé de dentro vai atrás do pé de fora, sem cruzar.' },
      { error: 'Ficar em pé, com as pernas esticadas.', fix: 'Fique baixo, como quem vai sentar numa cadeira, do começo ao fim.' },
    ],
    variations: {
      easier: 'Espaço: só dois cones, a 3 metros um do outro, e 20 segundos de trabalho.',
      harder: 'Tarefa: um parceiro aponta o cone a tocar, sem ordem fixa.',
    },
    safety: `Use tênis de quadra, com solado para movimento lateral. Quadra molhada ou com areia: não faça. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Base baixa e larga, peso na frente dos pés.',
        execucao: 'Passos laterais curtos, sem cruzar as pernas.',
        finalizacao: 'Pare equilibrado no cone e troque de direção.',
      },
      abilities: ['agilidade', 'equilibrio', 'resistencia'],
    },
    diagrams: [
      diagrama('Três cones na linha', 'cozinha', [
        cone(12, 68),
        cone(50, 68),
        cone(88, 68),
        jogador(50, 72, 'a'),
        desloca(54, 72, 84, 72),
        desloca(46, 72, 16, 72),
      ]),
    ],
    media: [],
  },
  {
    slug: 'reacao-aos-quatro-cones',
    version: 1,
    kind: 'fisico',
    title: 'Reação aos quatro cones',
    summary: 'Um parceiro chama o número de um cone e você sai do centro, toca nele e volta. Treina o primeiro passo depois do split step.',
    objective: 'Ao final, o atleta consegue reagir à chamada com split step e primeiro passo na direção certa em 9 de 10 reações.',
    skills: ['physical.agilidade'],
    level_min: 2.5,
    players_min: 2,
    players_max: 4,
    roles: ['Quem chama', 'Quem reage'],
    duration_min: 8,
    intensity: 7,
    place: ['quadra'],
    equipment: ['cones'],
    practice_mode: 'aleatorio',
    sets: 4,
    reps: '6 reações',
    rest_sec: 60,
    steps: [
      'Monte um quadrado de 3 metros com um cone em cada canto, numerados de 1 a 4.',
      'Quem reage fica no centro, saltitando de leve.',
      'Quem chama diz um número; quem reage faz o split step, sai para o cone, toca e volta ao centro.',
      'Quem chama espera quem reage voltar ao centro antes da próxima chamada.',
      'Depois de 6 reações, descanse e troquem.',
    ],
    cues: ['Ouviu o número, primeiro passo', 'Toque o cone e volte', 'Chegue no centro saltitando'],
    common_errors: [
      { error: 'Sair para o lado errado e corrigir no meio.', fix: 'Espere a chamada parado e equilibrado: chute não é reação.' },
      { error: 'Ficar parado com os pés colados no chão entre as chamadas.', fix: 'Saltite de leve no centro, com o peso na frente dos pés.' },
    ],
    variations: {
      easier: 'Tarefa: quem chama aponta o cone com a mão, em vez de falar o número.',
      harder: 'Tarefa: quem chama mostra uma bola e solta; quem reage a pega antes do segundo quique.',
    },
    safety: `Freie com passos curtos antes do cone. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Saltitar leve no centro, base aberta.',
        execucao: 'Split step na chamada e primeiro passo na direção do cone.',
        finalizacao: 'Toque, freie e volte ao centro.',
      },
      abilities: ['tempo_reacao', 'agilidade', 'equilibrio'],
    },
    diagrams: [
      diagrama('O quadrado', 'meia', [
        cone(35, 70),
        cone(65, 70),
        cone(35, 92),
        cone(65, 92),
        texto(30, 66, '1'),
        texto(70, 66, '2'),
        texto(30, 96, '3'),
        texto(70, 96, '4'),
        jogador(50, 81, 'a'),
        desloca(52, 79, 62, 72),
      ]),
    ],
    media: [],
  },
  {
    slug: 'panturrilha-com-descida-lenta',
    version: 1,
    kind: 'fisico',
    title: 'Panturrilha com descida lenta',
    summary: 'Subir na ponta dos pés rápido e descer devagar, num degrau. Fortalece a panturrilha e o tendão que mais sofrem com as arrancadas.',
    objective: 'Ao final de algumas semanas, o atleta consegue fazer 3 séries de 12 em cada perna com a descida controlada em 3 segundos.',
    skills: ['physical.forca_inferior'],
    level_min: 2.0,
    players_min: 1,
    players_max: 1,
    duration_min: 8,
    intensity: 4,
    place: ['casa', 'academia', 'quadra'],
    equipment: [],
    practice_mode: 'bloco',
    sets: 3,
    reps: '12 em cada perna',
    rest_sec: 60,
    tempo: '1 s sobe, 3 s desce',
    steps: [
      'Fique com a ponta dos pés num degrau, os calcanhares para fora, segurando num apoio firme.',
      'Suba na ponta dos dois pés em 1 segundo.',
      'Tire um pé e desça só com o outro, em 3 segundos, até o calcanhar ficar um pouco abaixo do degrau.',
      'Volte a subir com os dois pés e repita.',
      'Faça as 12 numa perna e depois troque.',
    ],
    cues: ['Suba rápido, desça em três tempos', 'Calcanhar passa da borda do degrau', 'Segure no apoio, sem pressa'],
    common_errors: [
      { error: 'Descer rápido, deixando o corpo cair.', fix: 'Conte três segundos na descida: é a parte que fortalece.' },
      { error: 'Fazer sem apoio e perder o equilíbrio.', fix: 'Segure numa parede ou corrimão: aqui o foco é a força, não o equilíbrio.' },
    ],
    variations: {
      easier: 'Tarefa: faça no chão plano, subindo e descendo com os dois pés.',
      harder: 'Equipamento: segure um peso leve (uma mochila com livros) na mão do lado da perna que trabalha.',
    },
    safety: `Dor forte e repentina atrás da perna ou no calcanhar: pare na hora. ${PARE_SE_DOER}`,
    media: [],
  },
  {
    slug: 'equilibrio-numa-perna-com-raquete',
    version: 1,
    kind: 'fisico',
    title: 'Equilíbrio numa perna com a raquete',
    summary: 'Ficar numa perna só, primeiro parado e depois fazendo o gesto do dink. Melhora o equilíbrio para bater esticado sem cair na cozinha.',
    objective: 'Ao final, o atleta consegue ficar 30 segundos numa perna fazendo o gesto do dink sem apoiar o outro pé.',
    skills: ['physical.forca_inferior', 'physical.core'],
    level_min: 2.0,
    players_min: 1,
    players_max: 2,
    duration_min: 6,
    intensity: 3,
    place: ['casa', 'quadra', 'academia'],
    equipment: ['raquete'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '30 s em cada perna',
    rest_sec: 30,
    steps: [
      'Fique numa perna só, com a perna de apoio levemente dobrada, perto de uma parede.',
      'Segure 30 segundos parado, olhando um ponto fixo à frente.',
      'Na segunda série, faça o gesto do dink devagar enquanto se equilibra.',
      'Na terceira, incline-se para a frente como quem alcança uma bola curta e volte.',
      'Troque de perna a cada série.',
    ],
    cues: ['Olhe um ponto fixo à frente', 'Raquete desenha o dink devagar', 'Alcance a bola e volte'],
    common_errors: [
      { error: 'Travar a perna de apoio totalmente esticada.', fix: 'Mantenha a perna de apoio levemente dobrada, como na quadra.' },
      { error: 'Apoiar o pé no chão a cada balanço.', fix: 'Diminua o movimento até conseguir os 30 segundos inteiros.' },
    ],
    variations: {
      easier: 'Tarefa: apenas parado, com a ponta dos dedos encostada na parede.',
      harder: 'Tarefa: um parceiro joga uma bola com a mão e você devolve um dink sem apoiar o outro pé.',
    },
    safety: `Faça perto de uma parede ou cadeira para se apoiar se perder o equilíbrio. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Perna de apoio levemente dobrada, olhar num ponto fixo.',
        execucao: 'Gesto do dink devagar sem perder a base.',
        finalizacao: 'Volte ao centro e segure parado.',
      },
      abilities: ['equilibrio', 'coordenacao'],
    },
    media: [],
  },
  {
    slug: 'rotacao-externa-com-elastico',
    version: 1,
    kind: 'fisico',
    title: 'Rotação externa com elástico',
    summary: 'Abrir o elástico girando a mão para fora, com o cotovelo colado ao corpo. Fortalece a parte de trás do ombro, que equilibra o saque e o smash.',
    objective: 'Ao final de algumas semanas, o atleta consegue fazer 3 séries de 15 com controle nos dois sentidos do movimento.',
    skills: ['physical.ombro_antebraco'],
    level_min: 2.0,
    players_min: 1,
    players_max: 1,
    duration_min: 6,
    intensity: 3,
    place: ['casa', 'academia'],
    equipment: ['elastico'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '12 a 15 de cada lado',
    rest_sec: 60,
    tempo: '2 s abre, 2 s volta',
    steps: [
      'Prenda o elástico numa maçaneta na altura da cintura e fique de lado para ela.',
      'Segure o elástico com a mão de fora, cotovelo dobrado em 90 graus e colado ao corpo (uma toalha enrolada ajuda).',
      'Gire a mão para fora, afastando-a da barriga, em 2 segundos.',
      'Volte em 2 segundos, sem deixar o elástico puxar.',
      'Faça a série, vire de lado e repita com a outra mão.',
    ],
    cues: ['Toalha presa até o fim', 'Mão abre como uma porta', 'Elástico volta devagar'],
    common_errors: [
      { error: 'A toalha cai porque o cotovelo se afasta do corpo.', fix: 'Diminua a amplitude: gire só até onde a toalha continua presa.' },
      { error: 'Elástico forte demais, com o corpo todo ajudando.', fix: 'Use um elástico mais leve: o movimento tem de ser limpo nas 15.' },
    ],
    variations: {
      easier: 'Equipamento: sem elástico, só o movimento, ou com o elástico mais leve.',
      harder: 'Tarefa: com o cotovelo na altura do ombro, como no saque de tênis, e elástico leve.',
    },
    safety: `Movimento sem dor e com carga leve. ${PARE_SE_DOER}`,
    media: [],
  },
  {
    slug: 'antebraco-com-descida-lenta',
    version: 1,
    kind: 'fisico',
    title: 'Antebraço com descida lenta (garrafa)',
    summary: 'Com uma garrafa de água, levantar a mão com ajuda e descer devagar. Fortalece o antebraço, que trabalha em todo golpe.',
    objective: 'Ao final de algumas semanas, o atleta consegue fazer 3 séries de 15 descidas lentas com uma garrafa de 1 litro.',
    skills: ['physical.ombro_antebraco'],
    level_min: 2.0,
    players_min: 1,
    players_max: 1,
    duration_min: 6,
    intensity: 3,
    place: ['casa', 'academia'],
    equipment: [],
    practice_mode: 'bloco',
    sets: 3,
    reps: '15 de cada lado',
    rest_sec: 45,
    tempo: '1 s sobe, 3 s desce',
    steps: [
      'Sente-se com o antebraço apoiado na coxa e a mão para fora do joelho, palma para baixo, segurando a garrafa.',
      'Com a ajuda da outra mão, leve a garrafa para cima.',
      'Tire a ajuda e desça a garrafa sozinho, em 3 segundos.',
      'Repita as 15 e troque de lado.',
      'Na semana seguinte, se estiver fácil, use uma garrafa mais pesada.',
    ],
    cues: ['Garrafa desce em três tempos', 'A outra mão ajuda a subir', 'Movimento só da mão'],
    common_errors: [
      { error: 'Subir sozinho e com tranco.', fix: 'Suba com a ajuda da outra mão: o exercício é a descida.' },
      { error: 'Garrafa pesada demais logo no começo.', fix: 'Comece com meio litro e aumente só quando as 15 ficarem fáceis.' },
    ],
    variations: {
      easier: 'Equipamento: garrafa de meio litro ou só a mão, sem carga.',
      harder: 'Equipamento: segure a raquete pela ponta do cabo, longe da cabeça, em vez da garrafa.',
    },
    safety: `Carga leve e sem dor. Dor na parte de fora do cotovelo que não melhora com o descanso: procure um profissional de saúde. ${PARE_SE_DOER}`,
    media: [],
  },
  {
    slug: 'afundo-com-alcance',
    version: 1,
    kind: 'fisico',
    title: 'Afundo com alcance de bola curta',
    summary: 'Dar um passo à frente, descer e tocar uma bola no chão com a raquete, como no dink esticado. Fortalece as pernas na posição em que se joga.',
    objective: 'Ao final, o atleta consegue fazer 3 séries de 8 afundos em cada perna voltando à base sem perder o equilíbrio.',
    skills: ['physical.forca_inferior'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 8,
    intensity: 5,
    place: ['quadra', 'casa', 'academia'],
    equipment: ['raquete', 'bolas'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '8 em cada perna',
    rest_sec: 60,
    tempo: '2 s desce, 1 s volta',
    steps: [
      'Ponha uma bola no chão, a um passo grande à sua frente.',
      'Dê o passo, desça devagar em 2 segundos e toque a bola com a raquete.',
      'Empurre o chão com o pé da frente e volte à base.',
      'Alterne as pernas até completar 8 de cada lado.',
      'Descanse e repita as séries.',
    ],
    cues: ['Toque a bola com a raquete', 'Pé da frente aponta a rede', 'Empurre o chão para voltar'],
    common_errors: [
      { error: 'O pé da frente vira para dentro na descida.', fix: 'Aponte o pé da frente para a rede e desça em linha reta.' },
      { error: 'Descer rápido e bater a perna de trás no chão.', fix: 'Conte dois tempos na descida e pare antes de encostar.' },
    ],
    variations: {
      easier: 'Espaço: passo mais curto e descida até a metade.',
      harder: 'Tarefa: afundo para os lados e na diagonal, como no dink esticado de forehand e de backhand.',
    },
    safety: `Desça só até onde controla. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Base com os pés na largura dos ombros, raquete na frente.',
        execucao: 'Passo à frente e descida controlada até a bola.',
        finalizacao: 'Empurrar o chão e voltar à base.',
      },
      abilities: ['forca', 'equilibrio'],
    },
    media: [],
  },
  {
    slug: 'freada-na-entrada-da-cozinha',
    version: 1,
    kind: 'fisico',
    title: 'Freada antes da linha da cozinha',
    summary: 'Correr do meio da quadra e frear em split step antes da linha. Treina a freada que evita pisar na cozinha e torcer o pé.',
    objective: 'Ao final, o atleta consegue frear de uma corrida curta e parar equilibrado, com os pés atrás da linha, em 5 de 5 repetições.',
    skills: ['physical.agilidade', 'physical.forca_inferior'],
    level_min: 2.5,
    players_min: 1,
    players_max: 4,
    duration_min: 8,
    intensity: 7,
    place: ['quadra'],
    equipment: ['cones'],
    practice_mode: 'bloco',
    sets: 4,
    reps: '5 freadas',
    rest_sec: 60,
    steps: [
      'Coloque um cone no meio da quadra, entre o fundo e a cozinha.',
      'Saia do cone correndo para a frente, em direção à linha da cozinha.',
      'Nos últimos três passos, encurte as passadas e abaixe o corpo.',
      'Pare com um saltinho, pés afastados e atrás da linha, raquete na frente.',
      'Volte andando até o cone e repita.',
    ],
    cues: ['Pare antes da linha', 'Passos curtos no fim', 'Chegue baixo, como mola'],
    common_errors: [
      { error: 'Frear com um passo longo, com o pé na frente do corpo.', fix: 'Encurte as passadas antes: a freada é em vários passos curtos.' },
      { error: 'Passar por cima da linha.', fix: 'Comece a frear mais cedo: escolha um ponto um metro antes da linha.' },
    ],
    variations: {
      easier: 'Tarefa: comece andando rápido em vez de correndo.',
      harder: 'Tarefa: um parceiro joga uma bola na chegada e você devolve um dink parado.',
    },
    safety: `Use tênis de quadra e faça só em quadra seca. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Saída curta e acelerada.',
        execucao: 'Passos curtos e corpo baixo nos últimos metros.',
        finalizacao: 'Split step atrás da linha, raquete na frente.',
      },
      abilities: ['agilidade', 'equilibrio', 'forca'],
    },
    diagrams: [
      diagrama('Corrida e freada', 'meia', [
        cone(50, 82),
        jogador(50, 86, 'a'),
        desloca(50, 84, 50, 69),
        texto(66, 68, 'Pare aqui'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'mobilidade-de-quadril-90-90',
    version: 1,
    kind: 'fisico',
    title: 'Mobilidade de quadril 90-90',
    summary: 'Sentado no chão com as duas pernas dobradas em 90 graus, trocar de lado devagar. Solta o quadril para abaixar e girar na quadra.',
    objective: 'Ao final, o atleta consegue trocar de lado 6 vezes devagar, sem apoiar as mãos, depois de algumas semanas de prática.',
    skills: ['physical.mobilidade'],
    level_min: 2.0,
    players_min: 1,
    players_max: 1,
    duration_min: 5,
    intensity: 2,
    place: ['casa', 'academia'],
    equipment: [],
    practice_mode: 'bloco',
    sets: 2,
    reps: '6 trocas de lado',
    rest_sec: 30,
    steps: [
      'Sente no chão com uma perna dobrada à frente e a outra dobrada ao lado, as duas em ângulo reto.',
      'Apoie as mãos atrás do corpo se precisar.',
      'Gire as duas pernas juntas para o outro lado, devagar, mantendo os pés no chão.',
      'Segure 2 respirações em cada lado.',
      'Repita as trocas.',
    ],
    cues: ['Pés no chão, troque devagar', 'Respire enquanto troca', 'Peito alto, olhando à frente'],
    common_errors: [
      { error: 'Forçar a troca com tranco.', fix: 'Gire devagar e só até onde não dói; a amplitude melhora com as semanas.' },
      { error: 'Prender a respiração.', fix: 'Solte o ar devagar durante a troca.' },
    ],
    variations: {
      easier: 'Tarefa: com as mãos apoiadas atrás e o ângulo das pernas mais aberto.',
      harder: 'Tarefa: sem as mãos, e incline o peito sobre a perna da frente por 2 respirações.',
    },
    safety: `Alongue até sentir tensão leve, nunca dor. ${PARE_SE_DOER}`,
    media: [],
  },
  {
    slug: 'livro-aberto-giro-da-coluna',
    version: 1,
    kind: 'fisico',
    title: 'Livro aberto: giro da coluna',
    summary: 'Deitado de lado, abrir o braço de cima como as páginas de um livro. Solta a parte de cima das costas para girar no drive e no smash.',
    objective: 'Ao final, o atleta consegue abrir o braço de cima até perto do chão do outro lado, sem tirar os joelhos do lugar.',
    skills: ['physical.mobilidade'],
    level_min: 2.0,
    players_min: 1,
    players_max: 1,
    duration_min: 5,
    intensity: 2,
    place: ['casa', 'academia'],
    equipment: [],
    practice_mode: 'bloco',
    sets: 2,
    reps: '8 em cada lado',
    rest_sec: 30,
    tempo: '2 s abre, 2 s fecha',
    steps: [
      'Deite de lado com os joelhos dobrados à frente e os braços esticados, uma mão sobre a outra.',
      'Abra a mão de cima num arco até o outro lado, seguindo-a com os olhos.',
      'Segure uma respiração aberto.',
      'Volte devagar até as mãos se encontrarem.',
      'Faça as 8 e troque de lado.',
    ],
    cues: ['Mão de cima desenha um arco', 'Siga a mão com os olhos', 'Volte devagar, sem tranco'],
    common_errors: [
      { error: 'Os joelhos saem do lugar junto com o giro.', fix: 'Deixe os joelhos parados (um travesseiro entre eles ajuda) e gire só as costas.' },
      { error: 'Forçar a mão até o chão.', fix: 'Abra só até a tensão leve; o chão é a meta das próximas semanas.' },
    ],
    variations: {
      easier: 'Tarefa: abra só até apontar a mão para o teto.',
      harder: 'Tarefa: sentado numa cadeira, com a raquete atravessada no peito, gire para os dois lados.',
    },
    safety: `Movimento lento e sem dor. ${PARE_SE_DOER}`,
    media: [],
  },
  {
    slug: 'prancha-lateral',
    version: 1,
    kind: 'fisico',
    title: 'Prancha lateral',
    summary: 'Apoiado de lado, segurar o corpo reto. Fortalece a lateral do abdômen, que segura o corpo nos giros e nas freadas.',
    objective: 'Ao final de algumas semanas, o atleta consegue segurar 30 segundos de cada lado com o corpo alinhado.',
    skills: ['physical.core'],
    level_min: 2.0,
    players_min: 1,
    players_max: 1,
    duration_min: 6,
    intensity: 4,
    place: ['casa', 'academia', 'quadra'],
    equipment: [],
    practice_mode: 'bloco',
    sets: 3,
    reps: '20 a 30 s de cada lado',
    rest_sec: 45,
    steps: [
      'Deite de lado, apoiado no antebraço, com o cotovelo embaixo do ombro.',
      'Tire o quadril do chão até o corpo ficar reto, da cabeça aos pés.',
      'Segure respirando normalmente.',
      'Desça, descanse e troque de lado.',
    ],
    cues: ['Corpo reto como uma tábua', 'Empurre o chão para longe', 'Respire durante a prancha'],
    common_errors: [
      { error: 'O quadril cai durante a prancha.', fix: 'Encurte o tempo: 15 segundos bem-feitos valem mais que 30 caindo.' },
      { error: 'Prender a respiração.', fix: 'Conte o tempo em voz alta: falando, você respira.' },
    ],
    variations: {
      easier: 'Tarefa: com os joelhos dobrados e apoiados no chão.',
      harder: 'Tarefa: levante a perna de cima por 2 segundos, várias vezes durante a prancha.',
    },
    safety: `Dor nas costas durante a prancha: pare e use a versão com os joelhos apoiados. ${PARE_SE_DOER}`,
    media: [],
  },
  {
    slug: 'anti-rotacao-com-elastico',
    version: 1,
    kind: 'fisico',
    title: 'Anti-rotação com elástico (Pallof)',
    summary: 'De lado para o elástico, empurrar as mãos para a frente sem deixar o corpo girar. Ensina o corpo a ficar firme enquanto a raquete trabalha.',
    objective: 'Ao final, o atleta consegue fazer 3 séries de 10 de cada lado sem que o elástico gire o corpo.',
    skills: ['physical.core'],
    level_min: 2.5,
    players_min: 1,
    players_max: 1,
    duration_min: 6,
    intensity: 4,
    place: ['casa', 'academia'],
    equipment: ['elastico'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '10 de cada lado',
    rest_sec: 45,
    tempo: '2 s vai, 2 s volta',
    steps: [
      'Prenda o elástico na altura do peito e fique de lado para ele, pernas um pouco dobradas.',
      'Segure o elástico com as duas mãos junto ao peito.',
      'Empurre as mãos para a frente até esticar, sem deixar o corpo virar.',
      'Segure 2 segundos e volte devagar ao peito.',
      'Faça as 10 e vire para o outro lado.',
    ],
    cues: ['Mãos saem em linha reta', 'O elástico não vira você', 'Pés firmes, como na base'],
    common_errors: [
      { error: 'O corpo gira junto com o elástico.', fix: 'Afaste-se menos da parede ou use um elástico mais leve.' },
      { error: 'As mãos saem para o lado.', fix: 'Empurre para a frente, apontando para longe de você, sempre em linha reta.' },
    ],
    variations: {
      easier: 'Equipamento: elástico mais leve e mais perto do ponto onde está preso.',
      harder: 'Tarefa: faça em base de afundo ou numa perna só.',
    },
    safety: `Carga leve, sem dor nas costas. ${PARE_SE_DOER}`,
    media: [],
  },
  {
    slug: 'recuo-seguro-virar-e-correr',
    version: 1,
    kind: 'fisico',
    title: 'Recuo seguro: virar e correr',
    summary: 'Treino do movimento para ir atrás do lob: virar o corpo e correr de lado, sem andar de costas. É a principal prevenção de quedas no pickleball.',
    objective: 'Ao final, o atleta consegue recuar da linha da cozinha até o fundo virando o corpo e correndo, nos dois lados, sem dar passos de costas.',
    skills: ['physical.agilidade'],
    level_min: 2.0,
    players_min: 1,
    players_max: 2,
    duration_min: 8,
    intensity: 5,
    place: ['quadra'],
    equipment: ['cones'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '5 de cada lado',
    rest_sec: 45,
    steps: [
      'Comece na linha da cozinha, na base, com a raquete na frente.',
      'Ao sinal, gire o corpo para o lado da raquete: o primeiro passo é para trás e para o lado.',
      'Corra de lado ou de frente até o cone no fundo, olhando por cima do ombro.',
      'Pare equilibrado, faça o gesto do golpe e volte andando para a cozinha.',
      'Alterne os lados: forehand e backhand.',
    ],
    cues: ['Vire e corra atrás da bola', 'Primeiro passo para trás e de lado', 'Olhe a bola por cima'],
    common_errors: [
      { error: 'Andar de costas, de frente para a rede.', fix: 'Gire primeiro, corra depois: andar de costas é como se cai.' },
      { error: 'Correr olhando o chão e perder a bola.', fix: 'Olhe por cima do lado da raquete, como quem procura a bola no céu.' },
    ],
    variations: {
      easier: 'Tarefa: só andando rápido, até o meio da quadra.',
      harder: 'Tarefa: um parceiro joga um lob de verdade e você devolve depois do quique.',
    },
    safety: `Andar de costas atrás do lob é uma das causas mais comuns de queda no pickleball: sempre vire e corra. Comece devagar. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Base na cozinha, leitura cedo do sinal.',
        execucao: 'Giro do corpo e corrida em diagonal, olhando por cima.',
        finalizacao: 'Parada equilibrada e volta andando para a frente.',
      },
      abilities: ['agilidade', 'equilibrio', 'leitura'],
    },
    diagrams: [
      diagrama('Virar e correr', 'inteira', [
        jogador(65, 68, 'a'),
        cone(80, 94),
        desloca(67, 70, 79, 92),
        trajeto(30, 34, 76, 90, 'Lob'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'circuito-de-quadra',
    version: 1,
    kind: 'fisico',
    title: 'Circuito de quadra: 30 segundos de cada',
    summary: 'Quatro estações com os movimentos do jogo, 30 segundos de trabalho e 30 de pausa. Constrói fôlego para os pontos longos.',
    objective: 'Ao final de algumas semanas, o atleta consegue completar 3 voltas do circuito mantendo a qualidade dos movimentos até o fim.',
    skills: ['physical.condicionamento', 'physical.agilidade'],
    level_min: 2.5,
    players_min: 1,
    players_max: 8,
    duration_min: 15,
    intensity: 7,
    place: ['quadra'],
    equipment: ['cones', 'raquete'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '4 estações de 30 s',
    rest_sec: 30,
    steps: [
      'Estação 1: deslocamento lateral na linha da cozinha, tocando os cones.',
      'Estação 2: saltinhos de split step com a raquete na frente.',
      'Estação 3: do meio da quadra até a cozinha, freando antes da linha, e volta andando.',
      'Estação 4: golpes de sombra, alternando forehand e backhand na base.',
      'Trinta segundos de trabalho e trinta de pausa em cada estação; descanse 2 minutos entre as voltas.',
    ],
    cues: ['Qualidade antes da velocidade', 'Raquete na frente em toda estação', 'Respire na pausa'],
    common_errors: [
      { error: 'O movimento piora no fim de cada estação.', fix: 'Diminua o ritmo: o que conta é o movimento certo até o último segundo.' },
      { error: 'Sair rápido demais na primeira volta.', fix: 'Comece a 70% e suba na última volta.' },
    ],
    variations: {
      easier: 'Tarefa: duas voltas e 45 segundos de pausa.',
      harder: 'Tarefa: quatro voltas, ou 40 segundos de trabalho e 20 de pausa.',
    },
    safety: `Faça depois do aquecimento, com água por perto, e evite as horas mais quentes do dia. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Aquecimento completo antes do circuito.',
        execucao: 'Movimentos do jogo em ritmo forte e controlado.',
        finalizacao: 'Volta à calma caminhando e respirando.',
      },
      abilities: ['resistencia', 'agilidade', 'coordenacao'],
    },
    diagrams: [
      diagrama('As quatro estações', 'meia', [
        texto(20, 66, '1'),
        cone(10, 68),
        cone(40, 68),
        texto(70, 76, '2'),
        cone(75, 88),
        texto(84, 84, '3'),
        desloca(75, 86, 75, 70),
        texto(30, 90, '4'),
        jogador(30, 94, 'a'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'volta-a-calma',
    version: 1,
    kind: 'fisico',
    title: 'Volta à calma depois do jogo',
    summary: 'Caminhada leve e alongamentos parados, sem pressa, ao terminar. Ajuda a baixar o ritmo e é a hora certa do alongamento parado.',
    objective: 'Ao final, o atleta termina o treino com a respiração normalizada e os principais grupos alongados em 6 a 8 minutos.',
    skills: ['physical.mobilidade'],
    level_min: 2.0,
    players_min: 1,
    players_max: 8,
    duration_min: 7,
    intensity: 1,
    place: ['quadra', 'casa', 'academia'],
    equipment: [],
    practice_mode: 'bloco',
    sets: 1,
    reps: '30 a 45 s em cada alongamento',
    rest_sec: 0,
    steps: [
      'Dois minutos de caminhada leve em volta da quadra.',
      'Panturrilha: mãos no alambrado, uma perna atrás esticada.',
      'Parte de trás da coxa: calcanhar num banco baixo, peito à frente.',
      'Peito e frente do ombro: mão no poste da rede, girando o corpo para longe.',
      'Antebraço: mão esticada à frente, a outra puxando os dedos de leve.',
      'Termine com 5 respirações lentas e beba água.',
    ],
    cues: ['Tensão leve, sem dor', 'Respire devagar e solte', 'Água antes de ir embora'],
    common_errors: [
      { error: 'Balançar para alongar mais.', fix: 'Fique parado na posição e deixe a tensão diminuir sozinha.' },
      { error: 'Ir embora direto depois do último ponto.', fix: 'Reserve 5 minutos: a volta à calma faz parte do treino.' },
    ],
    variations: {
      easier: 'Tarefa: só a caminhada e dois alongamentos.',
      harder: 'Tarefa: acrescente a mobilidade 90-90 e o livro aberto.',
    },
    safety: `Alongue até tensão leve, nunca até a dor. ${PARE_SE_DOER}`,
    media: [],
  },
];
