/** Biblioteca inicial — FUNDAMENTOS (como executar cada golpe e posição). */

import { diagrama, jogador, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const FUNDAMENTOS = [
  {
    slug: 'empunhadura-continental',
    version: 1,
    featured: true,
    kind: 'fundamento',
    title: 'Empunhadura continental',
    summary: 'A forma de segurar a raquete que serve para quase todos os golpes, de forehand e de backhand, sem trocar a mão de posição. A base de quem joga na rede.',
    objective: 'Ao final, o atleta segura a raquete na continental, com pressão leve, e joga dink e voleio dos dois lados sem trocar a empunhadura.',
    skills: ['net.voleio', 'kitchen.dink_paralelo', 'groundstrokes.drive'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 5,
    intensity: 1,
    place: ['quadra', 'casa'],
    equipment: ['raquete'],
    practice_mode: 'bloco',
    steps: [
      'Segure a raquete pelo cabo como quem segura um martelo para pregar um prego.',
      'A face da raquete fica de lado, em pé, perpendicular ao chão.',
      'O "V" entre o polegar e o indicador fica em cima do cabo, um pouco para o lado da borda de cima.',
      'Aperte pouco: numa escala de 1 a 10, entre 3 e 4.',
      'Teste: faça um voleio de forehand e um de backhand sem mexer a mão no cabo.',
    ],
    cues: ['Segure como um martelo', 'Aperto leve, como um passarinho', 'Mesma pegada nos dois lados'],
    positioning: [
      { type: 'certo', text: 'Raquete de lado, como um martelo, que serve para o forehand e o backhand sem trocar.' },
      { type: 'errado', text: 'Raquete deitada, como uma frigideira: o forehand fica fácil, mas o backhand e o voleio rápido chegam atrasados.' },
    ],
    common_errors: [
      { error: 'Apertar demais a raquete.', fix: 'Aperto leve dá toque no dink e reação no voleio; aperte só um pouco mais no golpe forte.' },
      { error: 'Trocar de empunhadura em cada bola rápida na rede.', fix: 'Na rede, fique sempre na continental: não há tempo de trocar.' },
    ],
    when_to_use: 'Na rede (dink, voleio, reset), no saque e como base para o resto. Alguns jogadores usam outra empunhadura no drive, mas a continental é o ponto de partida.',
    motor: {
      phases: {
        preparacao: 'Cabo na mão como um martelo, aperto leve.',
        execucao: 'A mesma pegada no forehand e no backhand.',
        finalizacao: 'A mão volta a relaxar entre as bolas.',
      },
      abilities: ['coordenacao'],
    },
    media: [],
  },
  {
    slug: 'posicao-de-prontidao',
    version: 1,
    kind: 'fundamento',
    title: 'Posição de prontidão na rede',
    summary: 'A base de espera na linha da cozinha: pernas afastadas e dobradas, peso na frente e raquete na frente do peito. Dela saem todos os golpes rápidos.',
    objective: 'Ao final, o atleta volta à posição de prontidão entre todas as bolas e reage aos dois lados sem atraso.',
    skills: ['net.contra_ataque', 'physical.agilidade', 'doubles.posicionamento'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 5,
    intensity: 2,
    place: QUADRA,
    equipment: ['raquete'],
    practice_mode: 'bloco',
    steps: [
      'Pés afastados um pouco mais que a largura dos ombros, logo atrás da linha da cozinha.',
      'Pernas dobradas e peso na parte da frente dos pés.',
      'Raquete na frente do peito, cabeça da raquete para cima, um pouco para o lado do backhand.',
      'Depois de cada golpe, volte a essa posição antes da próxima bola.',
    ],
    cues: ['Raquete na frente do peito', 'Peso na ponta dos pés', 'Bateu? Volte à base'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente do peito, entre o forehand e o backhand: chega aos dois lados no mesmo tempo.' },
      { type: 'errado', text: 'Raquete caída ao lado da perna: a bola rápida no peito passa antes de a raquete subir.' },
    ],
    common_errors: [
      { error: 'Ficar em pé, com as pernas esticadas.', fix: 'Pernas dobradas, como quem vai sentar: o corpo reage mais rápido.' },
      { error: 'Deixar a raquete cair depois de cada golpe.', fix: 'Termine o golpe e traga a raquete de volta para a frente do peito.' },
    ],
    when_to_use: 'Em todo momento na linha da cozinha, principalmente nas trocas rápidas.',
    motor: {
      phases: {
        preparacao: 'Base larga, pernas dobradas.',
        execucao: 'Raquete na frente do peito, peso à frente.',
        finalizacao: 'Volta à base depois de cada golpe.',
      },
      abilities: ['tempo_reacao', 'equilibrio'],
    },
    media: [],
  },
  {
    slug: 'dink',
    version: 1,
    kind: 'fundamento',
    title: 'Dink: a bola curta e baixa na cozinha',
    summary: 'Golpe suave, da linha da cozinha, que cai na cozinha do adversário. Bola baixa não pode ser atacada: o dink é o golpe da paciência.',
    objective: 'Ao final, o atleta executa o dink com gesto curto, a bola fazendo o ponto mais alto do seu lado e caindo na cozinha adversária.',
    skills: ['kitchen.dink_cruzado', 'kitchen.dink_paralelo', 'kitchen.paciencia'],
    level_min: 2.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique na linha da cozinha em posição de prontidão.',
      'Deixe a bola chegar à sua frente; se ela quicar curta, pode entrar na cozinha para buscá-la.',
      'Com a face um pouco aberta, levante a bola com as pernas, com gesto curto, de baixo para cima.',
      'O ponto mais alto da bola fica do seu lado da rede; ela cai na cozinha do adversário.',
      'Volte para trás da linha da cozinha e para a base.',
    ],
    cues: ['Raquete como uma pá', 'Pico antes da rede', 'Bola morre na cozinha'],
    positioning: [
      { type: 'certo', text: 'Dink que cai na cozinha, perto da linha: o adversário precisa bater de baixo para cima.' },
      { type: 'errado', text: 'Dink que cai fora da cozinha ou sobe alto: o adversário bate de cima para baixo e ataca.' },
    ],
    common_errors: [
      { error: 'Bater com o pulso, dando um tapa na bola.', fix: 'Quem faz a bola subir são as pernas; a raquete só acompanha.' },
      { error: 'Voltar à rede pisando na cozinha para volear.', fix: 'Depois de entrar na cozinha, volte com os dois pés para fora antes de volear.' },
      { error: 'Dink sempre no mesmo lugar.', fix: 'Varie entre cruzado, paralelo e o meio, sempre baixo.' },
    ],
    when_to_use: 'Quando os dois lados estão na rede e a bola chega baixa, abaixo da altura da fita.',
    motor: {
      phases: {
        preparacao: 'Base larga, raquete na frente e baixa, face um pouco aberta.',
        execucao: 'Gesto curto de baixo para cima; as pernas sobem.',
        finalizacao: 'A raquete para apontando o alvo e volta à frente.',
      },
      abilities: ['precisao', 'equilibrio', 'ritmo'],
    },
    diagrams: [
      diagrama('Certo: cai na cozinha', 'cozinha', [
        zona(0, 35, 100, 49, 'Alvo'),
        jogador(70, 68, 'a'),
        jogador(30, 32, 'b'),
        trajeto(70, 66, 32, 40),
      ], 'certo'),
      diagrama('Errado: longo e atacável', 'cozinha', [
        jogador(70, 68, 'a'),
        jogador(30, 32, 'b'),
        trajeto(70, 66, 34, 28),
        zona(15, 25, 50, 33, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'drop-da-terceira-bola',
    version: 1,
    kind: 'fundamento',
    title: 'Drop da terceira bola',
    summary: 'Do fundo da quadra, uma bola em arco que cai na cozinha adversária. Dá à dupla que sacou o tempo de chegar à rede.',
    objective: 'Ao final, o atleta executa o drop com arco que tem o pico do seu lado e a bola descendo para a cozinha adversária.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.transicao'],
    level_min: 2.5,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Prepare a raquete baixa e cedo, assim que a devolução sai.',
      'Encontre a bola na frente do corpo, depois do quique.',
      'Com a face um pouco aberta, levante a bola num arco: o pico fica do seu lado.',
      'A bola passa a rede descendo e cai na cozinha.',
      'Se o drop foi bom, avance dois passos e pare quando o adversário bater.',
    ],
    cues: ['Arco de arco-íris', 'Pico do seu lado', 'Drop bom? Avance e pare'],
    positioning: [
      { type: 'certo', text: 'Drop que cai na cozinha: os adversários só conseguem devolver de baixo para cima e você avança.' },
      { type: 'errado', text: 'Drop que cai no meio da quadra: os adversários avançam e atacam a sua chegada.' },
    ],
    common_errors: [
      { error: 'Drop em linha reta, rente à fita.', fix: 'Levante mais: o arco alto desce mais curto e mais devagar.' },
      { error: 'Correr para a rede logo depois de qualquer drop.', fix: 'Só avance depois de um drop baixo; alto, fique e defenda.' },
    ],
    when_to_use: 'Na terceira bola, quando os adversários já estão na rede e a devolução veio funda ou baixa.',
    motor: {
      phases: {
        preparacao: 'Raquete baixa e cedo, pernas dobradas.',
        execucao: 'Contato na frente, gesto de baixo para cima, as pernas sobem.',
        finalizacao: 'Raquete alta apontando a cozinha e passos para a frente.',
      },
      abilities: ['precisao', 'coordenacao'],
    },
    diagrams: [
      diagrama('Certo: na cozinha', 'inteira', [
        zona(5, 35, 95, 49, 'Alvo'),
        jogador(50, 96, 'a'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        trajeto(50, 94, 46, 42),
      ], 'certo'),
      diagrama('Errado: no meio da quadra', 'inteira', [
        jogador(50, 96, 'a'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        trajeto(50, 94, 48, 22),
        zona(10, 12, 90, 30, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'drive',
    version: 1,
    kind: 'fundamento',
    title: 'Drive: o golpe de fundo com força',
    summary: 'Golpe firme do fundo, com a bola passando baixa sobre a rede. Serve na devolução, na terceira bola contra quem demora a subir e para forçar a bola alta.',
    objective: 'Ao final, o atleta executa o drive com preparação cedo, contato na frente e a bola passando baixa sobre a rede.',
    skills: ['groundstrokes.drive', 'groundstrokes.terceira_bola_drive'],
    level_min: 2.5,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Vire de lado para a rede e prepare a raquete atrás, cedo.',
      'Dê um passo na direção da bola.',
      'Encontre a bola na frente do corpo, com o peso indo para a frente.',
      'O gesto vai de baixo para cima e para a frente, passando a bola baixa sobre a rede.',
      'Termine com a raquete alta do outro lado e volte à base.',
    ],
    cues: ['Prepare cedo, bata na frente', 'Bola rente à fita', 'Termine alto, do outro lado'],
    positioning: [
      { type: 'certo', text: 'De lado para a rede na preparação e com o peso indo para a bola no contato.' },
      { type: 'errado', text: 'De frente para a rede e com o peso para trás: a bola sobe e vira presente para o voleio.' },
    ],
    common_errors: [
      { error: 'Drive alto, que o adversário volea para baixo.', fix: 'Feche um pouco a face e termine para a frente: a bola passa baixa.' },
      { error: 'Drive em toda bola, até na baixa.', fix: 'Bola abaixo da altura da rede pede drop; o drive é para a bola alta e funda.' },
    ],
    when_to_use: 'Na devolução, na terceira bola com a devolução alta ou curta e contra quem demora a chegar à rede.',
    safety: 'Mire o meio ou os pés dos adversários, nunca o rosto.',
    motor: {
      phases: {
        preparacao: 'De lado, raquete atrás cedo, peso no pé de trás.',
        execucao: 'Passo à frente e contato na frente do corpo.',
        finalizacao: 'Raquete alta do outro lado e volta à base.',
      },
      abilities: ['potencia', 'coordenacao'],
    },
    diagrams: [
      diagrama('Alvo do drive', 'inteira', [
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        jogador(70, 96, 'a'),
        zona(38, 26, 62, 40, 'Meio'),
        trajeto(70, 94, 50, 34),
      ]),
    ],
    media: [],
  },
  {
    slug: 'voleio',
    version: 1,
    kind: 'fundamento',
    title: 'Voleio na rede',
    summary: 'Bater a bola antes do quique, fora da cozinha. Gesto curto: bloqueio quando a bola vem rápida, soco curto quando ela vem lenta e alta.',
    objective: 'Ao final, o atleta volea com gesto curto e a raquete na frente, escolhendo entre bloquear e atacar pela altura da bola.',
    skills: ['net.voleio', 'net.contra_ataque', 'rules.cozinha'],
    level_min: 2.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique em posição de prontidão, atrás da linha da cozinha.',
      'Encontre a bola na frente do corpo, com a raquete firme.',
      'Bola rápida: bloqueie, quase sem mexer a raquete.',
      'Bola lenta e alta: faça um soco curto para baixo, nos pés do adversário.',
      'Depois do voleio, nada de ir para a cozinha nem pisar na linha, nem pelo embalo.',
    ],
    cues: ['Raquete na frente, gesto curto', 'Rápida: bloqueie. Alta: ataque', 'Pés atrás da linha'],
    positioning: [
      { type: 'certo', text: 'Voleio com os dois pés atrás da linha da cozinha, terminando equilibrado fora dela.' },
      { type: 'errado', text: 'Volear e cair na cozinha ou na linha pelo embalo: é falta, mesmo depois de a bola morrer.' },
    ],
    common_errors: [
      { error: 'Balanço grande, como no tênis.', fix: 'No pickleball a rede é perto: gesto curto, a raquete anda um palmo.' },
      { error: 'Volear bola que ia para fora.', fix: 'Bola alta e funda que vai passar da linha de fundo: deixe ir.' },
    ],
    when_to_use: 'Em toda bola que chega na altura da rede ou acima quando você está na linha da cozinha.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente do peito, base aberta.',
        execucao: 'Contato na frente, gesto curto de bloqueio ou de soco.',
        finalizacao: 'Equilíbrio fora da cozinha e raquete de volta à frente.',
      },
      abilities: ['tempo_reacao', 'precisao', 'equilibrio'],
    },
    diagrams: [
      diagrama('Certo: atrás da linha', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 69, 'a'),
        trajeto(40, 34, 58, 64),
        trajeto(60, 66, 38, 30),
      ], 'certo'),
      diagrama('Errado: embalo na cozinha', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 62, 'a'),
        trajeto(40, 34, 58, 60),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'saque',
    version: 1,
    kind: 'fundamento',
    title: 'Saque por baixo: voleio ou com quique',
    summary: 'O saque é feito por baixo, atrás da linha de fundo, para a área de saque na diagonal. Pode ser de voleio ou deixando a bola quicar antes (drop serve).',
    objective: 'Ao final, o atleta saca dentro da regra, com uma rotina fixa, colocando a bola funda na área de saque da diagonal.',
    skills: ['serve.consistencia', 'serve.saque_profundo', 'rules.saque'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique atrás da linha de fundo, entre o prolongamento da linha central e o da lateral, sem pisar na linha.',
      'Saque de voleio: solte a bola e bata por baixo, num movimento de baixo para cima, com o contato abaixo da cintura e a cabeça da raquete abaixo do punho.',
      'Saque com quique: apenas solte a bola (sem jogar para cima nem empurrar), deixe quicar e bata.',
      'Mire fundo, na área de saque da diagonal: a bola não pode cair na cozinha nem na linha dela.',
      'Use a mesma rotina em todo saque: olhe o alvo, respire e saque.',
    ],
    cues: ['Bola sobe e cai funda', 'Mesma rotina em todo saque', 'Mire o fundo da diagonal'],
    positioning: [
      { type: 'certo', text: 'Pés atrás da linha de fundo, sem tocar nela, e entre os prolongamentos da linha central e da lateral.' },
      { type: 'errado', text: 'Pisar na linha de fundo ou sacar com o contato acima da cintura: é falta.' },
    ],
    common_errors: [
      { error: 'Saque curto, que cai perto da cozinha.', fix: 'Termine a raquete subindo na direção do alvo, mirando o terço final da área de saque.' },
      { error: 'Tentar sacar forte e errar muito.', fix: 'Saque é para pôr a bola em jogo, fundo: só ganha força quem já é consistente.' },
      { error: 'No saque com quique, jogar a bola para cima ou para baixo.', fix: 'Apenas solte a bola da mão, sem impulso.' },
    ],
    when_to_use: 'No início de todo ponto em que a sua dupla tem o saque.',
    motor: {
      phases: {
        preparacao: 'De lado, atrás da linha, bola na frente e raquete atrás e baixa.',
        execucao: 'Gesto de baixo para cima, contato abaixo da cintura.',
        finalizacao: 'Raquete alta apontando o alvo; continue atrás da linha.',
      },
      abilities: ['precisao', 'ritmo'],
    },
    diagrams: [
      diagrama('Certo: diagonal e fundo', 'inteira', [
        jogador(75, 97, 'a', 'Sac'),
        zona(1, 1, 49, 15, 'Fundo'),
        trajeto(75, 95, 30, 8),
      ], 'certo'),
      diagrama('Errado: na cozinha', 'inteira', [
        jogador(75, 97, 'a', 'Sac'),
        zona(1, 34, 49, 49, 'Falta'),
        trajeto(75, 95, 30, 40),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'devolucao-de-saque',
    version: 1,
    kind: 'fundamento',
    title: 'Devolução de saque',
    summary: 'A devolução deixa a bola quicar e volta alta e funda, para manter o sacador no fundo e dar tempo de chegar à cozinha.',
    objective: 'Ao final, o atleta devolve alto e fundo e já anda para a cozinha enquanto a bola viaja.',
    skills: ['serve.devolucao_profunda', 'groundstrokes.drive'],
    level_min: 2.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Espere um passo atrás da linha de fundo, com a raquete na frente.',
      'Deixe a bola quicar: na devolução o quique é obrigatório.',
      'Ande para a frente na bola e devolva alto, com gesto longo e lento.',
      'Mire o terço final da quadra do sacador, de preferência no meio ou no backhand dele.',
      'Siga andando até a linha da cozinha e pare quando o sacador bater.',
    ],
    cues: ['Alta e funda', 'Devolveu? Ande para a cozinha', 'Pare quando ele bater'],
    positioning: [
      { type: 'certo', text: 'Esperar um passo atrás da linha de fundo e bater andando para a frente.' },
      { type: 'errado', text: 'Esperar em cima da linha de fundo: o saque fundo obriga a recuar e a devolução sai curta.' },
    ],
    common_errors: [
      { error: 'Devolução curta, no meio da quadra.', fix: 'Mais altura: a bola alta cai mais funda e compra tempo.' },
      { error: 'Volear a devolução por pressa.', fix: 'O saque tem de quicar antes de você bater: espere o quique.' },
    ],
    when_to_use: 'Toda vez que você recebe o saque.',
    motor: {
      phases: {
        preparacao: 'Um passo atrás da linha, raquete na frente.',
        execucao: 'Passo à frente e gesto longo de baixo para cima.',
        finalizacao: 'Raquete alta e caminhada até a cozinha.',
      },
      abilities: ['precisao', 'leitura'],
    },
    diagrams: [
      diagrama('Certo: funda e subindo', 'inteira', [
        jogador(25, 3, 'b', 'Sac'),
        jogador(75, 98, 'a', 'Dev'),
        zona(1, 1, 99, 15, 'Fundo'),
        trajeto(75, 96, 40, 9),
        trajeto(80, 95, 74, 71),
      ], 'certo'),
      diagrama('Errado: curta', 'inteira', [
        jogador(25, 3, 'b', 'Sac'),
        jogador(75, 98, 'a', 'Dev'),
        trajeto(75, 96, 40, 32),
        zona(20, 20, 60, 40, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'reset',
    version: 1,
    kind: 'fundamento',
    title: 'Reset: amortecer a bola rápida',
    summary: 'Quando o adversário ataca, o reset tira a velocidade da bola e a devolve curta, na cozinha, trocando o ataque por um rally de dink.',
    objective: 'Ao final, o atleta amortece bolas rápidas com a raquete quase parada, devolvendo-as baixas para a cozinha.',
    skills: ['net.reset', 'groundstrokes.transicao'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Pare em split step quando o adversário bater.',
      'Abaixe-se com as pernas para a raquete chegar baixa, com a face um pouco aberta.',
      'Encontre a bola na frente e deixe a raquete ceder um pouco, como um travesseiro.',
      'A bola perde velocidade e cai na cozinha do adversário.',
      'Se a bola caiu curta, avance; se subiu, fique e defenda.',
    ],
    cues: ['Raquete parada, face para o céu', 'Amorteça como um ovo', 'Bola morre na cozinha'],
    positioning: [
      { type: 'certo', text: 'Parado e baixo quando a bola chega, com a raquete na frente.' },
      { type: 'errado', text: 'Ainda correndo e com as pernas esticadas: a bola sobe e o adversário finaliza.' },
    ],
    common_errors: [
      { error: 'Tentar devolver com força.', fix: 'O reset usa a velocidade da bola: a sua raquete só a amortece.' },
      { error: 'Raquete apontando para o chão.', fix: 'Abaixe o corpo, não a cabeça da raquete: a face fica aberta para cima.' },
    ],
    when_to_use: 'Na zona de transição e na rede, quando o adversário ataca nos seus pés e você não tem como atacar de volta.',
    safety: 'Bolas rápidas: óculos de proteção são recomendados.',
    motor: {
      phases: {
        preparacao: 'Split step no contato do adversário, corpo baixo.',
        execucao: 'Raquete quase parada, face aberta, cedendo à bola.',
        finalizacao: 'Raquete à frente e decisão: avançar ou defender.',
      },
      abilities: ['tempo_reacao', 'precisao', 'equilibrio'],
    },
    diagrams: [
      diagrama('Certo: da transição para a cozinha', 'inteira', [
        jogador(50, 80, 'a'),
        jogador(40, 32, 'b'),
        trajeto(40, 34, 48, 78),
        trajeto(50, 78, 46, 42),
        zona(10, 35, 90, 49, 'Alvo'),
      ], 'certo'),
      diagrama('Errado: a bola sobe', 'inteira', [
        jogador(50, 80, 'a'),
        jogador(40, 32, 'b'),
        trajeto(40, 34, 48, 78),
        trajeto(50, 78, 44, 26),
        zona(25, 20, 60, 33, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'smash',
    version: 1,
    kind: 'fundamento',
    title: 'Smash: finalizar o lob curto',
    summary: 'O golpe por cima da cabeça para a bola alta e curta. De lado, atrás da bola, com a mão livre apontando, e mirando os pés ou o meio.',
    objective: 'Ao final, o atleta posiciona-se de lado, atrás da bola, e finaliza para baixo com mais precisão do que força.',
    skills: ['net.smash'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Viu o lob curto: vire de lado e aponte a bola com a mão livre.',
      'Dê passos laterais até ficar um pouco atrás da bola.',
      'Leve a raquete para trás e para cima.',
      'Bata com a bola na frente e no alto, de cima para baixo, no meio ou nos pés do adversário.',
      'Volte para a linha da cozinha.',
    ],
    cues: ['Aponte a bola com a mão livre', 'Bola na frente e no alto', 'Alvo antes da força'],
    positioning: [
      { type: 'certo', text: 'De lado, atrás da bola, que cai na sua frente: o smash desce na quadra.' },
      { type: 'errado', text: 'Embaixo da bola, de frente para a rede: o smash vai na rede ou para fora.' },
    ],
    common_errors: [
      { error: 'Recuar de costas para alcançar a bola.', fix: 'Vire de lado e ande de lado: recuar de costas é como se cai.' },
      { error: 'Bater com toda a força e errar.', fix: 'Ângulo e alvo ganham o ponto: mire os pés ou o meio.' },
    ],
    when_to_use: 'No lob curto, que você alcança sem deixar quicar ou depois de um quique alto perto da rede.',
    safety: 'Para ir atrás do lob, vire de lado; nunca recue de costas.',
    motor: {
      phases: {
        preparacao: 'De lado, mão livre apontando, raquete atrás e alta.',
        execucao: 'Contato na frente e no alto, de cima para baixo.',
        finalizacao: 'Raquete termina do outro lado do corpo; volta à cozinha.',
      },
      abilities: ['coordenacao', 'potencia', 'leitura'],
    },
    diagrams: [
      diagrama('Alvo do smash', 'inteira', [
        jogador(50, 74, 'a'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        zona(38, 24, 62, 40, 'Meio'),
        trajeto(50, 72, 50, 33),
      ]),
    ],
    media: [],
  },
];
