/** Biblioteca inicial — FUNDAMENTOS (como executar cada golpe e posição). */

import { diagrama, jogador, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const FUNDAMENTOS = [
  {
    slug: 'empunhadura-continental',
    version: 2,
    featured: true,
    kind: 'fundamento',
    title: 'Empunhadura continental',
    summary: 'A forma de segurar a raquete que serve para quase todos os golpes, de forehand e de backhand, sem trocar a mão de posição. A base de quem joga na rede.',
    objective: 'Ao final, o atleta segura a raquete na continental, com pressão leve, e joga dink e voleio dos dois lados sem trocar a empunhadura.',
    skills: ['net.voleio', 'kitchen.dink_paralelo', 'groundstrokes.drive'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 5,
    intensity: 1,
    place: ['quadra', 'casa'],
    equipment: ['raquete'],
    practice_mode: 'bloco',
    steps: [
      'Segure a raquete pela cabeça com a mão livre, a face em pé (perpendicular ao chão) e o cabo apontando para você.',
      'Pegue o cabo com a outra mão como num aperto de mão, ou como quem segura um martelo para pregar um prego.',
      'Confira: o "V" entre o polegar e o indicador fica sobre a borda de cima do cabo, a parte estreita alinhada com a borda da raquete.',
      'Feche os dedos em volta do cabo, com o indicador um pouco separado dos outros, como num gatilho.',
      'Aperte pouco: numa escala de 1 a 10, entre 3 e 4.',
      'Teste: faça um voleio de forehand e um de backhand sem mexer a mão no cabo.',
    ],
    cues: ['Segure como um martelo', 'Aperto leve, como um passarinho', 'Mesma pegada nos dois lados'],
    positioning: [
      { type: 'certo', text: 'Raquete de lado, como um martelo, que serve para o forehand e o backhand sem trocar.' },
      { type: 'errado', text: 'Raquete deitada, como uma frigideira: o forehand fica fácil, mas o backhand e o voleio rápido chegam atrasados.' },
      { type: 'certo', text: 'Aperto leve, com os dedos soltos em volta do cabo.' },
      { type: 'errado', text: 'Aperto forte, com os dedos brancos: a bola rebate dura no dink e no reset, e o voleio chega atrasado.' },
    ],
    common_errors: [
      { error: 'Apertar demais a raquete.', fix: 'Aperto leve dá toque no dink e reação no voleio; aperte só um pouco mais no golpe forte.' },
      { error: 'Trocar de empunhadura em cada bola rápida na rede.', fix: 'Na rede, fique sempre na continental: não há tempo de trocar.' },
      { error: 'A mão escorrega para a pegada de frigideira ao longo do jogo, sem perceber.', fix: 'Entre os pontos, olhe o "V": ele volta para a borda de cima do cabo.' },
    ],
    when_to_use: 'Na rede (dink, voleio, reset), no saque e como base para o resto. Alguns jogadores usam outra empunhadura no drive, mas a continental é o ponto de partida.',
    motor: {
      phases: {
        preparacao: 'Cabo na mão como um martelo, aperto leve.',
        execucao: 'A mesma pegada no forehand e no backhand.',
        finalizacao: 'A mão volta a relaxar entre as bolas.',
      },
      abilities: ['coordenacao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'O "V" entre o polegar e o indicador fica sobre a borda de cima do cabo; com a mão nessa posição, a face fica em pé.' },
        { part: 'punho', text: 'Firme, mas sem tensão, nem dobrado para trás nem para a frente; ele não gira a pegada entre o forehand e o backhand.' },
        { part: 'braco', text: 'Relaxado, com o cotovelo à frente do corpo; é o antebraço que gira para virar a face de um lado para o outro.' },
        { part: 'raquete', text: 'Com a mão parada, a face fica perpendicular ao chão; para o forehand e o backhand a raquete só vira com o antebraço, sem a mão rodar no cabo.' },
        { part: 'olhar', text: 'Entre os pontos, um olhar rápido para a mão confere o "V"; durante a troca, os olhos ficam na bola, não na pegada.' },
      ],
      self_check: [
        'Você faz um voleio de forehand e um de backhand seguidos sem sentir a mão girar no cabo.',
        'No voleio de backhand a bola sai reta para a frente, sem subir torta para o alto.',
        'Depois de alguns minutos de troca, a mão não está cansada nem com os dedos marcados.',
        'Ao olhar a mão no fim do ponto, o "V" continua sobre a borda de cima do cabo.',
      ],
    },
    media: [],
  },
  {
    slug: 'posicao-de-prontidao',
    version: 2,
    kind: 'fundamento',
    title: 'Posição de prontidão na rede',
    summary: 'A base de espera na linha da cozinha: pernas afastadas e dobradas, peso na frente e raquete na frente do peito. Dela saem todos os golpes rápidos.',
    objective: 'Ao final, o atleta volta à posição de prontidão entre todas as bolas e reage aos dois lados sem atraso.',
    skills: ['net.contra_ataque', 'physical.agilidade', 'doubles.posicionamento'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 5,
    intensity: 2,
    place: QUADRA,
    equipment: ['raquete'],
    practice_mode: 'bloco',
    steps: [
      'Pés afastados um pouco mais que a largura dos ombros, paralelos à linha, logo atrás da linha da cozinha.',
      'Pernas dobradas e peso na parte da frente dos pés, com os calcanhares leves.',
      'Raquete na frente do peito, a um palmo do corpo, cabeça da raquete para cima, um pouco para o lado do backhand.',
      'Cotovelos soltos e à frente do corpo, sem colar na barriga.',
      'Quando o adversário for bater, dê um pulinho curto (split step) e caia nessa base, pronto para os dois lados.',
      'Depois de cada golpe, volte a essa posição antes da próxima bola.',
    ],
    cues: ['Raquete na frente do peito', 'Peso na ponta dos pés', 'Bateu? Volte à base'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente do peito, entre o forehand e o backhand: chega aos dois lados no mesmo tempo.' },
      { type: 'errado', text: 'Raquete caída ao lado da perna: a bola rápida no peito passa antes de a raquete subir.' },
      { type: 'certo', text: 'Logo atrás da linha da cozinha, com a ponta dos pés quase nela.' },
      { type: 'errado', text: 'Um ou dois passos atrás da linha: a bola baixa cai nos seus pés e o adversário ganha ângulo.' },
    ],
    common_errors: [
      { error: 'Ficar em pé, com as pernas esticadas.', fix: 'Pernas dobradas, como quem vai sentar: o corpo reage mais rápido.' },
      { error: 'Deixar a raquete cair depois de cada golpe.', fix: 'Termine o golpe e traga a raquete de volta para a frente do peito.' },
      { error: 'Raquete do lado do forehand o tempo todo.', fix: 'Deixe-a no meio, um pouco para o backhand: a bola no corpo e no backhand chega sem atraso.' },
      { error: 'Estar andando no momento em que o adversário bate.', fix: 'Pare com o split step no contato dele; depois vá para a bola.' },
    ],
    when_to_use: 'Em todo momento na linha da cozinha, principalmente nas trocas rápidas.',
    motor: {
      phases: {
        preparacao: 'Base larga, pernas dobradas.',
        execucao: 'Raquete na frente do peito, peso à frente.',
        finalizacao: 'Volta à base depois de cada golpe.',
      },
      abilities: ['tempo_reacao', 'equilibrio'],
    },
    technique: {
      checkpoints: [
        { part: 'pes', text: 'Afastados um pouco mais que os ombros, paralelos à linha da cozinha, com o peso na parte da frente e os calcanhares leves.' },
        { part: 'pernas', text: 'Dobradas, como quem vai sentar numa cadeira alta, prontas para empurrar o corpo para qualquer lado.' },
        { part: 'tronco', text: 'De frente para a rede e inclinado um pouco para a frente, com os ombros relaxados.' },
        { part: 'braco', text: 'Cotovelos soltos e à frente do corpo; a raquete fica a um palmo do peito.' },
        { part: 'raquete', text: 'Na frente do peito, cabeça para cima, um pouco para o lado do backhand.' },
        { part: 'olhar', text: 'Na bola e na raquete do adversário: no contato dele, você faz o split step.' },
      ],
      self_check: [
        'Uma bola rápida no peito é bloqueada sem você precisar levantar a raquete antes.',
        'No voleio de backhand, a raquete chega à frente do corpo sem atraso.',
        'Depois do split step, o primeiro passo sai para o lado da bola, sem um passinho para trás antes.',
        'Ao fim de cada golpe, a raquete volta para a frente do peito sem você pensar.',
      ],
    },
    diagrams: [
      diagrama('Certo: logo atrás da linha', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(30, 68, 'a'),
        jogador(70, 68, 'a'),
        jogador(30, 32, 'b'),
        trajeto(30, 34, 66, 62),
      ], 'certo'),
      diagrama('Errado: longe da linha', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(30, 74, 'a'),
        jogador(70, 74, 'a'),
        jogador(30, 32, 'b'),
        trajeto(30, 34, 68, 71),
        zona(58, 68, 82, 75, 'Pés'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'dink',
    version: 2,
    kind: 'fundamento',
    title: 'Dink: a bola curta e baixa na cozinha',
    summary: 'Golpe suave, da linha da cozinha, que cai na cozinha do adversário. Bola baixa não pode ser atacada: o dink é o golpe da paciência.',
    objective: 'Ao final, o atleta executa o dink com gesto curto, a bola fazendo o ponto mais alto do seu lado e caindo na cozinha adversária.',
    skills: ['kitchen.dink_cruzado', 'kitchen.dink_paralelo', 'kitchen.paciencia'],
    level_min: 2.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique na linha da cozinha em posição de prontidão, com a raquete baixa e na frente.',
      'Deixe a bola chegar à sua frente; se ela quicar curta, pode entrar na cozinha para buscá-la.',
      'Dobre as pernas para ficar baixo e encontre a bola na frente do corpo, depois do quique.',
      'Com a face um pouco aberta e o punho firme, faça um gesto curto de baixo para cima, como um pêndulo que sai do ombro.',
      'A bola passa um palmo acima da fita, com o ponto mais alto do seu lado da rede, e cai na cozinha do adversário.',
      'Volte para trás da linha da cozinha e para a base.',
    ],
    cues: ['Raquete como uma pá', 'Pico antes da rede', 'Bola morre na cozinha'],
    positioning: [
      { type: 'certo', text: 'Dink que cai na cozinha, perto da linha: o adversário precisa bater de baixo para cima.' },
      { type: 'errado', text: 'Dink que cai fora da cozinha ou sobe alto: o adversário bate de cima para baixo e ataca.' },
      { type: 'certo', text: 'Corpo baixo, pernas dobradas e contato na frente: os olhos ficam perto da altura da bola.' },
      { type: 'errado', text: 'Pernas esticadas e contato ao lado ou atrás do corpo: a bola sai alta ou vai na rede.' },
    ],
    common_errors: [
      { error: 'Bater com o pulso, dando um tapa na bola.', fix: 'Punho firme: o gesto vem do ombro, como um pêndulo, e as pernas dobradas acompanham a subida.' },
      { error: 'Voltar à rede pisando na cozinha para volear.', fix: 'Depois de entrar na cozinha, volte com os dois pés para fora antes de volear.' },
      { error: 'Dink sempre no mesmo lugar.', fix: 'Varie entre cruzado, paralelo e o meio, sempre baixo.' },
      { error: 'Dink que vai na rede.', fix: 'Abra um pouco mais a face e mire um palmo acima da fita, com o pico do seu lado.' },
    ],
    when_to_use: 'Quando os dois lados estão na rede e a bola chega baixa, abaixo da altura da fita.',
    motor: {
      phases: {
        preparacao: 'Base larga, raquete na frente e baixa, face um pouco aberta.',
        execucao: 'Gesto curto de baixo para cima, como um pêndulo; as pernas acompanham.',
        finalizacao: 'A raquete para apontando o alvo e volta à frente.',
      },
      abilities: ['precisao', 'equilibrio', 'ritmo'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto leve (3 de 10): a raquete absorve a bola em vez de rebatê-la.' },
        { part: 'olhar', text: 'Na bola até o contato; a cabeça fica parada enquanto a raquete toca a bola.' },
        { part: 'pes', text: 'Base larga, logo atrás da linha da cozinha; um passo curto na direção da bola, sem cruzar as pernas.' },
        { part: 'pernas', text: 'Dobradas para o corpo ficar baixo; esticam um pouco junto com o gesto, sem pular.' },
        { part: 'braco', text: 'Balança a partir do ombro, como um pêndulo; o cotovelo quase não dobra.' },
        { part: 'punho', text: 'Firme e parado: não dá tapa nem gira a raquete no contato.' },
        { part: 'raquete', text: 'Começa baixa, abaixo da bola, com a face um pouco aberta; termina apontando o alvo, na altura do peito ou abaixo.' },
      ],
      self_check: [
        'A bola faz o ponto mais alto do seu lado e passa a rede já descendo ou quase.',
        'Ela quica dentro da cozinha do adversário, e ele precisa bater de baixo para cima.',
        'O parceiro de treino não consegue atacar: a bola chega a ele abaixo da altura da fita.',
        'Depois do golpe, a raquete parou apontando o alvo, sem passar da altura do peito.',
      ],
    },
    diagrams: [
      diagrama('Certo: cai na cozinha', 'cozinha', [
        zona(0, 35, 100, 49, 'Alvo'),
        jogador(70, 68, 'a'),
        jogador(30, 32, 'b'),
        trajeto(70, 66, 32, 40),
      ], 'certo'),
      diagrama('Errado: longo e atacável', 'cozinha', [
        jogador(70, 68, 'a'),
        jogador(30, 32, 'b'),
        trajeto(70, 66, 34, 28),
        zona(15, 25, 50, 33, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'drop-da-terceira-bola',
    version: 3,
    kind: 'fundamento',
    title: 'Drop da terceira bola',
    summary: 'Do fundo da quadra, uma bola em arco que cai na cozinha adversária. Dá à dupla que sacou o tempo de chegar à rede.',
    objective: 'Ao final, o atleta executa o drop com arco que tem o pico do seu lado e a bola descendo para a cozinha adversária.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.transicao'],
    level_min: 2.5,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Prepare a raquete baixa e cedo, assim que a devolução sai.',
      'Deixe a devolução quicar (pela regra dos dois quiques, a dupla que sacou só bate depois do quique) e encontre a bola na frente do corpo.',
      'Com a face um pouco aberta e o punho firme, faça um gesto longo e lento de baixo para cima, como um pêndulo, e deixe as pernas subirem junto.',
      'Levante a bola num arco: o pico fica do seu lado, e ela passa a rede já descendo.',
      'A bola cai na cozinha do adversário.',
      'Se o drop foi bom, avance dois passos e pare (split step) quando o adversário bater.',
    ],
    cues: ['Arco de arco-íris', 'Pico do seu lado', 'Drop bom? Avance e pare'],
    positioning: [
      { type: 'certo', text: 'Drop que cai na cozinha: os adversários só conseguem devolver de baixo para cima e você avança.' },
      { type: 'errado', text: 'Drop que cai no meio da quadra: os adversários avançam e atacam a sua chegada.' },
      { type: 'certo', text: 'Contato na frente do corpo, com o peso passando do pé de trás para o da frente.' },
      { type: 'errado', text: 'Bater recuando, com o peso para trás: a bola sai alta e longa, pronta para o ataque.' },
    ],
    common_errors: [
      { error: 'Drop em linha reta, rente à fita.', fix: 'Levante mais: o arco alto desce mais curto e mais devagar.' },
      { error: 'Correr para a rede logo depois de qualquer drop.', fix: 'Só avance depois de um drop baixo; alto, fique e defenda.' },
      { error: 'Bater com o pulso, dando um tapa na bola.', fix: 'Punho firme: o gesto vem do ombro e das pernas, e a raquete termina apontando a cozinha.' },
      { error: 'Olhar o adversário em vez da bola na hora de bater.', fix: 'Olhos na bola até o contato; o alvo você escolheu antes.' },
    ],
    when_to_use: 'Na terceira bola, quando os adversários já estão na rede e a devolução veio funda ou baixa.',
    motor: {
      phases: {
        preparacao: 'Raquete baixa e cedo, pernas dobradas.',
        execucao: 'Contato na frente, gesto de baixo para cima, as pernas sobem.',
        finalizacao: 'Raquete alta apontando a cozinha e passos para a frente.',
      },
      abilities: ['precisao', 'coordenacao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto leve: aperto forte faz a bola sair rápida e longa.' },
        { part: 'olhar', text: 'Na bola até o contato; o alvo, a cozinha adversária, foi escolhido antes de ela quicar.' },
        { part: 'pes', text: 'Chegam cedo, para a bola ficar na frente do corpo; o pé da frente aponta para onde a bola vai.' },
        { part: 'pernas', text: 'Dobradas na preparação; esticam devagar junto com o gesto, ajudando a levantar a bola.' },
        { part: 'braco', text: 'Balança a partir do ombro, longo e lento, como um pêndulo; o cotovelo quase não dobra.' },
        { part: 'punho', text: 'Firme do começo ao fim: a face não muda de ângulo durante o gesto.' },
        { part: 'raquete', text: 'Começa baixa, abaixo da bola, com a face um pouco aberta; termina alta, apontando a cozinha.' },
      ],
      self_check: [
        'A bola faz o ponto mais alto antes de chegar à rede e passa por ela descendo.',
        'Ela quica na cozinha adversária ou perto da linha, e o adversário bate de baixo para cima.',
        'Você teve tempo de dar dois passos à frente antes de o adversário tocar a bola.',
        'Se a bola chega ao adversário acima da fita, o arco foi baixo ou o gesto foi rápido demais.',
      ],
    },
    diagrams: [
      diagrama('Certo: na cozinha', 'inteira', [
        zona(5, 35, 95, 49, 'Alvo'),
        jogador(50, 96, 'a'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        trajeto(50, 94, 46, 42),
      ], 'certo'),
      diagrama('Errado: no meio da quadra', 'inteira', [
        jogador(50, 96, 'a'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        trajeto(50, 94, 48, 22),
        zona(10, 12, 90, 30, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'drive',
    version: 2,
    kind: 'fundamento',
    title: 'Drive: o golpe de fundo com força',
    summary: 'Golpe firme de forehand (lado direito, para o destro), do fundo, com a bola passando baixa sobre a rede. Serve na devolução, na terceira bola contra quem demora a subir e para forçar a bola alta.',
    objective: 'Ao final, o atleta executa o drive de forehand com preparação cedo, contato na frente e a bola passando baixa sobre a rede.',
    skills: ['groundstrokes.drive', 'groundstrokes.terceira_bola_drive'],
    level_min: 2.5,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Viu que a bola vem para o seu forehand: gire ombros e quadril de lado para a rede e leve a raquete para trás, cedo, na altura da cintura.',
      'Dê um passo com o pé esquerdo (para o destro) na direção da bola, com o peso ainda no pé de trás.',
      'Deixe a cabeça da raquete descer um pouco abaixo da altura da bola.',
      'Empurre o chão com a perna de trás e gire quadril e ombros para a frente: o braço vem junto, sem puxar sozinho.',
      'Encontre a bola na frente do pé da frente, entre o joelho e a cintura, com a face em pé ou um pouco fechada.',
      'O gesto vai de baixo para cima e para a frente, dando efeito por cima (topspin) e passando a bola baixa sobre a rede.',
      'Termine com a raquete alta, por cima do ombro esquerdo, e volte à base.',
    ],
    cues: ['Prepare cedo, bata na frente', 'Bola rente à fita', 'Termine alto, do outro lado'],
    positioning: [
      { type: 'certo', text: 'De lado para a rede na preparação e com o peso indo para a bola no contato.' },
      { type: 'errado', text: 'De frente para a rede e com o peso para trás: a bola sobe e vira presente para o voleio.' },
      { type: 'certo', text: 'Contato na frente do pé da frente, a um braço de distância do corpo.' },
      { type: 'errado', text: 'Bola colada no corpo ou atrás dele: o braço fica preso, a face abre e a bola sobe ou sai para o lado.' },
    ],
    common_errors: [
      { error: 'Drive alto, que o adversário volea para baixo.', fix: 'Feche um pouco a face e termine para a frente: a bola passa baixa.' },
      { error: 'Drive em toda bola, até na baixa.', fix: 'Bola abaixo da altura da rede pede drop; o drive é para a bola alta e funda.' },
      { error: 'Bater só com o braço, sem girar o corpo.', fix: 'Gire quadril e ombros para a frente: a força vem das pernas e do giro, o braço acompanha.' },
      { error: 'Preparar tarde, com a bola já em cima.', fix: 'Gire e leve a raquete para trás assim que a bola sai da raquete do adversário.' },
    ],
    when_to_use: 'Na devolução, na terceira bola com a devolução alta ou curta e contra quem demora a chegar à rede.',
    safety: 'Mire o meio ou os pés dos adversários, nunca o rosto.',
    motor: {
      phases: {
        preparacao: 'De lado, raquete atrás cedo, peso no pé de trás.',
        execucao: 'Passo à frente e contato na frente do corpo.',
        finalizacao: 'Raquete alta do outro lado e volta à base.',
      },
      abilities: ['potencia', 'coordenacao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental ou a de aperto de mão (eastern de forehand), um pouco mais por trás do cabo; aperto firme, sem estrangular.' },
        { part: 'olhar', text: 'Na bola, do quique até o contato; a cabeça fica parada no momento de bater.' },
        { part: 'pes', text: 'O pé esquerdo (para o destro) dá o passo na direção da bola; o peso passa do pé de trás para o da frente.' },
        { part: 'pernas', text: 'Dobradas na preparação; a de trás empurra o chão e começa o golpe.' },
        { part: 'tronco', text: 'Gira de lado na preparação e volta de frente para a rede no golpe: é a maior fonte de força.' },
        { part: 'braco', text: 'Solto, a um braço do corpo no contato; acompanha o giro, sem puxar sozinho.' },
        { part: 'punho', text: 'Firme no contato: a face não abre nem fecha de repente.' },
        { part: 'raquete', text: 'Sai abaixo da bola, encontra a bola com a face em pé ou um pouco fechada e termina alta, por cima do ombro esquerdo.' },
      ],
      self_check: [
        'A bola passa a rede baixa, perto da fita, e não sobe depois.',
        'Ela cai funda, perto da linha de fundo, ou nos pés de quem está na rede.',
        'No fim do golpe, o peito está de frente para a rede e o peso no pé da frente.',
        'Se o adversário volea a bola para baixo com facilidade, a face abriu ou o contato foi atrasado.',
      ],
    },
    diagrams: [
      diagrama('Alvo do drive', 'inteira', [
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        jogador(70, 96, 'a'),
        zona(38, 26, 62, 40, 'Meio'),
        trajeto(70, 94, 50, 34),
      ]),
    ],
    media: [],
  },
  {
    slug: 'voleio',
    version: 3,
    kind: 'fundamento',
    title: 'Voleio na rede',
    summary: 'Bater a bola antes do quique, fora da cozinha. Gesto curto: bloqueio quando a bola vem rápida, soco curto quando ela vem lenta e alta.',
    objective: 'Ao final, o atleta volea com gesto curto e a raquete na frente, escolhendo entre bloquear e atacar pela altura da bola.',
    skills: ['net.voleio', 'net.contra_ataque', 'rules.cozinha'],
    level_min: 2.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique em posição de prontidão, atrás da linha da cozinha, com a raquete na frente do peito.',
      'Use a continental: ela serve para o voleio de forehand e o de backhand sem trocar a pegada.',
      'Encontre a bola na frente do corpo, com o punho firme e parado.',
      'Bola rápida: bloqueie, quase sem mexer a raquete, só apresentando a face.',
      'Bola lenta e alta: faça um soco curto para a frente e para baixo, nos pés do adversário.',
      'Depois do voleio, nada de ir para a cozinha nem pisar na linha, nem pelo embalo.',
    ],
    cues: ['Raquete na frente, gesto curto', 'Rápida: bloqueie. Alta: ataque', 'Pés atrás da linha'],
    positioning: [
      { type: 'certo', text: 'Voleio com os dois pés atrás da linha da cozinha, terminando equilibrado fora dela.' },
      { type: 'errado', text: 'Volear e cair na cozinha ou na linha pelo embalo: é falta, mesmo depois de a bola morrer.' },
      { type: 'certo', text: 'Contato na frente do corpo, com a raquete à frente dos pés.' },
      { type: 'errado', text: 'Deixar a bola chegar ao lado ou atrás do corpo: o voleio sai atrasado, alto ou para o lado.' },
    ],
    common_errors: [
      { error: 'Balanço grande, como no tênis.', fix: 'No pickleball a rede é perto: gesto curto, a raquete anda um palmo.' },
      { error: 'Volear bola que ia para fora.', fix: 'Bola alta e funda que vai passar da linha de fundo: deixe ir.' },
      { error: 'Punho solto, que dobra no contato.', fix: 'Punho firme: a raquete e o antebraço andam juntos, como uma peça só.' },
    ],
    when_to_use: 'Em toda bola que chega na altura da rede ou acima quando você está na linha da cozinha.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente do peito, base aberta.',
        execucao: 'Contato na frente, gesto curto de bloqueio ou de soco.',
        finalizacao: 'Equilíbrio fora da cozinha e raquete de volta à frente.',
      },
      abilities: ['tempo_reacao', 'precisao', 'equilibrio'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto leve na espera; no soco, um pouco mais firme no contato; no bloqueio, leve, para amortecer.' },
        { part: 'olhar', text: 'Na bola, da raquete do adversário até a sua; a cabeça fica parada no contato.' },
        { part: 'pes', text: 'Atrás da linha da cozinha; um passo curto para a bola, sem passar para dentro nem pisar na linha.' },
        { part: 'pernas', text: 'Dobradas; para a bola baixa, desça com as pernas, não com a cabeça da raquete.' },
        { part: 'braco', text: 'Cotovelo à frente do corpo; o gesto é curto e a raquete anda no máximo um palmo.' },
        { part: 'punho', text: 'Firme e parado: não quebra no contato.' },
        { part: 'raquete', text: 'Na frente do corpo; no bloqueio, a face quase parada; no ataque, para a frente e para baixo, terminando apontando o alvo.' },
      ],
      self_check: [
        'A bola sai na direção em que a face estava apontada, sem desvio.',
        'Depois do voleio você continua equilibrado, com os dois pés fora da cozinha.',
        'A raquete terminou na frente do corpo, pronta para a próxima, e não atrás nem lá no alto.',
        'O bloqueio volta baixo e lento; o ataque desce nos pés do adversário.',
      ],
    },
    diagrams: [
      diagrama('Certo: atrás da linha', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 69, 'a'),
        trajeto(40, 34, 58, 64),
        trajeto(60, 66, 38, 30),
      ], 'certo'),
      diagrama('Errado: embalo na cozinha', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 62, 'a'),
        trajeto(40, 34, 58, 60),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'saque',
    version: 3,
    kind: 'fundamento',
    title: 'Saque por baixo: voleio ou com quique',
    summary: 'O saque é feito por baixo, atrás da linha de fundo, para a área de saque na diagonal, passando da cozinha. Pode ser de voleio ou deixando a bola quicar antes (drop serve).',
    objective: 'Ao final, o atleta saca dentro da regra, com uma rotina fixa, colocando a bola funda na área de saque da diagonal.',
    skills: ['serve.consistencia', 'serve.saque_profundo', 'rules.saque'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique atrás da linha de fundo, entre o prolongamento da linha central e o da lateral. No contato, pelo menos um pé está no chão atrás da linha, e nenhum pé toca a linha nem a quadra.',
      'Saque de voleio: solte a bola e bata antes de ela quicar, com o braço subindo num arco de baixo para cima.',
      'No saque de voleio, no contato, a bola fica abaixo da cintura (umbigo) e a cabeça da raquete abaixo da parte mais alta do punho.',
      'Saque com quique (drop serve): apenas solte a bola da mão, sem jogar para cima nem para baixo, deixe quicar e bata; nele, a altura do contato e o arco não são exigidos.',
      'Nos dois saques, solte a bola sem girá-la com os dedos: pela regra, o efeito só pode vir da raquete.',
      'Mire fundo, na área de saque da diagonal: bola na cozinha ou na linha dela é falta; nas outras linhas da área, é boa.',
      'Use a mesma rotina em todo saque: confira o placar, olhe o alvo, respire e saque.',
    ],
    cues: ['Bola sobe e cai funda', 'Mesma rotina em todo saque', 'Mire o fundo da diagonal'],
    positioning: [
      { type: 'certo', text: 'Pés atrás da linha de fundo, sem tocar nela, e entre os prolongamentos da linha central e da lateral.' },
      { type: 'errado', text: 'Pisar na linha de fundo ou, no saque de voleio, bater acima da cintura: é falta.' },
      { type: 'certo', text: 'Contato abaixo do umbigo, com a cabeça da raquete abaixo da parte mais alta do punho e o braço subindo em arco.' },
      { type: 'errado', text: 'Raquete batendo de lado, como no tênis, com a cabeça da raquete acima da parte mais alta do punho: o saque de voleio é ilegal.' },
    ],
    common_errors: [
      { error: 'Saque curto, que cai perto da cozinha.', fix: 'Termine a raquete subindo na direção do alvo, mirando o terço final da área de saque.' },
      { error: 'Tentar sacar forte e errar muito.', fix: 'Saque é para pôr a bola em jogo, fundo: só ganha força quem já é consistente.' },
      { error: 'No saque com quique, jogar a bola para cima ou para baixo.', fix: 'Apenas solte a bola da mão, sem impulso.' },
      { error: 'Repetir o saque porque a bola tocou a fita.', fix: 'Desde 2021, o saque que toca a fita e cai na área certa está em jogo; se cair na cozinha ou fora, é falta.' },
      { error: 'Girar a bola com os dedos ao soltá-la, para dar efeito.', fix: 'Solte a bola sem girar; se quiser efeito, ele tem de vir da raquete.' },
    ],
    when_to_use: 'No início de todo ponto em que a sua dupla tem o saque. Não existe segundo saque: errou, a vez passa para o parceiro ou, se ele já sacou, para a outra dupla (no começo do jogo, só um da dupla saca).',
    motor: {
      phases: {
        preparacao: 'Atrás da linha, de lado ou de frente, bola na frente e raquete atrás e baixa.',
        execucao: 'Braço em arco de baixo para cima, contato abaixo da cintura.',
        finalizacao: 'Raquete alta apontando o alvo; continue atrás da linha.',
      },
      abilities: ['precisao', 'ritmo'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental ou a de aperto de mão, com aperto leve para controlar a profundidade.' },
        { part: 'olhar', text: 'No alvo durante a rotina; na hora de bater, na bola até o contato.' },
        { part: 'pes', text: 'Atrás da linha de fundo, entre os prolongamentos da linha central e da lateral; no contato, nenhum toca a linha.' },
        { part: 'pernas', text: 'Levemente dobradas; o peso passa do pé de trás para o da frente junto com o gesto.' },
        { part: 'braco', text: 'Sobe num arco de baixo para cima, como quem joga uma bola de boliche; o contato fica abaixo do umbigo.' },
        { part: 'punho', text: 'No contato do saque de voleio, fica acima da cabeça da raquete, que aponta para baixo; pela regra, a cabeça nunca passa da parte mais alta do punho.' },
        { part: 'raquete', text: 'Começa atrás e baixa, encontra a bola na frente do corpo e termina alta, apontando o alvo.' },
      ],
      self_check: [
        'Num vídeo do celular, no contato a cabeça da raquete aparece abaixo do punho e a bola abaixo do umbigo.',
        'No momento do contato, nenhum dos seus pés está sobre a linha de fundo.',
        'De 10 saques, a maioria cai no terço final da área de saque da diagonal.',
        'A bola sobe ao sair da raquete e desce funda, sem passar rente à fita.',
      ],
    },
    diagrams: [
      diagrama('Certo: diagonal e fundo', 'inteira', [
        jogador(75, 97, 'a', 'Sac'),
        zona(1, 1, 49, 15, 'Fundo'),
        trajeto(75, 95, 30, 8),
      ], 'certo'),
      diagrama('Errado: na cozinha', 'inteira', [
        jogador(75, 97, 'a', 'Sac'),
        zona(1, 34, 49, 49, 'Falta'),
        trajeto(75, 95, 30, 40),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'devolucao-de-saque',
    version: 2,
    kind: 'fundamento',
    title: 'Devolução de saque',
    summary: 'A devolução deixa a bola quicar e volta alta e funda, para manter o sacador no fundo e dar tempo de chegar à cozinha.',
    objective: 'Ao final, o atleta devolve alto e fundo e já anda para a cozinha enquanto a bola viaja.',
    skills: ['serve.devolucao_profunda', 'groundstrokes.drive'],
    level_min: 2.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Espere um passo atrás da linha de fundo, com a raquete na frente.',
      'Deixe a bola quicar: na devolução o quique é obrigatório (regra dos dois quiques).',
      'Ande para a frente na bola e devolva alto, com gesto longo e lento, a bola na frente do corpo.',
      'Mire o terço final da quadra do sacador, de preferência no meio ou no backhand dele.',
      'Siga andando até a linha da cozinha e pare quando o sacador bater.',
    ],
    cues: ['Alta e funda', 'Devolveu? Ande para a cozinha', 'Pare quando ele bater'],
    positioning: [
      { type: 'certo', text: 'Esperar um passo atrás da linha de fundo e bater andando para a frente.' },
      { type: 'errado', text: 'Esperar em cima da linha de fundo: o saque fundo obriga a recuar e a devolução sai curta.' },
      { type: 'certo', text: 'Depois da devolução, chegar à linha da cozinha e parar (split step) quando o sacador bater.' },
      { type: 'errado', text: 'Ficar no fundo ou parar no meio da quadra: a terceira bola cai nos seus pés.' },
    ],
    common_errors: [
      { error: 'Devolução curta, no meio da quadra.', fix: 'Mais altura: a bola alta cai mais funda e compra tempo.' },
      { error: 'Volear a devolução por pressa.', fix: 'O saque tem de quicar antes de você bater: espere o quique.' },
      { error: 'Tentar ganhar o ponto na devolução, forte e no ângulo, e errar fora.', fix: 'Profundidade antes de força: mire com margem dentro das linhas, no fundo.' },
    ],
    when_to_use: 'Toda vez que você recebe o saque.',
    motor: {
      phases: {
        preparacao: 'Um passo atrás da linha, raquete na frente.',
        execucao: 'Passo à frente e gesto longo de baixo para cima.',
        finalizacao: 'Raquete alta e caminhada até a cozinha.',
      },
      abilities: ['precisao', 'leitura'],
    },
    technique: {
      checkpoints: [
        { part: 'olhar', text: 'Na bola desde a raquete do sacador: leia cedo se ela vem para o forehand ou para o backhand.' },
        { part: 'pes', text: 'Um passo atrás da linha de fundo na espera; depois do quique, um passo para a frente, na bola.' },
        { part: 'pernas', text: 'Dobradas na espera; empurram o corpo para a frente no golpe e já começam a caminhada.' },
        { part: 'tronco', text: 'Gira de lado na preparação e volta de frente no contato, sem pressa.' },
        { part: 'braco', text: 'Gesto longo e lento, de baixo para cima; a força vem do passo e do giro, não do braço.' },
        { part: 'raquete', text: 'Contato na frente do corpo, face um pouco aberta, terminando alta e apontando o fundo da quadra do sacador.' },
      ],
      self_check: [
        'A bola cai no terço final da quadra do sacador.',
        'Você chega à linha da cozinha antes de o sacador bater a terceira bola.',
        'A bola viajou alta e lenta, e deu tempo de você subir.',
        'Se o sacador consegue avançar e bater perto da rede, a devolução saiu curta.',
      ],
    },
    diagrams: [
      diagrama('Certo: funda e subindo', 'inteira', [
        jogador(25, 3, 'b', 'Sac'),
        jogador(75, 98, 'a', 'Dev'),
        zona(1, 1, 99, 15, 'Fundo'),
        trajeto(75, 96, 40, 9),
        trajeto(80, 95, 74, 71),
      ], 'certo'),
      diagrama('Errado: curta', 'inteira', [
        jogador(25, 3, 'b', 'Sac'),
        jogador(75, 98, 'a', 'Dev'),
        trajeto(75, 96, 40, 32),
        zona(20, 20, 60, 40, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'reset',
    version: 2,
    kind: 'fundamento',
    title: 'Reset: amortecer a bola rápida',
    summary: 'Quando o adversário ataca, o reset tira a velocidade da bola e a devolve curta, na cozinha, trocando o ataque por um rally de dink.',
    objective: 'Ao final, o atleta amortece bolas rápidas com a raquete quase parada, devolvendo-as baixas para a cozinha.',
    skills: ['net.reset', 'groundstrokes.transicao'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Pare em split step quando o adversário bater.',
      'Abaixe-se com as pernas para a raquete chegar baixa, com a face um pouco aberta.',
      'Encontre a bola na frente, com aperto leve, e deixe a raquete ceder um pouco, como um travesseiro.',
      'A bola perde velocidade, passa baixa sobre a fita e cai na cozinha do adversário.',
      'Se a bola caiu curta, avance; se subiu, fique e defenda.',
    ],
    cues: ['Raquete quase parada, face aberta', 'Amorteça como quem pega um ovo', 'Bola morre na cozinha'],
    positioning: [
      { type: 'certo', text: 'Parado e baixo quando a bola chega, com a raquete na frente.' },
      { type: 'errado', text: 'Ainda correndo e com as pernas esticadas: a bola sobe e o adversário finaliza.' },
      { type: 'certo', text: 'Aperto leve e gesto curto, quase só apresentando a face à bola.' },
      { type: 'errado', text: 'Aperto forte ou gesto grande para a frente: a bola rebate rápida e sobe para o ataque.' },
    ],
    common_errors: [
      { error: 'Tentar devolver com força.', fix: 'O reset usa a velocidade da bola: a sua raquete só a amortece.' },
      { error: 'Raquete apontando para o chão.', fix: 'Abaixe o corpo, não a cabeça da raquete: a face fica aberta para cima.' },
      { error: 'Reset alto, que passa muito acima da fita.', fix: 'Menos face aberta e menos gesto: a bola só precisa passar a fita e cair.' },
    ],
    when_to_use: 'Na zona de transição e na rede, quando o adversário ataca nos seus pés e você não tem como atacar de volta.',
    safety: 'Bolas rápidas: óculos de proteção são recomendados.',
    motor: {
      phases: {
        preparacao: 'Split step no contato do adversário, corpo baixo.',
        execucao: 'Raquete quase parada, face aberta, cedendo à bola.',
        finalizacao: 'Raquete à frente e decisão: avançar ou defender.',
      },
      abilities: ['tempo_reacao', 'precisao', 'equilibrio'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto bem leve (2 a 3 de 10): é o aperto leve que tira a velocidade da bola.' },
        { part: 'olhar', text: 'Na raquete do adversário e depois na bola, até o contato.' },
        { part: 'pes', text: 'Parados no split step quando o adversário bate, em base larga.' },
        { part: 'pernas', text: 'Bem dobradas, para descer até a bola baixa sem abaixar a cabeça da raquete.' },
        { part: 'braco', text: 'Quase parado, à frente do corpo; recua um pouco junto com a bola, como quem amortece.' },
        { part: 'punho', text: 'Firme: segura o ângulo da face sem empurrar a bola.' },
        { part: 'raquete', text: 'Na frente, com a face um pouco aberta; anda pouco e termina apontando a cozinha adversária.' },
      ],
      self_check: [
        'A bola sai da raquete mais devagar do que chegou.',
        'Ela passa baixa sobre a fita e quica na cozinha ou perto dela.',
        'O adversário precisa bater de baixo para cima na resposta.',
        'No contato você estava parado e baixo, e não ainda andando.',
      ],
    },
    diagrams: [
      diagrama('Certo: da transição para a cozinha', 'inteira', [
        jogador(50, 80, 'a'),
        jogador(40, 32, 'b'),
        trajeto(40, 34, 48, 78),
        trajeto(50, 78, 46, 42),
        zona(10, 35, 90, 49, 'Alvo'),
      ], 'certo'),
      diagrama('Errado: a bola sobe', 'inteira', [
        jogador(50, 80, 'a'),
        jogador(40, 32, 'b'),
        trajeto(40, 34, 48, 78),
        trajeto(50, 78, 44, 26),
        zona(25, 20, 60, 33, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'smash',
    version: 3,
    kind: 'fundamento',
    title: 'Smash: finalizar o lob curto',
    summary: 'O golpe por cima da cabeça para a bola alta e curta. De lado, atrás da bola, com a mão livre apontando, e mirando os pés ou o meio.',
    objective: 'Ao final, o atleta posiciona-se de lado, atrás da bola, e finaliza para baixo com mais precisão do que força.',
    skills: ['net.smash'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Viu o lob curto: vire de lado para a rede e aponte a bola com a mão livre.',
      'Dê passos laterais (ou cruzados, se for longe) até ficar um pouco atrás da bola.',
      'Leve a raquete para trás e para cima da cabeça, como quem vai arremessar uma bola.',
      'Bata com o braço estendido, a bola na frente e no ponto mais alto que você alcança, de cima para baixo.',
      'Mire o meio ou os pés do adversário e termine a raquete do outro lado do corpo.',
      'Perto da rede, termine equilibrado fora da cozinha; depois volte para a linha.',
    ],
    cues: ['Aponte a bola com a mão livre', 'Bola na frente e no alto', 'Alvo antes da força'],
    positioning: [
      { type: 'certo', text: 'De lado, atrás da bola, que cai na sua frente: o smash desce na quadra.' },
      { type: 'errado', text: 'Embaixo da bola, de frente para a rede: o smash vai na rede ou para fora.' },
      { type: 'certo', text: 'Contato com o braço estendido, acima e um pouco à frente da cabeça.' },
      { type: 'errado', text: 'Deixar a bola cair até a altura da cabeça: o smash sai sem ângulo para baixo e vai na rede ou para fora.' },
    ],
    common_errors: [
      { error: 'Recuar de costas para alcançar a bola.', fix: 'Vire de lado e ande de lado: recuar de costas é como se cai.' },
      { error: 'Bater com toda a força e errar.', fix: 'Ângulo e alvo ganham o ponto: mire os pés ou o meio.' },
      { error: 'Tirar os olhos da bola para olhar o alvo.', fix: 'Olhos na bola até o contato; o alvo você escolheu antes.' },
      { error: 'Smash sem quique (um voleio) perto da linha, e o embalo leva o pé para a cozinha.', fix: 'É falta, mesmo com a bola já morta: termine o golpe parado fora da cozinha.' },
    ],
    when_to_use: 'No lob curto, que você alcança sem deixar quicar ou depois de um quique alto perto da rede.',
    safety: 'Para ir atrás do lob, vire de lado; nunca recue de costas.',
    motor: {
      phases: {
        preparacao: 'De lado, mão livre apontando, raquete atrás e alta.',
        execucao: 'Contato na frente e no alto, de cima para baixo.',
        finalizacao: 'Raquete termina do outro lado do corpo; volta à cozinha.',
      },
      abilities: ['coordenacao', 'potencia', 'leitura'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, a mesma da rede: não há tempo de trocar.' },
        { part: 'olhar', text: 'Na bola o tempo todo, apontada pela mão livre, até o contato.' },
        { part: 'pes', text: 'Passos laterais ou cruzados, nunca de costas; param um pouco atrás da bola, de lado para a rede.' },
        { part: 'pernas', text: 'Dobradas na chegada; empurram para cima e para a frente no golpe.' },
        { part: 'tronco', text: 'De lado na preparação; gira de frente para a rede no golpe.' },
        { part: 'braco', text: 'A mão livre aponta a bola; o braço da raquete vai atrás e acima da cabeça e estica no contato.' },
        { part: 'raquete', text: 'Atrás e acima da cabeça na preparação; encontra a bola na frente e termina do outro lado do corpo.' },
      ],
      self_check: [
        'A bola desce dentro da quadra, no meio ou nos pés do adversário.',
        'No contato, a bola estava na sua frente, e não atrás da cabeça.',
        'Você chegou à bola sem recuar de costas.',
        'Depois do golpe você está equilibrado, sem pisar na cozinha.',
      ],
    },
    diagrams: [
      diagrama('Alvo do smash', 'inteira', [
        jogador(50, 74, 'a'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        zona(38, 24, 62, 40, 'Meio'),
        trajeto(50, 72, 50, 33),
      ]),
    ],
    media: [],
  },
];
