/** Biblioteca inicial — GOLPES DE REDE: punch, bloqueio, defesa de corpo, speed-up, contra-ataque e flick (complementam `voleio` e `smash`). */

import { diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const GOLPES_REDE = [
  {
    slug: 'voleio-punch',
    version: 1,
    kind: 'fundamento',
    title: 'Voleio de punch: o soco curto para a frente',
    summary: 'Voleio firme e curto, como um soco para a frente, na bola que chega acima da fita da rede. Sem balanço para trás: a raquete já está na frente e só avança um palmo para mandar a bola baixa nos pés do adversário.',
    objective: 'Ao final, o atleta volea a bola acima da fita com um soco curto para a frente, contato na frente do corpo, mandando a bola nos pés do adversário ou no meio da dupla.',
    skills: ['net.voleio', 'net.contra_ataque'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Espere na posição de prontidão, atrás da linha da cozinha, com a empunhadura continental e a raquete na frente do peito, a cabeça da raquete acima da altura da rede.',
      'Leia a altura: o punch é para a bola que chega acima da fita. Bola abaixo da fita pede bloqueio ou reset, não soco.',
      'Leve a raquete ao encontro da bola sem puxá-la para trás: ela já está armada na frente.',
      'Encontre a bola na frente do corpo, uns 30 a 40 cm à frente, com a face firme apontando para o alvo.',
      'Empurre a raquete um palmo para a frente, como um soco curto, com o peso passando para o pé da frente. Bola bem acima da rede: feche um pouco a face e o soco vai para a frente e levemente para baixo.',
      'Mire os pés do adversário ou o espaço entre os dois da dupla.',
      'Pare a raquete logo depois do contato, apontando o alvo, e volte com ela para a frente do peito.',
    ],
    cues: ['Raquete na frente, acima da fita', 'Soco curto rumo aos pés', 'Raquete termina apontando o alvo'],
    positioning: [
      { type: 'certo', text: 'Contato na frente do corpo, com a raquete acima da altura da rede: a bola sai para a frente e para baixo, no pé do adversário.' },
      { type: 'errado', text: 'Contato ao lado ou atrás do corpo, com a bola já passando → a face chega aberta, a bola sobe e vira presente para o smash do adversário.' },
      { type: 'certo', text: 'Gesto de um palmo para a frente, a raquete parando apontada para o alvo: o voleio sai firme e você já está pronto para a próxima.' },
      { type: 'errado', text: 'Balanço para trás antes do voleio → a bola chega antes da raquete, o contato atrasa e o golpe sai sem direção, longo ou na rede.' },
    ],
    common_errors: [
      { error: 'A raquete vai para trás antes de cada voleio, como no tênis.', fix: 'Comece com a raquete na frente do peito e só avance. Para treinar, fique de costas perto de uma cerca: não sobra espaço para armar.' },
      { error: 'O voleio sai de cima para baixo e bate na fita.', fix: 'O soco é para a frente; desça a raquete só um pouco, e só quando a bola estiver bem acima da rede. Mire os pés, não o chão logo depois da rede.' },
      { error: 'Pegar a bola ao lado do corpo, atrasado.', fix: 'Leve a raquete ao encontro da bola, na frente. Se a bola chega rápida demais para isso, troque o punch por um bloqueio.' },
      { error: 'Mandar o punch na altura do peito do adversário.', fix: 'Bola alta volta atacada. Mire os pés ou o meio da dupla: ali ele tem de levantar a bola.' },
    ],
    when_to_use: 'Na linha da cozinha, quando a bola do adversário chega acima da fita da rede e dá tempo de avançar a raquete: dink alto, devolução flutuando, reset que subiu demais. Bola abaixo da fita, ou rápida demais, pede bloqueio.',
    motor: {
      phases: {
        preparacao: 'Prontidão com a raquete na frente do peito, cabeça da raquete acima da rede.',
        execucao: 'Contato na frente do corpo e soco curto de um palmo para a frente, com o peso indo para a frente.',
        finalizacao: 'A raquete para apontando o alvo e volta para a frente do peito.',
      },
      abilities: ['tempo_reacao', 'precisao', 'coordenacao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto firme mas sem esmagar: uns 5 numa escala de 1 a 10 no contato.' },
        { part: 'olhar', text: 'Na bola até o contato; é a altura dela em relação à fita que decide se é punch.' },
        { part: 'pes', text: 'Base aberta atrás da linha da cozinha; se der tempo, um passo curto com o pé da frente na direção da bola, sem pisar na linha.' },
        { part: 'pernas', text: 'Dobradas; o peso passa para a frente junto com o soco.' },
        { part: 'braco', text: 'O cotovelo fica à frente do corpo e se estende só um pouco: o soco é curto, não um balanço.' },
        { part: 'punho', text: 'Firme e parado: o punho não quebra no contato, quem anda é a raquete inteira.' },
        { part: 'raquete', text: 'Cabeça acima da altura da rede e da mão; face neutra apontando o alvo, fechando um pouco quando a bola está bem alta.' },
      ],
      self_check: [
        'A bola saiu baixa, passando perto da fita e caindo nos pés do adversário.',
        'A raquete terminou na frente, apontando o alvo, e não atrás do corpo.',
        'Você terminou equilibrado, sem dar passo para dentro da cozinha.',
        'O som foi seco e firme, e não um tapa com a raquete balançando.',
      ],
    },
    variations: {
      easier: 'Pessoas: um parceiro, do outro lado da rede, joga com a mão bolas lentas na altura do seu peito; você só faz o soco curto nos pés dele.',
      harder: 'Tarefa: o parceiro alterna bola alta e bola abaixo da fita, sem avisar; você faz punch só na alta e bloqueia a baixa na cozinha.',
    },
    diagrams: [
      diagrama('Certo: bola alta, soco curto no meio da dupla', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 68, 'a'),
        jogador(30, 32, 'b'),
        jogador(70, 32, 'b'),
        trajeto(35, 34, 58, 64, 'Bola alta'),
        trajeto(60, 66, 50, 30, 'No meio'),
      ], 'certo'),
      diagrama('Errado: de cima para baixo, na rede', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 68, 'a'),
        jogador(30, 32, 'b'),
        jogador(70, 32, 'b'),
        trajeto(35, 34, 58, 64, 'Bola alta'),
        trajeto(60, 66, 56, 50.5, 'Na rede'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'bloqueio',
    version: 2,
    kind: 'fundamento',
    title: 'Bloqueio: absorver a bola forte e devolver na cozinha',
    summary: 'A defesa contra a bola forte (drive ou speed-up): a raquete só se posiciona na frente, com a mão relaxada, e absorve a velocidade para a bola voltar curta e baixa na cozinha. Tira o ataque do adversário.',
    objective: 'Ao final, o atleta devolve um drive ou um speed-up com a raquete parada na frente e a mão relaxada, fazendo a bola cair na cozinha do adversário.',
    skills: ['net.bloqueio', 'net.reset'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Espere na prontidão, com a raquete na frente do peito e a cabeça da raquete para cima.',
      'Ao ver o ataque saindo, coloque a raquete na frente do corpo, no caminho da bola, sem armar e sem balançar.',
      'Abra um pouco a face (voltada levemente para cima), só o bastante para a bola passar a rede.',
      'Segure com aperto leve, uns 3 numa escala de 1 a 10: a mão relaxada amortece a bola, como quem recebe um ovo.',
      'Encontre a bola na frente do corpo; se ela vem muito rápida, deixe a raquete ceder uns centímetros para trás junto com ela.',
      'A bola volta curta e baixa e cai na cozinha do adversário.',
      'Volte à prontidão: o próximo ataque pode vir em seguida.',
    ],
    cues: ['Raquete parada, como parede macia', 'Bola morre na cozinha', 'Face um pouco aberta para cima'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente do corpo, face um pouco aberta e aperto leve: a bola perde a velocidade e cai curta na cozinha.' },
      { type: 'errado', text: 'Empurrar a raquete para a frente no contato → a força do golpe soma com a da bola, que volta alta ou longa, pronta para ser atacada de novo.' },
      { type: 'certo', text: 'Raquete já posicionada antes de a bola chegar, sem gesto: dá tempo mesmo contra a bola mais rápida.' },
      { type: 'errado', text: 'Raquete ao lado do corpo, buscando a bola tarde → o contato atrasa, a face chega torta e a bola vai para fora ou para a rede.' },
    ],
    common_errors: [
      { error: 'A bola bloqueada volta alta e longa.', fix: 'Pare de empurrar: o bloqueio usa a velocidade que veio e só a direciona para a cozinha.' },
      { error: 'Mão dura: a bola rebate na raquete como numa parede de concreto e sai longa.', fix: 'Aperte menos (3 de 10) e deixe a raquete ceder um pouco no contato.' },
      { error: 'A bola bloqueada cai na rede.', fix: 'Abra um pouco mais a face: a bola que chega abaixo da fita precisa subir para passar.' },
      { error: 'Tentar bloquear com a raquete ao lado do corpo.', fix: 'Volte a raquete para a frente do peito depois de cada bola: dali ela chega a qualquer bloqueio.' },
    ],
    when_to_use: 'Quando a bola chega rápida e você não tem tempo nem altura para contra-atacar: drive da terceira bola na sua chegada à rede, speed-up abaixo do ombro, bola no corpo. No contra-ataque você devolve com mais velocidade; no bloqueio você tira a velocidade e devolve na cozinha, para neutralizar o ponto.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente do peito, aperto leve, pernas dobradas.',
        execucao: 'A raquete se coloca no caminho da bola, face um pouco aberta, sem gesto, e cede no contato.',
        finalizacao: 'A bola cai na cozinha e a raquete volta à prontidão.',
      },
      abilities: ['tempo_reacao', 'precisao', 'leitura'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental com aperto leve, uns 3 de 10: é a mão relaxada que amortece a bola.' },
        { part: 'olhar', text: 'Na raquete do adversário, para ler o ataque cedo; depois na bola até o contato.' },
        { part: 'pernas', text: 'Dobradas e baixas: deixam a raquete na altura da bola e o corpo estável.' },
        { part: 'braco', text: 'Cotovelo à frente do corpo, o braço quase parado: ele só leva a raquete ao caminho da bola.' },
        { part: 'punho', text: 'Estável, sem tapa: a face não muda de ângulo no contato, mesmo com a mão relaxada.' },
        { part: 'raquete', text: 'Na frente do corpo, face levemente aberta; no contato ela cede alguns centímetros para trás junto com a bola.' },
      ],
      self_check: [
        'A bola caiu na cozinha do adversário, e não no meio da quadra.',
        'Depois do contato a bola passou baixa, sem subir acima da altura da rede.',
        'O som foi um toque macio, e não uma batida seca.',
        'O adversário teve de bater de baixo para cima na bola seguinte.',
      ],
    },
    variations: {
      easier: 'Espaço: o parceiro ataca do meio da quadra, mais devagar, e você bloqueia para qualquer lugar da cozinha.',
      harder: 'Tarefa: o parceiro ataca do fundo com drives fortes, alternando forehand, backhand e corpo; você bloqueia sempre para a cozinha da diagonal.',
    },
    diagrams: [
      diagrama('Certo: o drive volta curto na cozinha', 'inteira', [
        zona(0, 34, 100, 49, 'Cozinha'),
        jogador(30, 8, 'b'),
        jogador(60, 68, 'a'),
        trajeto(30, 10, 58, 64, 'Drive'),
        trajeto(60, 66, 40, 40, 'Bloqueio'),
      ], 'certo'),
      diagrama('Errado: empurrou e a bola voltou longa', 'inteira', [
        zona(0, 34, 100, 49, 'Cozinha'),
        jogador(30, 8, 'b'),
        jogador(60, 68, 'a'),
        trajeto(30, 10, 58, 64, 'Drive'),
        trajeto(60, 66, 35, 15, 'Longa'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'defesa-de-corpo',
    version: 1,
    kind: 'fundamento',
    title: 'Defesa de corpo: a bola que vem no peito',
    summary: 'Como defender a bola rápida mirada no seu corpo: raquete no centro, à frente do peito, defendendo de backhand, com o cotovelo à frente e longe do corpo. Só a bola no quadril do lado da raquete vai de forehand.',
    objective: 'Ao final, o atleta defende bolas rápidas no peito com o backhand à frente do corpo, sem travar o cotovelo, e devolve a bola baixa.',
    skills: ['net.defesa_corpo', 'net.contra_ataque'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Na batalha de rede, mantenha a raquete alta, no centro, à frente do peito, com a cabeça da raquete para cima e a face virada para o lado do backhand.',
      'Bola no peito, na barriga ou no ombro do lado da raquete (o direito, para o destro): defenda de backhand. O backhand cobre o corpo inteiro, até esse ombro.',
      'Leve o cotovelo para a frente e para longe do corpo, abrindo espaço entre a raquete e o peito.',
      'Se der tempo, gire e tire o corpo da linha da bola, para ela passar ao lado e não em você.',
      'Encontre a bola na frente do corpo com gesto curto: bloqueie se ela veio rápida demais, contra-ataque se deu tempo.',
      'Bola no quadril ou na perna do lado da raquete: aí sim, forehand, com a raquete descendo pelo lado.',
      'Volte a raquete para o centro do peito antes da próxima bola.',
    ],
    cues: ['Raquete no centro, na frente do peito', 'Backhand cobre a bola no peito', 'Espaço entre a raquete e o peito'],
    positioning: [
      { type: 'certo', text: 'Raquete no centro, à frente do peito, defendendo de backhand: a face chega na frente da bola em qualquer altura do peito à barriga.' },
      { type: 'errado', text: 'Defender a bola no peito de forehand, com o cotovelo levantado e preso ao lado ("asa de galinha") → a raquete trava, a face sai aberta e a bola sobe para o adversário matar.' },
      { type: 'certo', text: 'Cotovelo à frente e longe do corpo: sobra espaço para a raquete encontrar a bola na frente.' },
      { type: 'errado', text: 'Cotovelo encostado na barriga → a raquete fica presa junto ao peito e a bola bate no corpo ou na mão.' },
      { type: 'certo', text: 'Raquete alta, na altura do peito, durante toda a troca rápida.' },
      { type: 'errado', text: 'Raquete baixa, perto da cintura → a bola no peito chega antes de a raquete subir.' },
    ],
    common_errors: [
      { error: 'Cotovelo levantado ao lado e raquete de forehand na frente da barriga ("asa de galinha").', fix: 'Deixe o forehand para a bola no quadril do lado da raquete; no peito, use o backhand.' },
      { error: 'Levar a bolada no corpo sem reagir.', fix: 'Raquete no centro e alta antes de a bola sair; gire e tire o corpo da linha da bola.' },
      { error: 'Dar um passo para trás quando a bola vem forte.', fix: 'Fique firme na linha, peso à frente: recuando, a próxima bola cai nos seus pés.' },
      { error: 'Devolver alto depois de defender.', fix: 'Gesto curto e face neutra: a defesa é para a bola voltar baixa, não para ganhar o ponto.' },
    ],
    when_to_use: 'Na troca rápida de voleios na linha da cozinha, quando o adversário acelera no seu corpo (peito, barriga, ombro do lado da raquete), que é o alvo mais difícil de defender.',
    safety: 'Na batalha de rede a bola vem rápida e perto do rosto: use óculos de proteção e mantenha a raquete alta, na frente do peito, onde ela também protege.',
    motor: {
      phases: {
        preparacao: 'Raquete alta no centro do peito, face para o lado do backhand, base aberta.',
        execucao: 'Cotovelo à frente, o corpo sai da linha da bola e o backhand encontra a bola na frente com gesto curto.',
        finalizacao: 'A bola volta baixa e a raquete retorna ao centro do peito.',
      },
      abilities: ['tempo_reacao', 'agilidade', 'leitura'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental: a mesma empunhadura serve ao backhand do corpo, e não há tempo de trocar.' },
        { part: 'olhar', text: 'Na raquete do adversário, para ler a aceleração cedo, e na bola até o contato.' },
        { part: 'pes', text: 'Base aberta, quase paralela à rede, com o peso na parte da frente dos pés.' },
        { part: 'tronco', text: 'Gira um pouco e sai da linha da bola, deixando a raquete entre a bola e o corpo.' },
        { part: 'braco', text: 'Cotovelo à frente e afastado do corpo, nunca colado nas costelas.' },
        { part: 'punho', text: 'Firme, sem quebrar: a face fica neutra no contato.' },
        { part: 'raquete', text: 'No centro, à frente do peito, cabeça para cima e face para o lado do backhand; desce pelo lado só para a bola baixa do lado da raquete.' },
      ],
      self_check: [
        'Você encontrou a bola na frente do corpo, sem ela bater na mão ou no peito.',
        'A devolução passou baixa, sem subir para o adversário.',
        'Depois da defesa a raquete já estava de novo no centro do peito.',
        'Você defendeu sem dar passo para trás.',
      ],
    },
    variations: {
      easier: 'Pessoas: o parceiro, na linha da cozinha, joga com a mão bolas lentas no seu peito; você só defende de backhand, bloqueando.',
      harder: 'Tarefa: o parceiro acelera sem avisar entre peito, ombro do lado da raquete e quadril; você escolhe backhand ou forehand e devolve baixo.',
    },
    diagrams: [
      diagrama('Certo: backhand na frente do peito, bola baixa', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(40, 34, 'b'),
        jogador(58, 68, 'a', 'Você'),
        trajeto(40, 36, 58, 66, 'No peito'),
        trajeto(56, 66, 42, 38, 'Baixa'),
        texto(58, 74, 'Backhand'),
      ], 'certo'),
      diagrama('Errado: forehand travado, bola alta', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(40, 34, 'b'),
        jogador(58, 68, 'a', 'Você'),
        trajeto(40, 36, 58, 66, 'No peito'),
        trajeto(60, 66, 42, 26, 'Alta'),
        texto(58, 74, 'Forehand'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'speed-up',
    version: 1,
    kind: 'fundamento',
    title: 'Speed-up (aceleração): a bola rápida a partir do dink',
    summary: 'No meio do jogo de dink, acelerar de repente uma bola rápida no corpo do adversário. Só funciona na bola que dá para atacar: na altura da fita ou acima, mais alta que o joelho. Bola baixa acelerada sobe e vira contra-ataque.',
    objective: 'Ao final, o atleta escolhe a bola certa para acelerar e executa um speed-up curto, com topspin, no ombro do lado da raquete ou no quadril do adversário.',
    skills: ['net.speed_up', 'kitchen.dink_atacavel', 'tactics.selecao_golpe'],
    level_min: 3.5,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'variado',
    steps: [
      'Troque dinks com paciência, na prontidão, esperando a bola certa.',
      'Acelere só se a bola chega na altura da fita ou acima, mais alta que o seu joelho, e de preferência com o adversário fora da prontidão: raquete baixa, desequilibrado, de lado.',
      'Encontre a bola na frente do corpo, sem armar: a raquete sai de onde está, logo atrás e abaixo da bola.',
      'Faça um gesto curto e rápido de baixo para cima e para a frente, fechando a face ao passar pela bola para dar topspin (a bola gira para a frente e desce).',
      'Mire o ombro do lado da raquete do adversário (o direito, num destro), o quadril ou o meio do corpo.',
      'Termine com a raquete à frente, na altura do peito, e volte na hora à prontidão: a bola vai voltar rápida.',
      'Bola baixa, abaixo da fita: não acelere; faça outro dink e espere.',
    ],
    cues: ['Bola alta? Acelere. Baixa? Dink', 'Alvo: o lado da raquete dele', 'Raquete pronta para a volta'],
    positioning: [
      { type: 'certo', text: 'Acelerar a bola que chegou na altura da fita ou acima, com contato na frente: a bola sai reta e desce no corpo do adversário.' },
      { type: 'errado', text: 'Acelerar uma bola baixa, abaixo da fita → para passar a rede ela tem de subir, chega alta no adversário e ele contra-ataca para baixo, nos seus pés.' },
      { type: 'certo', text: 'Mirar o ombro do lado da raquete ou o quadril do adversário: é onde a defesa é mais difícil.' },
      { type: 'errado', text: 'Mirar longe do corpo, no backhand aberto ou na raquete dele → é a bola mais fácil de bloquear ou contra-atacar.' },
      { type: 'certo', text: 'Raquete de volta à frente do peito logo depois de acelerar.' },
      { type: 'errado', text: 'Ficar parado olhando a bola, com a raquete baixa, depois do speed-up → o contra-ataque passa antes de você reagir.' },
    ],
    common_errors: [
      { error: 'Acelerar bola baixa, abaixo do joelho.', fix: 'Bola baixa, dink. Espere a bola que chega na altura da fita para acelerar.' },
      { error: 'Armar a raquete para trás antes de acelerar.', fix: 'O adversário lê e se prepara. Acelere de onde a raquete está, com gesto curto.' },
      { error: 'A bola acelerada sai pelo fundo.', fix: 'Feche a face ao passar pela bola para dar topspin e mire o corpo, não o fundo.' },
      { error: 'Comemorar o speed-up e ser pego pelo contra-ataque.', fix: 'Depois de acelerar, raquete alta e na frente: conte com a bola voltando.' },
    ],
    when_to_use: 'No jogo de dink, quando o adversário deixa a bola alta (na altura da fita ou acima) ou está fora da prontidão: raquete baixa, desequilibrado, de lado. Nunca acelere bola baixa, abaixo da fita: é o erro que entrega o ponto.',
    safety: 'Mire ombro, quadril e pés, nunca o rosto, e use óculos de proteção: a bola acelerada volta rápida e perto do rosto.',
    motor: {
      phases: {
        preparacao: 'Prontidão de dink, raquete na frente, lendo a altura da bola.',
        execucao: 'Contato na frente e gesto curto de baixo para cima e para a frente, fechando a face (topspin).',
        finalizacao: 'A raquete termina à frente do peito, pronta para a volta.',
      },
      abilities: ['potencia', 'tempo_reacao', 'leitura'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto leve até o contato; firma um pouco só na hora de acelerar.' },
        { part: 'olhar', text: 'Na altura da bola em relação à fita e na raquete do adversário: é essa leitura que decide se acelera.' },
        { part: 'pernas', text: 'Dobradas; sobem junto com o golpe, de baixo para cima.' },
        { part: 'tronco', text: 'Gira um pouco para a frente no contato, dando força sem armar.' },
        { part: 'braco', text: 'Gesto curto: o antebraço leva a raquete para a frente e para cima, cerca de um palmo depois da bola.' },
        { part: 'punho', text: 'Acompanha o gesto e fecha a face ao passar pela bola, dando topspin, sem chicote exagerado.' },
        { part: 'raquete', text: 'Começa logo abaixo e atrás da bola e termina à frente, na altura do peito, pronta para a volta.' },
      ],
      self_check: [
        'A bola acelerada desceu no corpo do adversário, sem sair pelo fundo.',
        'O adversário reagiu atrasado: você não armou a raquete.',
        'Quando a bola voltou, sua raquete já estava na frente do peito.',
        'Você só acelerou bolas que chegaram na altura da fita ou acima.',
      ],
    },
    variations: {
      easier: 'Tarefa: o parceiro dá dinks altos de propósito, na altura da fita; você acelera devagar no ombro do lado da raquete dele, que só bloqueia.',
      harder: 'Tarefa: dink cruzado livre; quem receber bola alta acelera, quem receber bola baixa tem de fazer dink. O ponto segue até o erro.',
    },
    diagrams: [
      diagrama('Certo: bola alta acelerada no lado da raquete', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 68, 'a'),
        jogador(40, 32, 'b'),
        jogador(75, 32, 'b'),
        trajeto(42, 34, 58, 58, 'Dink alto'),
        trajeto(60, 62, 36, 32, 'Speed-up'),
      ], 'certo'),
      diagrama('Errado: bola baixa acelerada volta nos pés', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(60, 68, 'a'),
        jogador(40, 32, 'b'),
        texto(64, 60, 'Bola baixa'),
        trajeto(60, 64, 42, 27, 'Sobe'),
        trajeto(40, 30, 58, 70, 'Contra'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'contra-ataque',
    version: 1,
    kind: 'fundamento',
    title: 'Contra-ataque: devolver o speed-up com mais velocidade',
    summary: 'Responder à bola acelerada do adversário com outra bola rápida, curta e para baixo, usando a velocidade que veio. Quem tem a raquete alta e o gesto curto ganha a troca de voleios rápidos.',
    objective: 'Ao final, o atleta contra-ataca a bola rápida na altura do peito com gesto curto, mirando os pés ou o quadril do adversário, e bloqueia quando a bola chega baixa ou rápida demais.',
    skills: ['net.contra_ataque', 'net.bloqueio'],
    level_min: 3.5,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'variado',
    steps: [
      'Na prontidão, deixe a raquete alta e na frente do peito, com a cabeça da raquete para cima.',
      'Leia a altura da bola que vem: na altura do peito ou do ombro, contra-ataque; abaixo do ombro e rápida demais, bloqueie.',
      'Sem armar: a raquete vai direto da prontidão ao encontro da bola, na frente do corpo.',
      'Use a velocidade que veio: um gesto curto e firme, de um palmo, basta para a bola voltar mais rápida.',
      'Feche um pouco a face e mande a bola para baixo, nos pés ou no quadril do adversário, nunca para cima.',
      'Volte à prontidão: depois do contra-ataque a troca costuma continuar.',
    ],
    cues: ['Raquete alta, gesto curto', 'Mande a bola para baixo', 'Bola no peito? Contra-ataque'],
    positioning: [
      { type: 'certo', text: 'Contato na frente, com a raquete alta, mandando a bola para baixo nos pés do adversário: ele tem de levantar a próxima.' },
      { type: 'errado', text: 'Contra-atacar para cima, na altura do peito ou da cabeça dele → a bola fica atacável e ele acelera de novo, agora com vantagem.' },
      { type: 'certo', text: 'Gesto curto, saindo da prontidão: a raquete chega antes da bola.' },
      { type: 'errado', text: 'Armar a raquete para trás para bater forte → a bola rápida chega antes, o contato atrasa e a bola sai para fora ou na rede.' },
      { type: 'certo', text: 'Bloquear a bola baixa e rápida demais, devolvendo na cozinha.' },
      { type: 'errado', text: 'Contra-atacar a bola abaixo da cintura → ela tem de subir para passar a rede e o adversário a ataca.' },
    ],
    common_errors: [
      { error: 'Armar o golpe e chegar tarde.', fix: 'A raquete sai da prontidão direto para a bola; a força vem da bola que veio.' },
      { error: 'Contra-atacar para cima, dando outra bola atacável.', fix: 'Feche um pouco a face e mire os pés ou o quadril.' },
      { error: 'Raquete baixa na prontidão.', fix: 'Na troca rápida, raquete na altura do peito: de baixo ela não chega a tempo.' },
      { error: 'Contra-atacar tudo, até a bola baixa e rápida demais.', fix: 'Abaixo do ombro e sem tempo: bloqueie na cozinha e espere outra chance.' },
    ],
    when_to_use: 'Quando o adversário acelera e a bola chega na altura do peito ou do ombro, com tempo para um gesto curto. Abaixo disso, ou rápida demais, a escolha é o bloqueio.',
    safety: 'Na troca rápida a bola passa perto do rosto: use óculos de proteção e mire pés e quadril, nunca o rosto do adversário.',
    motor: {
      phases: {
        preparacao: 'Raquete alta, na frente do peito, lendo a raquete do adversário.',
        execucao: 'Gesto curto e firme, contato na frente, face fechando um pouco para a bola descer.',
        finalizacao: 'A raquete termina apontando para baixo e volta alta à prontidão.',
      },
      abilities: ['tempo_reacao', 'leitura', 'precisao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto médio: firme o bastante para a raquete não girar com a bola rápida.' },
        { part: 'olhar', text: 'Na raquete do adversário: o speed-up se lê antes de a bola sair.' },
        { part: 'pes', text: 'Base aberta e firme na linha, peso à frente, sem passo para trás.' },
        { part: 'braco', text: 'Cotovelo à frente do corpo; o gesto é curto, como um soco de um palmo.' },
        { part: 'punho', text: 'Firme, fechando um pouco a face no contato para a bola descer.' },
        { part: 'raquete', text: 'Alta, na frente do peito, cabeça para cima; termina apontando para baixo, para os pés do adversário.' },
      ],
      self_check: [
        'A sua bola desceu e o adversário teve de bater de baixo para cima.',
        'Você não armou: a raquete saiu da frente do peito direto para a bola.',
        'As bolas baixas e rápidas demais você bloqueou, e elas caíram na cozinha.',
        'Depois do contra-ataque a raquete voltou alta antes da próxima bola.',
      ],
    },
    variations: {
      easier: 'Pessoas: o parceiro, na linha da cozinha, acelera devagar e sempre na altura do seu peito; você contra-ataca nos pés dele.',
      harder: 'Tarefa: o parceiro alterna aceleração no peito e abaixo da cintura, sem avisar; você contra-ataca a alta e bloqueia a baixa.',
    },
    diagrams: [
      diagrama('Certo: contra-ataque para baixo, nos pés', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(40, 32, 'b'),
        jogador(60, 68, 'a'),
        trajeto(40, 34, 58, 62, 'Speed-up'),
        trajeto(60, 64, 42, 30, 'Nos pés'),
      ], 'certo'),
      diagrama('Errado: para cima, e o adversário ataca de novo', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(40, 32, 'b'),
        jogador(60, 68, 'a'),
        trajeto(40, 34, 58, 62, 'Speed-up'),
        trajeto(60, 64, 42, 26, 'Alta'),
        trajeto(40, 30, 62, 70, 'De novo'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'flick-de-backhand',
    version: 2,
    kind: 'fundamento',
    title: 'Flick de backhand: a aceleração de surpresa da cozinha',
    summary: 'Aceleração de backhand disfarçada de dink: a raquete baixa, de face aberta, parece que vai fazer outro dink e, no último instante, chicoteia de baixo para cima e para a frente, com topspin, mandando a bola rápida no ombro ou pelo lado do adversário.',
    objective: 'Ao final, o atleta executa o flick de backhand a partir da posição de dink, sem revelar a intenção, mandando a bola rápida e com topspin no ombro do lado da raquete do adversário ou pelo lado dele.',
    skills: ['net.speed_up', 'groundstrokes.backhand', 'groundstrokes.efeito'],
    level_min: 4.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Prepare-se como para um dink de backhand (lado esquerdo, para o destro): raquete baixa, à frente do corpo, face um pouco aberta.',
      'Escolha a bola: ela precisa chegar perto do corpo e não muito baixa, acima do joelho. Bola nos pés ou longe do corpo é dink.',
      'Deixe a bola vir até a frente do pé da frente, com a raquete parada e a mesma postura do dink.',
      'No último instante, o punho e o antebraço chicoteiam a raquete de baixo para cima e para a frente, girando a face por cima da bola (o "roll") para dar topspin.',
      'Mire o ombro do lado da raquete do adversário ou passe a bola pelo lado dele, na paralela.',
      'Termine com a raquete alta e à frente, e volte na hora à prontidão para o contra-ataque.',
    ],
    cues: ['Cara de dink até o fim', 'Raquete escova a bola para cima', 'Bola rápida rumo ao lado da raquete'],
    positioning: [
      { type: 'certo', text: 'Mesma preparação do dink, com a raquete baixa, face aberta e sem armar, até o último instante: o adversário espera um dink e é pego com a raquete baixa.' },
      { type: 'errado', text: 'Armar a raquete ou levantar o corpo antes do flick → o adversário lê, sobe a raquete e contra-ataca a sua bola.' },
      { type: 'certo', text: 'Contato na frente do corpo, com a bola perto: há espaço para chicotear e a face gira por cima da bola.' },
      { type: 'errado', text: 'Flick em bola baixa ou longe do corpo → sem topspin suficiente, a bola sobe e sai longa ou alta, pronta para o contra-ataque.' },
    ],
    common_errors: [
      { error: 'A bola do flick sai longa pelo fundo.', fix: 'Mais giro, menos força: a raquete sobe escovando a bola e a face termina fechada.' },
      { error: 'O adversário sempre espera o flick.', fix: 'Faça vários dinks de backhand idênticos antes; o flick só surpreende se começa igual a eles.' },
      { error: 'Flick em bola que quicou baixa, perto dos pés.', fix: 'Bola baixa ou longe do corpo: faça o dink e espere uma bola mais alta e mais perto.' },
      { error: 'Ficar admirando o golpe depois do flick.', fix: 'Raquete alta na frente do peito na hora: a bola costuma voltar rápida.' },
    ],
    when_to_use: 'No dink de backhand, quando a bola chega perto do corpo e não muito baixa, e o adversário está com a raquete baixa esperando outro dink. Não use em bola baixa (perto dos pés) nem longe do corpo, esticado: aí o certo é o dink.',
    safety: 'Mire o ombro do lado da raquete, o quadril ou o lado do adversário, nunca o rosto, e use óculos de proteção: a bola volta rápida e perto do rosto.',
    motor: {
      phases: {
        preparacao: 'Postura de dink de backhand: raquete baixa, face aberta, nada que denuncie a aceleração.',
        execucao: 'No último instante, chicotada curta de baixo para cima e para a frente, girando a face por cima da bola.',
        finalizacao: 'Raquete alta e à frente, e volta imediata à prontidão.',
      },
      abilities: ['coordenacao', 'potencia', 'precisao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto leve até o contato, para o punho ter liberdade de chicotear.' },
        { part: 'olhar', text: 'Na bola até o contato, sem olhar para o alvo antes: o olhar entrega a intenção.' },
        { part: 'pernas', text: 'Dobradas, como no dink; sobem junto com o golpe no contato.' },
        { part: 'tronco', text: 'De frente para a rede, como no dink; gira só um pouco no contato.' },
        { part: 'braco', text: 'O antebraço parte baixo, à frente do corpo, e sobe para a frente; o cotovelo fica à frente, longe do corpo.' },
        { part: 'punho', text: 'Começa solto, com a raquete baixa e a face aberta, e chicoteia para a frente e para cima no contato, girando para fechar a face.' },
        { part: 'raquete', text: 'Começa abaixo da bola com a face aberta e termina alta, à frente, com a face fechada, depois de escovar a bola de baixo para cima.' },
      ],
      self_check: [
        'A bola saiu rápida e desceu dentro da quadra, girando para a frente.',
        'O adversário reagiu atrasado, com a raquete ainda baixa.',
        'Seus dinks de backhand e o flick começam iguais: peça a alguém para olhar se dá para adivinhar.',
        'Você só fez o flick em bolas perto do corpo e acima do joelho.',
      ],
    },
    variations: {
      easier: 'Pessoas: o parceiro joga com a mão bolas na altura do seu joelho, do lado do backhand; você faz o flick devagar só para sentir a raquete escovar a bola para cima.',
      harder: 'Tarefa: dink de backhand na paralela; você decide sem avisar entre dink e flick, e o parceiro diz quantos flicks percebeu antes de a bola sair.',
    },
    diagrams: [
      diagrama('Certo: flick no ombro ou pela paralela', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(36, 68, 'a'),
        jogador(36, 32, 'b'),
        jogador(70, 32, 'b'),
        trajeto(36, 36, 36, 60, 'Dink'),
        trajeto(36, 64, 30, 30, 'No ombro'),
        trajeto(34, 64, 6, 27, 'Paralela'),
      ], 'certo'),
      diagrama('Errado: flick em bola baixa sobe e volta', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(36, 68, 'a'),
        jogador(36, 32, 'b'),
        texto(40, 74, 'Bola baixa'),
        trajeto(36, 64, 32, 26, 'Longa'),
        trajeto(34, 30, 40, 70, 'Contra'),
      ], 'errado'),
    ],
    media: [],
  },
];
