/** Biblioteca inicial — GOLPES DA COZINHA: meio-voleio, dink de backhand, dink com efeito e dink de voleio. */

import { diagrama, desloca, jogador, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const GOLPES_COZINHA = [
  {
    slug: 'meio-voleio',
    version: 1,
    kind: 'fundamento',
    title: 'Meio-voleio: a bola batida logo depois do quique',
    summary: 'O meio-voleio (half volley) é bater a bola baixinha logo depois que ela quica, a poucos centímetros do chão. É a saída para a bola que chega aos pés, na transição ou na rede.',
    objective: 'Ao final, o atleta devolve a bola que chega aos pés com meio-voleio, em gesto curto, e a bola passa baixa e cai na cozinha adversária.',
    skills: ['net.meio_voleio', 'groundstrokes.transicao', 'net.reset'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Na transição, pare em base quando o adversário for bater, com as pernas bem dobradas.',
      'Ao ver a bola vindo aos pés, desça com as pernas e coloque a raquete baixa, perto do chão, com a face levemente aberta, já esperando a bola.',
      'Mantenha a raquete parada na frente do corpo, sem levá-la para trás.',
      'Bata logo depois do quique, a poucos centímetros do chão, com a bola na frente do pé da frente.',
      'Faça um gesto curto de "bloquear e empurrar": a raquete sobe junto com as pernas, sem balanço.',
      'Termine com a raquete apontando o alvo, a cozinha do adversário, e volte à base.',
    ],
    cues: ['Raquete baixa antes de a bola chegar', 'Bloquear e empurrar, sem balanço', 'Raquete termina apontando a cozinha'],
    positioning: [
      { type: 'certo', text: 'Base baixa, raquete na frente perto do chão e contato logo depois do quique: a bola sobe pouco e cai na cozinha.' },
      { type: 'errado', text: 'Pernas esticadas, curvando só as costas para alcançar a bola → a face chega descontrolada e a bola sobe alta ou vai na rede.' },
      { type: 'certo', text: 'Gesto curto, do tamanho de um empurrão, com a raquete subindo junto com as pernas.' },
      { type: 'errado', text: 'Raquete levada para trás num balanço grande → a bola, que já vem rápida do quique, sai longa e vira ataque para o adversário.' },
      { type: 'certo', text: 'Contato na frente do corpo, onde dá para ver a bola encostar na raquete.' },
      { type: 'errado', text: 'Bola deixada passar até o lado ou para trás do corpo → a face abre demais e a bola sobe ou sai pela lateral.' },
    ],
    common_errors: [
      { error: 'A raquete vai para trás antes do golpe, num balanço grande.', fix: 'Deixe a raquete parada e baixa na frente; o golpe é só um empurrão curto para a frente e para cima.' },
      { error: 'O atleta fica em pé e se curva pelas costas para alcançar a bola.', fix: 'Dobre as pernas e desça o corpo inteiro: a cabeça fica perto da altura da bola e as costas ficam retas.' },
      { error: 'A bola passa do corpo e é batida ao lado ou atrás do pé.', fix: 'Antecipe: coloque a raquete onde a bola vai quicar, à frente do pé da frente.' },
      { error: 'A bola sai alta, acima da fita, e o adversário ataca.', fix: 'Face só um pouco aberta e menos força: o quique já dá velocidade, a raquete só direciona.' },
    ],
    when_to_use: 'Na transição do fundo para a rede, quando a bola do adversário cai nos seus pés no meio da quadra e não dá para volear nem esperar ela subir. Também na rede, quando um dink cai no seu pé. A ideia é neutralizar: devolver a bola baixa na cozinha e seguir avançando.',
    motor: {
      phases: {
        preparacao: 'Base baixa, pernas dobradas e a raquete parada perto do chão, com a face levemente aberta.',
        execucao: 'Contato logo depois do quique, na frente do corpo, com um empurrão curto.',
        finalizacao: 'A raquete sobe junto com as pernas e termina apontando a cozinha; volta à base.',
      },
      abilities: ['coordenacao', 'equilibrio', 'precisao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, com aperto leve (3 a 4 de 10): a mão firme demais devolve a bola rápida e longa.' },
        { part: 'olhar', text: 'Na bola até o quique e o contato; a cabeça fica parada na hora do toque.' },
        { part: 'pes', text: 'Parados e afastados no momento do golpe, com o pé da frente mais ou menos apontando o alvo.' },
        { part: 'pernas', text: 'Bem dobradas, como quem vai sentar, deixando a cabeça e a raquete perto da altura da bola; sobem junto com a raquete.' },
        { part: 'braco', text: 'Quase sem movimento para trás; o braço só empurra curto, para a frente e para cima, a partir do ombro.' },
        { part: 'punho', text: 'Firme, sem dobrar: o punho que bate na bola faz ela subir alto ou ir na rede.' },
        { part: 'raquete', text: 'Face levemente aberta, parada perto do chão antes do quique, na frente do pé da frente; termina apontando o alvo.' },
      ],
      self_check: [
        'A bola passou a rede baixa, perto da fita, e caiu na cozinha ou perto dela.',
        'Você viu a bola encostar na raquete na frente do seu corpo.',
        'Depois do golpe você estava equilibrado e conseguiu dar o próximo passo para a frente.',
        'A raquete terminou apontando o alvo, e não lá atrás nem acima da cabeça.',
      ],
    },
    variations: {
      easier: 'Espaço: comece a um passo da linha da cozinha, com o parceiro do outro lado jogando a bola devagar, com a mão, no seu pé.',
      harder: 'Tarefa: comece no meio da quadra; o parceiro, na rede, alterna bolas no pé e na cintura, e você decide entre volear e o meio-voleio, avançando um passo a cada bola.',
    },
    diagrams: [
      diagrama('Certo: do meio da quadra para a cozinha', 'inteira', [
        zona(5, 35, 95, 49, 'Alvo'),
        jogador(30, 32, 'b'),
        jogador(70, 32, 'b'),
        jogador(60, 80, 'a', 'Você'),
        trajeto(30, 34, 59, 78, 'Bola no pé'),
        trajeto(60, 78, 45, 42),
        desloca(62, 84, 62, 70, 'Avança'),
      ], 'certo'),
      diagrama('Errado: balanço grande, bola alta e atacada', 'inteira', [
        jogador(30, 32, 'b'),
        jogador(70, 32, 'b'),
        jogador(60, 80, 'a', 'Você'),
        trajeto(60, 78, 40, 24, 'Alta'),
        zona(15, 18, 55, 33, 'Ataque'),
        trajeto(40, 26, 62, 82, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'dink-de-backhand',
    version: 1,
    kind: 'fundamento',
    title: 'Dink de backhand',
    summary: 'O dink feito com a raquete do lado esquerdo do corpo (para o destro). A mesma ideia do dink de forehand, bola baixa na cozinha, mas com os ombros virados e um gesto mais curto, que sai do ombro.',
    objective: 'Ao final, o atleta faz o dink de backhand cruzado e paralelo com gesto curto do ombro, a bola fazendo o pico do seu lado e caindo na cozinha adversária.',
    skills: ['kitchen.dink_cruzado', 'kitchen.dink_paralelo', 'groundstrokes.backhand'],
    level_min: 2.5,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique na linha da cozinha em prontidão, com a raquete na frente do peito, na empunhadura continental.',
      'Quando a bola vier para o seu lado esquerdo (destro), vire um pouco os ombros: o ombro direito aponta para a rede.',
      'Leve a raquete para o lado esquerdo do corpo, baixa e curta, com a face levemente aberta e o cotovelo perto do corpo.',
      'Deixe a bola chegar à sua frente, um pouco à esquerda, e dobre as pernas para ficar na altura dela.',
      'Toque a bola com um gesto curto que sai do ombro, com o punho firme; as pernas acompanham o gesto, subindo junto.',
      'Termine com a raquete apontando o alvo: a diagonal esquerda (cruzado) ou em frente (paralelo).',
      'Volte de frente para a rede, na base de prontidão.',
    ],
    cues: ['Pico da bola do seu lado', 'Raquete termina apontando o alvo', 'Bola baixa na diagonal esquerda'],
    positioning: [
      { type: 'certo', text: 'Ombro direito virado para a rede e raquete ao lado esquerdo do corpo: a bola é tocada na frente e sai na direção que a raquete aponta.' },
      { type: 'errado', text: 'De frente para a rede, com a raquete cruzada na frente do peito → o gesto fica travado e a bola sai sem direção, muitas vezes alta.' },
      { type: 'certo', text: 'Gesto curto que sai do ombro, com o punho firme e as pernas acompanhando.' },
      { type: 'errado', text: 'Só o punho trabalhando, num tapinha → a altura muda a cada bola: uma vai na rede, a outra sobe para o ataque.' },
      { type: 'certo', text: 'Contato na frente do corpo e um pouco à esquerda, depois do quique.' },
      { type: 'errado', text: 'Bola deixada passar até o lado do corpo ou atrás dele → a face abre demais e a bola sobe ou sai pela lateral.' },
    ],
    common_errors: [
      { error: 'Bater com o punho, num tapinha.', fix: 'Punho firme; o gesto curto sai do ombro, como um pêndulo.' },
      { error: 'Ficar de frente para a rede, com o corpo travado.', fix: 'Antes do golpe, gire um pouco os ombros: o direito aponta para a rede (para o destro).' },
      { error: 'Trocar de empunhadura e ficar com a face virada para o chão.', fix: 'Fique na continental: ela serve para o dink dos dois lados sem trocar a mão.' },
      { error: 'Pernas esticadas, curvando as costas para alcançar a bola baixa.', fix: 'Dobre as pernas e desça até a altura da bola; as costas ficam retas.' },
    ],
    when_to_use: 'Sempre que a bola da troca de dinks vier para o lado esquerdo do corpo (para o destro). Na diagonal esquerda, o dink cruzado de backhand é a troca mais comum; o paralelo serve para mudar o ritmo ou buscar o adversário à sua frente.',
    motor: {
      phases: {
        preparacao: 'Ombros virados, raquete baixa ao lado esquerdo, face levemente aberta e pernas dobradas.',
        execucao: 'Gesto curto do ombro, punho firme, contato na frente; as pernas acompanham.',
        finalizacao: 'A raquete para apontando o alvo e o corpo volta de frente para a rede.',
      },
      abilities: ['precisao', 'coordenacao', 'equilibrio'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, aperto leve: é a mesma do dink de forehand, sem trocar a mão.' },
        { part: 'olhar', text: 'Na bola até o contato; a cabeça fica parada na hora do toque.' },
        { part: 'pes', text: 'Afastados, logo atrás da linha da cozinha; para a bola aberta, um passo lateral com o pé esquerdo.' },
        { part: 'pernas', text: 'Dobradas; sobem no contato e dão a altura da bola.' },
        { part: 'tronco', text: 'Gira um pouco antes do golpe, com o ombro direito para a rede (destro), e volta de frente depois. No forehand esse giro é menor.' },
        { part: 'braco', text: 'Gesto curto e suave, que sai do ombro, com o cotovelo perto do corpo e sem balanço para trás.' },
        { part: 'punho', text: 'Firme, sem dobrar nem chicotear: o punho mexendo muda a altura da bola a cada toque.' },
        { part: 'raquete', text: 'Face levemente aberta, abaixo da bola, terminando apontando o alvo.' },
      ],
      self_check: [
        'A bola fez o ponto mais alto do seu lado da rede e caiu na cozinha.',
        'A raquete terminou apontando o lugar onde a bola caiu.',
        'Você conseguiu repetir a mesma altura em 5 dinks seguidos.',
        'Depois do toque, você voltou de frente para a rede sem perder o equilíbrio.',
      ],
    },
    variations: {
      easier: 'Pessoas: o parceiro joga a bola com a mão, devagar, no seu lado esquerdo, e você faz só o dink paralelo, o mais curto.',
      harder: 'Tarefa: troca de dinks na diagonal esquerda só de backhand, alternando cruzado e paralelo a cada bola, sem a bola subir acima da cintura do parceiro.',
    },
    diagrams: [
      diagrama('Certo: backhand cruzado e paralelo, baixos na cozinha', 'cozinha', [
        zona(5, 35, 95, 49, 'Alvo'),
        jogador(30, 68, 'a', 'Você'),
        jogador(70, 32, 'b'),
        jogador(30, 32, 'b'),
        trajeto(31, 66, 66, 40, 'Cruzado'),
        trajeto(29, 66, 32, 42, 'Paralelo'),
      ], 'certo'),
      diagrama('Errado: corpo de frente, bola alta e atacada', 'cozinha', [
        jogador(30, 68, 'a', 'Você'),
        jogador(70, 32, 'b'),
        trajeto(30, 66, 64, 29, 'Alta'),
        zona(50, 25, 95, 33, 'Ataque'),
        trajeto(68, 30, 32, 66, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'dink-com-efeito',
    version: 1,
    kind: 'fundamento',
    title: 'Dink com efeito: topspin e slice',
    summary: 'O dink com efeito dado pela raquete. Com topspin a bola quica e avança no pé do adversário; com slice ela fica baixa e freia, difícil de atacar. Só depois de dominar o dink sem efeito.',
    objective: 'Ao final, o atleta executa o dink com topspin e com slice, mantendo a bola baixa e na cozinha, e escolhe qual usar pela bola que recebe.',
    skills: ['kitchen.dink_cruzado', 'groundstrokes.efeito', 'kitchen.paciencia'],
    level_min: 3.5,
    players_min: 2,
    players_max: 4,
    duration_min: 15,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Domine primeiro o dink sem efeito: altura e profundidade vêm antes do efeito.',
      'Para o topspin, deixe a raquete abaixo e atrás da bola, com a face quase em pé.',
      'Escove a bola de baixo para cima, raspando a parte de trás dela, com gesto curto e as pernas subindo; a raquete termina um pouco acima do contato, apontando o alvo.',
      'Mire um pouco mais alto sobre a fita que no dink comum: o topspin faz a bola cair mais rápido.',
      'Para o slice, comece com a raquete um pouco acima da altura da bola, com a face aberta.',
      'Deslize a raquete de cima para baixo e para a frente, raspando por baixo da bola, com gesto curto; termine com a raquete na frente, apontando o alvo.',
      'Escolha pelo que chega: bola confortável aceita topspin; bola baixa, no pé, pede slice leve ou o dink sem efeito.',
    ],
    cues: ['Topspin: escove a bola para cima', 'Slice: raquete desliza por baixo', 'Primeiro baixo, depois o efeito'],
    positioning: [
      { type: 'certo', text: 'Topspin numa bola confortável, que quicou na altura da canela ou acima: a bola passa a rede com margem, cai na cozinha e avança no pé do adversário.' },
      { type: 'errado', text: 'Topspin forçado numa bola rente ao chão → sem espaço para escovar de baixo para cima, a raquete bate de frente e a bola vai na rede.' },
      { type: 'certo', text: 'Slice curto, com a face aberta e a raquete terminando na frente: a bola quica baixo e freia.' },
      { type: 'errado', text: 'Slice com gesto grande, cortando com força de cima para baixo → a bola flutua alta e sem peso, pronta para o ataque.' },
      { type: 'certo', text: 'Efeito leve num dink que já sai baixo e cai na cozinha.' },
      { type: 'errado', text: 'Efeito como objetivo, com a bola subindo acima da fita ou caindo fora da cozinha → o efeito não salva uma bola atacável.' },
    ],
    common_errors: [
      { error: 'Escovar tanto a bola que ela mal anda e cai na rede.', fix: 'Mais para a frente que para cima: o efeito é leve e a bola ainda precisa passar a rede com margem.' },
      { error: 'No slice, a raquete corta para o lado do corpo e a bola sai pela lateral.', fix: 'Termine com a raquete na frente, apontando o alvo; o gesto vai para baixo e para a frente.' },
      { error: 'Efeito em toda bola, até nas baixas e difíceis.', fix: 'Na bola no pé, faça o dink sem efeito ou um slice leve; guarde o topspin para a bola confortável.' },
      { error: 'O efeito vem do punho, num chicote.', fix: 'Punho firme; o efeito vem do caminho da raquete (de baixo para cima ou de cima para baixo), com as pernas ajudando.' },
    ],
    when_to_use: 'Na troca de dinks, quando o adversário já devolve bem o dink comum. Topspin na bola confortável, para pressionar e fazer o adversário bater de baixo; slice na bola mais baixa ou para quebrar o ritmo, deixando a bola baixa e lenta. Se a bola chega difícil, o dink simples e baixo continua sendo a escolha.',
    motor: {
      phases: {
        preparacao: 'Raquete abaixo da bola para o topspin, ou acima e com a face aberta para o slice; pernas dobradas.',
        execucao: 'Gesto curto que raspa a bola: de baixo para cima no topspin, de cima para baixo no slice.',
        finalizacao: 'A raquete termina na frente, apontando o alvo, e volta à base.',
      },
      abilities: ['coordenacao', 'precisao', 'leitura'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental, aperto leve: é a mesma do dink comum; só o caminho da raquete muda.' },
        { part: 'olhar', text: 'Na altura da bola que chega: é ela que decide entre topspin, slice ou dink sem efeito.' },
        { part: 'pernas', text: 'Dobradas; no topspin sobem junto com a raquete e ajudam a escovar a bola.' },
        { part: 'braco', text: 'Gesto curto, que sai do ombro: de baixo para cima no topspin; de cima para baixo e para a frente no slice.' },
        { part: 'punho', text: 'Firme: o efeito vem do caminho da raquete, não de uma quebrada do punho.' },
        { part: 'raquete', text: 'No topspin, face quase em pé, raspando atrás da bola de baixo para cima; no slice, face aberta, raspando por baixo, de cima para baixo.' },
      ],
      self_check: [
        'No topspin, a bola girou para a frente e, depois do quique, avançou em direção aos pés do adversário.',
        'No slice, a bola girou para trás e quicou baixo, quase parando.',
        'A bola continuou passando baixa e caindo na cozinha, como no dink sem efeito.',
        'O adversário precisou bater de baixo para cima na maioria das bolas.',
      ],
    },
    variations: {
      easier: 'Tarefa: um efeito por vez, 10 bolas de topspin e depois 10 de slice, numa troca devagar e sem contar pontos.',
      harder: 'Tarefa: o parceiro alterna bolas mais altas e mais baixas; você escolhe o efeito pela bola que recebe e diz "topspin" ou "slice" antes de bater.',
    },
    diagrams: [
      diagrama('Certo: topspin baixo que avança no pé', 'cozinha', [
        zona(5, 35, 95, 49, 'Alvo'),
        jogador(70, 68, 'a', 'Você'),
        jogador(30, 30, 'b'),
        trajeto(70, 66, 36, 40, 'Topspin'),
        trajeto(36, 40, 31, 33, 'Avança'),
      ], 'certo'),
      diagrama('Errado: slice com gesto grande, bola flutua', 'cozinha', [
        jogador(70, 68, 'a', 'Você'),
        jogador(30, 32, 'b'),
        trajeto(70, 66, 33, 29, 'Flutua'),
        zona(15, 25, 50, 33, 'Ataque'),
        trajeto(31, 30, 68, 66, 'Ataque'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'dink-voleio',
    version: 1,
    kind: 'fundamento',
    title: 'Dink de voleio: o dink sem deixar quicar',
    summary: 'O dink tocado no ar, antes de a bola quicar, de pé atrás da linha da cozinha. Tira tempo do adversário e evita a bola que quicaria no seu pé.',
    objective: 'Ao final, o atleta faz o dink de voleio com os dois pés fora da cozinha, gesto curto e a bola caindo na cozinha adversária, sem entrar na cozinha depois do toque.',
    skills: ['kitchen.dink_cruzado', 'net.voleio', 'rules.cozinha'],
    level_min: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Fique de pé logo atrás da linha da cozinha, sem tocar a linha, em prontidão.',
      'Leia a bola cedo: se dá para tocá-la no ar na frente do corpo, sem se curvar nem se esticar para dentro da cozinha, voleie.',
      'Leve a raquete à frente, baixa, com a face aberta, na altura em que a bola vai chegar.',
      'Toque a bola na frente do corpo com um gesto curtíssimo, de "pegar e colocar", quase sem balanço.',
      'Levante a bola só o suficiente para passar a fita e cair na cozinha do adversário.',
      'Fique firme sobre os pés depois do toque: o impulso não pode levar você para dentro da cozinha.',
      'Volte à prontidão, com a raquete na frente do peito.',
    ],
    cues: ['Pegar e colocar', 'Raquete na frente, face aberta', 'Bola de volta na cozinha'],
    positioning: [
      { type: 'certo', text: 'Os dois pés atrás da linha da cozinha, contato na frente do corpo e equilíbrio depois do toque.' },
      { type: 'errado', text: 'Pé na linha da cozinha, ou o corpo caindo para dentro dela depois do voleio → pela regra é falta, e o ponto vai para o adversário.' },
      { type: 'certo', text: 'Bola que chega na sua frente, na altura da canela ou acima: voleie e tire o tempo do adversário.' },
      { type: 'errado', text: 'Volear uma bola baixa demais, que obriga a se curvar e esticar → a bola sobe alta e o impulso leva o corpo para a cozinha.' },
      { type: 'certo', text: 'Bola que vai cair fora, longa ou pela lateral: deixe passar.' },
      { type: 'errado', text: 'Volear a bola que ia sair → o ponto que já era seu volta ao jogo, e se você errar o ponto é do adversário.' },
    ],
    common_errors: [
      { error: 'Depois do voleio, o pé da frente cai dentro da cozinha.', fix: 'Voleie só a bola que dá para tocar de pé, com o peso no meio; se precisar se esticar, deixe quicar e faça o dink comum.' },
      { error: 'Gesto grande, empurrando a bola.', fix: 'O toque é quase sem balanço: a bola já vem com velocidade, a raquete só a coloca de volta.' },
      { error: 'Face fechada, e a bola bate na fita.', fix: 'Face aberta, por baixo da bola, para ela subir só o suficiente.' },
      { error: 'Volear bolas que iam sair.', fix: 'Leia a altura e a profundidade cedo: bola longa ou aberta demais, deixe passar.' },
    ],
    when_to_use: 'Na troca de dinks, quando o dink do adversário vem um pouco mais alto ou mais fundo e você consegue tocar a bola no ar à sua frente, de pé atrás da linha. Não use na bola muito baixa, que obrigaria a se curvar e entrar na cozinha, nem na bola que vai sair.',
    safety: 'Depois do toque, fique sobre os pés: o corpo caindo para a frente, além de falta, desequilibra você perto da rede. Se a bola obriga a se esticar, deixe quicar.',
    motor: {
      phases: {
        preparacao: 'Pés atrás da linha, pernas dobradas, raquete na frente com a face aberta.',
        execucao: 'Toque curtíssimo na frente do corpo, sem balanço.',
        finalizacao: 'O corpo fica parado sobre os pés, fora da cozinha, e volta à prontidão.',
      },
      abilities: ['tempo_reacao', 'equilibrio', 'precisao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Continental e leve: o aperto mole amortece a bola que já vem com velocidade.' },
        { part: 'olhar', text: 'Lê cedo a altura e a profundidade e decide entre volear e deixar quicar antes de a bola passar a rede.' },
        { part: 'pes', text: 'Os dois atrás da linha da cozinha, sem tocar a linha, afastados e firmes; nenhum passo para a frente no toque.' },
        { part: 'pernas', text: 'Dobradas para deixar a raquete na altura da bola sem curvar as costas.' },
        { part: 'tronco', text: 'Fica sobre os pés, com o peso no meio; inclinar para a frente leva o impulso para dentro da cozinha.' },
        { part: 'braco', text: 'Quase parado: o gesto é um toque curto à frente, sem levar a raquete para trás.' },
        { part: 'raquete', text: 'Face aberta, por baixo da bola, encontrando-a na frente do corpo.' },
      ],
      self_check: [
        'Depois do toque, os seus pés continuavam atrás da linha da cozinha, sem tocá-la.',
        'A bola passou baixa e caiu na cozinha do adversário.',
        'O adversário teve de se apressar para chegar à bola.',
        'Você não precisou se curvar nem se esticar para alcançar a bola.',
      ],
    },
    variations: {
      easier: 'Tarefa: o parceiro joga a bola com a mão, devagar, na altura da cintura, e você devolve com dink de voleio para a cozinha.',
      harder: 'Tarefa: troca de dinks em que você voleia toda bola possível e deixa quicar só a muito baixa ou a que vai sair; o parceiro avisa se o seu pé tocou a linha.',
    },
    diagrams: [
      diagrama('Certo: voleio de pé, atrás da linha, de volta à cozinha', 'cozinha', [
        zona(5, 35, 95, 49, 'Alvo'),
        jogador(70, 70, 'a', 'Você'),
        jogador(30, 32, 'b'),
        trajeto(32, 34, 68, 62, 'Dink'),
        trajeto(68, 62, 36, 40, 'Voleio'),
      ], 'certo'),
      diagrama('Errado: o impulso leva para dentro da cozinha', 'cozinha', [
        zona(5, 51, 95, 66, 'Cozinha'),
        jogador(70, 70, 'a', 'Você'),
        jogador(30, 32, 'b'),
        trajeto(32, 34, 66, 60, 'Dink'),
        desloca(70, 69, 68, 61, 'Falta'),
      ], 'errado'),
    ],
    media: [],
  },
];
