/** Biblioteca inicial — GOLPES DE BASE: empunhaduras eastern e western, o olhar na bola, split step e deslocamentos. */

import { diagrama, jogador, trajeto, desloca, zona, texto, bolinha } from './quadra.js';

const QUADRA = ['quadra'];

export const GOLPES_BASE = [
  {
    slug: 'empunhaduras-eastern-e-western',
    version: 2,
    kind: 'fundamento',
    title: 'Empunhaduras eastern e western',
    summary: 'As duas pegadas além da continental: a eastern, o "aperto de mão", boa para o drive e o dink de forehand de quem começa; e a western, por baixo do cabo, para o topspin forte de forehand.',
    objective: 'Ao final, o atleta acha a eastern e a western pelo nó do indicador no cabo, ajusta a pressão da mão ao golpe e volta à continental ao chegar à rede.',
    skills: ['groundstrokes.drive', 'groundstrokes.efeito'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: ['quadra', 'parede'],
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Comece pela continental (o fundamento "Empunhadura continental"): é dela que se chega às outras duas.',
      'Eastern: apoie a palma da mão aberta na face da raquete, deslize até o cabo e feche a mão como num aperto de mão. A palma fica atrás da face que bate o forehand (destro: lado direito).',
      'Confira a eastern pelo cabo: o nó da base do indicador fica na face larga e lateral do cabo, a que é paralela à face da raquete.',
      'Western: gire a mão ainda mais por baixo do cabo, até o nó do indicador ficar na face de baixo. Com o braço estendido à frente, a face da raquete olha para o chão (face fechada).',
      'Ajuste a força da mão numa escala de 1 a 10: entre 3 e 4 no dink e no toque; um pouco mais firme, perto de 5 ou 6, no drive.',
      'Troque de pegada na preparação, com a outra mão segurando o pescoço da raquete e girando o cabo; no contato, a mão já está parada.',
      'Ao chegar à linha da cozinha, volte à continental antes da troca rápida.',
    ],
    cues: ['Face da raquete de frente ao alvo', 'Na rede, volte à continental', 'Raquete leve no dink, firme no drive'],
    positioning: [
      { type: 'certo', text: 'No drive de forehand do fundo, eastern ou western, com a face de frente para o alvo no contato (na western, um pouco fechada): a bola sai firme e com direção.' },
      { type: 'errado', text: 'Na western, tentar um backhand ou um voleio baixo sem trocar a pegada → a face chega fechada demais e a bola vai para a rede.' },
      { type: 'certo', text: 'Na linha da cozinha, raquete já na continental antes de a troca rápida começar.' },
      { type: 'errado', text: 'Ficar na eastern ou na western na rede → o voleio de backhand chega atrasado e a bola sobe, pronta para o ataque do adversário.' },
      { type: 'certo', text: 'Aperto entre 3 e 4 no dink: a raquete amortece e a bola sai macia e curta.' },
      { type: 'errado', text: 'Aperto de 8 ou 9 no dink → a raquete não amortece nada, a bola sai rápida e passa da cozinha.' },
    ],
    common_errors: [
      { error: 'Achar que está na eastern, mas a mão está por baixo do cabo, como quem segura uma frigideira.', fix: 'Confira o nó do indicador: na eastern ele fica na face lateral do cabo, paralela à face da raquete; por baixo já é a western.' },
      { error: 'Trocar de pegada no meio do golpe.', fix: 'A troca acontece na preparação, com a outra mão girando o cabo pelo pescoço da raquete; no contato a mão está parada.' },
      { error: 'Apertar forte o tempo todo.', fix: 'Relaxe a mão entre as bolas e aperte um pouco mais só no drive.' },
      { error: 'Jogar tudo na western e ficar sem backhand.', fix: 'Use a western só no forehand de fundo; para o backhand e para a rede, volte à continental.' },
    ],
    when_to_use: 'Eastern: drive e dink de forehand para quem está começando e acha a continental estranha; serve também no saque. Western: forehand de fundo com topspin forte, para quem já domina o golpe. Na rede, nas trocas rápidas, a continental segue sendo a base.',
    motor: {
      phases: {
        preparacao: 'Na espera, mão na continental e a outra mão no pescoço da raquete.',
        execucao: 'Na preparação do drive, a outra mão gira o cabo para a eastern ou a western e solta antes do golpe.',
        finalizacao: 'Depois do golpe, a mão relaxa e volta à continental para a próxima bola.',
      },
      abilities: ['coordenacao', 'precisao'],
    },
    technique: {
      checkpoints: [
        { part: 'empunhadura', text: 'Eastern: nó do indicador na face lateral do cabo, palma atrás da face. Western: nó do indicador na face de baixo do cabo, mão por baixo.' },
        { part: 'olhar', text: 'Olhe o cabo só para conferir a pegada no começo; depois a referência é o tato, e os olhos ficam na bola.' },
        { part: 'braco', text: 'Solto, sem travar; com a mão apertando demais, o braço trava junto e o golpe perde velocidade.' },
        { part: 'punho', text: 'Na eastern, alinhado e firme no contato; na western, mais por baixo do cabo, o que ajuda a escovar a bola de baixo para cima.' },
        { part: 'raquete', text: 'No contato do forehand, de frente para o alvo na eastern e um pouco fechada na western, que pede gesto de baixo para cima para a bola passar a rede.' },
      ],
      self_check: [
        'Na eastern, com a raquete de lado, a palma e a face apontam para o mesmo lugar.',
        'Na western, com o braço à frente, a face da raquete olha para o chão.',
        'No dink, a bola sai macia e cai curta; se sai rápida, a mão está apertando demais.',
        'Na rede, o voleio de backhand chega a tempo: sinal de que você voltou à continental.',
      ],
    },
    variations: {
      easier: 'Tarefa: só eastern e só forehand, drive do fundo com a bola lançada pelo parceiro com a mão.',
      harder: 'Tarefa: drive do fundo na eastern ou na western e, ao avançar, um voleio na continental, trocando a pegada no caminho.',
    },
    diagrams: [
      diagrama('Fundo: eastern ou western no drive. Rede: continental', 'meia', [
        zona(0, 50, 100, 66, 'Continental'),
        zona(0, 78, 100, 100, 'Eastern'),
        jogador(30, 94, 'a'),
        trajeto(30, 92, 40, 44, 'Drive'),
        jogador(70, 64, 'a'),
        texto(70, 72, 'Troca aqui'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'olhar-na-bola',
    version: 1,
    kind: 'fundamento',
    title: 'Ver a bola até a raquete',
    summary: 'Ler a bola já na raquete do adversário e seguir com os olhos até ela tocar a sua, com a cabeça parada no contato. É o que faz o golpe sair limpo e o primeiro passo sair na hora.',
    objective: 'Ao final, o atleta diz a altura e o efeito da bola adversária antes de ela passar a rede e mantém a cabeça parada, com os olhos no ponto de contato, até depois do toque.',
    skills: ['tactics.leitura_adversario', 'mental.foco'],
    level_min: 2.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Antes de o adversário bater, olhe para a raquete dele, não para o rosto nem para a quadra.',
      'No toque dele, leia três coisas: a altura (alta ou baixa), o efeito (girando para a frente, para trás ou sem giro) e a direção (para você ou para o parceiro).',
      'Só então mova os pés: primeiro olhe, depois mova.',
      'Siga a bola com os olhos no voo e no quique, sem desviar para o alvo.',
      'No contato, mantenha a cabeça parada e os olhos no ponto em que a bola encontra a raquete, até um instante depois do toque.',
      'Só depois do golpe levante a cabeça para ver para onde a bola foi e volte à base.',
    ],
    cues: ['Leia a raquete do adversário', 'Bola até a face da raquete', 'Primeiro ver, depois mover'],
    positioning: [
      { type: 'certo', text: 'Cabeça parada no contato, olhos no ponto de toque: a bola pega no meio da raquete.' },
      { type: 'errado', text: 'Levantar a cabeça para ver o alvo antes de bater → a raquete acompanha a cabeça, a bola pega na borda e sai sem direção ou vai para a rede.' },
      { type: 'certo', text: 'Olhar para a raquete do adversário no golpe dele: a altura e o efeito aparecem ali.' },
      { type: 'errado', text: 'Olhar para o rosto dele, ou ver a bola só quando ela já passou a rede → a leitura chega tarde e o primeiro passo atrasa.' },
      { type: 'certo', text: 'Ler a bola e então sair com um passo firme na direção dela.' },
      { type: 'errado', text: 'Sair correndo antes de ver a bola sair → ela vai para o outro lado e você precisa voltar.' },
    ],
    common_errors: [
      { error: 'A cabeça sobe junto com a raquete na finalização.', fix: 'Conte "um" com os olhos no ponto de contato depois do toque; só então levante a cabeça.' },
      { error: 'Na rede, olhar para o adversário em vez da bola na troca rápida.', fix: 'Foque a raquete dele e a bola; o corpo do adversário fica na visão de canto.' },
      { error: 'Fechar os olhos ou virar o rosto na bola rápida no corpo.', fix: 'Treine com a bola lenta no corpo e aumente a velocidade aos poucos, de olhos abertos até o bloqueio.' },
      { error: 'Ler só a velocidade e ignorar o efeito.', fix: 'Olhe o gesto: raquete de baixo para cima dá topspin, a bola cai e pula para a frente; face aberta cortando por baixo dá slice, a bola quica baixa e escorrega.' },
    ],
    when_to_use: 'Em todo golpe. Mais ainda na devolução do saque (para ler o efeito), nas trocas rápidas na rede e na bola difícil, quando a vontade de olhar o alvo antes da hora é maior.',
    safety: 'Bola rápida no rosto pode machucar o olho. Na rede, use óculos de proteção esportivos e, no treino de bola no corpo, combine com o parceiro começar devagar.',
    motor: {
      phases: {
        preparacao: 'Olhos na raquete do adversário quando ele bate.',
        execucao: 'Os olhos seguem a bola até a raquete; a cabeça fica parada no contato.',
        finalizacao: 'Só depois do toque a cabeça sobe para ver a bola e o corpo volta à base.',
      },
      abilities: ['leitura', 'tempo_reacao', 'coordenacao'],
    },
    technique: {
      checkpoints: [
        { part: 'olhar', text: 'Na raquete do adversário no golpe dele; depois na bola, no voo e no quique, até a sua raquete.' },
        { part: 'pes', text: 'Quietos até a leitura; o primeiro passo sai na direção que a bola mostrou.' },
        { part: 'tronco', text: 'Gira para o golpe sem levar a cabeça junto: a cabeça é o eixo parado.' },
        { part: 'braco', text: 'Termina o golpe enquanto a cabeça ainda aponta para o ponto de contato.' },
        { part: 'raquete', text: 'Encontra a bola na frente do corpo, no ponto que os olhos acompanharam; com a cabeça parada, o toque sai no meio da face.' },
      ],
      self_check: [
        'Você diz se a bola vem alta ou baixa, e com que efeito, antes de ela passar a rede.',
        'O som do toque é limpo e a bola não pega na borda da raquete.',
        'Depois do golpe, a cabeça ainda aponta para o ponto de contato por um instante.',
        'O primeiro passo vai para o lado certo, sem precisar voltar.',
      ],
    },
    variations: {
      easier: 'Tarefa: o parceiro lança a bola com a mão e você diz "alta" ou "baixa" antes de bater.',
      harder: 'Tarefa: na troca de dinks, o parceiro varia entre bola com e sem efeito; diga o efeito em voz alta antes do quique.',
    },
    diagrams: [
      diagrama('Certo: lê na raquete dele, olha a bola até a sua', 'cozinha', [
        jogador(30, 32, 'b'),
        texto(30, 26, 'Leia aqui'),
        trajeto(31, 34, 68, 64),
        jogador(70, 68, 'a'),
        bolinha(68, 64),
        texto(70, 74, 'Olhos aqui'),
      ], 'certo'),
      diagrama('Errado: olha o alvo antes do toque', 'cozinha', [
        jogador(30, 32, 'b'),
        trajeto(31, 34, 68, 64),
        jogador(70, 68, 'a'),
        zona(55, 26, 95, 40, 'Olhou aqui'),
        texto(70, 74, 'Na borda'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'split-step',
    version: 1,
    kind: 'fundamento',
    title: 'Split step: o pequeno salto antes do golpe do adversário',
    summary: 'Um saltinho que aterrissa com os pés afastados no instante em que o adversário toca a bola. Deixa o corpo pronto para sair rápido para qualquer lado, na rede e na subida para ela.',
    objective: 'Ao final, o atleta aterrissa do split step no instante em que o adversário toca a bola, com os pés afastados e a raquete na frente, e sai para o lado certo no passo seguinte.',
    skills: ['physical.agilidade', 'groundstrokes.transicao'],
    level_min: 2.5,
    players_min: 1,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Acompanhe a raquete do adversário: quem marca o salto é o golpe dele.',
      'Quando a raquete dele começar a vir para a frente, dê um saltinho de poucos centímetros, quase sem tirar os pés do chão.',
      'Aterrisse no instante do toque dele, na parte da frente dos pés, com os pés afastados na largura dos ombros ou um pouco mais e os joelhos dobrados.',
      'Mantenha a raquete na frente do corpo, pronta para os dois lados.',
      'Leia a bola e saia com o primeiro passo para o lado dela.',
      'Na subida para a rede, pare no split step toda vez que o adversário for bater, mesmo no meio da quadra.',
      'Depois do seu golpe, volte a avançar e repita o split no toque seguinte dele.',
    ],
    cues: ['Aterrisse no toque do adversário', 'Raquete na frente, pés prontos', 'Ele bate, você para'],
    positioning: [
      { type: 'certo', text: 'Aterrissar no instante em que o adversário toca a bola, com a base larga e baixa.' },
      { type: 'errado', text: 'Saltar cedo demais e já estar parado, de pernas esticadas, quando ele bate → o corpo perde a mola e o primeiro passo sai lento.' },
      { type: 'certo', text: 'Na transição, avançar e parar no split step quando o adversário bate.' },
      { type: 'errado', text: 'Seguir correndo enquanto ele bate → a bola chega nos pés e você não consegue mudar de direção.' },
      { type: 'certo', text: 'Salto baixo, de poucos centímetros, só para carregar a mola.' },
      { type: 'errado', text: 'Saltar alto e ainda estar no ar quando a bola sai da raquete dele → ela já está no meio do caminho quando você consegue sair.' },
    ],
    common_errors: [
      { error: 'Ainda estar no ar quando a bola sai da raquete do adversário.', fix: 'Comece a subir quando a raquete dele vem para a frente: é a aterrissagem, não o salto, que coincide com o toque.' },
      { error: 'Pés juntos na aterrissagem.', fix: 'Aterrisse com os pés mais afastados do que estavam antes do salto: base larga muda de direção mais rápido.' },
      { error: 'Aterrissar nos calcanhares.', fix: 'Aterrisse na parte da frente dos pés, joelhos dobrados e peso um pouco à frente.' },
      { error: 'Esquecer o split na subida para a rede.', fix: 'Combine com o parceiro: toda vez que o adversário bate, os dois param e fazem o split.' },
    ],
    when_to_use: 'Em todo golpe do adversário: na rede, antes de cada voleio e dink, e principalmente na transição, quando se sobe do fundo para a cozinha.',
    motor: {
      phases: {
        preparacao: 'Base em movimento e olhos na raquete do adversário.',
        execucao: 'Saltinho baixo e aterrissagem na parte da frente dos pés, base larga, no toque dele.',
        finalizacao: 'Primeiro passo na direção da bola, com a raquete pronta.',
      },
      abilities: ['agilidade', 'tempo_reacao', 'equilibrio', 'leitura'],
    },
    technique: {
      checkpoints: [
        { part: 'olhar', text: 'Na raquete do adversário: é o golpe dele que marca o salto.' },
        { part: 'pes', text: 'Aterrissam juntos no tempo, na parte da frente, afastados na largura dos ombros ou um pouco mais.' },
        { part: 'pernas', text: 'Dobradas na aterrissagem, como uma mola carregada para sair para qualquer lado.' },
        { part: 'tronco', text: 'Um pouco inclinado à frente, com o peso sobre a frente dos pés.' },
        { part: 'raquete', text: 'Na frente do corpo, na altura do peito, entre o forehand e o backhand.' },
      ],
      self_check: [
        'Os dois pés tocam o chão juntos, no mesmo instante em que se ouve a bola na raquete do adversário.',
        'O primeiro passo sai sem um passinho de ajuste antes.',
        'Na subida para a rede, a bola nunca chega enquanto você ainda está correndo.',
      ],
    },
    variations: {
      easier: 'Tarefa: sem bola, o parceiro faz o gesto do golpe e você aterrissa o split no gesto dele.',
      harder: 'Tarefa: suba do fundo para a cozinha em etapas, com o split em cada golpe do parceiro, que manda a bola ora para um lado, ora para o outro.',
    },
    diagrams: [
      diagrama('Certo: avança e para no split quando o adversário bate', 'inteira', [
        jogador(30, 32, 'b'),
        jogador(55, 96, 'a'),
        desloca(55, 94, 55, 80, 'Avança'),
        texto(72, 80, 'Split'),
        trajeto(31, 34, 54, 78),
      ], 'certo'),
      diagrama('Errado: correndo quando o adversário bate', 'inteira', [
        jogador(30, 32, 'b'),
        jogador(55, 96, 'a'),
        desloca(55, 94, 55, 70, 'Correndo'),
        trajeto(31, 34, 56, 80),
        texto(75, 82, 'Bola no pé'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'deslocamento-lateral',
    version: 1,
    kind: 'fundamento',
    title: 'Deslocamento lateral: passos curtos de lado',
    summary: 'Como andar de lado sem perder o equilíbrio: passo lateral sem cruzar os pés para a bola perto, passo cruzado para a bola longe e a dupla se movendo junta na cozinha.',
    objective: 'Ao final, o atleta chega à bola de lado com passos curtos, bate parado e equilibrado, volta ao centro da sua metade e se move junto com o parceiro na linha da cozinha.',
    skills: ['physical.agilidade', 'doubles.posicionamento'],
    level_min: 2.0,
    players_min: 1,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Parta da posição de prontidão: base larga, joelhos dobrados, raquete na frente.',
      'Bola perto (um ou dois passos): passo lateral. O pé do lado da bola sai primeiro e o outro vem atrás, sem os pés se cruzarem nem se baterem.',
      'Bola longe: o primeiro passo é cruzado (o pé de fora passa na frente do outro) e depois passos laterais curtos para ajustar.',
      'Mantenha a mesma altura: a cabeça não sobe e desce enquanto você anda de lado.',
      'Chegue antes da bola e firme os pés para bater parado.',
      'Depois do golpe, volte com passos laterais ao centro da sua metade.',
      'Na cozinha, ande junto com o parceiro, como se uma corda ligasse os dois: se ele vai para a lateral, você fecha o meio.',
    ],
    cues: ['Raquete na frente enquanto anda', 'Chegue parado na bola', 'Ande junto, como uma corda'],
    positioning: [
      { type: 'certo', text: 'Passo lateral com a base larga e a raquete na frente: o corpo chega equilibrado e bate parado.' },
      { type: 'errado', text: 'Cruzar os pés para a bola perto → o corpo chega torto, bate desequilibrado e demora para voltar.' },
      { type: 'certo', text: 'A dupla se move junta: quando um vai para a lateral, o outro fecha o meio.' },
      { type: 'errado', text: 'Um vai para a lateral e o outro fica parado → abre um buraco no meio e a bola passa entre os dois.' },
      { type: 'certo', text: 'Depois do golpe, voltar ao centro da sua metade.' },
      { type: 'errado', text: 'Ficar parado na lateral depois de bater → o adversário joga no espaço que ficou aberto.' },
    ],
    common_errors: [
      { error: 'Andar de lado de pernas esticadas, com a cabeça subindo e descendo.', fix: 'Joelhos dobrados e a mesma altura do começo ao fim, como se houvesse um teto baixo.' },
      { error: 'Esticar o braço para alcançar a bola em vez de mover os pés.', fix: 'Leve os pés até a bola, para a raquete bater na frente do corpo.' },
      { error: 'Bater ainda andando.', fix: 'Último passo firme e corpo parado no contato.' },
      { error: 'Passos grandes e lentos.', fix: 'Passos curtos e rápidos: ajustam melhor a distância até a bola.' },
    ],
    when_to_use: 'Na linha da cozinha, para os dinks que vão para os lados e para acompanhar o parceiro; no fundo, para chegar à bola que vem para o lado e para voltar ao centro depois de cada golpe.',
    motor: {
      phases: {
        preparacao: 'Posição de prontidão: base larga e raquete na frente.',
        execucao: 'Passos laterais curtos, ou um cruzado para a bola longe, e chegada com os pés firmes.',
        finalizacao: 'Golpe equilibrado e volta ao centro com passos laterais.',
      },
      abilities: ['agilidade', 'equilibrio', 'coordenacao'],
    },
    technique: {
      checkpoints: [
        { part: 'olhar', text: 'Na bola: o deslocamento começa quando você vê para que lado ela vai.' },
        { part: 'pes', text: 'Passos curtos, sem cruzar na bola perto; um passo cruzado só para a bola longe.' },
        { part: 'pernas', text: 'Dobradas e afastadas o tempo todo, para a altura não mudar.' },
        { part: 'tronco', text: 'De frente para a rede no passo lateral; gira para o golpe só na chegada.' },
        { part: 'raquete', text: 'Na frente do corpo durante todo o deslocamento, pronta para bater.' },
      ],
      self_check: [
        'Você chega à bola com tempo de parar antes de bater.',
        'Depois do golpe, já está de volta ao centro quando o adversário bate.',
        'Na cozinha, a distância para o parceiro fica parecida de um lado ao outro.',
      ],
    },
    variations: {
      easier: 'Espaço: só meia linha da cozinha, ida e volta de lado entre dois cones, sem bola.',
      harder: 'Tarefa: dinks com o parceiro mandando para os dois lados; a cada bola, volte ao cone do centro antes do próximo dink.',
    },
    diagrams: [
      diagrama('Certo: a dupla anda junta, como uma corda', 'cozinha', [
        jogador(20, 32, 'b'),
        trajeto(21, 34, 92, 64),
        jogador(75, 68, 'a'),
        desloca(75, 70, 90, 70, 'Lateral'),
        jogador(35, 68, 'a'),
        desloca(35, 70, 55, 70, 'Fecha meio'),
      ], 'certo'),
      diagrama('Errado: o parceiro fica parado e abre o meio', 'cozinha', [
        jogador(20, 32, 'b'),
        jogador(75, 68, 'a'),
        desloca(75, 70, 90, 70, 'Lateral'),
        jogador(35, 68, 'a'),
        zona(45, 60, 70, 75, 'Buraco'),
        trajeto(21, 34, 58, 70),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'avancar-e-recuar',
    version: 1,
    kind: 'fundamento',
    title: 'Avançar para a rede e recuar com segurança',
    summary: 'Como subir do fundo para a cozinha em etapas, parando quando o adversário bate, e como voltar para buscar o lob virando de lado, nunca andando de costas.',
    objective: 'Ao final, o atleta chega à linha da cozinha em etapas, parado em split step em cada golpe do adversário, e recua para o lob virando de lado, sem nenhum passo de costas.',
    skills: ['groundstrokes.transicao', 'physical.agilidade', 'groundstrokes.lob'],
    level_min: 2.5,
    players_min: 2,
    players_max: 4,
    duration_min: 15,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'raquete'],
    practice_mode: 'bloco',
    steps: [
      'Depois do seu golpe do fundo (a devolução ou um drop baixo), avance alguns passos para a frente.',
      'Quando o adversário for bater, pare num split step, onde estiver.',
      'Bata a bola parado; se ela vier baixa no meio da quadra, devolva com um bloqueio ou um reset para a cozinha.',
      'Avance de novo e repita até chegar à linha da cozinha.',
      'Se vier um lob por cima de você, gire o corpo de lado para a rede, virado para o lado da bola, e recue com passos laterais ou cruzados, olhando a bola.',
      'Se chegar atrás e embaixo da bola, bata de lado (smash); se ela já passou, deixe quicar e devolva alta e funda para ganhar tempo.',
      'Depois, volte para a frente em etapas, como no começo.',
    ],
    cues: ['Ele bate, você para', 'Bata parado, avance depois', 'Lob: de lado, olhos na bola'],
    positioning: [
      { type: 'certo', text: 'Avançar em etapas e estar parado, em split step, quando o adversário bate.' },
      { type: 'errado', text: 'Bater correndo no meio da quadra → a bola sai alta ou para na rede e o adversário ataca os seus pés.' },
      { type: 'certo', text: 'Recuar para o lob virando de lado, com passos laterais ou cruzados, olhando a bola.' },
      { type: 'errado', text: 'Andar de costas para trás olhando para cima → o pé engancha, você cai de costas e pode bater a cabeça no chão.' },
      { type: 'certo', text: 'Sem conseguir chegar atrás da bola, deixar quicar e devolver alto e fundo.' },
      { type: 'errado', text: 'Insistir no smash já passado da bola → o golpe sai sem força ou para fora e você termina desequilibrado.' },
    ],
    common_errors: [
      { error: 'Correr direto do fundo para a rede depois de qualquer bola.', fix: 'Só avance depois de uma bola que o adversário não pode atacar; se ela subiu, fique e defenda.' },
      { error: 'Parar no meio da quadra e ficar ali.', fix: 'Use o meio da quadra só como parada: bata e continue avançando.' },
      { error: 'Andar de costas para buscar o lob.', fix: 'Primeiro gire o corpo de lado; depois corra com passos laterais ou cruzados.' },
      { error: 'Perder a bola de vista no recuo.', fix: 'Olhe a bola por cima do ombro durante todo o recuo e aponte para ela com a mão livre.' },
    ],
    when_to_use: 'Avançar: depois da devolução do saque, de um drop baixo na terceira bola ou de qualquer bola que o adversário não pode atacar. Recuar: quando o adversário levanta um lob por cima de você na rede.',
    safety: 'Andar de costas para trás é o jeito mais comum de cair de costas na quadra e bater a cabeça ou apoiar a mão no chão. Para buscar o lob, vire sempre de lado e corra; se a bola passou longe, deixe-a e chame o parceiro. Tênis com boa aderência e quadra seca reduzem o risco.',
    motor: {
      phases: {
        preparacao: 'Depois do golpe do fundo, olhos no adversário e passos para a frente.',
        execucao: 'Split step em cada golpe dele, golpe parado e novo avanço; no lob, giro de lado e recuo com passos laterais ou cruzados.',
        finalizacao: 'Chegada à linha da cozinha em posição de prontidão, ou golpe de lado no lob e volta para a frente.',
      },
      abilities: ['agilidade', 'equilibrio', 'leitura', 'tempo_reacao'],
    },
    technique: {
      checkpoints: [
        { part: 'olhar', text: 'Na raquete do adversário ao avançar; no lob, na bola o tempo todo, por cima do ombro.' },
        { part: 'pes', text: 'Passos curtos na subida e parada em split step; no recuo, o primeiro passo é para trás e para o lado, girando o corpo.' },
        { part: 'pernas', text: 'Dobradas em cada parada, prontas para a bola baixa nos pés.' },
        { part: 'tronco', text: 'De frente para a rede na subida; de lado para a rede no recuo.' },
        { part: 'braco', text: 'No recuo, a mão livre aponta para a bola e a raquete já sobe para trás da cabeça.' },
        { part: 'raquete', text: 'Na frente e baixa ao avançar, pronta para o bloqueio da bola nos pés no meio da quadra.' },
      ],
      self_check: [
        'Em cada golpe do adversário você está parado, nunca correndo.',
        'Você chega à linha da cozinha em duas ou três etapas, sem bater correndo.',
        'No recuo, os pés passam de lado e você nunca dá um passo de costas.',
        'Você enxerga a bola durante todo o recuo.',
      ],
    },
    variations: {
      easier: 'Tarefa: sem bola, o parceiro faz o gesto do golpe; você avança e para no split a cada gesto, até a cozinha.',
      harder: 'Tarefa: suba até a cozinha em etapas; a qualquer momento o parceiro levanta um lob lento e você recua de lado, devolve e volta para a frente.',
    },
    diagrams: [
      diagrama('Certo: sobe em etapas, parando quando o adversário bate', 'inteira', [
        jogador(30, 32, 'b'),
        jogador(60, 96, 'a'),
        desloca(60, 94, 60, 82),
        texto(80, 82, 'Para 1'),
        desloca(60, 80, 60, 70),
        texto(80, 70, 'Para 2'),
        jogador(60, 67, 'a'),
      ], 'certo'),
      diagrama('Errado: corre direto e é pego no meio da quadra', 'inteira', [
        jogador(30, 32, 'b'),
        jogador(60, 96, 'a'),
        desloca(60, 94, 60, 70, 'Correndo'),
        trajeto(31, 34, 61, 78),
        texto(80, 80, 'Bola no pé'),
      ], 'errado'),
    ],
    media: [],
  },
];
