/**
 * Biblioteca importada — nível 3 do pacote "100 drills" (drills 41 a 60),
 * avaliados um a um. Ficaram só os que eram corretos, relevantes e diferentes
 * do que a biblioteca já tinha; os textos foram reescritos e corrigidos.
 */

import { cone, desloca, diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const IMPORTADOS_NIVEL3 = [
  {
    slug: 'terceira-bola-drop-ou-drive-anunciado',
    version: 1,
    kind: 'drill',
    title: 'Drop ou drive: decidir e anunciar a terceira bola',
    summary: 'O parceiro devolve bolas fundas ou curtas e depois sobe ou fica no meio. Você fala "drop" ou "drive" antes de bater. Treina a decisão da terceira bola, não só o golpe.',
    objective: 'Ao final, o atleta consegue escolher entre drop e drive pela bola e pela posição do adversário, acertando a decisão em 24 de 30 terceiras bolas.',
    skills: ['tactics.selecao_golpe', 'groundstrokes.terceira_bola_drop', 'groundstrokes.terceira_bola_drive', 'tactics.leitura_adversario'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    roles: ['Devolvedor', 'Executor'],
    duration_min: 12,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'aleatorio',
    setup: 'O executor fica atrás da linha de fundo, como quem acabou de sacar. O devolvedor fica atrás da linha de fundo do outro lado, com o cesto. Ele manda a devolução e, logo depois, escolhe: avança até a linha da cozinha ou para no meio da quadra. A regra da decisão: bola funda ou baixa, ou adversário já na cozinha, pede drop; bola curta e na altura da cintura, com você parado e o adversário ainda no meio da quadra, pede drive nos pés dele.',
    steps: [
      'O devolvedor manda a bola variando: umas fundas e baixas, outras curtas e mais altas.',
      'Logo depois de bater, ele avança até a cozinha ou para no meio da quadra, sem avisar.',
      'O executor olha a bola e o devolvedor e fala "drop" ou "drive" assim que a bola quica do seu lado.',
      'Drop: bola em arco que cai na cozinha. Drive: bola firme e baixa nos pés do devolvedor.',
      'O devolvedor diz se a escolha combinou com a situação; a bola não é jogada.',
      'Contem as decisões certas e os golpes que saíram como foram anunciados; depois de 30 bolas, troquem.',
    ],
    cues: ['Bola baixa ou funda: drop', 'Bola curta e alta: drive', 'Veja onde o devolvedor parou', 'Fale antes de a raquete voltar'],
    positioning: [
      { type: 'certo', text: 'Antes de bater, você já viu duas coisas: a altura e a profundidade da bola e onde o adversário está.' },
      { type: 'certo', text: 'Raquete preparada cedo e pés parados quando a bola chega, seja para o drop, seja para o drive.' },
      { type: 'errado', text: 'Decidir pelo golpe de que mais gosta: drive de bola baixa sai para cima e vira bola fácil para quem está na rede.' },
    ],
    common_errors: [
      { error: 'A palavra sai no meio do golpe, quando a decisão já foi tomada pelo corpo.', fix: 'Fale quando a bola quica do seu lado, antes de a raquete ir para trás.' },
      { error: 'Drive em bola funda e baixa, batido de baixo para cima.', fix: 'Bola que obriga a bater para cima pede drop; deixe o drive para a bola curta, na altura da cintura.' },
      { error: 'Drop sempre, mesmo com o devolvedor parado no meio da quadra.', fix: 'Adversário ainda no meio é alvo de drive nos pés: olhe para ele antes de olhar para a bola.' },
      { error: 'Anunciar um golpe e bater outro.', fix: 'Mudou de ideia, a bola não conta: repita e decida mais cedo.' },
    ],
    variations: {
      easier: 'Tarefa: o devolvedor anuncia antes de bater se a devolução vai ser funda ou curta, e você só executa; depois, séries só de bolas fundas (drop) e só de curtas (drive).',
      harder: 'Pessoas: 2 contra 2, com o ponto jogado depois da terceira bola; decisão certa com golpe certo vale 2 pontos. Em jogo, a palavra fica só na cabeça.',
    },
    metric: { type: 'percentual', target: '24 de 30 decisões certas' },
    success_criteria: 'Conta a bola em que a decisão combinou com a situação e o golpe saiu como anunciado. 24 de 30 em duas séries? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Base aberta e raquete preparada cedo, olhando a bola e o adversário ao mesmo tempo.',
        execucao: 'Decisão falada no quique; drop com gesto de baixo para cima, drive com gesto firme e bola baixa sobre a rede.',
        finalizacao: 'Depois do drop, avance; depois do drive, prepare-se para a bola que volta rápida.',
      },
      abilities: ['leitura', 'precisao', 'tempo_reacao'],
    },
    when_to_use: 'Toda terceira bola da dupla que sacou: é a decisão que define se você chega à cozinha ou fica preso no fundo.',
    diagrams: [
      diagrama('Ler a bola e o devolvedor', 'inteira', [
        jogador(50, 96, 'a', 'Exec'),
        jogador(50, 4, 'b', 'Dev'),
        trajeto(50, 6, 56, 88, '1'),
        desloca(50, 7, 50, 30, 'sobe?'),
        zona(15, 35, 85, 49, 'Drop'),
        trajeto(52, 94, 44, 42, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'drop-com-topspin-roll-drop',
    version: 1,
    kind: 'drill',
    title: 'Drop com topspin (roll drop)',
    summary: 'O drop feito escovando a bola de baixo para cima: ela passa a rede com mais folga e mergulha na cozinha. Para quem já tem o drop sem efeito e quer uma segunda versão.',
    objective: 'Ao final, o atleta consegue colocar 10 de 12 drops com topspin na cozinha, de forehand e de backhand, primeiro do meio e depois do fundo da quadra.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.transicao'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 4,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'bloco',
    setup: 'O alimentador fica na linha da cozinha com o cesto e manda bolas fundas e fáceis. O executor começa no meio da quadra (zona de transição), onde o golpe é mais curto, e só recua para a linha de fundo depois de fechar a meta. Alvo: a cozinha do alimentador.',
    steps: [
      'O alimentador manda uma bola funda e fácil para o executor.',
      'Deixe a bola passar do ponto mais alto e começar a descer; bata na frente do corpo, entre o joelho e a cintura.',
      'A raquete começa abaixo da bola e sobe escovando a parte de trás dela, num gesto curto, mais para cima do que para a frente.',
      'A bola passa a rede com um pouco mais de folga que o drop sem efeito e mergulha dentro da cozinha.',
      '12 bolas de forehand e 12 de backhand; contem as que quicam na cozinha.',
      'Fechou 10 de 12 dos dois lados? Recue para a linha de fundo e repita.',
    ],
    cues: ['Raquete de baixo para cima', 'Escove a parte de trás da bola', 'Espere a bola começar a descer', 'Bola mergulha dentro da cozinha'],
    positioning: [
      { type: 'certo', text: 'Raquete abaixo da bola antes do contato, base equilibrada e a bola na frente do corpo.' },
      { type: 'errado', text: 'Raquete por cima da bola, empurrando para baixo: a bola sai sem efeito, ou com efeito para trás, e flutua.' },
    ],
    common_errors: [
      { error: 'O gesto vai de cima para baixo e a bola flutua ou morre na rede.', fix: 'Comece a raquete abaixo da bola e termine acima dela: o topspin nasce da raquete subindo.' },
      { error: 'A bola sai alta e passa da cozinha.', fix: 'Gesto mais curto e mais vertical; o topspin pede velocidade para cima, não força para a frente.' },
      { error: 'Batida na subida da bola, cedo demais.', fix: 'Espere a bola passar do ponto mais alto; batida cedo deixa a bola subir.' },
      { error: 'O drop sem efeito ainda sai irregular e você já está no topspin.', fix: 'Consolide primeiro o drop empurrado; o topspin aumenta o erro de quem ainda deixa a bola subir.' },
    ],
    variations: {
      easier: 'Equipamento: o alimentador lança com a mão bolas lentas para o meio da quadra; meta de 7 de 12. Sozinho: contra a parede, com uma fita na altura da rede.',
      harder: 'Tarefa: quando a bola quica, o alimentador grita "empurrado" ou "topspin"; alterne os dois drops sem perder a cozinha. Quem domina os dois esconde a intenção e escolhe o topspin quando é empurrado para o fundo.',
    },
    metric: { type: 'percentual', target: '10 de 12 na cozinha' },
    success_criteria: 'Conta o drop com efeito para a frente que quica na cozinha. 10 de 12 dos dois lados, do meio e do fundo? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Raquete baixa e preparada cedo, pernas dobradas, bola na frente do corpo.',
        execucao: 'Gesto curto de baixo para cima, escovando a parte de trás da bola, com as pernas subindo junto.',
        finalizacao: 'A raquete termina alta, à frente do corpo; dê os passos para a frente e pare antes do próximo golpe.',
      },
      abilities: ['precisao', 'coordenacao', 'ritmo'],
    },
    when_to_use: 'Terceira bola contra uma devolução funda que empurrou você para trás, e para variar o drop quando o adversário já leu o seu drop sem efeito.',
    diagrams: [
      diagrama('Do meio, depois do fundo', 'inteira', [
        zona(15, 35, 85, 49, 'Alvo'),
        jogador(50, 32, 'b', 'Alim'),
        jogador(50, 78, 'a', 'Exec'),
        trajeto(50, 34, 52, 74, '1'),
        trajeto(50, 76, 45, 42, '2'),
        desloca(56, 80, 56, 94, 'recua'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-com-dois-arcos-rasante-e-alto',
    version: 1,
    kind: 'drill',
    title: 'Dink com dois arcos: rasante e de arco',
    summary: 'Alterne o dink rasante, que passa perto da fita, com o dink de arco, mais lento e fundo na cozinha. Os dois têm de ficar inatacáveis. Treina a troca de ritmo no rally de cozinha.',
    objective: 'Ao final, o atleta consegue alternar dinks rasantes e de arco por 20 bolas seguidas sem dar bola atacável ao parceiro.',
    skills: ['kitchen.dink_cruzado', 'kitchen.paciencia', 'tactics.leitura_adversario'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'variado',
    setup: 'Os dois na linha da cozinha, na diagonal. Dois cones em cada cozinha marcam uma faixa no último meio metro antes da linha: é onde o dink de arco deve cair. Com quatro pessoas, a outra dupla usa a outra diagonal.',
    steps: [
      'Troquem dinks cruzados rasantes: a bola passa até um palmo acima da fita.',
      'Troquem dinks de arco: a bola sobe mais, tem o ponto mais alto do seu lado e cai devagar na faixa perto da linha.',
      'Alternem: 4 rasantes e 4 de arco, com a mesma preparação de raquete nos dois.',
      'Bola que o parceiro alcança no ar acima da altura da fita zera a conta: estava alta demais.',
      'Por fim, quem dinka escolhe o arco sem avisar e o parceiro diz qual foi.',
    ],
    cues: ['Rasante: um palmo acima da fita', 'Arco: ponto mais alto do seu lado', 'Os dois caem na cozinha', 'Mesma preparação, outra altura final'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente e base aberta nos dois dinks; o que muda é só a altura em que a raquete termina.' },
      { type: 'errado', text: 'Preparar o dink de arco com a raquete mais baixa e mais atrás: o parceiro lê o golpe antes de a bola sair.' },
    ],
    common_errors: [
      { error: 'O dink de arco chega alto ao parceiro e vira bola para atacar.', fix: 'O ponto mais alto fica do seu lado: a bola passa a rede já descendo e cai perto da linha da cozinha.' },
      { error: 'O rasante morre na rede.', fix: 'Mire um palmo acima da fita, não a fita; as pernas sobem junto com a raquete.' },
      { error: 'Só um tipo de dink, por hábito.', fix: 'Siga a contagem de 4 e 4 até a troca sair natural; depois escolha pela posição do parceiro.' },
    ],
    variations: {
      easier: 'Tarefa: um tipo por série, só rasante e depois só de arco, com meta de 10 seguidos.',
      harder: 'Pessoas: bola acima da fita pode ser atacada e o ponto é jogado; quem varia o arco sem dar bola atacável ganha 1 ponto a cada 10 dinks.',
    },
    metric: { type: 'sequencia', target: '20 seguidos alternando' },
    success_criteria: 'Conta o dink que cai na cozinha e que o parceiro não alcança no ar acima da fita. 20 seguidos alternando os dois arcos? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Base aberta, pernas dobradas, raquete na frente da cintura.',
        execucao: 'Gesto curto de baixo para cima; no rasante a raquete termina na altura da fita, no de arco termina um pouco mais alta.',
        finalizacao: 'A raquete volta para a frente do corpo, pronta para a próxima.',
      },
      abilities: ['precisao', 'ritmo', 'leitura'],
    },
    when_to_use: 'Rally de cozinha em que o adversário já pegou o seu ritmo; o dink de arco também compra tempo quando você precisa recuperar a posição.',
    diagrams: [
      diagrama('Rasante e de arco', 'cozinha', [
        jogador(75, 70, 'a', 'A'),
        jogador(25, 30, 'b', 'B'),
        zona(15, 35, 45, 40, 'Arco'),
        trajeto(73, 68, 40, 46, 'rasante'),
        trajeto(77, 68, 30, 37, 'arco'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'voleio-na-rede-decidir-pela-altura',
    version: 1,
    kind: 'drill',
    title: 'Voleio na rede: amortecer ou atacar pela altura da bola',
    summary: 'O alimentador manda bolas no ar em três alturas, sem avisar: abaixo da fita você amortece, entre a fita e o peito você volea firme, alta e curta você dá smash. Treina a decisão de atacar.',
    objective: 'Ao final, o atleta consegue escolher o golpe certo pela altura do contato em 12 de 15 bolas misturadas, com a bola no alvo.',
    skills: ['tactics.selecao_golpe', 'net.voleio', 'net.reset', 'net.smash'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'aleatorio',
    setup: 'O executor fica na linha da cozinha. O alimentador fica do outro lado, perto da linha de fundo, com o cesto, e manda bolas no ar para o executor. Dois cones ao lado dos pés do alimentador marcam o alvo do ataque; a cozinha dele é o alvo do amortecimento. A regra da decisão: contato abaixo da altura da fita, amorteça; acima, ataque para baixo.',
    steps: [
      'Em bloco: 5 bolas baixas, abaixo da fita, que o executor amortece para a cozinha.',
      'Em bloco: 5 bolas na altura do peito, que ele volea firme e curto entre os cones.',
      'Em bloco: 5 bolas altas e curtas, que ele finaliza com smash entre os cones.',
      'Agora aleatório: o alimentador mistura as três alturas sem avisar, 15 bolas.',
      'Conta a decisão certa com a bola no alvo; ataque em bola abaixo da fita perde o ponto mesmo se entrar.',
      'Depois de 15 bolas aleatórias, troquem os papéis.',
    ],
    cues: ['Abaixo da fita: bola curta', 'Acima da fita: bola para baixo', 'Raquete na frente, gesto curto', 'Smash: mire entre os cones'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente e alta, base aberta, pronta para decidir quando a bola chega.' },
      { type: 'errado', text: 'Raquete caída esperando a bola: a decisão chega atrasada e todo voleio vira bloqueio para cima.' },
    ],
    common_errors: [
      { error: 'Atacar bola abaixo da altura da rede.', fix: 'Bola tocada abaixo da fita só pode subir; amorteça para a cozinha e espere a próxima.' },
      { error: 'Bloquear para cima uma bola fácil na altura do peito.', fix: 'Raquete firme na frente e gesto curto para baixo, mirando os cones: bola acima da fita é a sua chance.' },
      { error: 'Smash com balanço grande, que sai longo.', fix: 'Vire de lado, aponte a bola com a mão livre e mire os pés, entre os cones.' },
    ],
    variations: {
      easier: 'Tarefa: fique só nas séries em bloco, com o alimentador falando a altura antes de mandar ("baixa", "média", "alta").',
      harder: 'Tarefa: o alimentador mistura também bolas na altura exata da fita; depois de cada decisão, o ponto é jogado até o fim.',
    },
    metric: { type: 'percentual', target: '12 de 15 decisões certas' },
    success_criteria: 'Conta a bola em que o golpe combinou com a altura e caiu no alvo. 12 de 15 aleatórias duas vezes? Use a regra no jogo: abaixo da fita, paciência.',
    safety: 'Óculos de proteção recomendados. O alimentador fica no fundo e o alvo do ataque são os cones ao lado dele, nunca o corpo.',
    motor: {
      phases: {
        preparacao: 'Raquete na frente do peito, pernas dobradas, peso na frente.',
        execucao: 'Bola baixa: gesto curto e macio para a cozinha. Bola média: soco curto para baixo. Bola alta: de lado, smash para baixo.',
        finalizacao: 'A raquete volta para a frente do peito e você volta à linha.',
      },
      abilities: ['leitura', 'tempo_reacao', 'precisao'],
    },
    when_to_use: 'Trocas na rede e bolas que chegam no ar quando você já está na cozinha: a altura do contato decide entre esperar e atacar.',
    diagrams: [
      diagrama('Três alturas, três golpes', 'inteira', [
        jogador(50, 68, 'a', 'Exec'),
        jogador(50, 12, 'b', 'Alim'),
        cone(40, 16),
        cone(60, 16),
        zona(20, 35, 80, 49, 'Amortecer'),
        trajeto(50, 14, 50, 64, '1'),
        trajeto(48, 66, 42, 42, 'baixa'),
        trajeto(52, 66, 58, 18, 'alta'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'speed-up-tres-alvos-anunciados',
    version: 1,
    kind: 'drill',
    title: 'Speed-up com três alvos',
    summary: 'No rally de dink, o speed-up vai para um de três alvos: ombro do lado da raquete, quadril do lado da raquete ou pés. Primeiro anunciado, depois escondido. Dá mais de uma resposta à bola atacável.',
    objective: 'Ao final, o atleta consegue acertar 15 de 20 speed-ups no alvo escolhido, variando entre os três, só em bolas atacáveis.',
    skills: ['net.speed_up', 'tactics.alvo', 'kitchen.dink_atacavel'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 2,
    roles: ['Atacante', 'Defensor'],
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: 'Os dois na linha da cozinha, frente a frente. Os alvos são três: o ombro do lado da raquete do defensor (a junção da raquete com o corpo), o quadril do lado da raquete e os pés. O meio do corpo também serve; o que não serve é a quadra aberta, onde a raquete do defensor já está.',
    steps: [
      'Troquem dinks; o atacante acelera no máximo uma bola a cada 5 dinks.',
      'Fase 1: antes do rally, o atacante fala o alvo em voz alta; o defensor sabe e tenta bloquear.',
      'Acelere só a bola que você alcança na altura da fita ou acima, com gesto curto e uns dois terços da força.',
      'Fase 2: o atacante escolhe sem avisar; depois da troca, o defensor diz onde a bola chegou e o atacante confirma o que pensou.',
      'Troque de alvo a cada ataque; o mesmo alvo duas vezes seguidas não conta.',
      'Depois de 20 ataques, troquem os papéis.',
    ],
    cues: ['Escolha o alvo antes da bola', 'Gesto curto, dois terços da força', 'Mire o lado da raquete', 'Troque o alvo a cada ataque'],
    positioning: [
      { type: 'certo', text: 'Mesma preparação do dink até o último instante; o speed-up sai curto, com a raquete na frente.' },
      { type: 'errado', text: 'Raquete puxada para trás antes de acelerar: o defensor vê o ataque chegando e já está pronto.' },
    ],
    common_errors: [
      { error: 'O ataque vai sempre para o mesmo alvo.', fix: 'Siga a rotação ombro, quadril, pés até ela sair sem pensar; o defensor que adivinha o alvo bloqueia fácil.' },
      { error: 'Acelerar bola baixa, abaixo da fita.', fix: 'Bola baixa acelerada sobe e vira contra-ataque; espere a bola na altura da fita ou acima.' },
      { error: 'Força total e a bola sai longa.', fix: 'Uns dois terços da força e gesto curto: o que ganha é a surpresa e o alvo, não a velocidade.' },
      { error: 'Mirar a quadra aberta, longe do corpo.', fix: 'Ali a raquete do defensor já está esperando; mire a junção da raquete com o corpo ou os pés.' },
    ],
    variations: {
      easier: 'Tarefa: só o quadril do lado da raquete, anunciado, com o defensor apenas bloqueando sem contra-atacar; meta de 10 de 20.',
      harder: 'Pessoas: o defensor pode contra-atacar e o ponto é jogado até o fim; vale ponto só o ataque que chega no alvo e não volta contra-atacado.',
    },
    metric: { type: 'percentual', target: '15 de 20 no alvo' },
    success_criteria: 'Conta o speed-up que chega ao alvo escolhido, em bola atacável. Acelerou bola abaixo da fita? Não conta. 15 de 20 escondendo o alvo? Passe para a variação mais difícil.',
    safety: 'Óculos de proteção recomendados. Os alvos são ombro, quadril e pés; o rosto do parceiro de treino está fora do combinado.',
    motor: {
      phases: {
        preparacao: 'A mesma do dink: base aberta, raquete na frente, sem puxar para trás.',
        execucao: 'Gesto curto para a frente, com a face apontando o alvo escolhido.',
        finalizacao: 'A raquete volta logo para a frente do peito, pronta para o contra-ataque.',
      },
      abilities: ['precisao', 'tempo_reacao', 'leitura'],
    },
    when_to_use: 'Rally de cozinha em que o adversário deixa uma bola na altura da fita ou acima, e você quer ter mais de um destino para ela.',
    diagrams: [
      diagrama('Os três alvos', 'cozinha', [
        jogador(60, 70, 'a', 'Atac'),
        jogador(40, 30, 'b', 'Def'),
        trajeto(60, 68, 46, 29, '1'),
        trajeto(62, 68, 44, 33, '2'),
        trajeto(58, 68, 40, 27, '3'),
        texto(52, 27, 'ombro'),
        texto(52, 34, 'quadril'),
        texto(30, 26, 'pés'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-nos-quatro-cantos-entrar-e-sair-da-cozinha',
    version: 1,
    kind: 'drill',
    title: 'Dink nos quatro cantos: lateral, curto e de volta',
    summary: 'O alimentador manda dinks para quatro cantos: dois junto à linha, nas laterais, e dois curtos, perto da rede, que obrigam a entrar na cozinha. Você joga e volta ao centro. Treina o deslocamento com bola na cozinha.',
    objective: 'Ao final, o atleta consegue devolver 24 de 30 dinks dos quatro cantos para a cozinha e estar de volta ao centro, fora da cozinha, antes da próxima bola.',
    skills: ['physical.agilidade', 'kitchen.dink_paralelo', 'kitchen.dink_cruzado', 'rules.cozinha'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 3,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'aleatorio',
    setup: 'O executor fica no centro, atrás da linha da cozinha. Quatro cones na cozinha dele: dois junto à linha, a uns 2 metros para cada lado do centro (cantos fundos), e dois perto da rede, um de cada lado (cantos curtos). O alimentador fica na linha da cozinha do outro lado, com o cesto. Com três pessoas, o terceiro recolhe bolas e entra no rodízio.',
    steps: [
      'O alimentador manda um dink para um dos quatro cantos, sem ordem fixa.',
      'Canto fundo: passos laterais curtos, sem cruzar as pernas, e dink de volta.',
      'Canto curto: entre na cozinha para jogar a bola depois do quique e devolva com dink.',
      'Depois de cada bola, volte ao centro, atrás da linha, antes de o alimentador bater a próxima.',
      'Se a próxima vier no ar com você ainda na cozinha, deixe quicar: voleio com um pé na cozinha é falta.',
      'Séries de 15 bolas; depois de duas séries, troquem.',
    ],
    cues: ['Chegue parado, depois bata', 'Toque a bola e volte ao centro', 'Fora da cozinha antes do voleio'],
    positioning: [
      { type: 'certo', text: 'Base baixa e raquete na frente durante todo o deslocamento, chegando parado na bola.' },
      { type: 'certo', text: 'Depois da bola curta, os dois pés voltam para trás da linha antes de qualquer voleio.' },
      { type: 'errado', text: 'Esticar a raquete para alcançar sem mover os pés: a bola sai alta e você fica fora de posição.' },
    ],
    common_errors: [
      { error: 'Volear a bola seguinte com um pé ainda dentro da cozinha.', fix: 'Saia com os dois pés antes de volear; se não deu tempo, deixe a bola quicar e jogue de dentro.' },
      { error: 'Cruzar as pernas no canto fundo e chegar desequilibrado.', fix: 'Passo lateral: o pé de dentro acompanha o de fora sem cruzar, e você para antes de bater.' },
      { error: 'Ficar no canto esperando a próxima bola.', fix: 'Toque e volte: a recuperação ao centro faz parte da repetição.' },
    ],
    variations: {
      easier: 'Espaço: só os dois cantos fundos, com o alimentador falando o canto antes de mandar; meta de 15 de 20.',
      harder: 'Tarefa: depois de uma bola curta, o alimentador manda a seguinte no ar, rápida; você precisa sair da cozinha a tempo de volear ou deixar quicar.',
    },
    metric: { type: 'percentual', target: '24 de 30 com recuperação' },
    success_criteria: 'Conta o dink que cai na cozinha com você de volta ao centro antes da próxima bola. Voleio com pé na cozinha zera a série. 24 de 30? Passe para a variação mais difícil.',
    safety: 'Freie com passos curtos e pernas dobradas antes de bater. Quadra molhada ou com areia: não faça.',
    motor: {
      phases: {
        preparacao: 'Base baixa no centro, raquete na frente, peso na frente dos pés.',
        execucao: 'Passos curtos até a bola, parada equilibrada e dink com gesto curto.',
        finalizacao: 'Recuperação ao centro, atrás da linha, com a raquete na frente.',
      },
      abilities: ['agilidade', 'equilibrio', 'precisao'],
    },
    when_to_use: 'Rally de cozinha em que o adversário puxa você para as laterais e para perto da rede com dinks curtos.',
    diagrams: [
      diagrama('Os quatro cantos', 'cozinha', [
        cone(28, 64),
        cone(72, 64),
        cone(30, 54),
        cone(70, 54),
        jogador(50, 70, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 34, 70, 53, '1'),
        desloca(53, 70, 68, 57),
        desloca(68, 60, 54, 70),
      ]),
    ],
    media: [],
  },
  {
    slug: 'saque-fundo-no-backhand-de-quem-devolve',
    version: 1,
    kind: 'drill',
    title: 'Saque fundo no backhand de quem devolve',
    summary: 'Primeiro a profundidade, depois o lado: saque fundo na metade da área onde fica o backhand de quem devolve. Treina a ler a mão do devolvedor e a ajustar o alvo em cada lado da quadra.',
    objective: 'Ao final, o atleta consegue colocar 8 de 10 saques fundos na metade do backhand do devolvedor, nas duas áreas de saque e contra destro ou canhoto.',
    skills: ['serve.saque_profundo', 'serve.consistencia', 'tactics.alvo', 'tactics.leitura_adversario'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    roles: ['Sacador', 'Devolvedor'],
    duration_min: 10,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'variado',
    setup: 'Na área de saque da diagonal, cones marcam o terço final e dividem esse terço em duas metades. O devolvedor fica na posição de devolução. Para um destro, o backhand fica do lado do meio quando ele está na área da direita (par) e do lado da lateral quando está na da esquerda (ímpar); para um canhoto, ao contrário. O saque segue a regra: por baixo, atrás da linha de fundo; no de voleio, contato abaixo da cintura, raquete subindo em arco e cabeça da raquete abaixo do punho; ou o saque com quique.',
    steps: [
      'Antes de sacar, olhe em que mão está a raquete do devolvedor e localize o backhand.',
      'Saque 10 bolas para o terço final, na metade do backhand.',
      'Troque de área de saque e repita, mudando o alvo para o novo lado do backhand.',
      'A cada 3 saques, o devolvedor diz "destro" ou "canhoto" (pode fingir); reajuste o alvo.',
      'O devolvedor só devolve de leve para conferir; conta o saque fundo na metade certa.',
      'Para não virar padrão, em 3 de cada 10 saques mire o outro lado de propósito.',
    ],
    cues: ['Primeiro fundo, depois o lado', 'Ache a raquete de quem devolve', 'Mire o terço final da metade'],
    positioning: [
      { type: 'certo', text: 'Mesma preparação para os dois lados; o alvo muda só pela direção da raquete no contato.' },
      { type: 'errado', text: 'Virar o corpo todo para o alvo antes de sacar: o devolvedor lê o lado e já se arruma para o forehand.' },
    ],
    common_errors: [
      { error: 'Para mirar o backhand, o saque sai curto.', fix: 'Saque curto no backhand é a bola mais fácil de atacar: mantenha o terço final como alvo e ajuste só o lado.' },
      { error: 'Sacar com força para compensar a mira e errar mais.', fix: 'Velocidade média e profundidade: o backhand sofre com a bola funda, não com a forte.' },
      { error: 'Para dar ângulo, o contato sobe acima da cintura ou a cabeça da raquete passa do punho.', fix: 'No saque de voleio, contato claramente abaixo da cintura e raquete subindo em arco; desde 2026, saque duvidoso é falta. Se ficar difícil, use o saque com quique.' },
    ],
    variations: {
      easier: 'Espaço: o alvo é a metade do backhand inteira, sem o terço final; meta de 7 de 10. Sozinho: imagine um devolvedor destro e alterne as áreas.',
      harder: 'Tarefa: depois do saque, joguem o ponto; quem sacou ganha ponto dobrado se a devolução vier curta ou alta.',
    },
    metric: { type: 'percentual', target: '8 de 10 fundos no backhand' },
    success_criteria: 'Conta o saque válido que quica no terço final, na metade do backhand. 8 de 10 nas duas áreas e com destro e canhoto? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Rotina de saque: olhe o devolvedor, ache o backhand, escolha o alvo e respire.',
        execucao: 'Gesto de baixo para cima, contato abaixo da cintura, raquete terminando na direção do alvo.',
        finalizacao: 'Volte para trás da linha de fundo e espere a devolução quicar.',
      },
      abilities: ['precisao', 'leitura', 'ritmo'],
    },
    when_to_use: 'Contra devolvedores com backhand mais fraco ou de preparação lenta; misture com saques no forehand para não virar padrão.',
    diagrams: [
      diagrama('Área da direita: backhand no meio', 'inteira', [
        jogador(75, 98, 'a', 'Sac'),
        jogador(25, 3, 'b', 'Dev'),
        zona(25, 1, 50, 12, 'Backhand'),
        trajeto(75, 96, 40, 7, '1'),
      ]),
      diagrama('Área da esquerda: backhand na lateral', 'inteira', [
        jogador(25, 98, 'a', 'Sac'),
        jogador(75, 3, 'b', 'Dev'),
        zona(75, 1, 100, 12, 'Backhand'),
        trajeto(25, 96, 88, 7, '1'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'saque-com-quatro-efeitos-da-raquete',
    version: 1,
    kind: 'drill',
    title: 'Saque com quatro efeitos dados pela raquete',
    summary: 'Saque liso, com topspin, com efeito lateral e cortado, em rotação, todos com o efeito vindo da raquete. O devolvedor tenta adivinhar qual veio. Treina variar o saque sem perder profundidade nem a regra.',
    objective: 'Ao final, o atleta consegue colocar 16 de 20 saques válidos alternando quatro efeitos, sem que o devolvedor acerte mais de 3 de 5 palpites.',
    skills: ['serve.consistencia', 'serve.saque_profundo', 'rules.saque'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 1,
    players_max: 2,
    roles: ['Sacador', 'Devolvedor'],
    duration_min: 12,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'variado',
    setup: 'Sacador atrás da linha de fundo; cones marcam o terço final da área de saque da diagonal. O devolvedor fica na posição de devolução. A regra vale para todos os efeitos: a bola é solta sem nenhum giro dado pela mão (proibido desde 2023) e o efeito vem só da raquete. No saque de voleio, contato abaixo da cintura, raquete subindo em arco e cabeça da raquete abaixo do punho; no saque com quique, a bola só é solta e quica antes do golpe.',
    steps: [
      'Solte a bola parada, sem girar com os dedos, ou deixe-a cair no saque com quique.',
      'Liso: raquete reta para a frente. Topspin: raquete subindo e escovando a parte de trás da bola.',
      'Lateral: raquete atravessando a bola de lado. Cortado: face aberta passando por baixo dela, ainda subindo.',
      'Cinco de cada, em rotação, sem repetir o mesmo efeito duas vezes seguidas; anote onde quicaram.',
      'O devolvedor diz em voz alta qual efeito veio, antes do quique.',
      'Conta o saque válido no terço final e o palpite errado do devolvedor.',
    ],
    cues: ['Solte a bola parada', 'O efeito sai da raquete', 'Profundidade antes do efeito', 'Mesma preparação nos quatro'],
    positioning: [
      { type: 'certo', text: 'A mesma preparação e o mesmo lançamento nos quatro saques; muda só o caminho da raquete no contato.' },
      { type: 'errado', text: 'Uma preparação diferente para cada efeito: o devolvedor descobre o saque antes do contato.' },
    ],
    common_errors: [
      { error: 'Girar a bola com os dedos ao soltar, para ganhar efeito.', fix: 'É proibido: solte a bola parada ou deixe cair. Todo efeito precisa vir da raquete no contato.' },
      { error: 'Para dar mais efeito, o contato sobe acima da cintura ou a raquete vem de lado.', fix: 'No saque de voleio, contato claramente abaixo da cintura e raquete subindo em arco; desde 2026, saque duvidoso é falta. O saque com quique deixa o gesto mais livre.' },
      { error: 'Tanto efeito que o saque sai curto ou fora.', fix: 'Profundidade primeiro: o efeito é tempero, não o prato. Diminua o giro até a bola voltar ao terço final.' },
    ],
    variations: {
      easier: 'Tarefa: só liso e topspin, alternados, com meta de 8 de 10 válidos. Sozinho: sem devolvedor, conferindo o quique de cada um.',
      harder: 'Tarefa: dois alvos de profundidade (fundo no meio e fundo na lateral) e o ponto é jogado; o sacador ganha 1 ponto a cada palpite errado do devolvedor.',
    },
    metric: { type: 'percentual', target: '16 de 20 válidos' },
    success_criteria: 'Conta o saque válido que quica no terço final. 16 de 20 com o devolvedor acertando no máximo 3 de 5 palpites? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Rotina igual para todos: olhar o alvo, posição dos pés, bola solta parada na frente do corpo.',
        execucao: 'Gesto de baixo para cima; no último instante, a raquete escolhe o caminho: reta, subindo, de lado ou por baixo.',
        finalizacao: 'A raquete termina na direção do alvo; volte para trás da linha de fundo.',
      },
      abilities: ['coordenacao', 'precisao', 'ritmo'],
    },
    when_to_use: 'Contra devolvedores que já pegaram o ritmo do seu saque: a variação de efeito tira o conforto da devolução sem arriscar a profundidade.',
    diagrams: [
      diagrama('Quatro efeitos, um alvo', 'inteira', [
        jogador(75, 98, 'a', 'Sac'),
        jogador(25, 3, 'b', 'Dev'),
        zona(0, 1, 50, 12, 'Fundo'),
        cone(5, 12),
        cone(45, 12),
        trajeto(75, 96, 25, 8, '1'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'lob-com-topspin-a-partir-do-dink',
    version: 1,
    kind: 'drill',
    title: 'Lob com topspin a partir do dink',
    summary: 'No rally de dink, um lob com topspin, preparado igual ao dink: a bola sobe acima da raquete erguida do adversário, mergulha no fundo e foge depois do quique. Para quem já faz o lob sem efeito.',
    objective: 'Ao final, o atleta consegue colocar 7 de 10 lobs com topspin nos últimos 1,5 metro da quadra adversária, sem o defensor alcançar de voleio.',
    skills: ['groundstrokes.lob', 'tactics.selecao_golpe', 'tactics.leitura_adversario'],
    level_min: 3.5,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Quem faz o lob', 'Defensor'],
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'variado',
    setup: 'Os dois na linha da cozinha, na diagonal (o lob cruzado tem mais quadra para cair). Cones a 1,5 metro da linha de fundo, na diagonal do defensor, marcam o alvo. Combinem quem pode fazer o lob na rodada.',
    steps: [
      'Troquem dinks cruzados baixos.',
      'Quem faz o lob escolhe a hora, no máximo uma vez a cada 5 dinks, de preferência com o defensor inclinado para a frente.',
      'Mesma preparação do dink; no contato, a raquete sobe escovando a parte de trás da bola, para cima e para a frente.',
      'A bola passa bem acima da raquete erguida do defensor e quica depois dos cones.',
      'O defensor vira de lado e corre para buscar, ou dá smash se o lob ficou curto; joguem o ponto.',
      'Depois de 10 lobs, troquem os papéis.',
    ],
    cues: ['Prepare igual ao dink', 'Raquete termina alta, para a frente', 'Bola passa acima da raquete erguida', 'Mire depois dos cones'],
    positioning: [
      { type: 'certo', text: 'Base e raquete iguais às do dink até o contato; a diferença está só no caminho da raquete, que sobe.' },
      { type: 'errado', text: 'Raquete baixa e lá atrás antes do lob: o defensor lê, recua cedo e espera o smash.' },
    ],
    common_errors: [
      { error: 'O lob sai curto e vira smash.', fix: 'Mais altura e raquete terminando alta: o topspin traz a bola para dentro, então ela pode subir mais.' },
      { error: 'A raquete empurra a bola sem escovar e ela sai longa.', fix: 'Comece a raquete abaixo da bola e suba por trás dela; o efeito é que faz a bola cair dentro.' },
      { error: 'Lob contra quem já está recuado ou esperando.', fix: 'Use contra quem está colado à linha e inclinado para a frente; contra quem espera, volte ao dink.' },
    ],
    variations: {
      easier: 'Tarefa: lob sem efeito, a partir de uma bola jogada com a mão; meta de 5 de 10 depois dos cones.',
      harder: 'Tarefa: o defensor pode recuar a qualquer hora e o lob só vale se sair de um rally de pelo menos 5 dinks, sem nenhum sinal antes.',
    },
    metric: { type: 'percentual', target: '7 de 10 no fundo' },
    success_criteria: 'Conta o lob com topspin que quica depois dos cones sem o defensor voleá-lo. 7 de 10 duas vezes? Use no jogo contra quem se inclina na rede.',
    safety: 'Quem recua para buscar o lob vira de lado e corre; andar de costas é uma causa comum de queda. Comece com lobs mais lentos.',
    motor: {
      phases: {
        preparacao: 'A mesma do dink: base aberta, pernas dobradas, raquete na frente.',
        execucao: 'Raquete de baixo para cima, escovando a parte de trás da bola, com as pernas subindo junto.',
        finalizacao: 'A raquete termina alta e à frente; volte à linha pronto para a resposta.',
      },
      abilities: ['precisao', 'coordenacao', 'leitura'],
    },
    when_to_use: 'Rally de cozinha contra quem fica colado à linha e inclinado para a frente; usado de vez em quando, para continuar sendo surpresa.',
    diagrams: [
      diagrama('Lob cruzado depois dos cones', 'inteira', [
        jogador(70, 68, 'a', 'Lob'),
        jogador(30, 32, 'b', 'Def'),
        cone(10, 12),
        cone(40, 12),
        zona(5, 1, 45, 11, 'Alvo'),
        trajeto(70, 66, 28, 7, 'lob'),
        desloca(30, 30, 33, 14, 'vira'),
      ]),
    ],
    media: [],
  },
];
