/**
 * Biblioteca inicial — itens importados do pacote "100 drills", nível 4 da
 * fonte (3.5–4.0). Cada um foi avaliado, corrigido e reescrito; os rejeitados
 * e os duplicados ficaram de fora.
 */

import { cone, desloca, diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];
const PARE_SE_DOER = 'Sentiu dor (não cansaço), tontura ou falta de ar fora do normal? Pare. Quem tem lesão ou alguma condição de saúde segue a orientação do seu profissional de saúde.';

export const IMPORTADOS_NIVEL4 = [
  {
    slug: 'dink-com-rolagem-de-backhand',
    version: 1,
    kind: 'drill',
    title: 'Dink com rolagem de backhand (topspin)',
    summary: 'Na diagonal do backhand, o dink ganha efeito para a frente: a raquete escova a bola de baixo para cima. A bola passa baixa, cai rápido e pressiona o adversário.',
    objective: 'Ao final, o atleta consegue fazer 15 de 20 dinks de backhand com rolagem caindo na cozinha, sem a bola subir acima da cintura do parceiro.',
    skills: ['kitchen.dink_cruzado', 'net.voleio', 'tactics.selecao_golpe'],
    level_min: 3.5,
    level_max: 4.5,
    players_min: 2,
    players_max: 4,
    roles: ['Parceiro de dink', 'Executor'],
    duration_min: 12,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    setup: 'Os dois na linha da cozinha, na diagonal do backhand (para destros, a esquerda de cada um). Dois cones na cozinha do parceiro marcam uma faixa de um metro junto à linha: é o alvo da rolagem. Com quatro pessoas, a outra dupla usa a diagonal oposta.',
    steps: [
      'O parceiro manda dinks cruzados, sem pressa, para o seu backhand, quicando à sua frente na altura do joelho ou acima.',
      'Leve a raquete abaixo da bola, com a face quase de pé, e escove a parte de trás da bola de baixo para cima, num gesto curto.',
      'A bola passa a um palmo da fita, cai rápido na faixa e segue para a frente depois do quique.',
      'Volte a raquete para a frente do corpo e espere o próximo dink na mesma linha, sem recuar.',
      'Bola baixa demais (abaixo do joelho) não se rola: devolva com o dink normal e espere a próxima.',
      'Faça séries de 20 e conte os acertos; a cada série, troque quem rola.',
    ],
    cues: ['Escove a bola de baixo para cima', 'Gesto curto, raquete termina alta', 'Bola passa um palmo da fita', 'Bola baixa? Dink normal'],
    positioning: [
      { type: 'certo', text: 'Base baixa e aberta, bola encontrada na frente do corpo, raquete subindo pela parte de trás da bola.' },
      { type: 'certo', text: 'Depois da rolagem, a raquete volta para a frente e você continua na linha da cozinha.' },
      { type: 'errado', text: 'Rolar com um balanço grande, de trás para a frente: a bola ganha velocidade, sobe e vira um presente para o ataque.' },
    ],
    common_errors: [
      { error: 'A bola sai alta e longa, passando da cozinha.', fix: 'Encurte o gesto e escove mais de baixo para cima do que para a frente; quem faz a bola cair é o efeito, não a força.' },
      { error: 'A bola morre na rede.', fix: 'Abra um pouco a face da raquete e comece o gesto mais embaixo da bola.' },
      { error: 'Tentar rolar bola que quicou muito baixa.', fix: 'Abaixo do joelho, devolva com dink normal; rolagem é para a bola que dá altura para escovar.' },
      { error: 'Treinar só o backhand e esquecer o forehand.', fix: 'Em cada sessão, guarde um terço das bolas para a rolagem de forehand.' },
    ],
    variations: {
      easier: 'Tarefa: o parceiro joga a bola com a mão, devagar e na altura da cintura; meta de 10 em 20. Sozinho, dá para treinar o gesto na parede, com bolas suaves.',
      harder: 'Tarefa: a rolagem entra no meio de um rally que alterna forehand e backhand, e o parceiro pode atacar a bola que subir. Depois, rolagem de voleio: a bola é rolada antes de quicar.',
    },
    metric: { type: 'percentual', target: '15 de 20 na faixa' },
    success_criteria: 'Conta a rolagem que cai na faixa e não passa da cintura do parceiro. 15 de 20 em duas séries? Passe para a rolagem no meio do rally.',
    motor: {
      phases: {
        preparacao: 'Base baixa, raquete na frente e abaixo do ponto de contato, face quase de pé.',
        execucao: 'Gesto curto de baixo para cima, escovando a parte de trás da bola.',
        finalizacao: 'A raquete termina alta, apontando o alvo, e volta para a frente do corpo.',
      },
      abilities: ['coordenacao', 'precisao', 'ritmo'],
    },
    when_to_use: 'No rally de cozinha, quando o dink do adversário quica com alguma altura no seu backhand e você quer pressionar sem dar bola alta.',
    diagrams: [
      diagrama('Diagonal do backhand', 'cozinha', [
        zona(60, 35, 90, 42, 'Alvo'),
        jogador(25, 68, 'a', 'A'),
        jogador(75, 32, 'b', 'B'),
        trajeto(75, 34, 30, 62, 'Dink'),
        trajeto(25, 66, 74, 39, 'Rolagem'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'punch-de-voleio-com-alvo-anunciado',
    version: 1,
    kind: 'drill',
    title: 'Punch de voleio com alvo anunciado',
    summary: 'Na rede, você escolhe o alvo e diz em voz alta antes do voleio: pés, cintura ou ombro do lado da raquete. Treina o punch curto e a escolha do alvo pela altura da bola.',
    objective: 'Ao final, o atleta consegue acertar 15 de 20 punches no alvo anunciado, com gesto curto e sem dar bola fácil de volta.',
    skills: ['net.voleio', 'tactics.alvo', 'net.speed_up'],
    level_min: 3.5,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'variado',
    setup: 'Os dois na linha da cozinha, frente a frente. O alimentador tem o cesto e um cone ao lado do pé. Três alvos no alimentador: o cone (pés), a cintura do lado da raquete e o ombro do lado da raquete. Ritmo controlado: o alimentador fica pronto para bloquear.',
    steps: [
      'O alimentador manda bolas de voleio em alturas variadas: na altura do peito, da cintura e um pouco acima da cabeça.',
      'Antes de a bola chegar, diga o alvo em voz alta: "pé", "cintura" ou "ombro".',
      'Bola acima da fita: punch curto, com a raquete na frente do corpo e quase sem preparar para trás.',
      'Bola abaixo da fita não é punch: bloqueie para a cozinha e diga "reset".',
      'O alimentador bloqueia ou deixa passar; conte só o punch que vai no alvo anunciado.',
      'A cada 4 bolas, mude o alvo: repetir o mesmo alvo deixa o adversário ler.',
    ],
    cues: ['Raquete na frente, golpe de um palmo', 'Bola acima da fita? Punch', 'Diga o alvo antes da bola', 'Mire o lado da raquete dele'],
    positioning: [
      { type: 'certo', text: 'Raquete na frente do peito antes da bola chegar; o punch anda um palmo e para apontando o alvo.' },
      { type: 'certo', text: 'Bola abaixo da altura da fita vira bloqueio para a cozinha, não ataque.' },
      { type: 'errado', text: 'Puxar a raquete para trás e bater com balanço: a bola chega atrasada, sai longa e o adversário tem tempo de bloquear.' },
    ],
    common_errors: [
      { error: 'O punch vira um golpe com balanço grande.', fix: 'Comece com a raquete já na frente e pare o gesto quando ela apontar o alvo.' },
      { error: 'Mirar o meio do peito, onde o adversário já está com a raquete.', fix: 'Escolha os pés ou o lado da raquete dele: cintura ou ombro, onde o bloqueio fica apertado.' },
      { error: 'Atacar bola que está abaixo da fita.', fix: 'Abaixo da fita a bola teria de subir para passar: bloqueie para a cozinha e espere a próxima.' },
    ],
    variations: {
      easier: 'Tarefa: um alvo só, o cone nos pés, com bolas lentas na altura do peito; meta de 10 em 20.',
      harder: 'Tarefa: o alimentador devolve o punch e o ponto continua; quem atacou precisa se recuperar para o bloqueio seguinte. O alvo é escolhido pela posição do adversário, sem anunciar.',
    },
    metric: { type: 'percentual', target: '15 de 20 no alvo' },
    success_criteria: 'Conta o punch que vai no alvo anunciado, com gesto curto. 15 de 20? Passe para a variação em que o ponto continua.',
    safety: 'Ritmo de treino, não de jogo: punch a 60 ou 70% da força e nunca no rosto. Óculos de proteção ajudam nas trocas rápidas na rede.',
    motor: {
      phases: {
        preparacao: 'Base na linha da cozinha, raquete na frente do peito, face apontando a rede.',
        execucao: 'Golpe curto para a frente e um pouco para baixo, quase sem preparação.',
        finalizacao: 'A raquete para apontando o alvo e volta para a frente do peito.',
      },
      abilities: ['tempo_reacao', 'precisao', 'leitura'],
    },
    when_to_use: 'Bola de voleio que chega acima da fita, quando os dois estão na rede e você quer fechar o ponto sem perder o controle.',
    diagrams: [
      diagrama('Três alvos no alimentador', 'cozinha', [
        jogador(65, 68, 'a', 'Executor'),
        jogador(65, 32, 'b', 'Alimentador'),
        cone(60, 28),
        texto(80, 30, 'Cintura'),
        texto(80, 26, 'Ombro'),
        texto(50, 28, 'Pés'),
        trajeto(63, 34, 65, 64, '1'),
        trajeto(65, 66, 61, 30, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'erne-passos-e-voleio-com-alimentador',
    version: 1,
    kind: 'drill',
    title: 'Erne em etapas: passos, alimentador e rally',
    summary: 'O Erne treinado em quatro degraus: só os passos, bola lenta, ritmo de jogo e rally. O voleio sai de fora da quadra, ao lado da cozinha, sem tocar a cozinha nem a linha dela.',
    objective: 'Ao final, o atleta consegue fazer 8 de 10 Ernes legais contra o dink paralelo, voltando para a quadra antes da bola seguinte.',
    skills: ['net.erne', 'rules.cozinha', 'tactics.leitura_adversario'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 12,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'bloco',
    setup: 'Os dois na linha da cozinha, junto à mesma lateral. Um cone fora da quadra, ao lado do canto da cozinha do executor, marca onde ele deve chegar. Confira o espaço fora da quadra: nada de banco, cadeira ou gente no caminho.',
    steps: [
      'Degrau 1, sem bola: saia da linha da cozinha pela lateral, contorne o canto por fora e pare ao lado do cone, de frente para a rede. Dez vezes, devagar.',
      'Degrau 2: o alimentador manda dinks paralelos lentos junto à sua lateral. Faça o caminho e volee a bola de fora da quadra, para baixo, no meio ou nos pés dele.',
      'No voleio, nada de pé na cozinha nem na linha dela, nem depois da batida: o embalo também conta.',
      'Se pisou na cozinha no caminho, os dois pés voltam para fora dela antes do voleio. Espere a bola passar a rede: bater do lado de lá é falta.',
      'Degrau 3: dinks em ritmo de jogo, misturando paralelo e cruzado. Só saia quando ler o paralelo; no cruzado, dink normal.',
      'Degrau 4: depois de cada Erne, volte para a quadra e o rally continua até o fim do ponto.',
    ],
    cues: ['Leia o paralelo, depois saia', 'Cone fora da quadra é o destino', 'Espere a bola passar a rede', 'Volee para baixo, no meio'],
    positioning: [
      { type: 'certo', text: 'No voleio, os dois pés fora da quadra, ao lado da cozinha, e nada tocando a cozinha nem a linha dela.' },
      { type: 'certo', text: 'Pulando sobre o canto, a saída é de fora da cozinha e a queda é fora da quadra, de frente para a rede.' },
      { type: 'errado', text: 'Volear e cair, por embalo, dentro da cozinha ou na linha dela: é falta, mesmo com a bola boa.' },
    ],
    common_errors: [
      { error: 'Sair cedo e o alimentador trocar para o cruzado.', fix: 'Saia só quando ele já se comprometeu com o paralelo; o Erne é leitura, não corrida.' },
      { error: 'O embalo leva o pé para a cozinha depois do voleio.', fix: 'Chegue parado ao lado do cone antes de bater; no começo, faça o caminho andando, sem pular.' },
      { error: 'Bater a bola antes de ela cruzar a rede.', fix: 'Espere a bola passar a linha da rede; tocar do lado do adversário é falta.' },
      { error: 'Ficar fora da quadra depois do Erne.', fix: 'Volte para a quadra logo depois de bater: se a bola voltar, o seu lado está aberto.' },
    ],
    variations: {
      easier: 'Tarefa: só os degraus 1 e 2, sempre andando em volta do canto, sem salto; meta de 5 Ernes legais.',
      harder: 'Tarefa: o Erne com salto sobre o canto e o alimentador variando o paralelo e o cruzado sem aviso; quem joga bem começa o movimento enquanto a bola ainda está do outro lado.',
    },
    metric: { type: 'percentual', target: '8 de 10 legais' },
    success_criteria: 'Conta o Erne legal (nada na cozinha nem na linha, bola já do seu lado), com o voleio dentro da quadra e a volta antes da próxima bola. 8 de 10? Suba um degrau.',
    safety: 'É o movimento de maior risco para o tornozelo na rede. Aqueça antes, comece andando e só pule depois de dominar o caminho; caia com as pernas dobradas e confira o espaço fora da quadra e o poste.',
    motor: {
      phases: {
        preparacao: 'Na linha da cozinha, leitura do dink paralelo e primeiro passo para fora da quadra.',
        execucao: 'Chegada ao lado da cozinha, base firme fora da quadra e voleio curto para baixo.',
        finalizacao: 'Equilíbrio sem tocar a cozinha e volta rápida para a quadra.',
      },
      abilities: ['leitura', 'agilidade', 'equilibrio', 'tempo_reacao'],
    },
    when_to_use: 'Contra o adversário que dinka repetidamente no paralelo, junto à sua lateral.',
    diagrams: [
      diagrama('Caminho do Erne', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(88, 68, 'a', 'A'),
        jogador(88, 32, 'b', 'Alimentador'),
        cone(98, 60),
        trajeto(88, 34, 94, 56, 'Paralelo'),
        desloca(92, 70, 98, 62, 'Por fora'),
        trajeto(98, 58, 55, 38),
      ]),
    ],
    media: [],
  },
  {
    slug: 'atp-ou-dink-leitura-da-bola-aberta',
    version: 1,
    kind: 'drill',
    title: 'ATP ou dink: a leitura da bola aberta',
    summary: 'O alimentador manda dinks cruzados cada vez mais abertos. Você decide: a bola que quica e sai pela lateral volta por fora do poste (ATP); a que fica na quadra volta por cima da rede.',
    objective: 'Ao final, o atleta decide certo entre ATP e dink em 10 de 12 bolas abertas e acerta o ATP dentro da quadra na maioria das tentativas.',
    skills: ['net.atp', 'tactics.leitura_adversario', 'tactics.selecao_golpe'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'aleatorio',
    setup: 'Os dois na linha da cozinha, na diagonal. Um cone na lateral do executor, na altura da linha da cozinha, marca o ponto a partir do qual a bola já está saindo da quadra. Espaço livre fora da quadra, sem cadeira nem gente perto do poste.',
    steps: [
      'O alimentador manda dinks cruzados com efeito para fora, alguns quicando dentro da quadra e outros já perto da lateral.',
      'Deixe a bola quicar do seu lado: o ATP sai depois do quique.',
      'A bola quicou e vai sair pela lateral, além do cone: vá atrás dela por fora da quadra e bata baixo, por fora do poste, para a quadra do alimentador.',
      'A bola ficou na quadra: devolva por cima da rede, com dink ou voleio. Tentar o ATP de dentro da quadra só leva a bola para a rede.',
      'Depois de cada bola, volte para a linha da cozinha antes da seguinte.',
      'Séries de 12; conte as decisões certas e os ATPs que caem na quadra.',
    ],
    cues: ['Bola saindo da quadra? Pense no poste', 'Deixe quicar, depois vá', 'Bata baixo, ao lado do poste', 'Volte depressa para a quadra'],
    positioning: [
      { type: 'certo', text: 'Fora da quadra, ao lado do poste, batendo a bola que já quicou do seu lado, baixa e para dentro da quadra adversária.' },
      { type: 'certo', text: 'Bola que fica dentro da quadra volta por cima da rede, com dink ou voleio.' },
      { type: 'errado', text: 'Insistir no ATP com a bola ainda dentro da quadra: sem ângulo para contornar o poste, ela bate na rede ou no poste.' },
    ],
    common_errors: [
      { error: 'Tentar o ATP em bola pouco aberta.', fix: 'Só pense no poste com a bola já fora da lateral; dentro, jogue por cima da rede.' },
      { error: 'Achar que o ATP precisa de força.', fix: 'Ele pode passar baixo, até abaixo da altura da rede: bata firme, mas mirando a quadra, não o adversário.' },
      { error: 'Ficar fora da quadra depois do ATP.', fix: 'Volte para a linha da cozinha logo depois de bater.' },
    ],
    variations: {
      easier: 'Tarefa: o alimentador avisa antes qual bola será aberta e joga com a mão; só o ATP, meta de 5 em 12.',
      harder: 'Tarefa: dinks cruzados ao vivo, com o alimentador escolhendo quando abrir; o ponto continua depois do ATP ou do dink.',
    },
    metric: { type: 'percentual', target: '10 de 12 decisões certas' },
    success_criteria: 'Conta a decisão certa (ATP só em bola fora da lateral) e a bola dentro da quadra. 10 de 12? Passe para os dinks ao vivo.',
    safety: 'Veja o espaço fora da quadra antes de correr: poste, cadeiras, outras quadras e pessoas.',
    motor: {
      phases: {
        preparacao: 'Leitura da bola aberta e deslocamento por fora da quadra, sem tirar o olho da bola.',
        execucao: 'Bola já quicada, batida baixa e firme, contornando o poste.',
        finalizacao: 'Raquete aponta a quadra adversária e o atleta volta à linha da cozinha.',
      },
      abilities: ['leitura', 'agilidade', 'precisao'],
    },
    when_to_use: 'Rally cruzado na cozinha em que o adversário abre muito o ângulo e a bola quica perto da lateral, já saindo da quadra.',
    diagrams: [
      diagrama('Decidir pela bola', 'cozinha', [
        jogador(28, 32, 'b', 'Alimentador'),
        jogador(80, 68, 'a', 'A'),
        cone(96, 66),
        trajeto(28, 34, 97, 62, 'Aberta'),
        desloca(84, 68, 98, 64),
        trajeto(100, 60, 100, 42, 'ATP'),
        trajeto(100, 42, 80, 36),
        texto(92, 50, 'Poste'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'smash-continuo-na-parede',
    version: 1,
    kind: 'drill',
    title: 'Smash contínuo na parede',
    summary: 'Sozinho, contra uma parede alta: o smash quica no chão, sobe na parede e volta alto para o próximo. Repetição do smash e do recuo de lado sem precisar de parceiro.',
    objective: 'Ao final, o atleta consegue encadear 10 smashes seguidos na parede, com a bola sempre na frente e o recuo de lado.',
    skills: ['net.smash', 'physical.agilidade'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 1,
    players_max: 1,
    duration_min: 8,
    intensity: 6,
    place: ['parede'],
    equipment: ['bolas', 'parede'],
    practice_mode: 'bloco',
    setup: 'Uma parede alta e lisa, sem janela. Fique a cerca de 5 metros dela. Uma fita no chão, a um ou dois metros da parede, marca onde o smash deve quicar.',
    steps: [
      'Jogue a bola alta com a mão ou com um lob suave contra a parede, para ela voltar alta.',
      'Vire de lado, aponte a bola com a mão livre e fique atrás dela.',
      'Bata o smash de cima para baixo, para a bola quicar perto da fita, subir na parede e voltar alta.',
      'Se a bola voltar funda, vire e ande de lado para trás; nada de recuar de costas.',
      'Encadeie o próximo smash. Perdeu o controle? Recomece com a mão.',
      'Séries curtas, de até 10 smashes, com descanso entre elas.',
    ],
    cues: ['Aponte a bola antes de bater', 'Bola na frente e no alto', 'Quique perto da fita', 'Vire de lado para recuar'],
    positioning: [
      { type: 'certo', text: 'De lado para a parede, atrás da bola, que cai à sua frente; o recuo é de lado.' },
      { type: 'errado', text: 'De frente e embaixo da bola, recuando de costas: o smash sai fraco e o risco de queda é alto.' },
    ],
    common_errors: [
      { error: 'A bola quica longe da parede e volta baixa.', fix: 'Mire o chão mais perto da parede: o quique perto da fita é o que devolve a bola alta.' },
      { error: 'Bater com toda a força e perder o controle.', fix: 'Metade da força basta: aqui o que se treina é a posição e o contato na frente.' },
      { error: 'Recuar de costas para a bola funda.', fix: 'Vire o corpo, ande de lado e só então prepare o smash.' },
    ],
    variations: {
      easier: 'Tarefa: um smash por vez, sempre recomeçando com a bola jogada com a mão; meta de 7 em 10 voltando alto.',
      harder: 'Tarefa: alterne a direção do smash para a direita e para a esquerda da fita, e encadeie 3 dinks suaves na parede antes de cada série.',
    },
    metric: { type: 'sequencia', target: '10 seguidos' },
    success_criteria: 'Conta o smash que quica perto da fita e volta alto o bastante para o próximo. 10 seguidos? Passe para o smash com direção alternada.',
    safety: 'É um treino puxado para o ombro: aqueça antes, faça séries curtas e pare se sentir dor. Recuo sempre de lado, com o chão livre atrás de você.',
    motor: {
      phases: {
        preparacao: 'De lado, raquete atrás e alta, mão livre apontando a bola.',
        execucao: 'Contato na frente e no alto, gesto de cima para baixo em direção à fita.',
        finalizacao: 'A raquete termina do outro lado do corpo e você já se ajusta para a próxima bola.',
      },
      abilities: ['coordenacao', 'potencia', 'ritmo'],
    },
    when_to_use: 'Quando não há parceiro e você quer repetir o smash e o recuo de lado.',
    diagrams: [
      diagrama('Chão, parede e volta', 'meia', [
        zona(0, 40, 100, 43, 'Parede'),
        jogador(50, 92, 'a', 'Você'),
        trajeto(50, 90, 50, 52, 'Smash'),
        trajeto(52, 52, 52, 44),
        trajeto(55, 44, 55, 86, 'Volta'),
        texto(30, 52, 'Fita'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'devolucao-com-slice-funda',
    version: 1,
    kind: 'drill',
    title: 'Devolução de saque com corte (slice) funda',
    summary: 'Devolução com efeito para trás, baixa e funda. A bola fica baixa depois do quique, atrapalha o drive da terceira bola e dá tempo para chegar à cozinha.',
    objective: 'Ao final, o atleta consegue devolver 10 de 15 saques com corte, passando baixo da rede e quicando no terço final da quadra.',
    skills: ['serve.devolucao_profunda', 'groundstrokes.transicao'],
    level_min: 3.5,
    level_max: 4.5,
    players_min: 2,
    players_max: 2,
    roles: ['Sacador', 'Quem devolve'],
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'bloco',
    setup: 'O sacador no fundo, com o cesto. Quem devolve fica um passo atrás da linha de fundo, na diagonal. Uma linha de cones a cerca de 3 metros da linha de fundo do sacador marca o terço final: é o alvo.',
    steps: [
      'O sacador varia os saques: fundos, curtos, no forehand e no backhand.',
      'Prepare a raquete alta, com a face um pouco aberta, e corte a bola de cima para baixo e para a frente, terminando na direção do alvo.',
      'A bola passa baixa sobre a rede, quica além dos cones e fica baixa depois do quique.',
      'Logo depois de bater, avance até a linha da cozinha e pare em split step quando o sacador tocar na bola.',
      'Comece só no forehand; quando sair, faça dos dois lados.',
      'Depois de 15 devoluções, troquem.',
    ],
    cues: ['Raquete alta, corte para a frente', 'Bola baixa sobre a fita', 'Quique além dos cones', 'Bateu? Ande para a cozinha'],
    positioning: [
      { type: 'certo', text: 'Raquete preparada acima da bola, gesto descendo e seguindo para a frente, terminando apontando o alvo.' },
      { type: 'certo', text: 'Devolução feita, o corpo já segue para a cozinha.' },
      { type: 'errado', text: 'Cortar só para baixo, com a face muito aberta: a bola sobe, flutua curta e vira uma terceira bola fácil.' },
    ],
    common_errors: [
      { error: 'O corte sai alto e curto.', fix: 'Leve o gesto mais para a frente do que para baixo e feche um pouco a face.' },
      { error: 'A bola vai na rede.', fix: 'Encontre a bola na frente do corpo e termine com a raquete apontando acima da fita.' },
      { error: 'Ficar parado admirando a devolução.', fix: 'O tempo que o corte dá é para avançar: bateu, ande para a cozinha.' },
    ],
    variations: {
      easier: 'Tarefa: o sacador saca devagar e no meio; só forehand, meta de 8 em 15.',
      harder: 'Tarefa: alterne devolução com corte e devolução com drive sem avisar; o sacador joga a terceira bola e o ponto continua.',
    },
    metric: { type: 'percentual', target: '10 de 15 além dos cones' },
    success_criteria: 'Conta a devolução que passa baixa, quica além dos cones e fica baixa. 10 de 15 dos dois lados? Passe para a alternância com o drive.',
    motor: {
      phases: {
        preparacao: 'Um passo atrás da linha de fundo, raquete alta, face levemente aberta.',
        execucao: 'Gesto de cima para baixo e para a frente, cortando a parte de trás e de baixo da bola.',
        finalizacao: 'A raquete termina apontando o alvo e o corpo segue para a cozinha.',
      },
      abilities: ['precisao', 'coordenacao', 'ritmo'],
    },
    when_to_use: 'Contra saque fundo que empurra você para trás, ou contra o sacador que gosta de atacar a terceira bola com drive.',
    diagrams: [
      diagrama('Corte fundo e avanço', 'inteira', [
        zona(0, 2, 100, 18, 'Alvo'),
        jogador(25, 3, 'b', 'Saque'),
        jogador(75, 97, 'a', 'A'),
        trajeto(25, 5, 72, 88, '1'),
        trajeto(75, 95, 40, 10, '2'),
        desloca(78, 92, 75, 68),
      ]),
    ],
    media: [],
  },
  {
    slug: 'disfarce-drop-ou-drive-na-terceira',
    version: 1,
    kind: 'drill',
    title: 'Disfarce na terceira bola: drop ou drive?',
    summary: 'Do fundo, você faz drop ou drive com a mesma preparação, e o parceiro na rede tenta adivinhar antes de a bola passar a rede. Treina a terceira bola que não se deixa ler.',
    objective: 'Ao final, o atleta faz drop e drive com a mesma preparação, a ponto de o parceiro não acertar mais que 6 de 10 palpites, mantendo os dois golpes bons.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.terceira_bola_drive', 'tactics.selecao_golpe'],
    level_min: 3.5,
    level_max: 5.0,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador e adivinhador', 'Executor'],
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'aleatorio',
    setup: 'O executor no fundo da quadra. O parceiro na linha da cozinha do outro lado, com o cesto: ele alimenta bolas fundas, como uma devolução, e é quem adivinha.',
    steps: [
      'O parceiro manda uma bola funda, como se fosse a devolução.',
      'Decida drop ou drive só no último instante e prepare os dois do mesmo jeito: mesma raquete, mesma base, mesmo passo.',
      'O parceiro grita "drop" ou "drive" assim que ler; palpite depois de a bola passar a rede não vale.',
      'Drop tem de cair na cozinha; drive tem de passar baixo, abaixo do peito dele. Golpe ruim não conta.',
      'Séries de 10 bolas; anotem quantos palpites ele acertou.',
    ],
    cues: ['Mesma raquete para os dois golpes', 'Decida no último instante', 'Drop na cozinha, drive baixo'],
    positioning: [
      { type: 'certo', text: 'A mesma preparação nos dois golpes: a diferença aparece só no contato, na face da raquete e na velocidade.' },
      { type: 'certo', text: 'Base parada e equilibrada antes de bater, nos dois casos.' },
      { type: 'errado', text: 'Preparar o drive com a raquete bem mais atrás e o drop com a raquete baixa: o adversário lê antes de você bater.' },
    ],
    common_errors: [
      { error: 'O drive tem uma preparação visivelmente maior.', fix: 'Encurte a preparação do drive até ela ficar igual à do drop; a força vem da velocidade da raquete no contato.' },
      { error: 'Disfarçar e perder a qualidade do golpe.', fix: 'Volte à velocidade lenta: o disfarce só vale se o drop cai na cozinha e o drive passa baixo.' },
      { error: 'Escolher sempre o mesmo golpe na mesma situação.', fix: 'Varie a ordem: o parceiro lê padrão tão bem quanto lê preparação.' },
    ],
    variations: {
      easier: 'Velocidade: bolas lentas e no forehand, sem palpite; só a preparação igual nos dois golpes.',
      harder: 'Tarefa: o parceiro responde ao golpe e o ponto continua; quem acerta o palpite marca ponto.',
    },
    metric: { type: 'percentual', target: 'Palpites certos: 6 de 10 ou menos' },
    success_criteria: 'Vale só com golpes bons: drop na cozinha e drive baixo. O parceiro acertou 6 de 10 ou menos em duas séries seguidas? Passe para o ponto ao vivo.',
    safety: 'O parceiro na rede usa óculos de proteção e mantém a raquete na frente do corpo: o drive vem na direção dele.',
    motor: {
      phases: {
        preparacao: 'Base no fundo, a mesma preparação curta para os dois golpes.',
        execucao: 'No contato, face aberta e gesto suave para o drop; face firme e raquete rápida para o drive.',
        finalizacao: 'Drop: siga para a frente. Drive: prepare-se para a quinta bola.',
      },
      abilities: ['coordenacao', 'precisao', 'leitura'],
    },
    when_to_use: 'Na terceira bola, contra adversários que já leem o seu drop e avançam, ou que recuam esperando o drive.',
    diagrams: [
      diagrama('Mesmo começo, dois finais', 'inteira', [
        zona(0, 34.1, 100, 49, 'Cozinha'),
        jogador(35, 32, 'b', 'Palpite'),
        jogador(65, 96, 'a', 'A'),
        trajeto(35, 34, 65, 92, '1'),
        trajeto(65, 94, 45, 42, 'Drop'),
        trajeto(65, 94, 30, 28, 'Drive'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'pontos-roteirizados-terceira-quinta-setima',
    version: 1,
    kind: 'drill',
    title: 'Pontos roteirizados: terceira, quinta e sétima bola',
    summary: 'A dupla combina antes um roteiro de 3, 5 ou 7 bolas e o joga com o parceiro colaborando. Depois o roteiro vira ponto disputado. Ensina a jogar com plano, não bola a bola.',
    objective: 'Ao final, o atleta executa sem erro 4 de 5 roteiros de cada tamanho e, nos pontos livres, consegue dizer qual roteiro estava montando.',
    skills: ['tactics.selecao_golpe', 'groundstrokes.terceira_bola_drop', 'groundstrokes.transicao'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 2,
    players_max: 4,
    roles: ['Executor', 'Parceiro colaborador'],
    duration_min: 15,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: 'Quadra inteira, em simples de meia quadra ou em duplas. Antes, combinem três roteiros. 3 bolas: saque, devolução funda, drop da terceira. 5 bolas: o mesmo, mais o reset da quinta na zona de transição e a chegada à cozinha. 7 bolas: o mesmo, mais dinks até a primeira bola alta, atacada para baixo.',
    steps: [
      'Combinem o roteiro antes do saque, nunca no meio do ponto.',
      'Joguem o roteiro de 3 com o parceiro colaborando, devolvendo cada bola onde o roteiro pede.',
      'Quando ele sair sem erro, passem para o de 5 e depois para o de 7.',
      'Se uma bola sai do roteiro, terminem o ponto e recomecem; o ajuste fica para o próximo.',
      'Por fim, joguem pontos livres: antes de cada um, quem saca diz qual roteiro quer montar.',
    ],
    cues: ['Combine o roteiro antes do saque', 'Saiba qual bola vem depois', 'Terceira bola na cozinha', 'Ajuste no próximo ponto'],
    positioning: [
      { type: 'certo', text: 'Depois do drop, a dupla avança junta e para em split step quando o adversário bate.' },
      { type: 'errado', text: 'Correr para a rede atrás de um drop alto: o roteiro manda resetar na quinta, não chegar a qualquer custo.' },
    ],
    common_errors: [
      { error: 'Começar pelo roteiro de 7 antes de dominar o de 3.', fix: 'Só suba de tamanho quando o roteiro anterior sair sem erro.' },
      { error: 'Abandonar o roteiro no meio porque veio uma bola difícil.', fix: 'Jogue a bola difícil da melhor forma e recomece; o roteiro é para treinar o plano, não para ganhar o ponto.' },
      { error: 'Ficar só no colaborativo.', fix: 'Na última parte, o parceiro passa a tentar impedir o roteiro.' },
    ],
    variations: {
      easier: 'Tarefa: só o roteiro de 3, com saque e devolução lentos; o parceiro joga a devolução com a mão se precisar.',
      harder: 'Tarefa: o adversário joga para ganhar o ponto; vale ponto dobrado para quem completa o roteiro que anunciou.',
    },
    metric: { type: 'sequencia', target: '4 de 5 roteiros de cada' },
    success_criteria: 'Conta o roteiro jogado do começo ao fim sem erro de quem executa. 4 de 5 nos três tamanhos? Passe para os pontos com adversário de verdade.',
    motor: {
      phases: {
        preparacao: 'O roteiro é combinado e cada um sabe a própria posição inicial.',
        execucao: 'Cada golpe do roteiro na ordem, com a dupla avançando junta.',
        finalizacao: 'Fim do ponto: conversem um instante sobre o que saiu do plano.',
      },
      abilities: ['leitura', 'ritmo', 'precisao'],
    },
    when_to_use: 'Para quem joga reagindo bola a bola e quer começar a montar os pontos com intenção.',
    diagrams: [
      diagrama('Roteiro de 5 bolas', 'inteira', [
        jogador(75, 97, 'a', 'A'),
        jogador(25, 3, 'b', 'B'),
        trajeto(75, 95, 28, 8, '1'),
        trajeto(25, 5, 70, 88, '2'),
        trajeto(72, 88, 35, 40, '3'),
        desloca(78, 92, 72, 76),
        trajeto(35, 40, 70, 74, '4'),
        trajeto(70, 74, 40, 42, '5'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'sinais-da-dupla-antes-da-devolucao',
    version: 1,
    kind: 'drill',
    title: 'Sinais da dupla antes da devolução',
    summary: 'Quem está na rede, ao lado de quem devolve, mostra um sinal escondido atrás das costas: ficar, trocar de lado ou atravessar na terceira bola. Comunicação combinada antes do ponto.',
    objective: 'Ao final, a dupla executa corretamente o plano sinalizado em 18 de 20 pontos, com o sinal dado e confirmado antes do saque.',
    skills: ['doubles.comunicacao', 'doubles.stacking', 'doubles.posicionamento'],
    level_min: 3.5,
    level_max: 5.0,
    players_min: 4,
    players_max: 4,
    roles: ['Quem sinaliza', 'Quem devolve', 'Dupla que saca'],
    duration_min: 12,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Duas duplas. A dupla que devolve combina antes três sinais, mostrados com a mão atrás das costas por quem está na linha da cozinha: punho fechado = cada um fica no seu lado; mão aberta = trocamos de lado depois da devolução; dedo indicador = vou atravessar na terceira bola. A dupla pode escolher outro código, desde que os dois saibam.',
    steps: [
      'Antes de cada saque, quem está na rede mostra o sinal atrás das costas, longe da vista dos adversários.',
      'Quem devolve olha o sinal e confirma com uma palavra combinada ou um toque na raquete.',
      'Trocar: depois da devolução, quem devolveu vai para o lado do parceiro e o parceiro desliza para o outro lado.',
      'Atravessar: o parceiro da rede ataca a terceira bola do meio, e quem devolveu cobre o lado que ficou livre.',
      'Joguem o ponto inteiro. Plano mudado no meio do ponto conta como falha do sinal.',
      'A cada 10 pontos, troquem quem sinaliza e quem saca.',
    ],
    cues: ['Sinal escondido, antes do saque', 'Confirme antes do sacador bater', 'Combinem poucos sinais', 'Trocar: atravesse logo após devolver'],
    positioning: [
      { type: 'certo', text: 'O sinal é feito atrás das costas, abaixo da linha da cintura, com o corpo de frente para a rede.' },
      { type: 'certo', text: 'Na troca, os dois se mexem juntos e chegam ao novo lado antes da terceira bola.' },
      { type: 'errado', text: 'Decidir a troca falando depois que a bola já está no ar: chega tarde e abre um lado inteiro.' },
    ],
    common_errors: [
      { error: 'Sinal visível para os adversários.', fix: 'Faça o sinal colado às costas, com a outra mão ou a raquete escondendo.' },
      { error: 'Mudar o plano depois do saque.', fix: 'O sinal vale até o fim da troca; se não der certo, ajustem no próximo ponto.' },
      { error: 'Sinais demais e esquecidos.', fix: 'Fiquem com dois ou três sinais que a dupla usa de verdade.' },
    ],
    variations: {
      easier: 'Tarefa: só dois sinais, ficar e trocar, sem ponto disputado; a dupla que saca só joga a terceira bola.',
      harder: 'Tarefa: entra um quarto sinal, o falso ataque (finge que vai atravessar e fica), usado poucas vezes por jogo; joguem a 11 pontos.',
    },
    metric: { type: 'percentual', target: '18 de 20 planos executados' },
    success_criteria: 'Conta o ponto em que o sinal foi dado antes do saque, confirmado e cumprido. 18 de 20? Passe para o quarto sinal.',
    motor: {
      phases: {
        preparacao: 'Quem sinaliza na linha da cozinha, de frente para a rede; quem devolve olha o sinal.',
        execucao: 'Devolução e movimento combinado da dupla.',
        finalizacao: 'Os dois chegam às posições do plano e jogam o ponto.',
      },
      abilities: ['leitura', 'tempo_reacao', 'agilidade'],
    },
    when_to_use: 'Em duplas que usam stacking ou que querem atacar a terceira bola com o parceiro da rede.',
    diagrams: [
      diagrama('Sinal de troca', 'inteira', [
        jogador(25, 3, 'b', 'Saque'),
        jogador(75, 3, 'b'),
        jogador(75, 97, 'a', 'Devolve'),
        jogador(25, 67, 'a', 'Sinal'),
        trajeto(25, 5, 72, 90, '1'),
        desloca(73, 94, 30, 70, 'Troca'),
        desloca(28, 66, 70, 66),
      ]),
    ],
    media: [],
  },
  {
    slug: 'jogo-das-chamadas-da-dupla',
    version: 1,
    kind: 'drill',
    title: 'Jogo das chamadas: minha, sua, troca e deixa',
    summary: 'Pontos disputados em duplas em que toda bola duvidosa exige uma chamada antes do contato. Chamada que falta custa ponto. Leva a comunicação do drill para o jogo.',
    objective: 'Ao final, a dupla joga 15 pontos seguidos sem nenhuma bola perdida por falta de chamada.',
    skills: ['doubles.comunicacao', 'doubles.cobertura_meio', 'experience.jogo'],
    level_min: 3.0,
    level_max: 4.5,
    players_min: 4,
    players_max: 4,
    roles: ['Dupla avaliada', 'Dupla adversária'],
    duration_min: 15,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Duas duplas em jogo normal. As chamadas valem para a dupla avaliada: "minha" ou "sua" na bola do meio, "troca" quando alguém atravessa para o lado do parceiro (no lob, por exemplo) e "deixa" na bola que vai sair. A chamada é feita antes do contato, alto o bastante para o parceiro ouvir.',
    steps: [
      'Joguem pontos normais; a dupla avaliada chama toda bola em que os dois poderiam bater.',
      'Na dúvida, chame "minha" cedo: chamar errado custa menos que ninguém chamar.',
      'Quem não chamou cobre o espaço que o parceiro deixou.',
      'Bola entre os dois sem chamada, choque de raquetes ou bola que sai depois de alguém bater por falta de "deixa": ponto para os adversários.',
      'Joguem a 11; depois, a outra dupla é avaliada.',
    ],
    cues: ['Chame cedo, chame alto', 'Na dúvida, diga minha', 'Bola indo para fora? Deixa', 'Atravessou? Troca'],
    positioning: [
      { type: 'certo', text: 'Quem chama vai na bola; o parceiro já se desloca para cobrir o espaço aberto.' },
      { type: 'certo', text: 'A chamada sai enquanto a bola ainda vem do outro lado, não no momento do contato.' },
      { type: 'errado', text: 'Os dois olhando a bola em silêncio e esperando o outro: ela passa entre os dois.' },
    ],
    common_errors: [
      { error: 'Chamar tarde, quando a bola já chegou.', fix: 'Chame quando a bola sai da raquete do adversário; ainda dá tempo de corrigir.' },
      { error: 'Falar baixo e o parceiro não ouvir.', fix: 'Uma palavra curta e alta: "minha", "sua", "troca", "deixa".' },
      { error: 'Chamar e depois não ir na bola.', fix: 'Quem chamou se compromete com a bola; o parceiro já foi cobrir outro espaço.' },
    ],
    variations: {
      easier: 'Tarefa: só a chamada da bola do meio, "minha" ou "sua", com um alimentador mandando bolas lentas antes de passar ao jogo.',
      harder: 'Tarefa: bola perdida por falta de chamada vale dois pontos para os adversários; joguem a 15.',
    },
    metric: { type: 'sequencia', target: '15 pontos sem falha de chamada' },
    success_criteria: 'Conta o ponto sem nenhuma bola perdida por falta ou atraso de chamada. 15 seguidos? Passe para a versão de dois pontos por falha.',
    motor: {
      phases: {
        preparacao: 'Split step quando o adversário bate, olho na bola e no parceiro.',
        execucao: 'Chamada curta e alta antes do contato; quem chamou vai na bola.',
        finalizacao: 'O parceiro cobre o espaço aberto e os dois voltam a se alinhar.',
      },
      abilities: ['leitura', 'tempo_reacao'],
    },
    when_to_use: 'Em duplas que perdem pontos fáceis com a bola passando entre os dois, choques de raquete ou bolas que iam sair.',
    diagrams: [
      diagrama('A bola do meio', 'cozinha', [
        jogador(70, 68, 'a', 'A1'),
        jogador(30, 68, 'a', 'A2'),
        jogador(30, 32, 'b'),
        jogador(70, 32, 'b'),
        trajeto(30, 34, 50, 64, 'Minha?'),
        texto(50, 72, 'Chame cedo'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'passo-cruzado-e-volta-lateral',
    version: 1,
    kind: 'fisico',
    title: 'Passo cruzado para a bola longe e volta lateral',
    summary: 'Do centro, um passo cruzado e uma corrida curta até a bola longe; de volta, passos laterais curtos e split step no centro. O padrão para cobrir distância e chegar equilibrado.',
    objective: 'Ao final de algumas semanas, o atleta completa 3 séries do padrão com a volta controlada e o split step no centro em todas as repetições.',
    skills: ['physical.agilidade', 'physical.forca_inferior'],
    level_min: 3.0,
    players_min: 1,
    players_max: 4,
    duration_min: 10,
    intensity: 6,
    place: ['quadra'],
    equipment: ['cones', 'raquete'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '8 idas e voltas',
    rest_sec: 90,
    setup: 'Três cones em linha, a cerca de 1,5 m um do outro: esquerda, centro e direita. Um quarto cone uns 2 metros além do da direita: é a bola longe.',
    steps: [
      'Comece no cone do centro, em base de prontidão, com a raquete na frente.',
      'Para ir ao cone longe, gire para o lado, cruze a perna de trás pela frente e dê dois ou três passos rápidos.',
      'No cone longe, pare com as pernas dobradas e faça o gesto de um dink ou de um voleio esticado.',
      'Volte com passos laterais curtos, sem cruzar as pernas, e faça um split step ao chegar ao centro.',
      'Alterne os lados a cada repetição. Descanse 90 segundos entre as séries.',
    ],
    cues: ['Longe: cruze e corra', 'Perto: passos curtos de lado', 'Pare antes de bater', 'Split step no cone do centro'],
    common_errors: [
      { error: 'Chegar ao cone longe ainda correndo e bater desequilibrado.', fix: 'Freie com as pernas dobradas no último passo e só então faça o gesto.' },
      { error: 'Voltar cruzando as pernas com pressa.', fix: 'Na volta, passos laterais curtos: é o momento em que o pé mais torce.' },
      { error: 'Esquecer o split step no centro.', fix: 'Pare com um pequeno salto no cone do centro antes da próxima saída.' },
    ],
    variations: {
      easier: 'Tarefa: só o padrão de passos, andando, e o cone longe a 1 metro; 2 séries.',
      harder: 'Tarefa: um parceiro aponta o lado no último instante, ou joga uma bola larga com a mão para você devolver.',
    },
    safety: `Faça depois do aquecimento, de tênis de quadra, em piso seco. Aumente a velocidade aos poucos, ao longo das semanas. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Base de prontidão no cone do centro, raquete na frente.',
        execucao: 'Giro, passo cruzado e corrida curta; freada com as pernas dobradas e o gesto do golpe.',
        finalizacao: 'Volta em passos laterais e split step no centro.',
      },
      abilities: ['agilidade', 'equilibrio', 'potencia'],
    },
    diagrams: [
      diagrama('Cruzado para ir, lateral para voltar', 'meia', [
        cone(25, 70),
        cone(50, 70),
        cone(75, 70),
        cone(95, 70),
        jogador(50, 76, 'a'),
        desloca(53, 80, 93, 80, 'Cruzado'),
        desloca(93, 86, 53, 86, 'Lateral'),
        texto(50, 92, 'Split step'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'bloqueio-em-dupla-contra-o-drive',
    version: 1,
    kind: 'drill',
    title: 'Bloqueio em dupla contra o drive',
    summary: 'Uma dupla na linha da cozinha contra um atacante no fundo que só bate drive. Os dois bloqueiam para a cozinha e cobrem o meio juntos. Treina a defesa em dupla contra a bola rápida.',
    objective: 'Ao final, a dupla bloqueia 15 de 20 drives seguidos para a cozinha, sem nenhuma bola passar pelo meio por falta de cobertura.',
    skills: ['net.reset', 'doubles.cobertura_meio', 'net.voleio'],
    level_min: 3.5,
    level_max: 4.5,
    players_min: 3,
    players_max: 4,
    roles: ['Atacante', 'Defensores'],
    duration_min: 10,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'aleatorio',
    setup: 'Dois defensores na linha da cozinha, um em cada lado. O atacante no fundo do outro lado, com o cesto: ele solta a bola e bate drive, em qualquer um dos dois ou no meio. Com quatro pessoas, o quarto alimenta o atacante ou reveza com ele. Também funciona com máquina de bolas.',
    steps: [
      'O atacante bate drives firmes, mirando um defensor, o outro ou o meio, sem aviso.',
      'Quem recebe bloqueia com a raquete na frente, sem balanço, e amortece a bola para a cozinha do atacante.',
      'O drive no meio é do defensor que tiver o forehand no meio, a não ser que o outro chame antes.',
      'Quando um dos dois vai à bola longe, o outro desliza para cobrir o meio.',
      'Bola que chega alta pode ser atacada para baixo; o resto é bloqueio.',
      'Depois de 20 drives, troquem: o atacante passa a defender.',
    ],
    cues: ['Raquete na frente, bloqueie e pare', 'Bola morre na cozinha', 'Meio: forehand do meio pega', 'Um vai, o outro cobre'],
    positioning: [
      { type: 'certo', text: 'Os dois na linha da cozinha, a cerca de 3 metros um do outro, raquetes na frente do peito.' },
      { type: 'certo', text: 'Quando a bola vai para um lado, os dois se deslocam juntos, mantendo o meio fechado.' },
      { type: 'errado', text: 'Os dois na mesma bola, ou os dois abertos para as laterais: o meio fica livre para o drive passar.' },
    ],
    common_errors: [
      { error: 'Bater de volta com força e a bola sair longa.', fix: 'Raquete firme e parada na frente: o bloqueio usa a velocidade do drive, não a sua.' },
      { error: 'Ninguém pega o drive no meio.', fix: 'Combinem antes: o forehand do meio pega, a não ser que o outro chame "minha".' },
      { error: 'Um defensor sai para atacar e o meio abre.', fix: 'Só ataque a bola que chegou alta; no resto, bloqueie e mantenha a posição.' },
    ],
    variations: {
      easier: 'Velocidade: drives a meia força, alternando os defensores em ordem.',
      harder: 'Tarefa: o atacante pode jogar um lob de vez em quando; depois, os defensores começam na zona de transição e avançam bloqueando.',
    },
    metric: { type: 'percentual', target: '15 de 20 na cozinha' },
    success_criteria: 'Conta o drive bloqueado para a cozinha, sem bola passando pelo meio. 15 de 20? Passe para a variação com lob.',
    safety: 'Óculos de proteção para os defensores. Atacante: drive firme na direção da dupla, mas abaixo do peito, nunca no rosto. Duas ou três séries bastam.',
    motor: {
      phases: {
        preparacao: 'Base baixa na linha da cozinha, raquete na frente do peito.',
        execucao: 'Bloqueio curto, com a face levemente aberta, amortecendo a bola.',
        finalizacao: 'A raquete volta para a frente e a dupla se alinha de novo.',
      },
      abilities: ['tempo_reacao', 'leitura', 'precisao'],
    },
    when_to_use: 'Quando os dois estão na rede e o adversário, no fundo, ataca com drive em vez de fazer o drop.',
    diagrams: [
      diagrama('Dois bloqueiam o drive', 'inteira', [
        zona(0, 34.1, 100, 49, 'Cozinha'),
        jogador(70, 67, 'a', 'A1'),
        jogador(30, 67, 'a', 'A2'),
        jogador(50, 4, 'b', 'Drive'),
        trajeto(50, 6, 50, 64, 'Meio'),
        trajeto(50, 6, 68, 64),
        trajeto(68, 64, 60, 42, 'Bloqueio'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'reset-mental-depois-do-erro',
    version: 1,
    kind: 'drill',
    title: 'Reset mental depois do erro: três segundos',
    summary: 'Depois de cada erro, três segundos para a frustração e uma rotina curta para voltar ao jogo: gesto, respiração e palavra para a frente. Treinado em pontos de verdade.',
    objective: 'Ao final, o atleta aplica a rotina de reset em 20 erros de jogo ou treino, voltando ao ponto seguinte sem comentar o erro anterior.',
    skills: ['mental.rotina_entre_pontos', 'mental.foco', 'mental.pressao'],
    level_min: 3.0,
    level_max: 5.0,
    players_min: 2,
    players_max: 4,
    roles: ['Atleta', 'Parceiro que observa'],
    duration_min: 20,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Em qualquer jogo ou treino com pontos. Antes, escolha o seu gesto de reset (tocar as cordas da raquete, ajeitar a raquete na mão ou dar um passo atrás) e a sua palavra para a frente ("próxima", "agora", "reset"). Combine com o parceiro: ele avisa se você passar dos três segundos.',
    steps: [
      'Errou: você tem três segundos para a frustração. Conte por dentro: um, dois, três.',
      'No três, faça o seu gesto de reset.',
      'Solte o ar devagar, uma vez, numa expiração mais longa que a inspiração.',
      'Diga a sua palavra para a frente e pense só no plano do próximo ponto.',
      'O parceiro anota quantas vezes a rotina saiu completa e quantas vezes o erro virou comentário.',
    ],
    cues: ['Um, dois, três: próximo ponto', 'Toque nas cordas da raquete', 'Solte o ar devagar', 'Palavra para a frente'],
    positioning: [
      { type: 'certo', text: 'Entre os pontos, de costas para a rede por um instante, gesto de reset, respiração e volta à posição pronto.' },
      { type: 'errado', text: 'Ficar repetindo o golpe errado no ar e comentando o erro com o parceiro até o saque seguinte.' },
    ],
    common_errors: [
      { error: 'Rever o erro na cabeça durante o ponto seguinte.', fix: 'Antes do saque, pense numa só intenção para o próximo ponto, como "devolução funda".' },
      { error: 'Desabafar com o parceiro logo depois do erro.', fix: 'Guarde o comentário técnico para a troca de lado; entre os pontos, só a palavra para a frente.' },
      { error: 'A contagem virar cinco, seis, sete segundos.', fix: 'Faça a contagem de verdade e combine com o parceiro um sinal para avisar.' },
    ],
    variations: {
      easier: 'Tarefa: conte os três segundos em voz alta, em treino sem placar, e faça só o gesto e a respiração.',
      harder: 'Tarefa: em jogo de competição ou com placar apertado; ao fim do jogo, conte quantos erros viraram dois pontos perdidos seguidos.',
    },
    metric: { type: 'reps', target: '20 erros com a rotina completa' },
    success_criteria: 'Conta o erro seguido da rotina completa em até três segundos, sem comentário sobre o erro. 20 vezes? Leve a rotina para jogos de competição.',
    motor: {
      phases: {
        preparacao: 'Logo depois do erro, contagem de três segundos.',
        execucao: 'Gesto de reset, uma expiração longa e a palavra para a frente.',
        finalizacao: 'Volta à posição com o plano do próximo ponto.',
      },
      abilities: ['ritmo'],
    },
    when_to_use: 'Em todo jogo, e principalmente quando um erro costuma puxar outro logo em seguida.',
    diagrams: [
      diagrama('Entre os pontos', 'inteira', [
        jogador(75, 96, 'a', 'Você'),
        jogador(25, 96, 'a'),
        jogador(25, 4, 'b'),
        jogador(75, 4, 'b'),
        desloca(75, 94, 85, 99, 'Reset'),
        texto(60, 86, '1, 2, 3'),
      ]),
    ],
    media: [],
  },
];
