/**
 * Biblioteca — drills importados e revisados do pacote "100 drills" (nível 2 da
 * fonte, drills 21 a 40). Só entraram os que não repetem a biblioteca inicial;
 * a avaliação de cada um (inclusive os duplicados e o rejeitado) fica fora do
 * código. Texto reescrito e corrigido; nenhuma imagem da fonte foi importada.
 */

import { cone, desloca, diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const IMPORTADOS_NIVEL2 = [
  {
    slug: 'dink-cruzado-pe-de-fora',
    version: 1,
    kind: 'drill',
    title: 'Dink cruzado no pé de fora',
    summary: 'Dink na diagonal mirando o pé de fora do parceiro, perto da lateral, com margem para dentro da linha. Tira o adversário do lugar e abre o espaço do meio para a bola seguinte.',
    objective: 'Ao final, o atleta consegue colocar 10 de 20 dinks cruzados na faixa do pé de fora do parceiro, sem errar na rede nem para fora.',
    skills: ['kitchen.dink_cruzado', 'tactics.alvo'],
    level_min: 2.5,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    roles: ['Parceiro de dink'],
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    setup: 'Os dois na linha da cozinha, na diagonal (direita com direita). Em cada cozinha, dois cones marcam uma faixa de um metro de largura que começa meio metro para dentro da lateral: é a área do pé de fora. A lateral é limite, não alvo. Com quatro pessoas, a outra dupla usa a diagonal da esquerda.',
    steps: [
      'Quem está à direita solta a bola e começa com um dink cruzado para a faixa do outro.',
      'Troquem dinks cruzados mirando sempre a faixa do pé de fora.',
      'Em séries de 20, contem quantos dinks caem dentro da faixa.',
      'A cada 5 bolas, quem recebe na faixa dá o passo até a bola e volta à sua posição antes da próxima.',
      'Depois de duas séries, troquem para a diagonal da esquerda.',
    ],
    cues: ['Mire a faixa, não a linha', 'Arco mais alto, não mais força', 'Bola desce antes da rede'],
    positioning: [
      { type: 'certo', text: 'Corpo de frente para a diagonal antes de a bola chegar, raquete na frente e base aberta.' },
      { type: 'certo', text: 'Depois do dink largo, você volta ao lugar de costume na linha, sem ficar parado olhando a bola.' },
      { type: 'errado', text: 'Bater mais forte para a bola alcançar a lateral: ela sai reta, alta e fácil de atacar.' },
    ],
    common_errors: [
      { error: 'Para alcançar a faixa, você aumenta a força e a bola passa alta.', fix: 'Distância se ganha com um arco um pouco mais alto e um gesto mais longo, nunca com pancada.' },
      { error: 'A bola sai pela lateral.', fix: 'Mire o meio da faixa, meio metro para dentro da linha; a margem é parte do alvo.' },
      { error: 'Quem recebe a bola larga perde o equilíbrio e não volta a tempo.', fix: 'Passo lateral curto até a bola e volta ao lugar com a raquete na frente antes de o outro bater.' },
    ],
    variations: {
      easier: 'Espaço: faixa de dois metros e alvo só visual, sem cones; meta de 6 de 20.',
      harder: 'Tarefa: sequência pé de fora, pé de fora e, na terceira bola, o pé de dentro ou o meio que abriu. Bola acima da rede pode ser atacada.',
    },
    metric: { type: 'percentual', target: '10 de 20 na faixa' },
    success_criteria: 'Conta o dink que cai na faixa sem passar da altura da cintura do parceiro. 10 de 20 dos dois lados? Passe para a sequência da variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Base aberta, pernas dobradas e o corpo já voltado para a diagonal.',
        execucao: 'Gesto de baixo para cima um pouco mais longo que o do dink reto, sem acelerar.',
        finalizacao: 'A raquete para apontando a faixa e volta para a frente do corpo.',
      },
      abilities: ['precisao', 'equilibrio', 'leitura'],
    },
    when_to_use: 'Rally de dink cruzado em duplas, para tirar o adversário da linha e abrir o meio ou a paralela para a bola seguinte.',
    diagrams: [
      diagrama('A faixa do pé de fora', 'cozinha', [
        zona(5, 35, 22, 49, 'Pé de fora'),
        zona(78, 51, 95, 65, 'Pé de fora'),
        jogador(72, 68, 'a', 'A'),
        jogador(28, 32, 'b', 'B'),
        trajeto(72, 66, 14, 42, '1'),
        trajeto(28, 34, 86, 58, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-tres-alvos-ordem-chamada',
    version: 1,
    kind: 'drill',
    title: 'Dink em três alvos com a ordem chamada',
    summary: 'Três cones na cozinha do parceiro: à esquerda, no meio e à direita dele. Primeiro numa ordem fixa, depois o parceiro chama o alvo de cada bola. Treina mudar a direção sem mudar o ritmo.',
    objective: 'Ao final, o atleta consegue completar 10 sequências de três dinks, cada um no alvo chamado, mantendo o mesmo ritmo e a bola baixa.',
    skills: ['kitchen.dink_paralelo', 'kitchen.dink_cruzado', 'tactics.alvo'],
    level_min: 2.5,
    level_max: 3.5,
    players_min: 2,
    players_max: 2,
    roles: ['Quem chama', 'Executor'],
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'aleatorio',
    setup: 'Os dois na linha da cozinha, frente a frente, na mesma metade da quadra. Na cozinha do parceiro, três cones a um palmo da linha: um um metro à esquerda dele, um à frente dele e um um metro à direita. O parceiro devolve sempre um dink fácil para o meio do executor.',
    steps: [
      'Primeira série: o executor manda os dinks na ordem esquerda, meio e direita, e repete.',
      'Cada sequência só conta se os três dinks caírem perto do cone certo e baixos.',
      'Segunda série: o parceiro chama "esquerda", "meio" ou "direita" logo depois de devolver a bola.',
      'O executor manda o dink para o alvo chamado, no mesmo ritmo dos outros.',
      'Errou o alvo ou a bola subiu, a sequência recomeça; depois de 10 sequências, troquem.',
    ],
    cues: ['Mesmo ritmo nos três alvos', 'Raquete aponta o cone chamado', 'Ouça o alvo, depois a bola'],
    positioning: [
      { type: 'certo', text: 'Parado e equilibrado no contato, com a raquete na frente; a direção muda pela face da raquete, não pela força.' },
      { type: 'errado', text: 'Acelerar o gesto para chegar ao alvo lateral: a bola sobe e o parceiro pode atacar.' },
    ],
    common_errors: [
      { error: 'O dink lateral sai mais forte que o do meio.', fix: 'Mantenha o mesmo gesto curto nos três alvos e só aponte a raquete para o lado.' },
      { error: 'Você decide o alvo antes de ouvir a chamada e erra quando ela muda.', fix: 'Espere a chamada com a raquete na frente; a decisão vem do parceiro, não do hábito.' },
      { error: 'Com a pressa de acertar, a bola começa a subir.', fix: 'Volte à ordem fixa por uma série e só retome a chamada quando as bolas voltarem a descer antes da rede.' },
    ],
    variations: {
      easier: 'Tarefa: só dois alvos, um de cada lado, sem o do meio, e ordem fixa.',
      harder: 'Tarefa: o parceiro chama o alvo só depois que o executor começa o gesto e também move a própria posição na linha.',
    },
    metric: { type: 'sequencia', target: '10 sequências completas' },
    success_criteria: 'Conta a sequência de três dinks no alvo certo, todos abaixo da cintura do parceiro. 10 sequências com chamada? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Base aberta, raquete na frente da cintura, atenção na chamada.',
        execucao: 'Gesto curto de baixo para cima, com a face da raquete apontando o alvo.',
        finalizacao: 'A raquete para no alvo e volta ao centro antes da próxima bola.',
      },
      abilities: ['precisao', 'tempo_reacao', 'ritmo'],
    },
    when_to_use: 'Rally de dink contra quem já lê o seu padrão: mudar o alvo com o mesmo gesto tira a antecipação dele.',
    diagrams: [
      diagrama('Três alvos chamados', 'cozinha', [
        cone(60, 38),
        cone(75, 38),
        cone(90, 38),
        jogador(75, 32, 'b', 'Chama'),
        jogador(75, 68, 'a', 'Exec'),
        trajeto(73, 66, 61, 40, 'E'),
        trajeto(75, 66, 75, 40, 'M'),
        trajeto(77, 66, 89, 40, 'D'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'drop-cruzado-da-terceira-bola',
    version: 1,
    kind: 'drill',
    title: 'Drop cruzado da terceira bola',
    summary: 'Do fundo, você faz o drop na diagonal, para a cozinha do outro lado. A bola passa pela parte mais baixa da rede e tem mais quadra para cair: é o alvo de maior margem do drop.',
    objective: 'Ao final, o atleta consegue colocar 10 de 15 drops cruzados dentro da cozinha da diagonal, primeiro do lado mais fraco e depois do mais forte.',
    skills: ['groundstrokes.terceira_bola_drop', 'tactics.alvo'],
    level_min: 2.5,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    roles: ['Alimentador', 'Executor'],
    duration_min: 12,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'bloco',
    setup: 'O executor atrás da linha de fundo, no lado direito. O alimentador na linha da cozinha da diagonal, com o cesto, manda bolas fundas e fáceis, como uma devolução de saque. Dois cones marcam a cozinha da diagonal como alvo.',
    steps: [
      'Aquecimento: 5 drops retos, para a cozinha da frente, só para sentir a distância.',
      'O alimentador manda a bola funda e o executor faz o drop na diagonal, para a cozinha dele.',
      'O alimentador deixa a bola quicar para ver onde ela caiu e diz "dentro" ou "fora".',
      'Contem quantos dos 15 drops cruzados caem na cozinha.',
      'Comecem pelo lado mais fraco do executor e, depois de 15, passem para o outro lado da quadra.',
      'Terminadas as duas diagonais, troquem os papéis.',
    ],
    cues: ['Passe a bola pelo meio da rede', 'Pico da bola antes da rede', 'Mire o canto da cozinha'],
    positioning: [
      { type: 'certo', text: 'Parado e equilibrado no contato, com o corpo virado para a diagonal antes de a bola chegar.' },
      { type: 'errado', text: 'Abrir a diagonal no último instante com um puxão: a bola sai reta, alta ou para fora da lateral.' },
    ],
    common_errors: [
      { error: 'O executor só faz o drop reto porque a diagonal parece mais difícil.', fix: 'Lembre que a diagonal passa pela parte baixa da rede e tem mais quadra: é o alvo com mais margem.' },
      { error: 'A bola cai no fundo da quadra do outro lado.', fix: 'Faça o ponto mais alto da bola ficar do seu lado da rede; ela tem de passar descendo.' },
      { error: 'A bola sai pela lateral da cozinha.', fix: 'Mire o meio da cozinha da diagonal, não o canto junto à linha.' },
    ],
    variations: {
      easier: 'Espaço: o executor começa no meio da quadra e recua um passo a cada 3 drops certos.',
      harder: 'Tarefa: o alimentador varia o lado e a profundidade da bola, e o executor escolhe drop reto ou cruzado conforme a posição do alimentador na linha.',
    },
    metric: { type: 'percentual', target: '10 de 15 na cozinha' },
    success_criteria: 'Conta o drop cruzado que quica dentro da cozinha da diagonal. 10 de 15 nos dois lados? Use o cruzado como primeira escolha no jogo e passe à variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Corpo virado para a diagonal, pernas dobradas e raquete baixa, atrás da bola.',
        execucao: 'Gesto de baixo para cima, longo e lento, com as pernas levantando a bola.',
        finalizacao: 'A raquete termina apontando a cozinha da diagonal e você começa a avançar.',
      },
      abilities: ['precisao', 'coordenacao', 'equilibrio'],
    },
    when_to_use: 'Terceira bola em duplas, quando a devolução veio funda e você quer chegar à rede com a margem maior da diagonal.',
    diagrams: [
      diagrama('A diagonal do drop', 'inteira', [
        zona(5, 35, 48, 49, 'Alvo'),
        jogador(75, 96, 'a', 'Exec'),
        jogador(25, 32, 'b', 'Alim'),
        trajeto(25, 34, 72, 90, '1'),
        trajeto(75, 94, 28, 42, '2'),
        texto(64, 52, 'Rede baixa'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'drop-em-deslocamento-bola-larga',
    version: 1,
    kind: 'drill',
    title: 'Drop em deslocamento: a bola larga',
    summary: 'O alimentador manda a bola funda para um dos lados e você sai do meio para buscá-la. Treina chegar à bola equilibrado e fazer o drop mesmo tirado do lugar, como no jogo.',
    objective: 'Ao final, o atleta consegue fazer 6 de 10 drops na cozinha depois de se deslocar até uma bola larga, dos dois lados.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.transicao', 'physical.agilidade'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'variado',
    setup: 'O executor começa no meio da linha de fundo, marcado por um cone. O alimentador fica na linha da cozinha do outro lado, com o cesto, e manda bolas fundas a cerca de dois metros para a direita ou para a esquerda do cone.',
    steps: [
      'O alimentador anuncia o lado e manda a bola funda e larga.',
      'O executor sai do cone com passos laterais curtos e chega antes da bola.',
      'Faz o drop para a cozinha com o corpo equilibrado no contato.',
      'Volta ao cone andando e se prepara para a próxima.',
      'Na segunda série, o alimentador escolhe o lado sem avisar; depois de 10 bolas, troquem.',
    ],
    cues: ['Chegue antes da bola', 'Passos curtos até a bola', 'Pico da bola antes da rede'],
    positioning: [
      { type: 'certo', text: 'Chega ao lado da bola com passos curtos e bate com as pernas dobradas e o corpo estável, mesmo que ainda em movimento.' },
      { type: 'certo', text: 'Quando a bola o tira totalmente do lugar, joga um lob alto e fundo para o meio e ganha tempo para voltar.' },
      { type: 'errado', text: 'Chegar esticado, com o corpo caindo para o lado: o drop sobe ou morre na rede.' },
    ],
    common_errors: [
      { error: 'Você corre até a bola e bate ainda desequilibrado.', fix: 'Saia cedo, com passos curtos, e faça os dois últimos passos menores para chegar estável.' },
      { error: 'A bola fica atrás de você e o drop sai alto.', fix: 'Coloque-se do lado da bola, um pouco atrás dela, para bater na frente do corpo.' },
      { error: 'Insistir no drop com a bola muito longe.', fix: 'Esticado ao máximo, troque o drop por um lob alto e fundo no meio; é a bola de maior margem nessa situação.' },
    ],
    variations: {
      easier: 'Espaço: bolas a só um metro do cone, lentas e sempre anunciadas.',
      harder: 'Tarefa: bolas mais rápidas e às vezes curtas, obrigando a avançar; depois do drop, o executor sobe dois passos e para com um split step.',
    },
    metric: { type: 'percentual', target: '6 de 10 na cozinha' },
    success_criteria: 'Conta o drop que cai na cozinha com o executor equilibrado no contato. 6 de 10 nos dois lados, sem aviso? Passe para a variação mais difícil.',
    safety: 'Desloque-se de lado com passos curtos e volte andando ao cone; não ande de costas. Quadra molhada ou com areia: não faça.',
    motor: {
      phases: {
        preparacao: 'Leitura cedo do lado da bola e primeiro passo lateral.',
        execucao: 'Últimos passos curtos, base estável e gesto longo e lento de baixo para cima.',
        finalizacao: 'A raquete aponta a cozinha e você volta ao centro.',
      },
      abilities: ['agilidade', 'equilibrio', 'precisao', 'leitura'],
    },
    when_to_use: 'Terceira e quinta bolas em que a devolução veio funda e para o lado, longe de onde você estava.',
    diagrams: [
      diagrama('Sair do meio para a bola', 'inteira', [
        zona(15, 35, 85, 49, 'Alvo'),
        cone(50, 97),
        jogador(50, 93, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 34, 76, 90, '1'),
        desloca(54, 94, 72, 94),
        trajeto(76, 88, 56, 42, '2'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'reset-de-absorcao-no-paredao',
    version: 1,
    kind: 'drill',
    title: 'Reset de absorção no paredão',
    summary: 'Sozinho, na parede: um drive forte, e a volta rápida é amortecida para tocar a parede logo acima da linha da rede e cair perto dela. O treino solo do reset contra bola com força.',
    objective: 'Ao final, o atleta consegue amortecer 15 de 20 bolas rápidas, tocando a parede até um palmo acima da linha da rede e com o quique a menos de um metro dela.',
    skills: ['net.reset', 'net.voleio'],
    level_min: 2.5,
    level_max: 4.0,
    players_min: 1,
    players_max: 1,
    duration_min: 10,
    intensity: 4,
    place: ['parede'],
    equipment: ['bolas', 'parede'],
    practice_mode: 'bloco',
    setup: 'Parede lisa e piso firme. Marque com fita uma linha a 86 cm do chão (a altura da rede no meio) e outra um palmo acima: a faixa entre elas é o alvo. Fique a cerca de três metros da parede.',
    steps: [
      'Bata um drive firme na parede, acima da faixa, para a bola voltar rápida.',
      'Na volta, de voleio ou depois do quique, ofereça a raquete parada na frente do corpo.',
      'Amorteça a bola para ela tocar a faixa e cair perto da parede.',
      'Pegue a bola ou recomece com outro drive; conte os resets certos em séries de 20.',
      'Faça 10 de forehand, 10 de backhand e depois alterne sem planejar.',
    ],
    cues: ['Raquete parada, a bola vem até ela', 'Toque a faixa e morra perto', 'Face só um pouco aberta'],
    positioning: [
      { type: 'certo', text: 'Base baixa e raquete na frente do corpo antes de a bola voltar, com a mão segurando a raquete sem apertar.' },
      { type: 'errado', text: 'Ir buscar a bola com um balanço: ela volta forte e alta, como uma bola de ataque para o adversário.' },
    ],
    common_errors: [
      { error: 'A bola bate alto na parede e volta longe.', fix: 'Diminua o gesto até quase nada e deixe a face só um pouco aberta; quem dá a força é a bola.' },
      { error: 'A bola bate abaixo da linha, que no jogo seria rede.', fix: 'Abra a face um pouco mais e encontre a bola na frente do corpo, não ao lado.' },
      { error: 'A mão aperta no contato e a bola sai pulando.', fix: 'Segure a raquete com firmeza média do começo ao fim; aperte menos do que no drive.' },
    ],
    variations: {
      easier: 'Equipamento: drive a meia força e a bola sempre depois do quique, só de forehand.',
      harder: 'Espaço: comece a cinco metros da parede e, a cada reset certo, dê um passo à frente, até três metros; o drive fica cada vez mais rápido.',
    },
    metric: { type: 'percentual', target: '15 de 20 na faixa' },
    success_criteria: 'Conta o reset que toca a faixa e quica a menos de um metro da parede. 15 de 20 alternando forehand e backhand? Passe para a variação mais difícil e leve o reset para o jogo 7-11.',
    motor: {
      phases: {
        preparacao: 'Base baixa, raquete na frente do corpo e face levemente aberta.',
        execucao: 'A raquete fica quase parada e cede um pouco no contato, absorvendo a força.',
        finalizacao: 'A raquete volta para a frente do corpo, pronta para a próxima.',
      },
      abilities: ['tempo_reacao', 'precisao', 'coordenacao'],
    },
    when_to_use: 'Treino sozinho do reset, entre as sessões de quadra; não substitui o reset contra um adversário de verdade.',
    diagrams: [
      diagrama('Drive e reset na parede', 'meia', [
        zona(5, 41, 95, 45, 'Parede'),
        jogador(50, 82, 'a'),
        trajeto(54, 80, 60, 46, '1 drive'),
        trajeto(58, 46, 52, 78, '2'),
        trajeto(46, 80, 42, 47, '3 reset'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-com-deslocamento-lateral-sem-aviso',
    version: 1,
    kind: 'drill',
    title: 'Dink com deslocamento lateral sem aviso',
    summary: 'O alimentador manda dinks ora para a direita, ora para a esquerda, sem avisar. Você se desloca de lado pela linha da cozinha, chega parado e devolve. Junta o passo lateral ao dink.',
    objective: 'Ao final, o atleta consegue devolver 30 dinks seguidos para a cozinha do alimentador, chegando a cada bola com passos laterais e equilibrado.',
    skills: ['physical.agilidade', 'kitchen.dink_paralelo', 'kitchen.paciencia'],
    level_min: 2.5,
    level_max: 3.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'cones'],
    practice_mode: 'aleatorio',
    setup: 'Os dois na linha da cozinha, frente a frente. Um cone marca o centro do executor e outros dois, um a cada lado, a cerca de dois metros dele. O alimentador, com o cesto, manda dinks para perto de um dos cones laterais, em ordem que só ele sabe.',
    steps: [
      'O executor espera no cone do centro, com a raquete na frente.',
      'O alimentador manda um dink para um dos lados, sem avisar.',
      'O executor vai até a bola com passos laterais, chega parado e devolve um dink para a cozinha do alimentador.',
      'Volta ao centro com passos laterais antes da próxima bola.',
      'Séries de 25 bolas com 60 segundos de descanso; depois de duas séries, troquem.',
    ],
    cues: ['Chegue parado, depois bata', 'Raquete na frente o tempo todo', 'Olho na bola, passo curto'],
    positioning: [
      { type: 'certo', text: 'Passos laterais curtos, de frente para a rede, chegando ao lado da bola com a base aberta.' },
      { type: 'certo', text: 'Na bola bem larga do lado do backhand, um passo cruzado para alcançá-la vale; depois volte com passos laterais.' },
      { type: 'errado', text: 'Esticar a raquete sem mexer os pés: a bola fica no limite do alcance e o dink sobe.' },
    ],
    common_errors: [
      { error: 'Você cruza as pernas em toda bola e chega desequilibrado.', fix: 'Para bola perto, só passos laterais; deixe o passo cruzado para a bola muito larga do backhand.' },
      { error: 'Bate ainda andando e o dink sai alto.', fix: 'Encurte o último passo e pare antes de bater, mesmo que por um instante.' },
      { error: 'Fica no lado onde bateu e a bola seguinte o pega fora do lugar.', fix: 'Depois de cada dink, volte ao cone do centro antes de o alimentador bater.' },
    ],
    variations: {
      easier: 'Tarefa: o alimentador avisa o lado e manda as bolas devagar, a um metro do centro.',
      harder: 'Tarefa: o alimentador mistura dinks curtos, que exigem avançar, e de vez em quando uma bola mais rápida no corpo para bloquear.',
    },
    metric: { type: 'sequencia', target: '30 seguidos' },
    success_criteria: 'Conta o dink devolvido na cozinha com o executor parado no contato. 30 seguidos sem esticar nem cruzar à toa? Passe para a variação mais difícil.',
    safety: 'Passos curtos e quadra seca; se cansar e começar a arrastar os pés, encerre a série. Quem tem dor no joelho ou no tornozelo reduz a distância dos cones.',
    motor: {
      phases: {
        preparacao: 'Base aberta e baixa no centro, raquete na frente, atenção no alimentador.',
        execucao: 'Passos laterais curtos até a bola e dink curto de baixo para cima.',
        finalizacao: 'Volta ao centro com passos laterais, raquete na frente.',
      },
      abilities: ['agilidade', 'equilibrio', 'tempo_reacao', 'precisao'],
    },
    when_to_use: 'Rally de cozinha em que o adversário move você de um lado para o outro da linha.',
    diagrams: [
      diagrama('Para um lado ou para o outro', 'cozinha', [
        cone(30, 68),
        cone(50, 68),
        cone(70, 68),
        jogador(50, 72, 'a', 'Exec'),
        jogador(50, 32, 'b', 'Alim'),
        trajeto(50, 34, 32, 64, '?'),
        trajeto(50, 34, 68, 64, '?'),
        desloca(46, 72, 34, 72),
        desloca(54, 72, 66, 72),
      ]),
    ],
    media: [],
  },
];
