/**
 * Biblioteca — drills importados do pacote "100 drills" (nível 1, iniciante).
 * Cada item foi avaliado, corrigido e reescrito; a avaliação de todos os 20
 * da fonte (inclusive os duplicados e o rejeitado) fica fora do código.
 */

import { cone, desloca, diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

const PARE_SE_DOER = 'Sentiu dor (não cansaço), tontura ou falta de ar fora do normal? Pare. Quem tem lesão ou alguma condição de saúde segue a orientação do seu profissional de saúde.';

export const IMPORTADOS_NIVEL1 = [
  {
    slug: 'rebatida-de-fundo-no-paredao',
    version: 1,
    kind: 'drill',
    title: 'Rebatida de fundo no paredão',
    summary: 'Sozinho, contra uma parede: forehand e backhand depois do quique, em ritmo médio, contando os golpes seguidos. Constrói um contato limpo e repetível antes de jogar contra alguém.',
    objective: 'Ao final, o atleta consegue manter 20 rebatidas seguidas depois do quique contra a parede, primeiro só de forehand e depois alternando com o backhand.',
    skills: ['groundstrokes.drive', 'groundstrokes'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 1,
    players_max: 1,
    duration_min: 10,
    intensity: 3,
    place: ['parede', 'quadra'],
    equipment: ['parede', 'bolas', 'raquete'],
    practice_mode: 'bloco',
    setup: 'Uma parede lisa (muro, porta de garagem, paredão de quadra) com piso firme na frente. Marque com fita uma linha a 86 cm do chão, a altura da rede no meio. Fique a 4 ou 5 metros da parede, com uma bola e a raquete.',
    steps: [
      'Jogue a bola na parede acima da linha, deixe quicar uma vez e rebata de forehand.',
      'Mantenha um ritmo médio: a bola tem de voltar para perto de você, sem obrigar a correr.',
      'Conte as rebatidas seguidas acima da linha; bola abaixo dela ou dois quiques zera a conta.',
      'Fechou 20 de forehand, faça o mesmo só de backhand.',
      'Depois alterne um forehand e um backhand, dando um passo lateral entre os golpes.',
      'Faça 4 séries de 2 minutos, com 45 segundos de descanso.',
    ],
    cues: ['Bola na frente, depois do quique', 'Mire um palmo acima da linha', 'Raquete termina apontando a parede'],
    positioning: [
      { type: 'certo', text: 'De lado para a parede quando a bola chega, com espaço para a raquete passar na frente do corpo.' },
      { type: 'errado', text: 'De frente e colado à bola: o golpe sai espremido e a bola volta torta.' },
    ],
    common_errors: [
      { error: 'Você bate forte e a bola volta rápida demais para a próxima rebatida.', fix: 'Reduza a força pela metade: aqui vale a sequência, não a velocidade.' },
      { error: 'A bola bate abaixo da linha.', fix: 'Encontre a bola na frente e termine a raquete subindo na direção do alvo.' },
      { error: 'Você fica parado e a bola quica no seu pé.', fix: 'Dê passos curtos até a bola e chegue parado antes de bater.' },
    ],
    variations: {
      easier: 'Espaço: fique a 3 metros e pare para segurar a bola com a mão a cada 5 rebatidas; meta de 10 seguidas.',
      harder: 'Tarefa: alterne uma bola alta e funda com uma baixa, perto da linha, sem perder a sequência.',
    },
    metric: { type: 'sequencia', target: '20 seguidas' },
    success_criteria: 'Conta a rebatida acima da linha, depois de um quique só. 20 seguidas de forehand e 20 alternando? Passe para os dois alvos na parede.',
    motor: {
      phases: {
        preparacao: 'Passos curtos até a bola, de lado para a parede, raquete atrás e baixa.',
        execucao: 'Gesto de baixo para cima, com o contato na frente do corpo e o peso indo para a frente.',
        finalizacao: 'A raquete termina apontando a parede e você volta ao centro.',
      },
      abilities: ['coordenacao', 'ritmo', 'precisao'],
    },
    when_to_use: 'Treino sozinho entre as sessões de quadra, para quem ainda erra o contato nos golpes de fundo.',
    diagrams: [
      diagrama('Rebatida no paredão', 'meia', [
        zona(5, 41, 95, 45, 'Parede'),
        jogador(50, 80, 'a', 'A'),
        trajeto(50, 78, 50, 46, '1'),
        trajeto(50, 46, 60, 76, '2'),
        desloca(56, 82, 64, 82),
      ]),
    ],
    media: [],
  },
  {
    slug: 'bola-quicando-na-raquete',
    version: 1,
    kind: 'drill',
    title: 'Bola quicando na raquete',
    summary: 'Faça a bola quicar para cima na raquete, sem deixá-la cair, primeiro parado e depois andando. Dá a mão leve que o dink e o reset pedem.',
    objective: 'Ao final, o atleta consegue fazer 40 toques seguidos para cima com a bola em altura constante, alternando as duas faces da raquete.',
    skills: ['kitchen', 'net.reset'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 1,
    players_max: 1,
    duration_min: 5,
    intensity: 1,
    place: ['quadra', 'casa'],
    equipment: ['raquete', 'bolas'],
    practice_mode: 'bloco',
    setup: 'Qualquer espaço livre, com teto alto e sem nada frágil por perto. Uma bola e a raquete segurada com pressão leve, a face virada para cima.',
    steps: [
      'Raquete na frente da cintura, face para cima: toque a bola para que ela suba até a altura do peito.',
      'Deixe a raquete ceder um pouco quando a bola cai, como quem amortece, e toque de novo.',
      'Conte os toques seguidos sem a bola cair no chão.',
      'Fechou 20, mantenha a bola em altura menor, na altura da cintura.',
      'Depois alterne as faces da raquete a cada toque (forehand e backhand).',
      'Por fim, faça os toques andando em linha reta de uma lateral à outra.',
    ],
    cues: ['Bola sobe sempre na mesma altura', 'Raquete cede quando a bola chega', 'Olhos na bola, raquete leve'],
    positioning: [
      { type: 'certo', text: 'Pernas dobradas e raquete na frente da cintura, com espaço para a bola subir e descer na sua frente.' },
      { type: 'errado', text: 'Raquete colada ao corpo e pernas esticadas: cada toque sai mais forte que o outro e a bola foge.' },
    ],
    common_errors: [
      { error: 'Cada toque sai mais alto que o anterior.', fix: 'Encurte o gesto: a raquete sobe só um palmo e cede quando a bola volta.' },
      { error: 'A bola escapa para os lados.', fix: 'Mantenha a face da raquete reta, paralela ao chão, e toque no meio dela.' },
      { error: 'Você segura a raquete com força.', fix: 'Aperte o cabo só o bastante para ele não girar; a mão leve é o que amortece.' },
    ],
    variations: {
      easier: 'Tarefa: um toque, deixa a bola quicar no chão, outro toque; meta de 20 seguidos.',
      harder: 'Tarefa: alterne um toque alto e um baixo, ou ande pela linha da cozinha alternando as faces sem parar.',
    },
    metric: { type: 'sequencia', target: '40 toques seguidos' },
    success_criteria: 'Conta o toque em que a bola não cai e fica entre a cintura e o peito. 40 seguidos alternando as faces? Leve a mão leve para os primeiros dinks.',
    motor: {
      phases: {
        preparacao: 'Pernas dobradas, raquete na frente da cintura, pressão leve no cabo.',
        execucao: 'Toque curto para cima, com a raquete cedendo quando a bola cai.',
        finalizacao: 'A raquete volta para baixo da bola, pronta para o próximo toque.',
      },
      abilities: ['coordenacao', 'precisao', 'ritmo'],
    },
    when_to_use: 'Aquecimento de mão antes da quadra, ou um treino rápido em casa para quem está começando.',
    diagrams: [
      diagrama('Andando pela linha', 'cozinha', [
        jogador(15, 70, 'a', 'A'),
        desloca(20, 70, 85, 70),
        texto(50, 62, 'Toques'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'golpes-de-sombra-saque-drop-dink',
    version: 1,
    kind: 'drill',
    title: 'Golpes de sombra: saque, drop e dink',
    summary: 'Sem bola, de frente para um espelho ou janela: repita o saque, o drop e o dink devagar e depois no ritmo do jogo. Fixa o desenho do golpe em casa, em poucos minutos.',
    objective: 'Ao final, o atleta repete 20 vezes cada golpe (saque, drop e dink) com o mesmo desenho do começo ao fim, conferindo no reflexo.',
    skills: ['serve.consistencia', 'groundstrokes.terceira_bola_drop', 'kitchen.dink_paralelo'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 1,
    players_max: 4,
    duration_min: 10,
    intensity: 1,
    place: ['casa', 'quadra'],
    equipment: ['raquete'],
    practice_mode: 'bloco',
    setup: 'Um espelho, porta de vidro ou janela em que você se veja de corpo inteiro, com espaço para balançar a raquete sem bater em nada. Marque com fita um ponto no chão à sua frente: é onde estaria a bola no contato.',
    steps: [
      'Saque: 20 vezes devagar, com a raquete passando de baixo para cima e o contato imaginário abaixo da cintura, na frente do corpo.',
      'Drop: 20 vezes, gesto de baixo para cima, como quem levanta a bola por cima da rede, terminando a raquete apontando o alvo.',
      'Dink: 20 vezes, gesto curto, raquete na frente e face um pouco aberta.',
      'Confira no reflexo, a cada repetição, se a raquete passa pelo ponto marcado no chão.',
      'Repita a série no ritmo do jogo, sem perder o desenho.',
      'Nas últimas 5 de cada golpe, feche os olhos e abra no fim para conferir onde a raquete parou.',
    ],
    cues: ['Raquete passa pela marca no chão', 'Mesmo desenho, do primeiro ao último', 'Raquete termina apontando o alvo'],
    positioning: [
      { type: 'certo', text: 'Base aberta, pernas dobradas e o contato imaginário sempre na frente do corpo, sobre a marca.' },
      { type: 'errado', text: 'Gesto feito só com a mão, de pernas esticadas: o desenho muda a cada repetição e não vale para a quadra.' },
    ],
    common_errors: [
      { error: 'Você acelera e o gesto encolhe.', fix: 'Volte ao ritmo lento até o desenho sair igual 5 vezes seguidas.' },
      { error: 'No saque, a raquete termina alta demais, acima da cabeça.', fix: 'Pare a raquete na altura do alvo imaginado do outro lado, à frente.' },
      { error: 'O dink vira um balanço grande.', fix: 'Use a marca no chão: a raquete anda só um palmo antes e depois dela.' },
    ],
    variations: {
      easier: 'Tarefa: só um golpe por dia, 20 repetições lentas.',
      harder: 'Tarefa: um parceiro fala "saque", "drop" ou "dink" em ordem aleatória e você executa na hora, voltando à base entre os golpes.',
    },
    metric: { type: 'reps', target: '20 de cada golpe' },
    success_criteria: 'Conta a repetição em que a raquete passou pela marca e terminou apontando o alvo. 20 de cada, iguais, no ritmo do jogo? Leve para a quadra, com bola.',
    motor: {
      phases: {
        preparacao: 'Base aberta, pernas dobradas, raquete na frente e olhar na marca.',
        execucao: 'Gesto de baixo para cima passando pela marca, no tamanho de cada golpe.',
        finalizacao: 'A raquete para apontando o alvo e volta à base.',
      },
      abilities: ['coordenacao', 'ritmo'],
    },
    when_to_use: 'Em casa, nos dias sem quadra, ou nos 5 minutos antes de entrar na quadra para lembrar o desenho do golpe.',
    diagrams: [
      diagrama('Marca de contato', 'meia', [
        zona(30, 41, 70, 45, 'Espelho'),
        jogador(50, 80, 'a', 'A'),
        cone(50, 72),
        texto(62, 72, 'Marca'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dois-alvos-na-parede-direcao',
    version: 1,
    kind: 'drill',
    title: 'Dois alvos na parede: escolha a direção',
    summary: 'Duas caixas marcadas na parede, uma à esquerda e outra à direita. Você diz qual vai acertar antes de bater. Treina direção do golpe de fundo, sozinho.',
    objective: 'Ao final, o atleta acerta 7 de 10 rebatidas na caixa anunciada, a 5 metros da parede, alternando forehand e backhand.',
    skills: ['groundstrokes.drive', 'tactics.alvo'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 1,
    players_max: 2,
    roles: ['Quem chama o alvo'],
    duration_min: 12,
    intensity: 3,
    place: ['parede', 'quadra'],
    equipment: ['parede', 'bolas', 'raquete', 'alvo'],
    practice_mode: 'variado',
    setup: 'Com fita, desenhe na parede duas caixas de uns 50 por 50 centímetros, com a parte de baixo logo acima da altura da rede (86 cm) e cerca de 2 metros entre elas. Fique a 4 metros da parede, no meio das duas caixas, com bolas à mão.',
    steps: [
      'Solte a bola, deixe quicar e rebata de forehand na caixa da direita, 10 vezes.',
      'Faça o mesmo na caixa da esquerda, 10 vezes.',
      'Agora diga em voz alta "direita" ou "esquerda" antes de cada bola e mire a caixa anunciada.',
      'Conte quantas de 10 acertam a caixa certa.',
      'Fez 7 de 10, recue 1 metro e repita, até chegar a 6 metros.',
    ],
    cues: ['Anuncie o alvo, depois bata', 'Raquete termina apontando a caixa', 'Mire o meio da caixa'],
    positioning: [
      { type: 'certo', text: 'Pés arrumados antes de cada bola, de lado para a parede e com a frente do corpo virada para a caixa escolhida.' },
      { type: 'errado', text: 'Pés escorregando na direção da bola no último instante: a base some e a bola vai para onde o corpo caiu.' },
    ],
    common_errors: [
      { error: 'A bola acerta sempre o mesmo lado, seja qual for o anúncio.', fix: 'Vire os pés para a caixa anunciada antes de a bola quicar.' },
      { error: 'Você anuncia tarde, com a bola já chegando.', fix: 'Fale o alvo enquanto a bola ainda está a caminho da parede.' },
      { error: 'Você recua e passa a errar quase tudo.', fix: 'Abaixo de 4 de 10, volte um metro; distância só cresce com a meta batida.' },
    ],
    variations: {
      easier: 'Espaço: caixas maiores (1 metro) e a 3 metros da parede, só de forehand.',
      harder: 'Pessoas: um parceiro atrás de você grita o alvo quando a bola bate na parede; você tem só o tempo do quique para decidir.',
    },
    metric: { type: 'percentual', target: '7 de 10 na caixa anunciada' },
    success_criteria: 'Conta a bola que acerta a caixa anunciada. 7 de 10 a 5 metros, alternando forehand e backhand? Passe para a devolução em três alvos.',
    motor: {
      phases: {
        preparacao: 'Anuncie o alvo e arrume os pés de lado para a parede, virados para a caixa.',
        execucao: 'Gesto de baixo para cima com a bola na frente do corpo.',
        finalizacao: 'A raquete termina apontando a caixa; volte ao meio.',
      },
      abilities: ['precisao', 'coordenacao'],
    },
    when_to_use: 'Quando a bola já volta com consistência da parede e falta escolher para onde ela vai.',
    diagrams: [
      diagrama('Duas caixas', 'meia', [
        zona(15, 41, 35, 45, 'Esquerda'),
        zona(65, 41, 85, 45, 'Direita'),
        jogador(50, 80, 'a', 'A'),
        trajeto(50, 78, 25, 46, 'E'),
        trajeto(50, 78, 75, 46, 'D'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'saque-com-efeito-da-raquete',
    version: 1,
    kind: 'drill',
    title: 'Saque com efeito dado pela raquete',
    summary: 'Saques liso, com efeito para a frente, cortado e lateral, todos gerados pela raquete no contato. O parceiro diz qual efeito veio. Para quem já põe a bola em jogo com segurança.',
    objective: 'Ao final, o atleta consegue sacar dentro da área com três efeitos diferentes, e o parceiro reconhece o efeito certo em 4 de 5 saques.',
    skills: ['serve.consistencia', 'serve.saque_profundo', 'rules.saque'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 2,
    roles: ['Sacador', 'Quem lê o efeito'],
    duration_min: 15,
    intensity: 2,
    place: QUADRA,
    equipment: ['bolas', 'cesto', 'raquete'],
    practice_mode: 'variado',
    setup: 'Sacador atrás da linha de fundo com o cesto; o parceiro do outro lado, na posição de devolução da diagonal. Pela regra, o efeito só pode vir da raquete no contato: soltar a bola girando com a mão ou com a raquete é falta (vale para o saque de voleio e para o saque com quique).',
    steps: [
      'Saque 5 bolas lisas, só para acertar a área com a mesma altura sobre a rede.',
      'Saque 5 com efeito para a frente: a raquete sobe por trás da bola e termina alta.',
      'Saque 5 cortados: a raquete passa por baixo da bola, com a face um pouco aberta.',
      'Saque 5 com efeito lateral: a raquete passa por fora da bola, de um lado para o outro.',
      'Depois, misture os efeitos sem avisar; o parceiro deixa quicar, diz qual efeito veio e devolve.',
      'A cada 20 saques, troquem os papéis e a diagonal.',
    ],
    cues: ['Solte a bola parada, sem girar', 'O efeito nasce no contato', 'Primeiro dentro, depois efeito'],
    positioning: [
      { type: 'certo', text: 'Bola apenas solta da mão, sem giro; o efeito vem do caminho da raquete no contato, que no saque de voleio é abaixo da cintura e de baixo para cima.' },
      { type: 'certo', text: 'No saque com quique a bola pode cair de qualquer altura natural, e as exigências do saque de voleio não se aplicam.' },
      { type: 'errado', text: 'Girar a bola com os dedos (ou na raquete) antes de soltá-la: é falta desde 2023.' },
    ],
    common_errors: [
      { error: 'O efeito sai, mas metade dos saques erra a área.', fix: 'Volte ao saque liso até acertar 9 de 10 e só então acrescente um efeito por vez.' },
      { error: 'Você gira a bola com a mão ao soltar.', fix: 'Solte a bola com a mão aberta e parada; quem dá o efeito é a raquete.' },
      { error: 'No saque de voleio, a raquete sobe acima do punho para dar efeito lateral.', fix: 'Mantenha a cabeça da raquete abaixo do punho no contato, ou use o saque com quique para o efeito lateral.' },
    ],
    variations: {
      easier: 'Tarefa: só liso e com efeito para a frente, 5 de cada, com saque com quique.',
      harder: 'Tarefa: o efeito escolhido tem de cair no terço final da área; o parceiro devolve para valer e o ponto é jogado.',
    },
    metric: { type: 'percentual', target: '4 de 5 efeitos reconhecidos' },
    success_criteria: 'Conta o saque válido em que o parceiro acertou o efeito. Três efeitos com 4 de 5 reconhecidos e 8 de 10 dentro? Use o efeito em jogo, não só no treino.',
    motor: {
      phases: {
        preparacao: 'De lado para a rede, bola parada na mão aberta, raquete atrás e baixa.',
        execucao: 'Solte a bola sem girar e escove a bola com a raquete no caminho do efeito escolhido.',
        finalizacao: 'A raquete termina na direção do alvo e você volta à posição atrás da linha.',
      },
      abilities: ['precisao', 'coordenacao', 'leitura'],
    },
    when_to_use: 'Quando o saque já entra quase sempre e o devolvedor começa a atacar a devolução: variar o efeito tira o ritmo dele.',
    diagrams: [
      diagrama('Saque e leitura', 'inteira', [
        jogador(75, 97, 'a', 'Sac'),
        jogador(25, 3, 'b', 'Lê'),
        zona(1, 1, 49, 15, 'Fundo'),
        trajeto(75, 95, 30, 10, '1'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'devolucao-em-tres-alvos-fundos',
    version: 1,
    kind: 'drill',
    title: 'Devolução em três alvos fundos',
    summary: 'O devolvedor anuncia o alvo antes de bater: fundo no meio, fundo no backhand do sacador ou fundo na outra lateral. Junta profundidade e direção na devolução.',
    objective: 'Ao final, o atleta coloca 7 de 10 devoluções no alvo fundo anunciado antes do contato, sem perder profundidade.',
    skills: ['serve.devolucao_profunda', 'tactics.alvo', 'tactics.selecao_golpe'],
    level_min: 2.5,
    level_max: 3.5,
    players_min: 2,
    players_max: 4,
    roles: ['Sacador', 'Devolvedor'],
    duration_min: 12,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'cesto'],
    practice_mode: 'variado',
    setup: 'No lado do sacador, uma fileira de cones a cerca de 1 metro da linha de fundo marca a faixa funda. Dentro dela, três alvos (toalha, cone deitado ou bambolê): um no meio, um em cada canto. O devolvedor fica um passo atrás da linha de fundo, na diagonal do sacador.',
    steps: [
      'O sacador saca na diagonal, sem forçar.',
      'Antes de a bola quicar, o devolvedor diz em voz alta "meio", "esquerda" ou "direita".',
      'O devolvedor deixa quicar e devolve alto e fundo, mirando o alvo anunciado.',
      'Depois de devolver, ele anda até a linha da cozinha e volta para a próxima.',
      'Contem quantas de 10 caem na faixa funda e perto do alvo anunciado.',
      'A cada 10 devoluções, troquem os papéis e a diagonal.',
    ],
    cues: ['Diga o alvo antes do quique', 'Alto e fundo, depois a direção', 'Mire o fundo do meio'],
    positioning: [
      { type: 'certo', text: 'Um passo atrás da linha de fundo para esperar o saque, andando para a frente ao bater.' },
      { type: 'errado', text: 'Em cima da linha de fundo: o saque fundo empurra você para trás e a devolução sai curta.' },
    ],
    common_errors: [
      { error: 'Para acertar o canto, a devolução sai curta ou fora.', fix: 'Profundidade primeiro: mire um metro para dentro da lateral e por cima da faixa funda.' },
      { error: 'Você vira para o alvo só no contato e a bola sai torta.', fix: 'Anuncie cedo e vire os pés para o alvo enquanto a bola quica.' },
      { error: 'Escolhe sempre o meio.', fix: 'Sorteiem a ordem dos alvos na série: dois de cada antes de repetir.' },
    ],
    variations: {
      easier: 'Tarefa: dois alvos só (meio e o backhand do sacador) e alimentação com a mão em vez do saque.',
      harder: 'Tarefa: o sacador anda um passo para o lado que quiser antes de sacar, e o devolvedor escolhe o alvo pela posição dele, sem anunciar.',
    },
    metric: { type: 'percentual', target: '7 de 10 no alvo anunciado' },
    success_criteria: 'Conta a devolução que cai na faixa funda e no terço do alvo anunciado. 7 de 10 nos dois lados? Jogue o ponto inteiro a partir da devolução.',
    motor: {
      phases: {
        preparacao: 'Um passo atrás da linha, base aberta, decidindo o alvo enquanto o saque vem.',
        execucao: 'Pés virados para o alvo, gesto longo de baixo para cima, bola alta e funda.',
        finalizacao: 'A raquete termina apontando o alvo e você já começa a andar para a cozinha.',
      },
      abilities: ['precisao', 'leitura', 'coordenacao'],
    },
    when_to_use: 'Quando a devolução já sai funda e é hora de escolher o lado: o fundo do meio cria a dúvida de quem bate, o backhand do sacador costuma render a terceira bola mais fraca.',
    diagrams: [
      diagrama('Três alvos fundos', 'inteira', [
        cone(5, 12),
        cone(50, 12),
        cone(95, 12),
        texto(10, 5, 'Canto'),
        texto(50, 5, 'Meio'),
        texto(90, 5, 'Canto'),
        jogador(25, 3, 'b', 'Sac'),
        jogador(75, 98, 'a', 'Dev'),
        trajeto(25, 5, 72, 90, '1'),
        trajeto(75, 96, 50, 6, '2'),
        desloca(78, 94, 72, 70),
      ]),
    ],
    media: [],
  },
  {
    slug: 'escada-de-agilidade-pes-rapidos',
    version: 1,
    kind: 'fisico',
    title: 'Escada de agilidade: pés rápidos e leves',
    summary: 'Sequências na escada de agilidade (dentro-dentro-fora-fora, passo lateral) com toque curto no chão, terminando com freada e split step. Treina pés rápidos e a parada que o jogo pede.',
    objective: 'Ao final, o atleta faz 3 passagens de cada padrão sem pisar na escada e termina cada uma parado em split step, equilibrado.',
    skills: ['physical.agilidade', 'physical.aquecimento'],
    level_min: 2.0,
    players_min: 1,
    players_max: 6,
    duration_min: 10,
    intensity: 5,
    place: ['quadra', 'academia', 'casa'],
    equipment: ['escada'],
    practice_mode: 'bloco',
    sets: 3,
    reps: '1 passagem de cada padrão',
    rest_sec: 60,
    steps: [
      'Faça antes o aquecimento dinâmico: escada não é o primeiro movimento do dia.',
      'Passo em cada quadrado, andando, para pegar o ritmo.',
      'Dentro-dentro-fora-fora, de frente: os dois pés entram no quadrado, os dois saem dos lados, e assim até o fim.',
      'Passo lateral: de lado para a escada, os dois pés passam por cada quadrado, sem cruzar as pernas.',
      'No fim de cada passagem, freie e pare em split step, raquete na frente, por 2 segundos.',
      'Volte andando até o começo; a volta é o descanso. As duas primeiras séries são lentas, a última mais rápida.',
    ],
    cues: ['Toque curto, chão quente', 'Olhar à frente, no fim da escada', 'Pare firme no final'],
    common_errors: [
      { error: 'Pisar na escada e perder o ritmo ao acelerar.', fix: 'Volte à velocidade em que não pisa em nada: primeiro limpo, depois rápido.' },
      { error: 'Joelhos caindo para dentro nas trocas de direção.', fix: 'Mantenha os joelhos alinhados com a ponta dos pés, inclusive na freada.' },
      { error: 'Olhar fixo nos pés o tempo todo.', fix: 'Olhe para o fim da escada e confira os pés só de relance.' },
    ],
    variations: {
      easier: 'Tarefa: só o passo em cada quadrado e o dentro-dentro-fora-fora, andando, 2 passagens de cada.',
      harder: 'Tarefa: no fim da escada um parceiro aponta para a esquerda ou a direita, e você sai dois passos laterais para aquele lado antes da freada.',
    },
    safety: `Use tênis de quadra e uma escada que não escorregue; piso molhado ou com areia, não faça. Qualidade antes de velocidade: pare a série quando o passo ficar pesado. ${PARE_SE_DOER}`,
    motor: {
      phases: {
        preparacao: 'Pernas um pouco dobradas, peso na frente dos pés, olhar no fim da escada.',
        execucao: 'Toques curtos e rápidos no chão, sem pisar na escada nem cruzar as pernas.',
        finalizacao: 'Freada com a base aberta e split step, raquete na frente.',
      },
      abilities: ['agilidade', 'coordenacao', 'ritmo', 'equilibrio'],
    },
    diagrams: [
      diagrama('Escada e freada', 'meia', [
        zona(40, 50, 60, 90, 'Escada'),
        jogador(50, 95, 'a', 'A'),
        desloca(50, 92, 50, 52),
        texto(50, 44, 'Split'),
      ]),
    ],
    media: [],
  },
];
