/** Biblioteca inicial — drills importados do pacote "100 drills", nível 5 (4.0+), revisados e reescritos. */

import { bolinha, desloca, diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const IMPORTADOS_NIVEL5 = [
  {
    slug: 'defesa-contra-o-erne',
    version: 1,
    kind: 'drill',
    title: 'Defesa contra o Erne: ler a saída e jogar no espaço',
    summary: 'Você dinka paralelo e o adversário pode sair pela lateral para o Erne. A missão é ler a saída e mandar a bola para onde ele estava, em vez de perseguir o poste.',
    objective: 'Ao final, o atleta reconhece a preparação do Erne e responde com a bola no espaço que o adversário deixou em 6 de 10 tentativas.',
    skills: ['net.erne', 'tactics.leitura_adversario', 'tactics.alvo', 'kitchen.dink_cruzado'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 4,
    roles: ['Defensor', 'Quem tenta o Erne'],
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'aleatorio',
    setup: 'Os dois na linha da cozinha, frente a frente, junto à mesma lateral: o defensor embaixo, quem tenta o Erne em cima. Deixem livre o espaço fora da quadra, ao lado do poste. Com quatro pessoas, os parceiros ficam na outra metade e só entram quando a bola vai para o meio.',
    steps: [
      'O defensor dinka paralelo, junto à lateral; o outro devolve dinks normais.',
      'Quem tenta o Erne escolhe a hora: sai pela lateral, por fora da cozinha, e volea a bola perto do poste.',
      'O defensor observa os sinais da saída: o adversário colando na lateral e dando passos para fora antes do seu dink.',
      'Leu a saída antes de bater? Mande a bola para onde ele estava: dink cruzado ou bola no meio da quadra dele.',
      'Se o Erne já veio, raquete na frente e bloqueio curto para o espaço vazio, sem tentar matar a bola.',
      'Erne que vence é ponto de quem atacou; saída lida e punida é ponto do defensor. Troquem a cada 10 bolas.',
    ],
    cues: ['Ele saiu? Bola onde ele estava', 'Dink baixo, longe do poste', 'Raquete na frente, bloqueio curto'],
    positioning: [
      { type: 'certo', text: 'Dink paralelo baixo e curto, que quica antes de chegar ao lado do poste: o Erne fica difícil de alcançar.' },
      { type: 'certo', text: 'Com o adversário fora da quadra, a bola vai para o meio da quadra dele ou cruzada, longe do poste.' },
      { type: 'errado', text: 'Dinks paralelos altos e sempre para o mesmo lugar: é o convite para o Erne.' },
    ],
    common_errors: [
      { error: 'Perseguir o Erne e mandar a bola de volta na direção do poste.', fix: 'Quem saiu da quadra deixou o meio vazio: jogue lá.' },
      { error: 'Tentar responder ao voleio do Erne com força.', fix: 'Bloqueie curto para o espaço vazio; a velocidade vem da bola dele.' },
      { error: 'Dinkar sempre paralelo para o mesmo jogador.', fix: 'Alterne paralelo e cruzado: o Erne nasce do dink previsível.' },
    ],
    variations: {
      easier: 'Tarefa: quem ataca avisa "vou" um dink antes de sair, e o defensor treina só a resposta para o espaço vazio.',
      harder: 'Pessoas: em 2 contra 2, quem ataca escolhe entre Erne e ATP; o parceiro dele cobre o meio e o defensor procura o espaço que sobrou.',
    },
    metric: { type: 'percentual', target: '60% das saídas punidas' },
    success_criteria: 'Conta a saída lida em que a bola foi para o espaço vazio e entrou. 6 de 10 em duas rodadas? Passe para o 2 contra 2.',
    motor: {
      phases: {
        preparacao: 'Na linha da cozinha, raquete na frente, olhando a posição do adversário enquanto a bola vem.',
        execucao: 'Dink ou bloqueio curto, apontando a raquete para o espaço que ele deixou.',
        finalizacao: 'Volte para a frente da sua área, pronto para a bola seguinte.',
      },
      abilities: ['leitura', 'tempo_reacao', 'precisao'],
    },
    when_to_use: 'Contra quem já tentou o Erne no jogo, ou quando o seu dink paralelo começou a ficar previsível.',
    safety: 'Quem sai pela lateral precisa de espaço livre fora da quadra: sem banco, cadeira ou pessoas perto do poste.',
    diagrams: [
      diagrama('Ler a saída e jogar no espaço', 'cozinha', [
        jogador(12, 68, 'a', 'Defensor'),
        jogador(14, 32, 'b', 'Erne'),
        trajeto(12, 66, 12, 40, 'Paralelo'),
        desloca(14, 30, 1, 42, 'Saída'),
        zona(30, 28, 75, 45, 'Espaço vazio'),
        trajeto(14, 66, 52, 38, 'Resposta'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'dink-no-backhand-quebra-de-padrao',
    version: 1,
    kind: 'drill',
    title: 'Dink no backhand e a quebra do padrão',
    summary: 'Rally de dink em que você pressiona o backhand do adversário e, quando escolher, muda para o meio ou o forehand. Treina explorar o lado fraco sem ficar previsível.',
    objective: 'Ao final, o atleta mantém o dink baixo no backhand do parceiro e muda de alvo na hora que escolhe, forçando bola alta ou erro em 4 de 20 bolas.',
    skills: ['tactics.alvo', 'tactics.leitura_adversario', 'kitchen.dink_paralelo', 'kitchen.paciencia'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 2,
    roles: ['Quem pressiona', 'Quem defende'],
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'variado',
    setup: 'Os dois na linha da cozinha, de frente um para o outro. Na cozinha de quem defende, um cone divide o alvo em duas faixas: a do backhand e a do forehand. Para um destro de frente para você, o backhand fica à sua direita.',
    steps: [
      'Quem pressiona manda dinks baixos sempre na faixa do backhand; quem defende devolve dinks neutros.',
      'Quando quiser, sem contar bolas, quem pressiona muda o dink para o meio ou para o forehand.',
      'Quem defende tenta antecipar: se percebe a mudança antes do contato, diz "li".',
      'Bola que sobe acima da rede pode ser atacada; o ponto segue até alguém errar.',
      'A cada 20 bolas, troquem os papéis.',
    ],
    cues: ['Bola baixa no lado fraco', 'Mude quando ele se ajeitar', 'Mesma preparação para todo alvo'],
    positioning: [
      { type: 'certo', text: 'A raquete se prepara igual para o backhand e para o meio; a direção só aparece no fim do gesto.' },
      { type: 'errado', text: 'Abrir o corpo para o meio antes de bater: quem defende lê a mudança e chega antes da bola.' },
    ],
    common_errors: [
      { error: 'Mandar todas as bolas no backhand: o adversário se posiciona para ele e o lado fraco deixa de ser fraco.', fix: 'Mude de alvo quando perceber o adversário dando um passo para proteger o backhand.' },
      { error: 'Mudar de alvo sempre na mesma contagem de bolas.', fix: 'Escolha a hora pela posição do adversário, nunca por um número fixo.' },
      { error: 'Caprichar no alvo e deixar o dink subir.', fix: 'Primeiro a altura, depois o alvo: dink alto no lado fraco continua atacável.' },
    ],
    variations: {
      easier: 'Espaço: a faixa do backhand ocupa metade da cozinha, e quem defende só devolve, sem tentar ler.',
      harder: 'Tarefa: quem pressiona também varia altura e profundidade; quem defende pode acelerar qualquer bola acima da rede.',
    },
    metric: { type: 'reps', target: '4 bolas forçadas em 20' },
    success_criteria: 'Conta a bola em que o adversário devolveu alto, errou ou chegou atrasado depois de uma mudança de alvo. 4 em 20, com ele lendo menos da metade das mudanças? Vá para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Base aberta na linha, raquete na frente, a mesma para qualquer alvo.',
        execucao: 'Gesto curto de baixo para cima; a direção sai no fim, apontando a faixa escolhida.',
        finalizacao: 'A raquete volta para a frente do corpo, pronta para uma bola alta.',
      },
      abilities: ['precisao', 'leitura', 'coordenacao'],
    },
    when_to_use: 'Quando você percebe que o adversário tem um lado mais fraco no dink, quase sempre o backhand.',
    diagrams: [
      diagrama('Pressão no backhand e quebra', 'cozinha', [
        jogador(50, 68, 'a', 'Pressiona'),
        jogador(50, 32, 'b', 'Defende'),
        zona(52, 35, 82, 48, 'Backhand'),
        zona(18, 35, 48, 48, 'Forehand'),
        trajeto(50, 66, 66, 42, 'Padrão'),
        trajeto(50, 66, 34, 42, 'Quebra'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'stacking-em-jogo-empilhar-ou-nao',
    version: 1,
    kind: 'drill',
    title: 'Stacking em jogo: empilhar ou não?',
    summary: 'Duas duplas jogam pontos alternando a formação normal e o stacking, e a dupla decide pelos resultados qual funciona contra aqueles adversários. Começa com uma passagem a pé pelas quatro situações.',
    objective: 'Ao final, a dupla empilha no saque e na devolução sem falta de posição e escolhe a formação pelo resultado dos pontos, não pelo hábito.',
    skills: ['doubles.stacking', 'doubles.comunicacao', 'rules.placar', 'experience.jogo'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 4,
    players_max: 4,
    duration_min: 20,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Duas duplas, quadra inteira. A dupla que treina combina antes o sinal da devolução (mão atrás das costas: fechada, cada um fica; aberta, troca) e leva papel para anotar os pontos.',
    steps: [
      'Passagem a pé, sem bola: a dupla percorre as quatro situações (sacando da direita, sacando da esquerda, devolvendo da direita, devolvendo da esquerda) dizendo o placar em voz alta.',
      'Com bola, em ritmo lento: saque ou devolução, e quem precisa trocar de lado atravessa enquanto a bola viaja.',
      'Jogo: 5 pontos em formação normal, depois 5 empilhando; a outra dupla joga normal.',
      'Na devolução, o parceiro na cozinha mostra o sinal antes do saque e quem devolve confirma com a voz: "fica" ou "troca".',
      'Anotem os pontos ganhos em cada formação e as faltas de posição.',
      'Depois de 20 pontos, decidam qual formação usar e digam por quê; na rodada seguinte, a outra dupla também pode empilhar.',
    ],
    cues: ['O placar decide quem saca', 'Troque enquanto a bola viaja', 'Sinal antes do saque, voz depois'],
    positioning: [
      { type: 'certo', text: 'Quem saca e quem recebe ficam sempre no lado que o placar manda; o parceiro pode esperar em qualquer lugar do seu lado da quadra.' },
      { type: 'certo', text: 'Na troca, cada um assume o seu lado antes da terceira bola, e só um atravessa a quadra.' },
      { type: 'errado', text: 'Os dois mudando de lugar sem combinar: um lado fica vazio ou os dois vão para o mesmo.' },
    ],
    common_errors: [
      { error: 'Falta de posição: sacar ou devolver do lado errado para ficar no lado preferido.', fix: 'Antes de cada ponto, quem saca anuncia o placar e confere o lado; o lado preferido vem depois do saque.' },
      { error: 'Troca atrasada, com a terceira bola já chegando.', fix: 'Comece a atravessar assim que a bola sai da raquete; quem está mais longe sai primeiro.' },
      { error: 'Empilhar em todo ponto mesmo quando os adversários já atacam a troca.', fix: 'Olhem as anotações: se a formação perde pontos, voltem à normal.' },
    ],
    variations: {
      easier: 'Tarefa: só a dupla que saca empilha; na devolução, formação normal.',
      harder: 'Pessoas: as duas duplas empilham e cada uma tenta atacar a troca da outra, mandando a bola no lado que está vazio.',
    },
    metric: { type: 'reps', target: '20 pontos sem falta de posição' },
    success_criteria: 'Conta o ponto sem falta de posição e com a troca completa antes da terceira bola. 20 pontos assim e uma decisão anotada? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Placar anunciado, sinal combinado e cada um no lugar de partida.',
        execucao: 'Saque ou devolução e, enquanto a bola viaja, a travessia para o lado preferido.',
        finalizacao: 'Os dois parados nos seus lados, raquete na frente, antes da terceira bola.',
      },
      abilities: ['leitura', 'agilidade', 'coordenacao'],
    },
    when_to_use: 'Quando um parceiro é canhoto, quando um tem forehand bem melhor ou quando a dupla quer o mais forte no meio, e para decidir se vale a pena contra estes adversários.',
    diagrams: [
      diagrama('Devolução empilhada com sinal', 'inteira', [
        jogador(25, 3, 'b', 'Saque'),
        trajeto(25, 5, 72, 92, 'Saque'),
        jogador(75, 97, 'a', 'Devolve'),
        jogador(93, 68, 'a', 'Sinal'),
        trajeto(75, 95, 30, 12, 'Devolução'),
        desloca(74, 94, 30, 71, 'Troca'),
        desloca(92, 71, 70, 71, 'Desliza'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'poach-da-terceira-bola-com-sinal',
    version: 1,
    kind: 'drill',
    title: 'Poach da terceira bola com sinal',
    summary: 'A dupla que devolve combina o poach antes do saque: o parceiro na cozinha atravessa e volea a terceira bola, e quem devolveu cobre o lado vazio. A devolução nunca pode ser voleada pelo outro lado.',
    objective: 'Ao final, a dupla executa o poach combinado na terceira bola, com a cobertura do lado vazio, e converte 6 de 10 tentativas.',
    skills: ['doubles.posicionamento', 'doubles.comunicacao', 'net.voleio', 'tactics.leitura_adversario'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 4,
    players_max: 4,
    duration_min: 15,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    setup: 'Duas duplas, quadra inteira. A dupla B saca; a dupla A devolve. O parceiro de quem devolve espera na linha da cozinha e combina o sinal com a mão atrás das costas antes de cada saque.',
    steps: [
      'Antes do saque, o parceiro da cozinha mostra o sinal (poach ou fica) e quem vai devolver confirma com a voz.',
      'A devolução vai funda e cruzada, e quem devolveu sobe para a cozinha.',
      'Quando o sacador se compromete com a terceira bola cruzada, o parceiro atravessa em diagonal para a frente e volea no meio ou nos pés.',
      'Quem devolveu, vendo o poach, segue para o lado que ficou vazio; o ponto continua com os lados trocados.',
      'Terceira bola baixa, que vai quicar na cozinha? Não force: deixe para o parceiro e mantenham os lados.',
      'Depois de 10 saques, as duplas trocam de papel.',
    ],
    cues: ['Sinal antes, saída na batida', 'Volee para baixo, no meio', 'Atravessou? Fique do lado novo'],
    positioning: [
      { type: 'certo', text: 'O parceiro sai quando o sacador já está batendo a terceira bola, nunca antes.' },
      { type: 'certo', text: 'Quem devolveu corre para o lado que ficou vazio assim que vê o poach começar.' },
      { type: 'errado', text: 'Atravessar antes de o sacador bater: ele vê e joga na paralela vazia.' },
    ],
    common_errors: [
      { error: 'Volear a terceira bola com um pé na cozinha ao atravessar.', fix: 'Atravesse andando junto à linha, por fora dela: voleio só com os dois pés fora da cozinha.' },
      { error: 'Poach em terceira bola baixa, que vai na rede.', fix: 'Poach só em bola na altura da rede ou acima; o drop baixo fica para o parceiro.' },
      { error: 'Quem devolveu fica no lado de origem e a paralela fica livre.', fix: 'O sinal já avisou: depois da devolução, suba pensando no lado novo.' },
    ],
    variations: {
      easier: 'Tarefa: o sacador manda a terceira bola cruzada e um pouco alta, sempre, para a dupla treinar a saída e a troca.',
      harder: 'Tarefa: o sinal pode ser "poach", "fica" ou "falso", e o sacador escolhe livremente entre cruzado, paralelo e drop.',
    },
    metric: { type: 'percentual', target: '60% dos poaches convertidos' },
    success_criteria: 'Conta o poach em que o voleio entrou na quadra adversária e o lado vazio foi coberto. 6 de 10? Libere o sacador para escolher a direção.',
    safety: 'Atravessar a quadra exige mudança rápida de direção: faça depois do aquecimento, com tênis de quadra, e combinem a fala para não trombarem.',
    motor: {
      phases: {
        preparacao: 'Na linha, raquete alta e na frente, olhando a raquete do sacador.',
        execucao: 'Passo cruzado em diagonal para a frente e voleio curto, para baixo.',
        finalizacao: 'Siga para o lado novo e fique lá; o parceiro assume o outro lado.',
      },
      abilities: ['tempo_reacao', 'agilidade', 'leitura'],
    },
    when_to_use: 'Contra sacadores que mandam a terceira bola sempre cruzada ou um pouco alta.',
    diagrams: [
      diagrama('Poach da terceira bola', 'inteira', [
        jogador(25, 4, 'b', 'Saque'),
        jogador(72, 32, 'b'),
        jogador(75, 97, 'a', 'Devolve'),
        jogador(28, 68, 'a', 'Poach'),
        trajeto(75, 95, 28, 10, 'Devolução'),
        trajeto(25, 8, 62, 64, '3ª bola'),
        desloca(30, 67, 56, 63, 'Atravessa'),
        desloca(75, 94, 30, 72, 'Cobre'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'falso-poach-no-dink-cruzado',
    version: 1,
    kind: 'drill',
    title: 'Falso poach: mostrar a saída e ficar',
    summary: 'No dink cruzado, o jogador da frente do adversário finge que vai atravessar e volta para a sua linha. Com medo do poach, o adversário muda para a paralela e encontra quem fingiu esperando.',
    objective: 'Ao final, o jogador faz o falso poach sem perder a posição e volea a paralela provocada em 5 de 10 tentativas.',
    skills: ['doubles.posicionamento', 'tactics.leitura_adversario', 'net.voleio', 'doubles.comunicacao'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 4,
    players_max: 4,
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'aleatorio',
    setup: 'Dois contra dois na cozinha. A diagonal da direita troca dinks cruzados. Quem faz o falso poach é o jogador da dupla A que está de frente para o adversário que dinka; os outros jogam normal.',
    steps: [
      'A diagonal da direita troca dinks cruzados; quem vai fingir fica pronto na linha, raquete na frente.',
      'Quando o adversário prepara o dink, quem finge dá um passo rápido e visível em direção ao meio.',
      'Antes de o adversário bater, volta para a sua posição e espera a bola na paralela.',
      'Se ele mudou para a paralela, volee para baixo, no meio ou nos pés; se manteve o cruzado, o rally segue.',
      'Misturem poach de verdade, falso poach e nada; o parceiro do rally sabe qual vai ser pelo sinal combinado.',
      'Depois de 10 tentativas, troquem quem faz a finta.',
    ],
    cues: ['Mostre a saída, volte antes da batida', 'Raquete pronta para a paralela', 'Finta com passo, sem barulho'],
    positioning: [
      { type: 'certo', text: 'Passo curto para o meio e volta rápida: quando o adversário bate, você já está parado na sua linha.' },
      { type: 'certo', text: 'A finta é um movimento normal de jogo, como o início de um poach, sem grito nem raquete agitada.' },
      { type: 'errado', text: 'Continuar indo para o meio depois de fingir: a paralela passa livre.' },
    ],
    common_errors: [
      { error: 'Fingir tarde, com o adversário já batendo, e ficar no meio do caminho.', fix: 'O passo falso sai na preparação dele; na batida você já voltou e está parado.' },
      { error: 'Fingir em todo ponto.', fix: 'Misture poach de verdade, falso e nada: previsível, a finta deixa de funcionar.' },
      { error: 'Tentar distrair com barulho, pisada forte ou raquete agitada enquanto o adversário bate.', fix: 'Isso é falta de distração pela regra. Use só o movimento normal de jogo.' },
    ],
    variations: {
      easier: 'Tarefa: o adversário do rally é avisado de que, ao ver o passo, deve jogar paralelo; quem finge treina só a volta e o voleio.',
      harder: 'Tarefa: quem finge escolhe entre falso poach e poach de verdade sem combinar, e o parceiro do rally precisa ler e cobrir o lado vazio.',
    },
    metric: { type: 'percentual', target: '50% das paralelas voleadas' },
    success_criteria: 'Conta a finta que provocou a paralela e o voleio que entrou. 5 de 10 tentativas? Passe a misturar com o poach de verdade.',
    motor: {
      phases: {
        preparacao: 'Na linha, raquete na frente, olhando a preparação do adversário.',
        execucao: 'Passo curto e visível para o meio e volta imediata para a posição.',
        finalizacao: 'Parado na sua linha na hora da batida, raquete pronta para o voleio na paralela.',
      },
      abilities: ['agilidade', 'tempo_reacao', 'leitura'],
    },
    when_to_use: 'Contra adversários que já perceberam os seus poaches e passaram a jogar na paralela para puni-los.',
    diagrams: [
      diagrama('A finta e a paralela', 'cozinha', [
        jogador(28, 68, 'a', 'Finta'),
        jogador(72, 68, 'a'),
        jogador(28, 32, 'b'),
        jogador(72, 32, 'b'),
        trajeto(28, 34, 68, 62, 'Cruzado'),
        desloca(30, 70, 45, 70, 'Mostra'),
        desloca(45, 73, 30, 73, 'Volta'),
        trajeto(28, 34, 28, 64, 'Paralela'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'atacar-ou-resetar-na-transicao',
    version: 1,
    kind: 'drill',
    title: 'Atacar ou resetar? A altura da bola decide',
    summary: 'Na zona de transição, o alimentador mistura bolas baixas, médias e altas, e você decide antes de bater: reset, voleio firme ou smash. Treina a escolha do golpe enquanto avança.',
    objective: 'Ao final, o atleta escolhe o golpe pela altura do contato (reset abaixo da rede, ataque acima dela) e acerta a decisão em 15 de 20 bolas.',
    skills: ['tactics.selecao_golpe', 'net.reset', 'groundstrokes.transicao', 'net.smash'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 12,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'aleatorio',
    setup: 'O executor começa na zona de transição, no meio da quadra. O alimentador fica na linha da cozinha do outro lado, com o cesto, e mistura três bolas sem avisar: baixa nos pés, na altura da cintura e alta e curta, acima da cabeça.',
    steps: [
      'O alimentador manda uma bola sem avisar o tipo.',
      'O executor para com um split step e lê em que altura vai bater.',
      'Contato abaixo da altura da rede: reset para a cozinha, com gesto curto.',
      'Contato entre a rede e o peito: voleio firme e curto nos pés do alimentador.',
      'Bola alta e curta, acima da cabeça: smash para o meio ou para os pés.',
      'A cada decisão certa, o executor avança um passo; a sequência termina na linha da cozinha. Depois de 20 bolas, troquem.',
    ],
    cues: ['Abaixo da fita: amorteça', 'Acima da fita: ataque para baixo', 'Pare quando ele bater'],
    positioning: [
      { type: 'certo', text: 'Parado em split step quando o alimentador bate, raquete na frente, pronto para as três respostas.' },
      { type: 'certo', text: 'Avançar só depois de uma bola bem resolvida; bola mal resolvida pede ficar e resetar de novo.' },
      { type: 'errado', text: 'Atacar uma bola que você vai bater abaixo da altura da rede: ela sobe para o adversário ou vai na rede.' },
    ],
    common_errors: [
      { error: 'Atacar a bola na altura do joelho porque ela veio rápida.', fix: 'Rápida e baixa é reset: só a altura do contato libera o ataque.' },
      { error: 'Resetar uma bola alta que dava para atacar.', fix: 'Bola acima da rede e lenta é a sua chance: voleio firme para baixo.' },
      { error: 'Avançar correndo depois de atacar e ser pego no pé.', fix: 'Ataque, pare em split step e avance um passo de cada vez.' },
    ],
    variations: {
      easier: 'Tarefa: o alimentador diz a altura em voz alta ("baixa", "média", "alta") antes de mandar.',
      harder: 'Pessoas: o alimentador devolve e o ponto é jogado; o executor ganha 1 por chegada à linha e perde 1 por ataque que voltou contra ele.',
    },
    metric: { type: 'reps', target: '15 de 20 decisões certas' },
    success_criteria: 'Conta como certa a decisão que combina com a altura e a bola que caiu onde devia: na cozinha no reset, nos pés no ataque. 15 de 20 em duas rodadas? Passe para o ponto jogado.',
    safety: 'Bola que passa por cima da sua cabeça: vire de lado e corra, nunca ande de costas.',
    motor: {
      phases: {
        preparacao: 'Split step na batida do alimentador, pernas dobradas, raquete na frente.',
        execucao: 'Gesto curto e face aberta no reset; gesto firme e para baixo no ataque.',
        finalizacao: 'Raquete de volta à frente e um passo à frente se a bola foi bem resolvida.',
      },
      abilities: ['leitura', 'tempo_reacao', 'precisao'],
    },
    when_to_use: 'Quando você chega à zona de transição e não sabe se ataca ou amortece a bola que vem.',
    diagrams: [
      diagrama('Três alturas, três respostas', 'inteira', [
        jogador(50, 36, 'b', 'Alimenta'),
        jogador(50, 78, 'a', 'Executor'),
        zona(0, 72, 100, 86, 'Transição'),
        trajeto(47, 38, 45, 78, 'Baixa'),
        trajeto(53, 38, 56, 75, 'Média'),
        texto(80, 92, 'Avança 1'),
        desloca(50, 80, 50, 70),
      ]),
    ],
    media: [],
  },
  {
    slug: 'meio-voleio-no-pe-na-linha-da-cozinha',
    version: 1,
    kind: 'drill',
    title: 'Meio-voleio no pé, sem recuar da cozinha',
    summary: 'O alimentador manda dinks que quicam bem no seu pé, na linha da cozinha. Em vez de recuar, você joga a bola logo depois do quique, curta e baixa.',
    objective: 'Ao final, o atleta devolve 15 de 20 bolas no pé com meio-voleio para dentro da cozinha, sem dar passo para trás.',
    skills: ['kitchen.dink_paralelo', 'kitchen.paciencia', 'net.reset'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 2,
    roles: ['Alimentador', 'Executor'],
    duration_min: 8,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'bloco',
    setup: 'O executor na linha da cozinha. O alimentador do outro lado, também na linha, com o cesto, manda dinks que quicam a um palmo da linha, bem na frente dos pés do executor, alternando forehand e backhand.',
    steps: [
      'O alimentador manda um dink que quica bem perto da linha, no pé do executor.',
      'O executor fica na linha, dobra as pernas e leva a raquete baixa, com a face um pouco aberta, até onde a bola vai quicar.',
      'Toque curto logo depois do quique: a bola sobe pouco e cai na cozinha do alimentador.',
      'Sem recuar e sem arrumar os pés: a próxima bola já vem.',
      '10 de forehand, 10 de backhand e depois misturadas. Troquem a cada 20 bolas.',
    ],
    cues: ['Raquete baixa onde a bola quica', 'Toque curto, bola morre na cozinha', 'Fique na linha'],
    positioning: [
      { type: 'certo', text: 'Na linha, base aberta e pernas dobradas, raquete baixa na frente: a bola é jogada logo depois do quique.' },
      { type: 'errado', text: 'Um passo para trás para deixar a bola subir: você perde a linha e o dink sai de baixo, alto.' },
    ],
    common_errors: [
      { error: 'Recuar para jogar a bola mais alta.', fix: 'Abaixe-se em vez de recuar: a linha da cozinha é a sua posição.' },
      { error: 'Abaixar só a raquete, com as pernas esticadas.', fix: 'Dobre as pernas até a raquete chegar baixa, com a face aberta.' },
      { error: 'Bater forte e a bola passar da cozinha.', fix: 'O gesto anda um palmo: a bola só encosta e sobe.' },
    ],
    variations: {
      easier: 'Equipamento: o alimentador joga a bola com a mão, devagar e sempre do mesmo lado.',
      harder: 'Tarefa: o alimentador mistura bolas no pé com dinks normais e bolas altas; o executor mantém o ritmo e ataca só a bola alta.',
    },
    metric: { type: 'reps', target: '15 de 20 na cozinha' },
    success_criteria: 'Conta a bola que caiu na cozinha do alimentador, abaixo da cintura dele, sem passo para trás. 15 de 20 dos dois lados? Passe para a mistura.',
    motor: {
      phases: {
        preparacao: 'Na linha, pernas dobradas e raquete baixa na frente antes de a bola quicar.',
        execucao: 'Toque curto logo depois do quique, com a face aberta.',
        finalizacao: 'A raquete para curta e volta para a frente do corpo, sem recuar.',
      },
      abilities: ['precisao', 'equilibrio', 'tempo_reacao'],
    },
    when_to_use: 'Quando o adversário dinka fundo, no seu pé, para tirar você da linha da cozinha.',
    diagrams: [
      diagrama('A bola no pé', 'cozinha', [
        jogador(50, 69, 'a', 'Executor'),
        jogador(50, 31, 'b', 'Alimenta'),
        zona(30, 61, 70, 65.9, 'Quique'),
        trajeto(50, 33, 47, 63, 'No pé'),
        bolinha(47, 63),
        trajeto(47, 63, 53, 40, 'Curto'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'lob-com-topspin-escondido-no-dink',
    version: 1,
    kind: 'drill',
    title: 'Lob com topspin escondido no dink',
    summary: 'No rally de dink, um lob com topspin que começa igual ao dink. O parceiro tenta perceber quando ele vem; a meta é ele errar mais da metade das vezes.',
    objective: 'Ao final, o atleta coloca o lob com topspin na metade de trás da quadra em 5 de 8 tentativas, sem que o parceiro perceba antes do contato na maioria delas.',
    skills: ['groundstrokes.lob', 'tactics.selecao_golpe', 'tactics.leitura_adversario'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 2,
    roles: ['Quem joga o lob', 'Quem lê'],
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'aleatorio',
    setup: 'Os dois na linha da cozinha, de frente ou na diagonal, com o fundo da quadra livre. Quem joga o lob escolhe a hora; quem lê fica na linha e diz "lob" assim que perceber.',
    steps: [
      'Troquem dinks baixos e pacientes.',
      'Quem joga o lob escolhe uma bola na altura da cintura e prepara igual ao dink, com a raquete na frente e baixa.',
      'No contato, a raquete escova a bola por trás, de baixo para cima, e termina alta: o topspin faz a bola cair mais cedo e escapar depois do quique.',
      'Quem lê grita "lob" no instante em que percebe; grito antes do contato conta como lido.',
      'Quem lê vira e corre atrás da bola, se der, e o ponto é jogado.',
      'Depois de 8 lobs, troquem os papéis.',
    ],
    cues: ['Começo igual ao dink', 'Escove a bola de baixo para cima', 'Mire o fundo do backhand'],
    positioning: [
      { type: 'certo', text: 'Preparação idêntica à do dink; a raquete só acelera e sobe no contato.' },
      { type: 'certo', text: 'Quem defende vira de lado e corre atrás do lob, sem andar de costas.' },
      { type: 'errado', text: 'Abaixar a raquete e armar o golpe antes: o lob aparece antes de sair.' },
    ],
    common_errors: [
      { error: 'O lob sai sem efeito e fica curto para o smash.', fix: 'Escove de baixo para cima e termine com a raquete alta: o efeito deixa a bola passar alta e cair dentro.' },
      { error: 'Um balanço grande que denuncia o lob.', fix: 'Gesto do tamanho do dink até o contato; a aceleração vem só no fim.' },
      { error: 'Tentar o lob numa bola muito baixa, perto do chão.', fix: 'Escolha a bola na altura da cintura; a muito baixa vira lob curto.' },
    ],
    variations: {
      easier: 'Tarefa: o lob é avisado e sai de uma bola jogada com a mão; treine só o efeito e a profundidade.',
      harder: 'Tarefa: quem defende pode dar smash, e o lob só conta se cair no fundo e não voltar como smash vencedor.',
    },
    metric: { type: 'reps', target: '5 de 8 lobs não lidos' },
    success_criteria: 'Conta o lob que cai na metade de trás da quadra e que o parceiro não anunciou antes do contato. 5 de 8 assim? Libere o smash.',
    safety: 'Quem corre atrás do lob vira de lado e corre: andar de costas é causa comum de queda. Fundo da quadra sempre livre.',
    motor: {
      phases: {
        preparacao: 'A mesma base e a mesma raquete baixa e na frente do dink.',
        execucao: 'Raquete escova a bola por trás, de baixo para cima, acelerando só no contato.',
        finalizacao: 'A raquete termina alta, apontando o fundo da quadra, e você volta para a linha.',
      },
      abilities: ['coordenacao', 'precisao', 'leitura'],
    },
    when_to_use: 'Rally de dink contra adversário inclinado para a frente, colado na rede, quando o lob comum já foi lido.',
    diagrams: [
      diagrama('O lob por cima de quem lê', 'inteira', [
        jogador(70, 68, 'a', 'Lob'),
        jogador(30, 32, 'b', 'Lê'),
        trajeto(70, 66, 30, 10, 'Topspin'),
        desloca(30, 30, 26, 12, 'Vira e corre'),
        zona(0, 0, 100, 25, 'Fundo'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'visualizacao-de-tres-cenarios-antes-do-jogo',
    version: 1,
    kind: 'drill',
    title: 'Visualização de três cenários antes do jogo',
    summary: 'Cinco minutos de olhos fechados antes da partida, ensaiando na cabeça três momentos que costumam travar: o ponto apertado, o erro e o adversário mais forte.',
    objective: 'Ao final de quatro semanas, o atleta faz a visualização em 5 minutos antes de todo jogo e volta mais rápido ao seu plano depois de um erro.',
    skills: ['mental.foco', 'mental.pressao', 'mental.rotina_entre_pontos'],
    level_min: 3.0,
    level_max: 5.5,
    players_min: 1,
    players_max: 1,
    duration_min: 5,
    intensity: 1,
    place: ['casa', 'quadra'],
    setup: 'Sente-se num lugar tranquilo, antes de aquecer. Olhos fechados, celular guardado. Imagine a quadra em que vai jogar, com a luz, os sons e a bola de verdade.',
    steps: [
      'Respire devagar por um minuto, soltando o ar mais devagar do que puxou.',
      'Cenário 1, o ponto apertado: você saca em 9-9; veja a bola saindo funda, a terceira bola baixa e você chegando à cozinha.',
      'Cenário 2, o erro: um dink seu vai na rede; veja o gesto de soltar, a respiração, a palavra de foco e a volta à posição.',
      'Cenário 3, o adversário mais forte: veja-se em rallies longos, dinks baixos e pacientes, esperando a bola alta.',
      'Feche com uma frase técnica e uma mental para o jogo e abra os olhos.',
      'Depois do jogo, anote em uma linha como foi a volta ao plano depois dos erros.',
    ],
    cues: ['Veja o golpe, não o placar', 'Bola funda, terceira bola baixa', 'Errou: solte, respire, próxima bola'],
    positioning: [
      { type: 'certo', text: 'Imaginar o processo (a bola, o alvo, o gesto) na quadra e no ritmo reais do jogo.' },
      { type: 'errado', text: 'Imaginar só o resultado ("vou ganhar"): não há nada para ensaiar.' },
    ],
    common_errors: [
      { error: 'Imaginar só a vitória.', fix: 'Ensaie o que você faz: o saque, a terceira bola, a resposta ao erro.' },
      { error: 'Fazer em 30 segundos, já na entrada da quadra.', fix: 'Reserve 5 minutos antes do aquecimento; com pressa, a imagem não fica nítida.' },
      { error: 'Ensaiar só os cenários fáceis.', fix: 'O cenário do erro é o mais importante: é o que mais acontece num jogo.' },
    ],
    variations: {
      easier: 'Tarefa: dois minutos e um cenário só, o do erro.',
      harder: 'Tarefa: depois de cada jogo, acrescente o momento que mais travou como quarto cenário e compare as anotações por quatro semanas.',
    },
    metric: { type: 'tempo', target: '5 min antes de cada jogo' },
    success_criteria: 'Conta a visualização feita inteira, com os três cenários nítidos. Quatro semanas seguidas sem pular? Passe para a variação mais difícil.',
    motor: {
      phases: {
        preparacao: 'Sentado, olhos fechados, respiração lenta.',
        execucao: 'Os três cenários, um de cada vez, na velocidade real do jogo.',
        finalizacao: 'Uma frase técnica, uma mental, e os olhos abertos.',
      },
      abilities: ['leitura'],
    },
    when_to_use: 'Antes de jogos importantes e nos dias em que não dá para treinar em quadra.',
    diagrams: [
      diagrama('Os três cenários', 'inteira', [
        jogador(70, 97, 'a', 'Você'),
        trajeto(70, 95, 30, 10, 'Saque'),
        texto(70, 86, '1 Saque 9-9'),
        texto(30, 62, '2 O erro'),
        texto(50, 22, '3 Mais forte'),
      ]),
    ],
    media: [],
  },
  {
    slug: 'pontos-decisivos-jogos-a-partir-de-9-9',
    version: 1,
    kind: 'drill',
    title: 'Pontos decisivos: jogos que começam em 9-9',
    summary: 'Jogos curtos que já começam no fim, em 9-9, para treinar o golpe mais seguro e a rotina entre pontos quando o placar aperta.',
    objective: 'Ao final, o atleta disputa pontos decisivos com o golpe que mais acerta e a mesma rotina entre pontos, com no máximo 3 erros por arriscar em 20 pontos.',
    skills: ['mental.pressao', 'mental.rotina_entre_pontos', 'tactics.selecao_golpe', 'experience.jogo'],
    level_min: 3.5,
    level_max: 5.5,
    players_min: 2,
    players_max: 4,
    duration_min: 15,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    setup: 'Simples em meia quadra ou duplas em quadra inteira, com o placar visível. Antes de começar, cada um diz qual é o seu golpe mais seguro para ponto decisivo, por exemplo devolução funda no meio ou dink cruzado baixo.',
    steps: [
      'Cada jogo começa em 9-9 e vai até 11, com 2 de diferença; neste treino, todo rally vale ponto.',
      'Antes de cada ponto, a rotina de sempre: soltar o ponto que passou, respirar e decidir o plano.',
      'Jogue com o golpe seguro combinado; quem tenta um golpe que não domina e erra anota "erro por arriscar".',
      'Quem perde o jogo saca no seguinte.',
      'A cada 4 jogos, um vale como match point: quem perde faz 10 drops extras antes de continuar.',
      'Depois de 20 pontos, comparem quantos pontos perdidos foram erros por arriscar.',
    ],
    cues: ['Golpe seguro, alvo grande', 'Solte, respire, decida', 'Um plano por ponto'],
    positioning: [
      { type: 'certo', text: 'A mesma rotina antes do ponto ganho e do ponto perdido, sem pressa para sacar.' },
      { type: 'errado', text: 'Sacar correndo depois de um erro, ainda pensando no ponto que passou.' },
    ],
    common_errors: [
      { error: 'Tentar o golpe mais difícil justo no ponto decisivo.', fix: 'Use o golpe que você combinou antes do jogo; o ponto bonito fica para outro dia.' },
      { error: 'Pular a rotina quando o placar aperta.', fix: 'Só saque depois de soltar, respirar e decidir.' },
      { error: 'Pensar no placar em vez do próximo alvo.', fix: 'Um ponto de cada vez: escolha o alvo da próxima bola e jogue nele.' },
    ],
    variations: {
      easier: 'Tarefa: jogos começando em 7-7 e sem os drops extras.',
      harder: 'Tarefa: jogos começam em 10-10, com a contagem tradicional (só quem saca pontua), e alguém anuncia o placar antes de cada saque, como numa final.',
    },
    metric: { type: 'placar', target: 'Até 3 erros por arriscar em 20' },
    success_criteria: 'Conta o ponto jogado com a rotina completa e sem erro por arriscar. Em 20 pontos, no máximo 3 erros por arriscar? Passe para os jogos em 10-10.',
    motor: {
      phases: {
        preparacao: 'Rotina entre pontos: soltar, respirar, decidir o alvo.',
        execucao: 'O golpe seguro combinado, com margem sobre a rede e longe das linhas.',
        finalizacao: 'Fim do ponto, a mesma rotina, ganhando ou perdendo.',
      },
      abilities: ['leitura', 'precisao'],
    },
    when_to_use: 'Antes de torneios e quando você costuma perder jogos no fim, depois de estar na frente.',
    diagrams: [
      diagrama('Ponto decisivo', 'inteira', [
        jogador(70, 97, 'a', 'Saque'),
        jogador(30, 3, 'b'),
        trajeto(70, 95, 30, 8, 'Fundo'),
        texto(50, 75, '9-9 até 11'),
      ]),
    ],
    media: [],
  },
];
