/** Biblioteca inicial — JOGADAS (padrões táticos de duplas). */

import { desloca, diagrama, jogador, texto, trajeto, zona } from './quadra.js';

const QUADRA = ['quadra'];

export const JOGADAS = [
  {
    slug: 'posicionamento-na-devolucao',
    version: 1,
    featured: true,
    kind: 'jogada',
    title: 'Posição da dupla que devolve o saque',
    summary: 'Quem devolve fica um passo atrás da linha de fundo; o parceiro já espera na linha da cozinha. A posição inicial que dá vantagem à dupla que recebe.',
    objective: 'Ao final, a dupla sabe onde cada um fica na devolução e chega junta à cozinha antes da terceira bola.',
    skills: ['doubles.posicionamento', 'serve.devolucao_profunda'],
    level_min: 2.0,
    players_min: 4,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'Quem devolve fica um passo atrás da linha de fundo, no lado em que o saque vai cair.',
      'O parceiro de quem devolve fica na linha da cozinha, do outro lado, de frente para a rede.',
      'Quem devolve joga alto e fundo e anda até a cozinha.',
      'Os dois terminam lado a lado na linha, prontos para a terceira bola.',
      'Para treinar: 10 saques seguidos, contando quantas vezes a dupla chega junta.',
    ],
    cues: ['Parceiro já na linha', 'Devolva fundo e suba', 'Terminem lado a lado'],
    positioning: [
      { type: 'certo', text: 'Parceiro de quem devolve já na linha da cozinha: a dupla começa o ponto com um na rede.' },
      { type: 'certo', text: 'Quem devolve, um passo atrás da linha de fundo, andando para a frente na bola.' },
      { type: 'errado', text: 'Os dois no fundo esperando a devolução: a dupla perde a vantagem de quem recebe e precisa atravessar a quadra inteira.' },
    ],
    common_errors: [
      { error: 'O parceiro de quem devolve fica no fundo "para ajudar".', fix: 'A devolução só pode ser batida por quem recebe: o parceiro espera na cozinha.' },
      { error: 'Quem devolve fica parado no fundo depois de devolver.', fix: 'Devolva alto e fundo e ande para a cozinha enquanto a bola viaja.' },
    ],
    when_to_use: 'Toda vez que a sua dupla recebe o saque.',
    motor: {
      phases: {
        preparacao: 'Quem devolve atrás da linha de fundo; parceiro na cozinha.',
        execucao: 'Devolução alta e funda.',
        finalizacao: 'Os dois na linha da cozinha, lado a lado.',
      },
      abilities: ['leitura', 'agilidade'],
    },
    diagrams: [
      diagrama('Certo: parceiro na cozinha', 'inteira', [
        jogador(75, 98, 'a', 'Dev'),
        jogador(28, 68, 'a', 'Parc'),
        jogador(25, 3, 'b', 'Sac'),
        trajeto(25, 5, 72, 90, 'Saque'),
        desloca(75, 95, 72, 70),
      ], 'certo'),
      diagrama('Errado: os dois no fundo', 'inteira', [
        jogador(75, 98, 'a', 'Dev'),
        jogador(28, 96, 'a', 'Parc'),
        jogador(25, 3, 'b', 'Sac'),
        trajeto(25, 5, 72, 90, 'Saque'),
        zona(2, 52, 98, 70, 'Vazio'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'posicionamento-no-saque',
    version: 1,
    kind: 'jogada',
    title: 'Posição da dupla que saca',
    summary: 'Os dois da dupla que saca ficam no fundo até a devolução quicar. Pela regra dos dois quiques, quem corre para a rede cedo demais fica sem jogada.',
    objective: 'Ao final, a dupla que saca espera a devolução no fundo e só então avança junta, depois de uma boa terceira bola.',
    skills: ['doubles.posicionamento', 'rules.saque'],
    level_min: 2.0,
    players_min: 4,
    players_max: 4,
    duration_min: 10,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'Quem saca fica atrás da linha de fundo, no lado que o placar manda.',
      'O parceiro também fica no fundo, do outro lado, perto da linha.',
      'A devolução precisa quicar antes de vocês baterem: esperem no fundo.',
      'Depois da terceira bola (drop bom), os dois avançam juntos.',
    ],
    cues: ['Os dois no fundo no saque', 'Deixe a devolução quicar', 'Drop bom? Subam juntos'],
    positioning: [
      { type: 'certo', text: 'Os dois atrás da linha de fundo, prontos para deixar a devolução quicar e jogar a terceira bola.' },
      { type: 'errado', text: 'Parceiro do sacador na linha da cozinha: a devolução precisa quicar, então ele fica sem poder volear e a bola funda passa por ele.' },
    ],
    common_errors: [
      { error: 'O parceiro do sacador corre para a rede no saque.', fix: 'A regra dos dois quiques obriga a deixar a devolução quicar: espere no fundo.' },
      { error: 'Os dois avançam depois de uma terceira bola alta.', fix: 'Só avancem depois de um drop baixo; bola alta pede ficar e defender.' },
    ],
    when_to_use: 'Todo ponto em que a sua dupla saca.',
    diagrams: [
      diagrama('Certo: os dois no fundo', 'inteira', [
        jogador(75, 97, 'a', 'Sac'),
        jogador(25, 96, 'a', 'Parc'),
        jogador(25, 4, 'b'),
        jogador(75, 32, 'b'),
        trajeto(75, 95, 28, 8, 'Saque'),
      ], 'certo'),
      diagrama('Errado: parceiro na rede', 'inteira', [
        jogador(75, 97, 'a', 'Sac'),
        jogador(25, 68, 'a', 'Parc'),
        jogador(25, 4, 'b'),
        jogador(75, 32, 'b'),
        trajeto(25, 6, 30, 90, 'Dev'),
        texto(40, 80, 'Sem voleio'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'dupla-como-corda',
    version: 1,
    kind: 'jogada',
    title: 'A dupla como uma corda',
    summary: 'Os dois parceiros andam juntos, como se estivessem presos por uma corda de 3 metros. Quando a bola vai para um lado, os dois deslizam para lá.',
    objective: 'Ao final, a dupla se desloca junta acompanhando a bola, sem abrir buraco no meio nem deixar a lateral livre.',
    skills: ['doubles.posicionamento', 'doubles.cobertura_meio'],
    level_min: 2.5,
    players_min: 4,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'Imagine uma corda de cerca de 3 metros entre você e o parceiro.',
      'A bola foi para a lateral da direita: quem está à direita cobre a lateral, quem está à esquerda desliza para cobrir o meio.',
      'A bola voltou ao meio: os dois voltam juntos ao centro de cada lado.',
      'A bola foi para a esquerda: o movimento é o espelho.',
      'Para treinar: um alimentador manda dinks para todos os lados e a dupla só se move, sem atacar.',
    ],
    cues: ['A bola anda, a dupla anda', 'Corda esticada, nunca frouxa', 'Quem está longe cobre o meio'],
    positioning: [
      { type: 'certo', text: 'Bola na lateral da direita: o da direita na lateral e o da esquerda perto do meio, os dois na linha.' },
      { type: 'errado', text: 'Cada um parado no seu lado, longe um do outro: o meio fica aberto para a bola passar entre os dois.' },
    ],
    common_errors: [
      { error: 'Só quem está perto da bola se mexe.', fix: 'Os dois se mexem: quando um vai para a lateral, o outro vai para o meio.' },
      { error: 'Os dois correm para a bola.', fix: 'Quem está perto pega; quem está longe cobre o meio.' },
    ],
    when_to_use: 'Em todo rally de duplas, na rede ou no fundo.',
    diagrams: [
      diagrama('Certo: os dois deslizam', 'cozinha', [
        jogador(88, 68, 'a', 'A1'),
        jogador(55, 68, 'a', 'A2'),
        jogador(25, 32, 'b'),
        trajeto(25, 34, 86, 60),
        desloca(30, 72, 52, 72),
      ], 'certo'),
      diagrama('Errado: meio aberto', 'cozinha', [
        jogador(88, 68, 'a', 'A1'),
        jogador(15, 68, 'a', 'A2'),
        jogador(25, 32, 'b'),
        zona(30, 51, 75, 73, 'Buraco'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'ataque-ao-meio',
    version: 1,
    kind: 'jogada',
    title: 'Ataque ao meio: a bola da dúvida',
    summary: 'Jogar no meio dos dois adversários cria dúvida sobre quem pega e diminui o ângulo da resposta. O alvo mais simples e eficiente das duplas.',
    objective: 'Ao final, o atleta escolhe o meio como alvo quando está em dúvida e ganha pontos na hesitação dos adversários.',
    skills: ['tactics.alvo', 'tactics.selecao_golpe'],
    level_min: 2.5,
    players_min: 4,
    players_max: 4,
    duration_min: 10,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'jogo',
    steps: [
      'Na dúvida sobre onde jogar, mire o meio, entre os dois adversários.',
      'Do fundo, o drive ou a devolução no meio dificulta o ângulo da resposta.',
      'Na rede, o voleio ou o ataque no meio cria a dúvida: quem pega?',
      'Para treinar: joguem pontos em que a bola no meio que ninguém tocou vale 2.',
    ],
    cues: ['Na dúvida, meio', 'Mire entre os dois', 'Meio fecha o ângulo'],
    positioning: [
      { type: 'certo', text: 'Bola no meio, baixa: os adversários hesitam e a resposta volta para o centro, sem ângulo.' },
      { type: 'errado', text: 'Bola sempre na lateral: abre o ângulo para o adversário cruzar a resposta para fora do seu alcance.' },
    ],
    common_errors: [
      { error: 'Ir para a lateral em toda bola e errar fora.', fix: 'A lateral é para quando a quadra está aberta; na dúvida, meio.' },
      { error: 'Bola no meio, mas alta.', fix: 'Meio só funciona baixo: alto, os dois atacam.' },
    ],
    when_to_use: 'Quando você está em dúvida, quando os adversários estão bem posicionados e em toda devolução e drive.',
    diagrams: [
      diagrama('Certo: no meio, baixo', 'inteira', [
        jogador(25, 32, 'b', 'B1'),
        jogador(75, 32, 'b', 'B2'),
        jogador(60, 96, 'a'),
        trajeto(60, 94, 50, 34),
        zona(40, 25, 60, 40, 'Dúvida'),
      ], 'certo'),
      diagrama('Errado: lateral aberta', 'inteira', [
        jogador(25, 32, 'b', 'B1'),
        jogador(75, 32, 'b', 'B2'),
        jogador(60, 96, 'a'),
        trajeto(60, 94, 92, 34),
        trajeto(90, 32, 5, 80, 'Ângulo'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'poach-na-rede',
    version: 1,
    kind: 'jogada',
    title: 'Poach: atravessar e finalizar',
    summary: 'O parceiro do meio atravessa para volear a bola que ia para o colega. Bem feito, termina o ponto; feito cedo, abre a lateral.',
    objective: 'Ao final, a dupla combina o poach, escolhe a bola certa e troca de lado sem deixar a quadra aberta.',
    skills: ['doubles.posicionamento', 'net.voleio', 'doubles.comunicacao'],
    level_min: 3.5,
    players_min: 4,
    players_max: 4,
    duration_min: 12,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'Combinem um sinal (por exemplo, a mão atrás das costas) para avisar o poach.',
      'Espere o adversário se comprometer com a bola cruzada.',
      'Atravesse em diagonal para a frente, volee para baixo, no meio ou nos pés.',
      'Continue para o lado novo; o parceiro troca e cobre o lado vazio.',
    ],
    cues: ['Saia quando a bola sai', 'Volee para baixo, no meio', 'Atravessou? Fique do lado novo'],
    positioning: [
      { type: 'certo', text: 'Quem fez o poach fica do lado novo e o parceiro passa para o lado que ficou vazio.' },
      { type: 'errado', text: 'Atravessar cedo, antes de o adversário bater: ele vê e joga na lateral que ficou vazia.' },
    ],
    common_errors: [
      { error: 'Poach em bola baixa, que vai na rede.', fix: 'Atravesse só para bola na altura da rede ou acima.' },
      { error: 'O parceiro não troca e a lateral fica livre.', fix: 'Com o sinal ou o grito de "troca", o parceiro vai para o lado vazio.' },
    ],
    when_to_use: 'Na bola cruzada lenta ou alta para o seu parceiro, principalmente na terceira bola fraca ou no dink cruzado alto.',
    diagrams: [
      diagrama('Certo: atravessa e troca', 'cozinha', [
        jogador(28, 68, 'a', 'A1'),
        jogador(72, 68, 'a', 'A2'),
        jogador(28, 32, 'b'),
        jogador(72, 32, 'b'),
        trajeto(28, 34, 66, 60),
        desloca(31, 66, 55, 61, 'Poach'),
        desloca(72, 71, 32, 71, 'Troca'),
      ], 'certo'),
      diagrama('Errado: saiu cedo', 'cozinha', [
        jogador(55, 64, 'a', 'A1'),
        jogador(72, 68, 'a', 'A2'),
        jogador(28, 32, 'b'),
        zona(2, 51, 35, 73, 'Vazio'),
        trajeto(28, 34, 12, 66),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'shake-and-bake',
    version: 1,
    kind: 'jogada',
    title: 'Shake and bake: drive e parceiro na rede',
    summary: 'Um parceiro faz o drive na terceira bola e o outro corre para a rede para finalizar a resposta fraca. Para duplas que já têm um bom drive.',
    objective: 'Ao final, a dupla executa o drive na terceira bola com o parceiro avançando junto e finaliza o bloqueio alto.',
    skills: ['groundstrokes.terceira_bola_drive', 'doubles.posicionamento', 'net.voleio'],
    level_min: 3.5,
    players_min: 4,
    players_max: 4,
    duration_min: 12,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'A devolução veio alta ou curta: quem está com ela faz o drive forte e baixo.',
      'Assim que o drive sai, o parceiro corre para a cozinha, do lado dele.',
      'A dupla adversária bloqueia: o parceiro que subiu volea o bloqueio alto para baixo.',
      'Quem fez o drive avança logo depois, para os dois terminarem na linha.',
    ],
    cues: ['Drive saiu, parceiro sobe', 'Bloqueio alto, voleio para baixo', 'Quem bateu avança atrás'],
    positioning: [
      { type: 'certo', text: 'Parceiro chega à cozinha antes de o bloqueio passar a rede, com a raquete alta e na frente.' },
      { type: 'errado', text: 'Parceiro sobe depois de um drive alto: o adversário volea nos pés dele, no meio do caminho.' },
    ],
    common_errors: [
      { error: 'Usar a jogada com drive fraco ou alto.', fix: 'Só faça shake and bake com bola atacável; bola baixa pede drop.' },
      { error: 'O parceiro fica no fundo olhando o drive.', fix: 'A jogada depende da subida: o drive saiu, o parceiro corre.' },
    ],
    when_to_use: 'Terceira bola com devolução alta ou curta, contra duplas que bloqueiam alto.',
    diagrams: [
      diagrama('Certo: drive e subida', 'inteira', [
        jogador(70, 92, 'a', 'Drive'),
        jogador(25, 96, 'a', 'Parc'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        trajeto(70, 90, 30, 36, '1'),
        desloca(25, 94, 30, 70, '2'),
        trajeto(28, 34, 32, 64, '3'),
      ], 'certo'),
      diagrama('Errado: subiu no drive alto', 'inteira', [
        jogador(70, 92, 'a', 'Drive'),
        jogador(30, 80, 'a', 'Parc'),
        jogador(25, 32, 'b'),
        jogador(75, 32, 'b'),
        trajeto(25, 34, 30, 78, 'Pés'),
        texto(48, 76, 'No caminho'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'cobertura-do-lob-troca',
    version: 1,
    kind: 'jogada',
    title: 'Cobertura do lob: troca de lado',
    summary: 'Quando o lob passa por cima do parceiro, quem está na diagonal vai buscar e o parceiro troca de lado. A dupla grita "troca" e ninguém anda de costas.',
    objective: 'Ao final, a dupla cobre o lob com a troca de lado e se reorganiza na posição certa para a próxima bola.',
    skills: ['doubles.comunicacao', 'doubles.cobertura_meio', 'groundstrokes.lob'],
    level_min: 3.0,
    players_min: 4,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'O lob passou por cima do parceiro: quem está na diagonal, com melhor ângulo, grita "minha" e vira para correr.',
      'O parceiro grita "troca" e passa para o lado que ficou vazio.',
      'Quem buscou devolve alto (lob ou drop) para ganhar tempo.',
      'Os dois voltam juntos para a frente, cada um no seu lado novo.',
    ],
    cues: ['Lob no parceiro? Diagonal busca', 'Grite troca e atravesse', 'Vire e corra, sem recuar'],
    positioning: [
      { type: 'certo', text: 'Quem está na diagonal corre em diagonal até atrás da bola; o parceiro atravessa para o outro lado.' },
      { type: 'errado', text: 'O jogador que teve o lob por cima anda de costas para buscá-lo: risco de queda e chegada atrasada.' },
    ],
    common_errors: [
      { error: 'Os dois vão buscar o lob e a quadra fica vazia.', fix: 'Um busca, o outro troca: combinem antes quem busca qual lob.' },
      { error: 'Quem buscou devolve com força e correndo.', fix: 'Devolva alto e lento para dar tempo de os dois se reorganizarem.' },
    ],
    when_to_use: 'Quando o adversário joga lob por cima de um de vocês na cozinha, principalmente no lado do backhand.',
    diagrams: [
      diagrama('Certo: diagonal busca, parceiro troca', 'inteira', [
        jogador(30, 68, 'a', 'A1'),
        jogador(70, 68, 'a', 'A2'),
        jogador(70, 32, 'b'),
        trajeto(70, 34, 28, 90, 'Lob'),
        desloca(68, 70, 32, 92, 'Busca'),
        desloca(32, 71, 66, 71, 'Troca'),
      ], 'certo'),
      diagrama('Errado: recua de costas', 'inteira', [
        jogador(30, 68, 'a', 'A1'),
        jogador(70, 68, 'a', 'A2'),
        jogador(70, 32, 'b'),
        trajeto(70, 34, 28, 90, 'Lob'),
        desloca(30, 70, 30, 88, 'De costas'),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'stacking-empilhamento',
    version: 1,
    kind: 'jogada',
    title: 'Stacking: cada um no seu lado preferido',
    summary: 'A dupla se arruma para que cada parceiro jogue sempre no lado em que é mais forte, por exemplo com o melhor forehand no meio. Só o sacador e quem recebe têm lugar fixo.',
    objective: 'Ao final, a dupla executa o empilhamento no saque e na devolução sem cometer falta de posição e sem deixar lado vazio.',
    skills: ['doubles.stacking', 'doubles.posicionamento', 'rules.placar'],
    level_min: 3.5,
    players_min: 4,
    players_max: 4,
    duration_min: 15,
    intensity: 4,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'Combinem quem quer ficar em qual lado (por exemplo, o canhoto à esquerda e o destro à direita).',
      'No saque: quem saca fica no lado que o placar manda; o parceiro espera do mesmo lado, perto da lateral.',
      'Depois de sacar, quem precisa trocar atravessa para o lado preferido; o parceiro fica no seu.',
      'Na devolução: quem recebe fica no lado certo; o parceiro espera na cozinha, do mesmo lado, perto da lateral.',
      'Depois de devolver, quem recebeu corre para o lado preferido e o parceiro desliza para o outro.',
    ],
    cues: ['Placar decide quem saca', 'Saque saiu, troque', 'Grite fica ou troca'],
    positioning: [
      { type: 'certo', text: 'Sacador no lado que o placar manda e parceiro do mesmo lado, perto da lateral, pronto para atravessar depois do saque.' },
      { type: 'certo', text: 'Na devolução, o parceiro espera na cozinha, do lado de quem recebe, e troca depois da devolução.' },
      { type: 'errado', text: 'Sacar ou receber do lado errado para ficar no lado preferido: é falta de posição, e o ponto vai para o adversário.' },
    ],
    common_errors: [
      { error: 'Trocar de lugar com o adversário ainda batendo e deixar um lado vazio.', fix: 'Troquem logo depois do saque ou da devolução, enquanto a bola viaja.' },
      { error: 'Perder a conta de quem saca.', fix: 'Quem saca e de que lado sai do placar, não do lado preferido: anunciem o placar em voz alta.' },
    ],
    when_to_use: 'Quando um parceiro é canhoto, quando um tem forehand muito melhor ou quando um domina a rede e quer ficar no meio.',
    diagrams: [
      diagrama('Certo: empilhados no saque', 'inteira', [
        jogador(62, 97, 'a', 'Sac'),
        jogador(92, 94, 'a', 'Parc'),
        trajeto(62, 95, 25, 10, 'Saque'),
        desloca(60, 94, 30, 84, 'Troca'),
        jogador(25, 4, 'b'),
        jogador(75, 32, 'b'),
      ], 'certo'),
      diagrama('Certo: empilhados na devolução', 'inteira', [
        jogador(75, 98, 'a', 'Dev'),
        jogador(94, 68, 'a', 'Parc'),
        jogador(25, 3, 'b', 'Sac'),
        trajeto(25, 5, 72, 90, 'Saque'),
        desloca(73, 95, 30, 72, 'Troca'),
        desloca(92, 71, 70, 71),
      ], 'certo'),
      diagrama('Errado: lado vazio na troca', 'inteira', [
        jogador(30, 84, 'a', 'Sac'),
        jogador(36, 72, 'a', 'Parc'),
        zona(52, 52, 98, 99, 'Vazio'),
        jogador(25, 32, 'b'),
        trajeto(25, 34, 80, 80),
      ], 'errado'),
    ],
    media: [],
  },
  {
    slug: 'erne',
    version: 1,
    kind: 'jogada',
    title: 'Erne: voleio por fora da cozinha',
    summary: 'Contra o dink paralelo junto à lateral, o jogador sai da quadra pela lateral, ao lado da cozinha, e volea a bola perto do poste. Jogada avançada e legal quando os pés ficam fora da cozinha.',
    objective: 'Ao final, o atleta reconhece o dink paralelo previsível e executa o Erne com os pés fora da cozinha no momento do voleio.',
    skills: ['net.erne', 'tactics.leitura_adversario', 'rules.cozinha'],
    level_min: 4.5,
    level_max: 7.0,
    players_min: 2,
    players_max: 4,
    duration_min: 12,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'variado',
    steps: [
      'Repare no adversário que dinka paralelo, junto à lateral, de forma previsível.',
      'No dink seguinte, saia pela lateral, por fora da cozinha, até ficar ao lado do poste, fora da quadra.',
      'Volee a bola antes de ela quicar, para baixo, no pé ou no meio dos adversários.',
      'Se você pisou na cozinha no caminho, os dois pés precisam voltar para fora dela antes do voleio.',
      'Volte para a quadra para a próxima bola.',
    ],
    cues: ['Leia o paralelo, depois saia', 'Pés fora da cozinha no voleio', 'Volee para baixo, no meio'],
    positioning: [
      { type: 'certo', text: 'No voleio, os dois pés fora da cozinha e da linha dela, ao lado da quadra, perto do poste.' },
      { type: 'errado', text: 'Volear com um pé ainda na cozinha ou na linha: é falta, mesmo que a bola entre.' },
    ],
    common_errors: [
      { error: 'Sair cedo e o adversário mudar o dink para o cruzado.', fix: 'Saia quando ele já se comprometeu com o paralelo.' },
      { error: 'Esquecer de restabelecer os pés fora da cozinha.', fix: 'Pisou na cozinha? Os dois pés voltam para fora antes de volear.' },
    ],
    when_to_use: 'Contra quem dinka repetidamente no paralelo, junto à lateral do seu lado.',
    safety: 'Cuidado com o poste e com o espaço fora da quadra: veja se não há banco, cadeira ou outra pessoa no caminho.',
    diagrams: [
      diagrama('O caminho do Erne', 'cozinha', [
        zona(0, 51, 100, 65.9, 'Cozinha'),
        jogador(90, 68, 'a', 'A'),
        jogador(90, 32, 'b', 'B'),
        trajeto(90, 34, 96, 56, 'Paralelo'),
        desloca(94, 70, 100, 56, 'Por fora'),
        trajeto(100, 55, 55, 38),
      ]),
    ],
    media: [],
  },
  {
    slug: 'atp-por-fora-do-poste',
    version: 1,
    kind: 'jogada',
    title: 'ATP: a bola por fora do poste',
    summary: 'Quando o adversário abre muito o ângulo e a bola quica para fora da quadra, ela pode voltar por fora do poste, sem passar por cima da rede. Raro e legal.',
    objective: 'Ao final, o atleta reconhece a bola aberta o bastante para o ATP e a devolve baixa, por fora do poste, dentro da quadra.',
    skills: ['net.atp', 'tactics.leitura_adversario'],
    level_min: 4.5,
    level_max: 7.0,
    players_min: 2,
    players_max: 4,
    duration_min: 10,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas'],
    practice_mode: 'variado',
    steps: [
      'O adversário mandou um dink cruzado muito aberto, que vai quicar perto da lateral e sair da quadra.',
      'Deixe a bola quicar (ela precisa quicar do seu lado) e vá atrás dela, por fora da quadra.',
      'Bata a bola baixa, por fora do poste, direto para a quadra adversária.',
      'A bola não precisa passar por cima da rede, mas precisa cair dentro da quadra.',
      'Volte depressa para a quadra: se o ATP for devolvido, seu lado está aberto.',
    ],
    cues: ['Bola bem aberta? Pense no poste', 'Bata baixo, por fora do poste', 'Volte depressa para a quadra'],
    positioning: [
      { type: 'certo', text: 'Ir atrás da bola por fora da quadra e bater depois do quique, ao lado do poste.' },
      { type: 'errado', text: 'Tentar o ATP com a bola ainda dentro da quadra ou sem o quique: a bola tem de passar por cima da rede.' },
    ],
    common_errors: [
      { error: 'Tentar o ATP em bola pouco aberta.', fix: 'Sem ângulo, jogue por cima da rede, com um dink ou um voleio normal.' },
      { error: 'Ficar fora da quadra depois do ATP.', fix: 'Volte para a quadra logo depois de bater.' },
    ],
    when_to_use: 'Dink cruzado ou bola com efeito muito aberta, que sai da quadra pela lateral perto da rede.',
    safety: 'Veja o espaço fora da quadra antes de correr: poste, cadeiras e outras pessoas.',
    diagrams: [
      diagrama('Por fora do poste', 'cozinha', [
        jogador(28, 32, 'b', 'B'),
        jogador(80, 68, 'a', 'A'),
        trajeto(28, 34, 97, 60, 'Aberta'),
        desloca(84, 68, 98, 62),
        trajeto(100, 60, 100, 42, 'Por fora'),
        trajeto(100, 42, 82, 36, 'ATP'),
        texto(92, 50, 'Poste'),
      ]),
    ],
    media: [],
  },
];
