/** Biblioteca inicial — TREINOS (sessões completas, do aquecimento à volta à calma). */

const QUADRA = ['quadra'];
const SEGURANCA = 'Água por perto e pausas para beber. Quadra molhada ou escorregadia: não treine. Para buscar o lob, vire e corra; nunca recue de costas. Sentiu dor, tontura ou falta de ar fora do normal? Pare.';

/** Um bloco do treino. O drill é citado pelo nome: a semente não liga itens. */
const bloco = (type, title, duration_min, notes) => ({ type, title, duration_min, item_id: null, notes });

const AQUECIMENTO = (min) => bloco('aquecimento', 'Aquecimento dinâmico', min, 'Siga o "Aquecimento dinâmico de 10 minutos": movimento leve, depois amplo, depois no ritmo do jogo, terminando com dinks leves.');
const VOLTA_CALMA = (min) => bloco('volta_calma', 'Volta à calma', min, 'Siga a "Volta à calma depois do jogo": caminhada leve, alongamentos parados até tensão leve e água.');

export const TREINOS = [
  {
    slug: 'treino-iniciante-primeiro-treino',
    version: 1,
    featured: true,
    kind: 'treino',
    title: 'Primeiro treino: dink, saque e jogo',
    summary: 'Uma hora para quem está começando: aquecer, aprender o dink, sacar com consistência e terminar jogando. O roteiro de quem nunca treinou com método.',
    objective: 'Ao final, o atleta iniciante coloca o dink na cozinha, saca dentro da área com rotina fixa e mantém um rally curto em jogo.',
    skills: ['kitchen.dink_paralelo', 'serve.consistencia', 'kitchen.paciencia', 'physical.aquecimento'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 60,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'cesto'],
    practice_mode: 'bloco',
    blocks: [
      AQUECIMENTO(10),
      bloco('tecnica', 'Primeiros dinks com alimentador', 15, 'Siga "Primeiros dinks: bola na mão e alvo na cozinha". Rodadas de 10 bolas, trocando os papéis. Meta: 7 de 10 na cozinha.'),
      bloco('tecnica', 'Saque com alvo', 12, 'Siga "Saque fundo com alvo" na versão mais fácil: toda a área de saque vale. Meta: 8 de 10 válidos, com a mesma rotina antes de cada saque.'),
      bloco('jogo', 'Dink cooperativo', 18, 'Siga "Dink até 11" na versão cooperativa: a dupla conta quantos dinks seguidos faz. Tente bater o próprio recorde.'),
      VOLTA_CALMA(5),
    ],
    safety: SEGURANCA,
    media: [],
  },
  {
    slug: 'treino-iniciante-saque-devolucao',
    version: 1,
    kind: 'treino',
    title: 'Saque e devolução em 45 minutos',
    summary: 'Treino curto para os dois golpes que começam todo ponto: saque fundo e devolução funda, terminando com a caminhada até a cozinha.',
    objective: 'Ao final, o atleta saca e devolve fundo com consistência e chega à cozinha depois de devolver.',
    skills: ['serve.consistencia', 'serve.saque_profundo', 'serve.devolucao_profunda', 'doubles.posicionamento'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 45,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'cesto'],
    practice_mode: 'bloco',
    blocks: [
      AQUECIMENTO(8),
      bloco('tecnica', 'Saque com alvo no fundo', 12, 'Siga "Saque fundo com alvo": 10 saques em cada diagonal. Meta: 8 de 10 válidos e 5 no terço final.'),
      bloco('tecnica', 'Devolução funda', 10, 'Siga "Devolução de saque funda". Um saca, o outro devolve alto e fundo, para trás dos cones. Troquem a cada 10.'),
      bloco('jogo', 'Devolver e chegar à cozinha', 12, 'Siga "Devolver e chegar à cozinha": ponto em que quem devolveu estava parado na linha na terceira bola vale 2.'),
      VOLTA_CALMA(3),
    ],
    safety: SEGURANCA,
    media: [],
  },
  {
    slug: 'treino-iniciante-cozinha',
    version: 1,
    kind: 'treino',
    title: 'Treino de cozinha para iniciantes',
    summary: 'Uma hora para ganhar paciência e controle no dink: paralelo, cruzado e um jogo só na cozinha.',
    objective: 'Ao final, o atleta mantém rallies de dink paralelo e cruzado com a bola baixa e joga pontos só na cozinha.',
    skills: ['kitchen.dink_paralelo', 'kitchen.dink_cruzado', 'kitchen.paciencia'],
    level_min: 2.0,
    level_max: 3.0,
    players_min: 2,
    players_max: 4,
    duration_min: 60,
    intensity: 3,
    place: QUADRA,
    equipment: ['bolas', 'cones'],
    practice_mode: 'bloco',
    blocks: [
      AQUECIMENTO(10),
      bloco('tecnica', 'Dink paralelo junto à lateral', 12, 'Siga "Dink paralelo junto à lateral" com a faixa larga (versão mais fácil). Troquem de lateral a cada 2 minutos.'),
      bloco('tecnica', 'Dink cruzado no pé de dentro', 10, 'Siga "Dink cruzado no pé de dentro". Meta: 5 seguidos na cozinha; quem chegar, passa a mirar o cone.'),
      bloco('jogo', 'Dink até 11', 23, 'Siga "Dink até 11": jogos curtos, trocando de parceiro e de diagonal entre os jogos.'),
      VOLTA_CALMA(5),
    ],
    safety: SEGURANCA,
    media: [],
  },
  {
    slug: 'treino-intermediario-terceira-bola',
    version: 1,
    kind: 'treino',
    title: 'Terceira bola: do fundo para a rede',
    summary: 'Uma hora para a parte mais difícil das duplas: o drop da terceira bola e a chegada à cozinha, terminando com pontos ao vivo.',
    objective: 'Ao final, a dupla que saca coloca o drop na cozinha em metade das tentativas e chega junta à linha em jogo.',
    skills: ['groundstrokes.terceira_bola_drop', 'groundstrokes.transicao', 'doubles.posicionamento'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    duration_min: 60,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'cesto'],
    practice_mode: 'variado',
    blocks: [
      AQUECIMENTO(10),
      bloco('tecnica', 'Drop com alimentador', 12, 'Siga "Drop da terceira bola com alimentador". Rodadas de 10, trocando os papéis. Meta: 6 de 10 na cozinha.'),
      bloco('tecnica', 'Escada do drop', 12, 'Siga "Escada do drop: do meio para o fundo": 3 seguidos para subir de degrau, 2 erros seguidos para descer.'),
      bloco('jogo', 'Terceira bola ao vivo', 21, 'Siga "Terceira bola ao vivo em duplas" (com dois, use o "Jogo 7-11"). Ponto dobrado para a dupla que saca se chegar inteira à cozinha.'),
      VOLTA_CALMA(5),
    ],
    safety: SEGURANCA,
    media: [],
  },
  {
    slug: 'treino-intermediario-cozinha',
    version: 1,
    kind: 'treino',
    title: 'Cozinha: dink, bola alta e o meio',
    summary: 'Uma hora e quinze para dominar a cozinha: deslocamento no dink, a hora de atacar a bola alta e a comunicação na bola do meio.',
    objective: 'Ao final, o atleta mantém o dink com deslocamento, ataca só a bola acima da rede e a dupla resolve a bola do meio com chamada.',
    skills: ['kitchen.dink_cruzado', 'kitchen.dink_atacavel', 'doubles.comunicacao', 'kitchen.paciencia'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 3,
    players_max: 4,
    duration_min: 75,
    intensity: 5,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'variado',
    blocks: [
      AQUECIMENTO(10),
      bloco('tecnica', 'Dink em oito', 15, 'Siga "Dink em oito: cruzado e paralelo". Troquem os papéis a cada 3 minutos. Meta: 12 seguidos.'),
      bloco('tatica', 'Dink e ataque da bola alta', 12, 'Siga "Dink e ataque da bola alta": ataque só a bola acima da fita, nos pés.'),
      bloco('tatica', 'Bola do meio: quem chama?', 12, 'Siga "Bola do meio: quem chama?". Combinem a regra antes (forehand no meio pega) e chamem cedo.'),
      bloco('jogo', 'Dink até 11 com ataque', 20, 'Siga "Dink até 11" na versão mais difícil: bola acima da rede pode ser atacada.'),
      VOLTA_CALMA(6),
    ],
    safety: SEGURANCA,
    media: [],
  },
  {
    slug: 'treino-intermediario-transicao',
    version: 1,
    kind: 'treino',
    title: 'Transição: parar, amortecer e subir',
    summary: 'Uma hora e meia para a zona de transição: split step no tempo certo, reset das bolas nos pés e o jogo 7-11.',
    objective: 'Ao final, o atleta para em split step no contato do adversário, amortece a bola rápida para a cozinha e chega à linha em até três golpes.',
    skills: ['net.reset', 'groundstrokes.transicao', 'physical.agilidade'],
    level_min: 3.0,
    level_max: 4.0,
    players_min: 2,
    players_max: 4,
    duration_min: 90,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cones', 'cesto'],
    practice_mode: 'variado',
    blocks: [
      AQUECIMENTO(10),
      bloco('fisico', 'Reação e split step', 10, 'Siga "Reação aos quatro cones": 4 séries de 6 reações, com o split step antes de cada saída.'),
      bloco('tecnica', 'Reset de bloqueio nos pés', 15, 'Siga "Reset de bloqueio nos pés": primeiro só forehand, depois só backhand, depois misturado.'),
      bloco('tatica', 'Reset na zona de transição', 15, 'Siga "Reset na zona de transição": avance, pare quando o atacante bater, amorteça e avance de novo.'),
      bloco('jogo', 'Jogo 7-11', 32, 'Siga "Jogo 7-11: chegar à rede contra quem está nela". Troquem os papéis a cada jogo.'),
      VOLTA_CALMA(8),
    ],
    safety: `Bolas rápidas no meio da quadra: óculos de proteção são recomendados. ${SEGURANCA}`,
    media: [],
  },
  {
    slug: 'treino-avancado-maos-rapidas',
    version: 1,
    kind: 'treino',
    title: 'Mãos rápidas na rede',
    summary: 'Uma hora e quinze de trocas rápidas: voleio, bloqueio contra o drive, speed-up e contra-ataque, terminando com dink e ataque liberado.',
    objective: 'Ao final, o atleta bloqueia drives para a cozinha, acelera só a bola atacável e vence mais trocas rápidas do que perde.',
    skills: ['net.speed_up', 'net.contra_ataque', 'net.voleio', 'kitchen.dink_atacavel'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 2,
    players_max: 4,
    duration_min: 75,
    intensity: 7,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'aleatorio',
    blocks: [
      AQUECIMENTO(10),
      bloco('tecnica', 'Troca rápida de voleios', 10, 'Siga "Troca rápida de voleios na rede": comecem cooperando e subam a velocidade a cada 5 seguidos.'),
      bloco('tecnica', 'Bloqueio contra o drive', 12, 'Siga "Voleio de bloqueio contra o drive" na versão mais difícil: drive, drop e lob misturados.'),
      bloco('tatica', 'Speed-up e contra-ataque', 15, 'Siga "Speed-up e contra-ataque": jogos até 7, trocando quem ataca.'),
      bloco('jogo', 'Dink até 11 com ataque liberado', 22, 'Siga "Dink até 11" em 2 contra 2, com qualquer bola acima da rede podendo ser atacada.'),
      VOLTA_CALMA(6),
    ],
    safety: `Óculos de proteção são recomendados nas trocas rápidas. Ataque no corpo e nos pés, nunca no rosto. ${SEGURANCA}`,
    media: [],
  },
  {
    slug: 'treino-avancado-padroes-duplas',
    version: 1,
    kind: 'treino',
    title: 'Padrões de duplas: poach, drive e stacking',
    summary: 'Uma hora e meia de padrões combinados de duplas: poach no dink cruzado, drive com subida do parceiro e empilhamento, terminando com pontos ao vivo.',
    objective: 'Ao final, a dupla executa poach, drive da terceira com drop da quinta e stacking sem falta de posição, em jogo.',
    skills: ['doubles.posicionamento', 'doubles.stacking', 'doubles.comunicacao', 'groundstrokes.terceira_bola_drive'],
    level_min: 4.0,
    level_max: 5.5,
    players_min: 4,
    players_max: 4,
    duration_min: 90,
    intensity: 6,
    place: QUADRA,
    equipment: ['bolas', 'cesto'],
    practice_mode: 'variado',
    blocks: [
      AQUECIMENTO(10),
      bloco('tatica', 'Poach no dink cruzado', 15, 'Siga "Poach no dink cruzado": combinem o sinal e troquem quem faz o poach a cada 10 tentativas.'),
      bloco('tatica', 'Drive da terceira e drop da quinta', 15, 'Siga "Drive da terceira e drop da quinta" com a subida do parceiro do "Shake and bake".'),
      bloco('tatica', 'Stacking no saque e na devolução', 10, 'Repassem as posições de "Stacking: cada um no seu lado preferido", anunciando o placar em voz alta a cada ponto.'),
      bloco('jogo', 'Terceira bola ao vivo com stacking', 32, 'Siga "Terceira bola ao vivo em duplas" usando o stacking. Falta de posição vale ponto para o adversário.'),
      VOLTA_CALMA(8),
    ],
    safety: SEGURANCA,
    media: [],
  },
];
