/** Chaves do React Query do Centro de Treino — fonte única (chave escrita duas vezes diverge um dia). */
export const trainingKeys = {
  all: ['treino'],
  settings: ['treino', 'config'],
  items: ['treino', 'itens'],
  publicItems: ['treino', 'itens', 'publicos'],
  myItems: (uid) => ['treino', 'itens', 'meus', uid],
  coachItems: (ids) => ['treino', 'itens', 'professores', [...ids].sort().join(',')],
  sharedItems: (uid) => ['treino', 'itens', 'compartilhados', uid],
  item: (id) => ['treino', 'itens', 'um', id],
  allItems: ['treino', 'itens', 'admin'],
  shares: ['treino', 'envios'],
  inbox: (uid) => ['treino', 'envios', 'recebidos', uid],
  sent: (uid) => ['treino', 'envios', 'enviados', uid],
  sessions: ['treino', 'diario'],
  mySessions: (uid) => ['treino', 'diario', 'meu', uid],
  studentSessions: (coach, ids) => ['treino', 'diario', 'alunos', coach, [...ids].sort().join(',')],
  comments: (sid) => ['treino', 'diario', 'comentarios', sid],
  plans: (uid) => ['treino', 'planos', uid],
  meta: (uid) => ['treino', 'meta', uid],
  debriefs: (uid) => ['treino', 'balanco', uid],
  recentPlay: (uid) => ['treino', 'balanco', 'jogos', uid],
  questions: ['treino', 'duvidas'],
  myQuestions: (uid) => ['treino', 'duvidas', 'minhas', uid],
  coachQuestions: (uid) => ['treino', 'duvidas', 'professor', uid],
  messages: (qid) => ['treino', 'duvidas', 'mensagens', qid],
  reports: ['treino', 'denuncias'],
  seedPlan: ['treino', 'semente'],
};
